### ISSUE TITLE
ODK Collect 1.6.1 the ${username} variable not set.

### ISSUE THREAD

**Issue by acoveny** [getodk/collect#1009]
#### Software and hardware versions 
ODK Collect v1.6.1, Android v7.0, Motorola 4G
ODK Aggregate Server 1.4.9 

#### Problem description

Using ODK Collect 1.6.1 the ${username} variable not set when the form starts to be filled in, not sent back, and does not appear in the exported json.

#### Steps to reproduce the problem
1. Filled in a form loaded on 1.6.1 Android 7 ( 1.6.0 works ok )
The Form displays the username in a lable - the username is not displayed.

2. Downloaded the sumbitted form as json

{"start_dt":"2017-05-04T17:59:36.128+10","end_dt":"2017-05-04T18:01:34.354+10","today_date_d":"2017-05-04","username":null,"phonenumber":null, 
the rest of the form filled in ... }

The phonenumber is always null - (we don't utilise the phone number) by we do rely on the username

#### Expected behavior

Expect to have the ${username} filled in. Noticed the username was missing straight away as the form behaviour is dependent of who the users is - so my form stopped behaving as expected immediately.

Also it is worth noting that the labels at the bottom of the Username and Password pop-up edit window under the General Setting Menu appear in a font which is not readable.

#### Other information 
Tried re-installing ODK Collect. Tried rebooting the phone. Tried logging in as different users.
None of these worked.

ODK Collect does use the username + password to authorise and fetch forms from the ODK Aggregate server correctly.

**Comment by lognaturel** [comment]
I'm looking into this but am having trouble reproducing it. On my Nexus 5, Android 6.0.1, I went back down to v1.5.1, put in username 'test1' in the username field and my gmail in the gmail address field,  updated to 1.6.1 from the Play Store, filled out [preloads.txt](https://github.com/opendatakit/collect/files/976376/preloads.txt) and verified that username and email are correctly populated when I upload the form to Aggregate. Furthermore, I see that the data properly shows up in the Form metadata settings category.

It would be helpful if someone else could try reproducing this. I'll also give it a try with an Android 7 Moto G4 in a moment and report back.

@acoveny Are you sure that it worked properly for 1.6.0? Nothing related to that functionality was changed between 1.6.0 and 1.6.1. Is it possible that you mean the change happened between 1.5.1 and 1.6.1? Did you note the new Form metadata settings category and make sure that the username is set there? It is now possible to set a separate username for the server and for the metadata preload. The server username should have been copied over when you first launched the new version.

The strange text you are seeing is from issue #993. Since it's a problem specific to the Moto G4, the core team won't be prioritizing it but you are welcome to send in a pull request!

**Comment by lognaturel** [comment]
I tried the same thing on a Moto G4 running Android 7.0 and that is also working for me.

@acoveny The update from 1.5.1 to 1.6.1 was set up to copy the Aggregate username to the form metadata username field and the Google account to the form metadata email field so that username/email collection continued seamlessly. 

If you reset settings after updating, then you would have to make sure that you set the form metadata username separately, perhaps that's the root of the problem? We have separated form metadata username from Aggregate username because many organizations use a single Aggregate account but still want to keep track of the specific person collecting data.
<img width="244" alt="screen shot 2017-05-04 at 9 40 32 am" src="https://cloud.githubusercontent.com/assets/967540/25709192/408b4022-30ae-11e7-97be-a9a3af7f67a9.png"><img width="244" alt="screen shot 2017-05-04 at 9 44 02 am" src="https://cloud.githubusercontent.com/assets/967540/25709208/496575a0-30ae-11e7-8ee2-9362d470a754.png">

If that doesn't help, could you please upload your form? If it's not one you can share publicly, please try building the smallest form you can that demonstrates the problem.

**Comment by acoveny** [comment]
Hi Helene,

Thank-you so much for looking into this. Was not sure if this was an issue
more widely - looks like it is not.

I had upgraded my phone from 1.5.1 to 1.6.0, and then 1.6.1

Have _not_ noted the new Form metadata settings category.
Will have a go with the new Form metadata tomorrow at work and let you know
how it goes.

We are not using gmail or other google integration yet for ODK. We are
running ODK Aggregate on tomcat with a json server publish behind that.

If it is still a problem - will code our form up so our users can set the
username from a drop down list of valid usernames, if the username variable
is not set by ODK collect when the form loads initially.

My moto G4 was recently upgraded to Android 7.0 so that may be a
contributing factor.

As the problem would seem to be only my Moto 4g and 1.6.1, and I have a
valid workaround, this issue is not at all urgent. Will let you know how I
go.

Once again thank-you very much for helping Helene.

Best Regards,

Anne

**Comment by lognaturel** [comment]
@acoveny Do keep us posted! It would be very helpful to know whether or not setting the values in the Form metadata settings works (it should!).

**Comment by acoveny** [comment]
Hi Helene,

Apologies - feeling very stupid about now - just filled in the Form
metadata in General Settings and the username was picked up by my form an
pre-loaded beautifully.

The notes under the word Form metadata explains very clearly what it is
used for, and  should have picked that up.

Warm Regards,

Anne

**Comment by lognaturel** [comment]
It's no problem, I'm so happy to hear that's what it was! 

I'm not sure why the values weren't copied as they were supposed to but perhaps it has to do with the Android update or phone reset. Happy data collection and let us know if you run into any other issues!

**Comment by mfrasca** [comment]
I came across this issue because I had myself also assumed that the username in the credentials would be used as metadata username.
maybe not such a silly idea: if username in the server credentials is set, and username in metadata is empty, use the first as default value for the second.

**Comment by lognaturel** [comment]
Makes sense. How about a checkbox that is checked by default that says something like "Use server username"? If it's checked, the server username would be in the username textbox and not be editable. If it is unchecked, the username textbox would be editable.

The reason I suggest using an explicit checkbox instead of falling back to the server username automatically is that it would give the user a little bit more information on what is happening and what they can control. I think it would be confusing to go to the metadata menu, find that username is blank but know that ${username} does get set.

@mfrasca please file an issue with a description of the behavior that you think would make the most sense so that we can get this slotted into a release!
