### ISSUE TITLE
problema con el usuario

### ISSUE THREAD

**Issue by navitojr** [getodk/collect#1017]
buenas tardes soy encuestador de México y toda la aplicación funcionaba de maravilla hasta hace unos días que el nombre el usuario que se enviaba de forma anónima ahora ya no lo hace tengo que agregarlo en los meta data de la aplicación lo cual me cuesta mucho trabajo por que usamos el dispositivo mas de  un individuo espero me puedan ayudar en esta duda

**Comment by lognaturel** [comment]
@navitojr Mi español es básico entonces le voy a contestar en inglés. Puede usar [Google Tanslate](https://translate.google.com/) para leer la respuesta y contestar en español.

In version 1.6.1, we separated the metadata username from the Aggregate username. This is because many organizations use a single Aggregate username but still want to know which person is submitting data. Also, some people use Google Sheets submission but still want to know which person is submitting data.

It sounds like you have a single device shared between multiple users with different Aggregate usernames, is that correct? Are you using Aggregate or another server type?

**Comment by navitojr** [comment]
ok muchas gracias una cuestión mas estoy tratando de exportar mis encuestas de odk aggregate pero de forma masiva pero no logra exportarse y es un problema grave porque me estoy quedando sin espacio en servidor (espero me puedan ayudar a exportar todas mis encuestas de forma masiva o decirme como poder hacerlo sin que odk aggregate truene de ante mano muchas gracias

google translate
Ok thanks a lot one more question I am trying to export my odk aggregate surveys but in a massive way but it does not manage to export and it is a serious problem because I am running out of server space (I hope I can help export all my surveys in bulk or Tell me how to do it without odk aggregate truene from beforehand many thanks
![image](https://cloud.githubusercontent.com/assets/28632872/26040009/dbe546ae-38e6-11e7-8bff-16e824ff31e8.png)

**Comment by navitojr** [comment]
¿hay alguna manera de regresar a la versión 1.6.0 ?

**Comment by lognaturel** [comment]
Para ayuda con Aggregate, por favor escriba a la [lista de correo para usuarios](https://groups.google.com/forum/#!forum/opendatakit).

La versión 1.6.0 también tiene este cambio. APKs de las versiones anteriores están [aquí](https://opendatakit.org/downloads/download-info/odk-collect-apk/#).

What we could add is an option to use the Aggregate username as the metadata username, perhaps as a checkbox in the metadata menu. Would that be useful to you? If so, I will open another issue so we can discuss it. I will close this one for now.
