### ISSUE TITLE
Changing layers when the map view is open

### ISSUE THREAD

**Issue by grzesiek2010** [getodk/collect#1042]
Currently we allow selecting basemap in "General Settings" and we are not able to change selected layer during the work. We can only choose offline layers.

It should be possible to do that - be able to choose online layers as well.

**Comment by grzesiek2010** [comment]
I'm working on it.

**Comment by lognaturel** [comment]
I don't have a good enough sense of how these geo features are used to know quite what the right thing to do is. For me, I do find it cool to be able to change basemaps on the fly. But then if I do, should it be just for this use of this widget? Should it change the basemap set in general settings?

In the context of organizations sending enumerators out into the field, I suspect that project leaders would prefer to choose the basemap and not let the enumerator change it. That makes it seem like the real problem is that offline layers should be able to be set in general settings. Perhaps "Mapping SDK" could be changed to "Mapping source" with an "Offline mbtiles" option added to the list.

If all basemaps can be selected on the fly in the geo widgets, I think we should probably consider adding an admin settings option to hide the layers button.

Paging @geomapdev @spatialdude @jnordling @yanokwa

**Comment by grzesiek2010** [comment]
@lognaturel 

> Should it change the basemap set in general settings

No, I think it shouldn't. It should be only for this use.

> If all basemaps can be selected on the fly in the geo widgets, I think we should probably consider adding an admin settings option to hide the layers button.

We can of course if needed

**Comment by grzesiek2010** [comment]
Maps have changed a lot for last 2 years, we can select layers, not styles but there is no need to clutter the map view. If anyone disagree we should probably discuss such a change on the forum.
