### ISSUE TITLE
Redesign settings

### ISSUE THREAD

**Issue by shobhitagarwal1612** [getodk/collect#1048]
The following changes were proposed in the GSoC [proposal ](https://docs.google.com/document/d/1tAP5vRdwiF3KdqXnXGKJnjlh98SywbeoyQSZQWMRhSA/edit)for this: 

- Removing separate options for admin and general settings and merging them into one
- Regrouping the preferences in order to reduce the number of options on a single screen

This issue is created in order to discuss the re-work that should be done in the settings. 
Everyone, please share your views. @yanokwa @lognaturel @grzesiek2010 I would love to hear your thoughts.

**Comment by lognaturel** [comment]
YES. I think everyone gets lost in the settings and the grouping will make a huge difference. 

To refresh everyone's memory, here are @shobhitagarwal1612's wireframes:
<img width="726" alt="screen shot 2017-05-25 at 2 29 25 pm" src="https://cloud.githubusercontent.com/assets/967540/26467206/38f1bb3e-4157-11e7-89f5-6686768b4da9.png">

Different sub-screens for the admin settings is perfect (access to main menu items / change settings / form entry).

How about doing the same for the general preferences and having sub-screens for server, user interface, mapping, etc?

From the usage I've seen, different people access admin and general settings so it's good for admin settings to be easily accessible. Maybe it could be at the top of settings rather than at the bottom? That's something I'd like to get some other opinions on. It might also be worth leaving things as they are for now to focus on the grouping and then deciding exactly where admin settings will be launched from once we have more feedback on changing the first screen.

The [material design guidelines on settings](https://material.io/guidelines/patterns/settings.html#settings-writing-guidelines) are great to review.

**Comment by shobhitagarwal1612** [comment]
https://drive.google.com/open?id=0B9BxtLVL3EziZXltOGZqTm42ZGM
@lognaturel @yanokwa I have shared the screenshots of the settings screens. Please check them out and give your views.

**Comment by shobhitagarwal1612** [comment]
Another thing that I wanted to say is that currently the user can control the items that can be made visible in the general settings. Currently, we can select each individual preference from admin settings. What I want to propose is that the user can only make the group of preference (eg. server settings, mapping, etc.) visible/invisible
