### ISSUE TITLE
Still able to fetch forms after deleting credentials!

### ISSUE THREAD

**Issue by smoyte** [getodk/collect#1109]
#### Software and hardware versions 
Collect v1.7.0, Android v7.1.2, Nexus 6P

#### Problem description
Once authenticated, can still get new forms and send data after deleting password from device.

#### Steps to reproduce the problem
1. Download forms and authenticate
2. Go to platform settings and remove password
3. Try to get new forms again or send data. It works!

#### Expected behavior
Auth should fail and password prompt should appear.

#### Other information 
Seems like a security issue, no? If this is getting cached, that is cool and all, but there should be a way to clear it. Also what if I want to change to a different user account? This suggests that I would keep submitting under the old one...

Let me know how I can be of help on this one.

**Comment by lognaturel** [comment]
This has been a long standing issue. Would be great if you could propose an approach for addressing it!

**Comment by carl-eis** [comment]
This could actually be a bug with Aggregate and not Collect.

Why? 

We use digest authentication to aggregate to pull the form list from our aggregate server into a separate app. It seems as though aggregate keeps this connection "alive" for some time - If I remove the Authorization item from the request header and make a second request from the same IP, I can still pull the form list even though I am not sending any credentials through.

**Comment by smoyte** [comment]
ELMO uses basic auth so I don't think that's it.

**Comment by smoyte** [comment]
@lognaturel Is anything known about the reason for the bug? Like, has anyone investigated it and knows why it's happening, but can't figure out a way around it, or has the investigation not happened yet?

My guess is something is getting cached in the class that builds the HTTP requests...

**Comment by lognaturel** [comment]
I have a vague memory of thinking about this for a little bit but don't remember what I found. I meant more to say that it's not a regression, it's something about the design of the code. If I remember correctly, if you change the username/password, kill the app and then restart it, then you'll see the auth window pop up as expected. So yes, it's probably a matter of clearing some kind of cache when the username/password are changed!

**Comment by grzesiek2010** [comment]
@hooverlunch @lognaturel 
Are you really able to reproduce this issue using the latest version or even mentioned by @hooverlunch v1.7.0?
I'm not able at all... I tested three different devices and I'm asked about the password every time I change/remove it.

I was able to reproduce the issue using v1.5.1 but it's tricky too:
v1.5.1 is the last version in which we were able to set username and password in two different places:

**In General Setting:**
![screenshot_20171019-112315](https://user-images.githubusercontent.com/3276264/31764318-1c071a68-b4c1-11e7-8bb6-6a99f70da1c1.png)

**and in General Settings -> Configure Aggregate Settings:**
![screenshot_20171019-112326](https://user-images.githubusercontent.com/3276264/31764403-58ce2680-b4c1-11e7-821a-fb8ab6c1f802.png)

If I set my pass using the first option I can reproduce the issue but if I set the pass in that second screen everything works as expected (I'm asked about my pass). 

Everything has been working well since we kept only that second option (v1.6.0 +).

I've noticed only one a bit strange behavior:
If you open Generall Settings just form Get Blank Form View (using three dots/or device menu button) and you set your pass and return to the activity you are able to see a list of for but you can not download them so it's maybe a bit weird but works well.

**Comment by lognaturel** [comment]
@hooverlunch would be great if you could try this on the latest Collect version and see if the behavior is now as you expect.

**Comment by smoyte** [comment]
I confirm the bug is not present in 1.10.2. Yay!

**Comment by lognaturel** [comment]
Another one squashed! 😅
