### ISSUE TITLE
Items disappearing from View Sent Form 

### ISSUE THREAD

**Issue by smoyte** [getodk/collect#1110]
#### Software and hardware versions 
Collect v1.7.0, Android v7.1.2, Nexus 6P

#### Problem description
Items disappearing from View Sent Form screen upon filling out a new instance.

#### Steps to reproduce the problem
1. Fill out instance.
1. Send to server.
1. Delete all saved forms via Delete Saved Form.
1. Confirm shows as deleted in View Sent Form.
1. Fill out another instance.
1. Go back to View Sent Form, first instance has disappeared.

#### Expected behavior
Deleted instances should remain viewable under View Sent Form (with crossed eye icon) forever (?) I am not sure of the exact expected behavior as this feature is fairly new to me but @lognaturel said this isn't it :)

**Comment by grzesiek2010** [comment]
@hooverlunch 
What do you delete in step 3? Instance or form? (I mean saved form or blank form) If you delete an instance it can't by visible in `View sent form` anymore. 

I can see only one bug: Number after `View Sent Form` is not updated immediately.
1. Fill out instance.
2. Send to server.
3. Delete that instance via Delete Saved Form.
4. Go back to main menu I can see `View sent form (1)` despite the fact I removed the only instance

But if I open `View Sent Form` activity it's empty as expected.

Items in View Sent form should be visible if you remove original form but not if you remove an instance as we remove all related data from our database in that case.

**Comment by lognaturel** [comment]
As I remember it, the goal of view sent form was so that enumerators could know that they had successfully sent the submissions they thought they had, even if they had been deleted. Delete was slightly tweaked so that it would remove the submission XML but leave the record in the DB with a delete flag so that the submission could be shown in View Sent Form as deleted. So @grzesiek2010, that instance should still be in View Sent Form. Is that not what you remember?

**Comment by smoyte** [comment]
@grzesiek2010, I delete all saved forms. The instance _is still there after I delete_. It's only after I fill out a new instance that the old one disappears.

**Comment by grzesiek2010** [comment]
@lognaturel @hooverlunch You are right the problem has been implemented here: https://github.com/opendatakit/collect/pull/676/files

**Comment by lognaturel** [comment]
Thank you for reporting @hooverlunch and thanks for the quick find and fix, @grzesiek2010!

I completely missed that #676 interacted with View Sent Form. 😳 This is the kind of thing that only integration tests could really help us out with since it involves a sync task. Will keep thinking about how we could make sure to avoid this kind of regression in the future.
