### ISSUE TITLE
Improving the audio widget

### ISSUE THREAD

**Issue by shobhitagarwal1612** [getodk/collect#1120]
This is the proposed wireframe for the new UI
![audio widget](https://user-images.githubusercontent.com/8918023/26966702-d8dda5dc-4d18-11e7-8da2-cb542e8fe0c4.png)

When no audio file is selected, then the bottom layout with play buttons and seekbar will remain hidden

**Comment by lognaturel** [comment]
I really like that the buttons are still large and visible, that the filename is shown and that the audio progress bar/seeker is easily accessible.

This is related to #641 which @rajatthakur had filed and you might be able to get good ideas from there. One thing we had discussed on his pull request is that there must be a full audio playing interface available like you have in your mockups so that users can pause/seek as desired.
