### ISSUE TITLE
Message in header overlaps location icon on GeoPoint view with map

### ISSUE THREAD

**Issue by mmarciniak90** [getodk/collect#1181]
#### Software and hardware versions 
Collect v1.7.1
Android v4.2

#### Problem description
Header with message: 'Long press to place mark or tap add marker button. Using network. Accuracy is XXm' overlaps location button.

#### Steps to reproduce the problem
1. User start form
2. User is on question with 'Start GeoPoint' button
3. User clicks on the button
4. View with map opens
5. User sees that header with message overlaps location icon

#### Expected behavior
Elements do not overlap

#### Other information 
Discovered during testing [Migrating to Android Support Library #912](https://github.com/opendatakit/collect/pull/912)
![screenshot_2017-06-14-16-23-25](https://user-images.githubusercontent.com/3907554/27137431-3b51e1de-511e-11e7-8a5b-9a56f76d2bd8.png)
![screenshot_2017-06-14-16-21-09](https://user-images.githubusercontent.com/3907554/27137437-3e5507e4-511e-11e7-86ef-4582a03d9006.png)

**Comment by huangyz0918** [comment]
At my quick look, this problem may be caused by the narrow screen ? (I mean the screen resolution or size ,etc)
It's not an issue related to API level, because my Android 4.2 device doesn't have this problem :

|   Android 4.2 (720x1280)          |  Android 4.1 (240x320)     |  Android 4.1 (480x800)     |
| ---- | ---- | :----: |
|<img src="https://i.loli.net/2018/04/05/5ac58571b0b92.png" width = "300" align=center />|<img src="https://i.loli.net/2018/04/05/5ac58b749b00c.png" width = "300" align=center />|<img src="https://i.loli.net/2018/04/05/5ac58c84e90a1.png" width = "300" align=center />|

**Comment by huangyz0918** [comment]
I can give this a quick fix @opendatakit-bot claim
