### ISSUE TITLE
Ex String Widget, Ex Integer Widget, Ex Decimal Widget with `readonly=true()` option allow to use paste option

### ISSUE THREAD

**Issue by mmarciniak90** [getodk/collect#1197]
#### Software and hardware versions 
Collect v1.8.0 beta 10, 
Android v4.1, v4.2, v4.4, v5.1, v6.0

#### Problem description
Ex String Widget, Ex Integer Widget, Ex Decimal Widget with `readonly=true()` option allow to use paste option
#### Steps to reproduce the problem
1. User starts job with Ex String Widget, Ex Integer Widget, Ex Decimal Widget
2. Questions are read only
3. User tap and hold on question
4. User is able to paste some value

#### Expected behavior
Paste option is blocked for read only questions

#### Other information 
Discovered during testing [StringWidget/IntegerWidget/DecimalWidget with option allow to use paste option](https://github.com/opendatakit/collect/pull/1193)

**Comment by grzesiek2010** [comment]
@lognaturel 
It's really funny that @mmarciniak90 has discovered this issue as it's possible only if that widget is `readOnly` :)

Why? because we don't even support paste option in ExStringWidget/ExIntegerWidget/ExDecimalWidget !

In this pr https://github.com/opendatakit/collect/pull/291 we have implemented paste option but only for StrigWidget/IntegerWidget/DecimalWidget look:

https://github.com/opendatakit/collect/pull/291/files#diff-03ff45091550285dd88b56927010c457R1261

So as I said this is possible only if that widget is `readOnly` otherwise `Edit prompt` dialog is shown.

Quick fix: https://github.com/opendatakit/collect/pull/1198
