### ISSUE TITLE
Proposal of adding new simple widget for displaying text.

### ISSUE THREAD

**Issue by grzesiek2010** [getodk/collect#1202]
#### Software and hardware versions 
Current master branch

#### Problem description
The first question from "All Widgets" form is used only for displaying text but disabled EditText is visible below:
![screenshot_2017-06-26-16-45-11](https://user-images.githubusercontent.com/3276264/27545089-393d4d6e-5a8f-11e7-8257-cba028e78b7c.png)

it takes place because we use StringWidget with readOnly option to build this view but StringWidget should display disabled EditText.

I think we should add another widget only to display text that we can use in similar cases.

@lognaturel what do you think?

**Comment by lognaturel** [comment]
Form builders/generators like Build or pyxform generate readonly string widgets as notes so it won't be be something that we can deprecate fully. 

I'd be ok with adding an alternative but I'd like to first be sure that there's no way to make that line disappear. I think it appeared a while after the switch to the support libraries. Was it because of the paste suppression? Is there another way to make it go away when the widget is read-only?

**Comment by lognaturel** [comment]
@grzesiek2010 What do you think of not showing a line when the field is read-only?

Somewhat related to this, it occurred to me that read-only fields are sometimes used to show a value as in the following:
<img src="https://user-images.githubusercontent.com/967540/28395670-70e2212c-6caa-11e7-9618-171cd59fb238.png" width=300>

Those are now looking pretty pale. @yanokwa do you think this is common? Is it worth making a change for this case? If so I can file another issue.

**Comment by batkinson** [comment]
@lognaturel I'm not sure whether you're asking about this or not, but I have actually received complaints from our field staff as recent versions of collect have been delivered over Play. The complaint is that read-only values are really hard to see on the tablets when they are outside. The reason is that pale read-only text you're pointing out. I just wanted to take the opportunity to mention it since you're talking about it.

**Comment by grzesiek2010** [comment]
@lognaturel 
I think we should keep this line to show that it's a StringWidhet/IntegerWidget/DecimalWidget because we should be consistent. If we use readOnly option with SelectOneWidget we can see all options not only the selected one etc.

So readOnly option should just protect from edition. If we want to show a message we should add another widget I think.

**Comment by lognaturel** [comment]
@grzesiek2010 In principle I agree that consistency and separation of concerns is important but we really need to pay attention to actual usage! @batkinson's comment is really important and one we need to pay attention to. Perhaps we could separately discuss introducing new types and recommending deprecating current usage but if we've created a problem for users I think we should start by fixing it as soon as we can and then later consider changing the usage. 

I think that when we were increasing the consistency of the read only modifier, we were thinking of it more as a switch that would be turned on and off such that a value is sometimes read only and under other conditions is editable. But I think that in practice it's used much more common to use read-only fields to echo back a value as demonstrated by XLSForm's use of a read-only text field for notes and @batkinson's comment.

I will file an issue.
