### ISSUE TITLE
Add an option to set an image size in settings

### ISSUE THREAD

**Issue by grzesiek2010** [getodk/collect#1217]
Here https://github.com/opendatakit/collect/pull/1210 we have started a discussion about adding an option to settings in order to setting image size for all widgets. 

My proposal is to add a dialog with three options:
* Normal - by default
* Small - for example if I use my camera I get 1920x1080 pictures originally it's 2073600 pixels so I think small might be normal/2 - 2073600 / 2  = 1036800 it's 1357x764
* Extra small - small / 2

@lognaturel @yanokwa what do you think?

**Comment by kusaasira** [comment]
@grzesiek2010 , was this resolved? 

My suggestion here, I think we can add this under Shared Preferences for the user to be able to adjust to Low Res images as it is with High Res video recording under General Settings.

**Comment by grzesiek2010** [comment]
@kusaasira no it isn't.

I wanted to do that since I implemented the same on a form level https://github.com/opendatakit/collect/pull/1210 but I had more important issues to fix that's why I havent even thought about it much.

I think it should be marked with "needs discussion" label. 

@opendatakit-bot label "needs discussion"

Probably @lognaturel and @yanokwa  have some ideas and I mentioned them above but they are busy so looks like they didn't have time to think about it.

**Comment by acawood777** [comment]
@grzesiek2010 Just to clarify - will the form-level settings overrule any user settings?  

From a project management side it's preferable to be able to force images to a low resolution for a specific form, even if the user happens to change his local settings to high-res, so that we can prevent bloat on the server side.

**Comment by grzesiek2010** [comment]
@acawood777 yes form-level settings should be more important since you can specify max image size for each question there.
Let's assume we have both option implemented.
If you set max pixels in General Settings it should impact all image questions apart from those you specified max pixels on a form level (since as I said it's more important).

**Comment by kusaasira** [comment]
@grzesiek2010 @grzesiek2010 does ODK have any form level settings on the other hand? And would it be hectic too for all the forms each time a new form is downloaded to the phone?

**Comment by grzesiek2010** [comment]
By `form-level settings` I mean this https://github.com/opendatakit/collect/pull/1210 you can find there an example form to use. If you want to set the max-pixels value for specific question you can add for example `max-pixels="1500"` .

It's not like General Settings in the app sorry for misunderstanding it's something you can add in your form.

**Comment by lognaturel** [comment]
Thanks for reviving this conversation. The only thing we need to decide before this can be completed is what the different size options should be. 

Because device cameras vary so much, I strongly feel that the size options should be absolute and not relative to the original image size. For example:

- Original size from camera (default)
- Very small - 640px
- Small - 1024px
- Medium - 2048px
- Large - 4096px

As a reminder, those values will represent the maximum pixels of the long edge of the image. 

@acawood777, @kusaasira and @grzesiek2010 what do you think?

**Comment by grzesiek2010** [comment]
Sounds good to me.

**Comment by grzesiek2010** [comment]
@kusaasira do you want to work on it? Otherwise I'll take it since I've implemented #1210

**Comment by kusaasira** [comment]
@grzesiek2010 please take it on. Will be ready to review and since you have also implemented something similar before, you are in a much better position to do so.

@lognaturel this is a good idea. I second it.
