### ISSUE TITLE
SQL error when downgrading after #1151

### ISSUE THREAD

**Issue by lognaturel** [getodk/collect#1252]
In #1151, some new database columns were introduced to the forms db for auto-send and auto-delete. After running that migration, it is no longer possible to go back to a version previous to it. The reason is that `onUpgrade` had an `else` instead of `else if (oldVersion < 4)` and so the version 4 migration is run even if the current db version is 5.

To reproduce, install the latest from `master` and then install v1.8.1 from the Play Store or checking out the tag. The exception is `ComponentInfo{org.odk.collect.android/org.odk.collect.android.activities.FormChooserList}: android.database.sqlite.SQLiteException: Can't upgrade read-only database from version 5 to 4: /storage/emulated/0/odk/metadata/forms.db`.

This is problematic because users may have reasons to go back to an earlier version of the app. Because this is a database issue, uninstalling and reinstalling the app doesn't help, the `forms.db` would need to be deleted and recreated. 

Is there any way to add database columns to `forms.db` without introducing this problem? @grzesiek2010

**Comment by lognaturel** [comment]
Alternately, what about implementing `auto-send` and `auto-delete` without making modifications to the database?

**Comment by grzesiek2010** [comment]
@lognaturel we could load related form instead of read from database but I don't like such an approach...
It's a problem that has been existed since beginning I think as we haven't handled downgrade. We should fix that problem ASAP and as you know I've started work on this #1253.

So we can try to load those information from the form as I said or just let to crash. We shouldn't avoid extending our tables as it's normal we need that we should fix the problem with downgrade.

In my opinion doing that in another way (than extending database) is not a good solution because in the future we will need to change something in our database anyway and then we will occur the same if someone tries to back to 1.8.1 version (or lower). So I think we should just leave this bug and fix the database to avoid similar issues in newer versions.

**Comment by lognaturel** [comment]
@grzesiek2010 and I spoke a bit about this and decided to delay the `auto-send` and `auto-delete` features for now. It might be best to couple them with a major version change. Since #1151 also included some good refactoring, @grzesiek2010 will issue a pull request taking out the features rather than reverting those commits and we will re-open the issue. He will also look at a longer-term fix for more gracefully handling downgrades (#1253).
