### ISSUE TITLE
post server username as metadata

### ISSUE THREAD

**Issue by mfrasca** [getodk/collect#1306]
this is a spin-off from issue #1009: I landed there because I assumed that the username in the credentials would be used as metadata username and I was surprised it kept appearing blank.
What about doing as @lognaturel suggests: in the metadata section, a "use server username" checkbox, defaulting to checked, and if unchecked, then the metadata username would be enabled and used.

However, when it comes to identifying the submitter, I think I don't particularly like the possibility offered here, stating a different identity just by changing a setting, so I guess that in my own forms I will just rely on the IMEI number.

**Comment by lognaturel** [comment]
What I would recommend for making sure that it can't change is using the admin settings. You can uncheck Admin Settings > User settings > Form metadata to make the form metadata unchangeable. You can also uncheck Admin Settings > User settings > Type to make the server information unchangeable (Type is not a good name and I have filed that at #1311).

Would that work for what you are doing? You may also be interested in the [QR code configuration feature](https://opendatakit.org/2017/06/configure-collect-on-many-devices-with-qr-codes/) if you're configuring multiple devices in the same way.

**Comment by mfrasca** [comment]
Sorry, I'm possibly too new to this data collection interaction to say anything sensible.
My impression and perplexity, what is the point of hiding the possibility of fiddling with identification just behind a "Admin Settings" menu, which any user can access? As far as I'm concerned, the only setting I would trust for identifying the data source is still only the IMEI.

**Unless, that is, unless you would separate the username (server credentials) from username (metadata), then I would trust that the validated user is the one providing the data.**

Other option could be if the username (metadata) was set at installation of the software, and only editable given a password, set at installation.
But then again, I'm not sure if all this security is really needed, apparently it's not. After all, I'm happy with the non-changeable IMEI number in the metadata. For the amount of data providers we have (small botanical gardens), I can easily keep a small table of correspondences, and ignore whatever comes from non-registered devices.

**Comment by lognaturel** [comment]
The idea with Admin Settings is that you set a password that only administrators know in Admin Settings > Admin Password. That's typically what organizations do. The reason I was bringing up the QR code configuration is that you could set up one device exactly as you want it, show its QR code and then configure all the others identically. You can then go in to each phone and simply set values specific to that device (username, for example). 

Using IMEI is also a fine approach but just do make sure every device you use allows Collect to read it (some don't).

I know the documentation on that is pretty spotty and I've filed an issue at opendatakit/docs#54 to make sure we address it in our ongoing documentation effort. I also invite you to join the [ODK forum](forum.opendatakit.org) if you haven't already!

**Comment by acawood777** [comment]
I seem to be chiming in here a little late, but we bumped into this a little while back (as the previous change breaks our implementation) and I want to add a suggestion. I'm not 100% sure on what has actually been implemented, but my suggestion would be:

a) Have 2 username fields:
- username   - this is the credentials username, used for login
- secondary_username - this can be used for identifying a specific enumerator, where several have use the same credentials

b) Include both fields in the form data/metadata - this does away with extra settings checkboxes and confusion there.

-----------
The current deployed version of ODK Collect has broken some of our functionality.

We need access to the credential-username, as that is used to assign ownership of the data once it hits our primary database.

1) Currently we have been getting some submissions where no username was populated. We setup ODK using a JSON settings file created by our own mobile app, and as we didn't know about the extra settings fields (user-defined username) we didn't populate them, resulting in blank usernames.

2) Having the user able to define a different name into the secondary "User-Defined" username field, and having that override the primary credential username in the form submission means we can't verify that the person submitting the data is who they say they are (record ownership can get assigned to users who didn't submit them)

-----------

Question:  What was implemented in #1372   in the end? 

And does my suggestion above make more sense in clarifying this functionality?

**Comment by lognaturel** [comment]
Thanks for chiming in @acawood777 and I'm sorry you're just now getting a response! #1372 ended up being reverted because settings weren't being correctly maintained across updates.

Part of the reason for the change was to, as you say, make it possible to identify enumerators when shared credentials are used. Additionally, it makes it clearer that the username that's preloaded isn't necessarily the username used to auth with the server. This was the case even in the previous implementation when there was a single field. An enumerator could easily fill out all their forms with a certain "server username" set and then change the username upon sending. If it's important that this username have a certain value, then it's best to set an admin password and prevent the user from modifying those fields.

The behavior we're aiming for is:
- on a fresh install, the server username field is used for the preload
- on upgrade, if the server username was set and not the metadata username, the server username field is used for the preload
- on upgrade, if the metadata username was set, the metadata username field is used for the preload

The current implementation in #1545 uses a checkbox to accomplish this. I was thinking this would help make the behavior more clear but your suggestion is better. We could leave the interface exactly as it is now but add a description to the form metadata field that says something like "If blank, server username is used". @grzesiek2010 I think this also simplifies the implementation. Would that work for you?

**Comment by lognaturel** [comment]
Thanks @acawood777 @mfrasca. I think we have a nice, simple solution that makes sense, now. Basically, the server username is used by default but if the form metadata username is set, that's used instead. If you want to ensure the form metadata username can't be changed, you can use the admin settings for that.
