### ISSUE TITLE
User is able to pass any string as an email address in Form metadata

### ISSUE THREAD

**Issue by grzesiek2010** [getodk/collect#1308]
#### Problem description
We are able to pass whatever we want as an email address in Form metadata.

#### Steps to reproduce the problem
1. Go to `General Settings -> User and device identity -> Form metadata`
2. Click on `Email address`

#### Expected behavior
Entered value should be validated

**Comment by lognaturel** [comment]
At first glance, this seems disruptive since users could previously have repurposed the field but the field only became open a few months ago so it's probably ok (it was previously linked to Google Drive / Sheets identity). There is some user benefit.

There are a million and one ways to validate email addresses, some more useful or complete than others. The pull request should clearly document what approach was chosen and why.

**Comment by grzesiek2010** [comment]
@lognaturel 

> The pull request should clearly document what approach was chosen and why

I've added a comment in the code
