### ISSUE TITLE
publishing Kobo Collect on playstore

### ISSUE THREAD

**Issue by aamirshayanshaikh** [getodk/collect#1346]
I am new to Kobo Collect, I was required to add some changes to Kobo Collect project. I have successfully run the project in android studio and have applied changes now need to publish that.

I want to ask that I have cloned this project from GitHub means it has the same package name with which already an APK is published on play-store. What should I do to publish APK that I have created. Should I change the package name or there is another alternate except changing package name, Will there beany licence issue if I change package name of APK ?

**Comment by lognaturel** [comment]
This is Open Data Kit Collect, Kobo Collect is a fork maintained by the Kobo project.

ODK Collect should be usable directly from the Play Store. If there are features you would like to see added, perhaps you could suggest them [here](https://forum.opendatakit.org/c/features) so they could potentially be added to the core? 

If you really need to maintain a fork, you do need to change the package name. You should also change the directory that form files are stored in so that it doesn't conflict with core Collect. You are encouraged to include something like "powered by Open Data Kit" in the interface though this is not currently a strict requirement.

**Comment by aamirshayanshaikh** [comment]
If i am changing the package name definitely I will have to change it in google-service.json file too. so if I change package name in that file obviously I will not have all functionalities because of modification in that file . as far as adding features by kobo collect team is concerned, I am required by client to add some custom themes and languages to it and some other changes that Kobo Collect team may not do for me only. And I tried by changing package name It gave me exception (attempt to invoke interface method int android.database.curser.getColumnIndex()) while saving and finalized form. 

please any solution?
