### ISSUE TITLE
Deprecate ActivityLogger

### ISSUE THREAD

**Issue by shobhitagarwal1612** [getodk/collect#1395]
[ActivityLogger](https://github.com/opendatakit/collect/blob/master/collect_app/src/main/java/org/odk/collect/android/database/ActivityLogger.java) was added for logging all user interface activity into a SQLite database. The main purpose of adding this feature was to prevent reduction in quality of data collection due to Interviewer fabrication (for more info, read [this](http://bbirnbaum.com/assets/publications/dissertation.pdf)). But this feature is **deactivated** by default.
Logging is enabled if the file `sdcard/odk/log/enabled` exists. Given the fact that this feature is neither well documented nor is being discussed despite the fact that the data that is being stored is not complete. So it's better we think about deprecating this feature in future releases.

**Comment by lognaturel** [comment]
👍 The tentative timeline is to deprecate this shortly after #257 is officially announced. The hold up there is that Aggregate does not yet correctly receive or process the files.

**Comment by yanokwa** [comment]
One easy first win on this issue might be to remotely logging if `sdcard/odk/log/enabled` exists. If we keep that log message around for one or two releases, then we'll have data on if anyone uses this.

**Comment by lognaturel** [comment]
We've had two analytics events for this since May 22nd -- one May 29th and one July 19th. This certainly means no campaigns are using it. I don't think we need to do any kind of deprecation warning within the app like we're doing for the `current()` change.

I propose we let folks know with the 1.17.0 release something like "an undocumented database-based activity logger used for early usability research will be removed in the next release. To track enumerator behavior, we recommend using [the audit log feature](https://docs.opendatakit.org/form-audit-log)." Then we can just remove it.

**Comment by yanokwa** [comment]
We forgot to let folks know in the 1.17.0 release (which is fine). I propose we do this in the beta for 1.18 instead 😁

**Comment by lognaturel** [comment]
Oh no! Well, I added a "changes coming next release" section to https://forum.opendatakit.org/t/odk-collect-v1-17/15392 that hopefully some people will see.

I agree we can go ahead and remove it and @shobhitagarwal1612 is so fast he's already on it!
