### ISSUE TITLE
Record altitude and accuracy in Google Maps geotrace points

### ISSUE THREAD

**Issue by lognaturel** [getodk/collect#1459]
#### Software and hardware versions 
Collect v1.10.2

#### Problem description
Altitude and accuracy are always 0.0 in geotraces using Google Maps SDK.

#### Steps to reproduce the problem
Make sure the map SDK in settings is set to Google Maps SDK
Start a geotrace collection from the All Widgets form

#### Expected behavior
Altitude and accuracy should be populated as they are in the geopoint type and in geotrace with OpenStreetMap SDK.

**Comment by lognaturel** [comment]
This is now fixed in master but I can't see when/how it was fixed! @jknightco can you see anything in #1433 that would explain this? Was the `getAnswer` double conversion causing loss of the values or something?

**Comment by heyjamesknight** [comment]
Huh, I don't believe I changed anything there. The section that was removed in getAnswer() was actually just dead code:
```
                for (String sa :  s.split(";")) {
                    String[] sp = sa.trim().split(" ");
                    double[] gp = new double[4];
                    gp[0] = Double.valueOf(sp[0]);
                    gp[1] = Double.valueOf(sp[1]);
                    gp[2] = Double.valueOf(sp[2]);
                    gp[3] = Double.valueOf(sp[3]);
                }
                return new StringData(s);
```

Neither `sp`, nor `gp` actually get used.

**Comment by heyjamesknight** [comment]
Yeah looking at all of my changes, everything else was just pure refactor or removal of dead code. I am happy to retain credit for the fix though :)

**Comment by lognaturel** [comment]
@mmarciniak90 this is very strange. Can you please verify that altitude and accuracy are now successfully saved under all conditions?

**Comment by mmarciniak90** [comment]
Mentioned values are not saved on v1.10.2 and also on master when user uses Google Maps SDK
![screenshot_2017-10-18-11-53-52](https://user-images.githubusercontent.com/3907554/31712540-b0cf54c4-b3fb-11e7-9510-eea51f0b9f0a.png)

Altitude and accuracy are successfully saved when user uses OpenStreetMap SDK on both versions.
![screenshot_2017-10-18-11-57-33](https://user-images.githubusercontent.com/3907554/31712544-b3015436-b3fb-11e7-8a31-4d10395b9d13.png)

**Comment by mmarciniak90** [comment]
@opendatakit-bot unlabel "needs testing"

**Comment by lognaturel** [comment]
Ahh, mystery solved. Thanks so much @mmarciniak90! 😊 I'll update the issue.

**Comment by grzesiek2010** [comment]
@opendatakit-bot claim

**Comment by grzesiek2010** [comment]
@lognaturel 
I investigated this issue and I would vote for removing `Altitude` and `Accuracy` from `GeoTraceWidget` and `GeoShapeWidget` at all.

I've tested altitude using simple `GeoPointWidget` (and OSM maps) and looks like it works incorrectly. We are in Gdańsk
https://www.google.pl/maps/place/Gda%C5%84sk/@54.3635402,18.6050755,11.63z/data=!4m5!3m4!1s0x46fd731c14d4fa6f:0x9bb9fbf163b7be8d!8m2!3d54.3520252!4d18.6466384

it's about 20m above the sea (something like that) but we got values like:

![ialt1](https://user-images.githubusercontent.com/3276264/31886955-c72de27c-b7f6-11e7-8837-9c78a7ff7e20.png)
![alt2](https://user-images.githubusercontent.com/3276264/31886954-c712c88e-b7f6-11e7-9095-6c9544a59a11.png)
![alt3](https://user-images.githubusercontent.com/3276264/31887038-1e706410-b7f7-11e7-8b6e-37145e0740c5.png)

and sometimes something real.

When it comes to Google maps it works better but values I'm receiving are still too high.

The next thing is that collecting `accuracy` for `GeoTraceWidget` and `GeoShapeWidget` and even for `GeoPointWidget` (with `placement-map` appearance) doesn't make sense to me since we can change the location of points manually so it should be super accurate itself.

What do you think @lognaturel

**Comment by lognaturel** [comment]
I think we should always report `altitude` and `accuracy` when points are collected from the GPS device. That is, they should be added to the Google Maps trace activity but they should both be 0.0 when points are manually collected (as with the `placement-map` geo point). 

`accuracy` refers to the accuracy of the latitude and longitude. This can be quite different from the altitude accuracy which is often much worse so I'm not surprised by your findings. I don't think there's much we can do about that.

**Comment by grzesiek2010** [comment]
@lognaturel 
I've added small changes to test it you can look here:
https://github.com/grzesiek2010/collect/commit/74dec985993b4a595f817b8cce34c6a5de77183d
The problem is that there is no easy way to get the altitude if you manually change your marker location (you can move it in another place manually). The Marker class: https://developers.google.com/android/reference/com/google/android/gms/maps/model/Marker
contains only latitude and longitude.

I found this https://developers.google.com/maps/documentation/elevation/start?authuser=0 it works you can look [here](https://github.com/grzesiek2010/collect/commit/ab6a7f0c72fd22869907126666618b8a403ce6c9) (I've tested it using the GeoShapeWidget) but it's an elevation and it takes some time and returns negative values for depth locations on the ocean floor.

The question is: do we need that option in GeoTraceWidget (I mean moving markers manually). Shouldn't it be in GeoShapeWidget only? If we can get rid of that option I can easily fix this issue otherwise as I said there is a problem with getting the altitude.

On the other hand, even if we don't need that option, this problem will return if you want to add the altitude in GeoShapeWidget too. In the title of this issue, there is only GeoTrace so what about GeoShape?
