### ISSUE TITLE
Forks shouldn't report to Firebase Crash

### ISSUE THREAD

**Issue by lognaturel** [getodk/collect#1472]
Currently, we get crash reports from forks and from developer debug builds. Why is this happening and how can we prevent it? The intent is to only get crashes from release builds of the core.

This is problematic because a lot of forks have really buggy extensions that overwhelm the crash list, making it hard to see true Collect crashes.

**Comment by akshay-ap** [comment]
Found this link relevant to the issue.  
[https://firebase.googleblog.com/2016/08/organizing-your-firebase-enabled-android-app-builds.html](url)
There can be separate firebase app for developer builds where the crash can be reported and another app where end user crashes will be reported. 
I propose to create another firebase app with application ID `org.odk.collect.android.debug` and change the `build.gradle (Moudle:collect_app)` as follows :

`
defaultConfig {

     applicationId "org.odk.collect.android"
        // etc...
    }
    buildTypes {
        debug {
            applicationIdSuffix ".debug"
        }
        release {
            // etc...
        }
    }
`

**Comment by NaderBeshr** [comment]
Hi all of you,

in fact i traced that issue and the problem was from (**Timber**)

for each Code of Timer like (**Timber.v, Timber.e, Timber.w,....etc**)
it happen an internal error in the Timber class

this error fire the firebase crash report.
it's even when you use a plain text like this
Timber.v("plainnnnn textttt onlllly") throw the firebase crash report.

the error from **NonNls** inside Timber.java which need "annotations.jar" as a lib.

i added the file (**annotations-10.0.2.jar** as a lib) "Firebase Crash Report" resolved.

Best Regards

**Comment by lognaturel** [comment]
@akshay-ap I think adding the variants is a very good idea. I thought logging wouldn't happen on debug builds because of the conditional block starting on line 274 in `Collect.java` but it doesn't appear to work as expected. Additionally, hopefully adding the `applicationId` explicitly will prevent release builds of forks from logging. And there's no API key specified for Firebase, right? That made me think that only applications released under the ODK Google account would log but apparently not.

@NaderVIP I think you're facing a different problem. Timber is supposed to log to Firebase Crash but only when on a release build (not a debug build). That doesn't seem to be the case. Further, forks with custom `applicationId`s are also logging to the ODK Firebase Crash account. I don't see any exception when making Timber calls and I don't recall having to explicitly include `annotations`. @akshay-ap did you?

**Comment by NaderBeshr** [comment]
am sorry i misdundrstand the isuee, no i git it.

so you need to seprate the logges between developer (fork) and the users (Released)

if this what you want then we have to change the application ID fro the release one

like as @akshay-ap said org.odk.collect.android.debug

**this can be done by changing the application ID from project structure and also you have to change
the file "google-service.json" in "collect-app" directory.**

line 11 : "package_name": "org.odk.collect.android.debug"

result by android studio monitor (debug-time/run-time) :

09-24 22:38:11.324 1548-1565/**org.odk.collect.android.debug** V/FA: Successful upload. Got network response. code, size: 204, 0

**Comment by grzesiek2010** [comment]
@lognaturel I've made a mistake... I [disable timber logs](https://github.com/opendatakit/collect/pull/1554/files#diff-3c113177d1ed88d85228fb0ec9f88210R279) only but crashes are still automatically reported of course.

Probably we should disable it here: https://github.com/opendatakit/collect/blob/master/collect_app/src/main/java/org/odk/collect/android/activities/MainMenuActivity.java#L566 ?

and we should hide that checkbox from `General Settings` -> `User and device identity` if we use other build type than `odkCollectRelease`


Btw. now I wonder why we use Google analytics and not Firebase Analytics? I wonder how it works because we setup `Google Analytics` in `MainMenuActivity` https://github.com/opendatakit/collect/blob/master/collect_app/src/main/java/org/odk/collect/android/activities/MainMenuActivity.java#L567 but crashed are reported to the `Firebase` console, does it work out of the box? Are those crashes visible in both GA and FA consoles?

**Comment by lognaturel** [comment]
@grzesiek2010 Can we also do what @akshay-ap was suggesting to at least not get debug builds logging in the same place? I think that would address a lot of clutter in the logs.

No crashes are logged to GA. I vaguely remember picking GA over FA because at the time the interface was more complete.
