### ISSUE TITLE
All translations are not available

### ISSUE THREAD

**Issue by mmarciniak90** [getodk/collect#1535]
#### Software and hardware versions 
Collect current master

#### Problem description
User does not see all available languages.

#### Steps to reproduce the problem
1. User goes to 'General settings'
2. User goes to 'User interface'
3. User opens list of languages
4. User sees 49 languages

#### Expected behavior
More than 49 directories with translations are visible on project files.
User should see list of all available languages.

**Comment by grzesiek2010** [comment]
There is lack of:
`es_SV` but the related file is almost empty so I think it doesn't make sense to add this language.
`ml` - new language added https://github.com/grzesiek2010/collect/commit/965b5345c853472802ce32b274a1288d17c06fd0 doesn't contain lots of translations but since it's new maybe someone is working on it.
`sv_SE` - Sweden, looks like we should add it.
`tl_PH` Philippines, not sure what is the difference between `tl` and `tl_PH` translations look the same probably it's a different dialect.

**Comment by lognaturel** [comment]
The issue is that those languages aren't in `TRANSLATIONS_AVAILABLE` in `ApplicationConstants`. I agree with what @grzesiek2010 is saying -- `ml` and `sv_SE` should be added but `es_SV` and `tl_PH` are duplicates and shouldn't.

@nribeka You want to take this fun and easy one?! 😄

**Comment by lognaturel** [comment]
Or @codedsun this would be a really nice, quick one to do if you're still looking for an issue to get started. 😊

**Comment by icemc** [comment]
@lognaturel can I go on this fun one. Have been very busy lately but this will be fun and no time consuming. 😊

**Comment by lognaturel** [comment]
Oh yeah @icemc!! 🎉

**Comment by icemc** [comment]
@opendatakit-bot claim
