### ISSUE TITLE
Pictures taken by the SelfieWidget are rotated incorrectly on some devices

### ISSUE THREAD

**Issue by grzesiek2010** [getodk/collect#1552]
#### Software and hardware versions 
Collect v1.10.2

#### Problem description
Pictures taken by the SelfieWidget are rotated incorrectly on some devices.

#### Other information 
This table is from https://github.com/opendatakit/collect/pull/1541 so it might look a little different on v1.10.2 but the problem is visible there too and once we have merged #1541 it will look the same.

| case/device  | Samsung S7 | huawei | sony z3 | samsung J1 | infinix | 
| ------------- | ------------- | ------------- | ------------- | ------------- | ------------- |
| image widget, front camera, vertical | vertical | vertical | vertical | vertical | vertical |
| image widget, front camera, horizontal | horizontal | horizontal | horizontal | horizontal | horizontal |
| selfie widget, front camera, vertical | vertical | vertical | vertical | horizontal | horizontal |
| selfie widget, front camera, horizontal | crash  | upside down | upsiede down | horizontal | horizontal |

**Comment by ShenJack** [comment]
Excuse me,I've been searching on this problem for 2days，and i also found the same problem appears in Google's Camera2 example. 
If you don't mind that  I‘m just an Android greenhand with 1 year experience and  4 months for intern , please asign it to me, I'll try to fix it up with pleasure.
May I claim it ?

**Comment by ShenJack** [comment]
@grzesiek2010 @lognaturel

**Comment by grzesiek2010** [comment]
@ShenJack yeah sure, sounds good! You can claim any issue by yourself, here you can find a way how to do that https://github.com/opendatakit/collect/blob/master/CONTRIBUTING.md

> i also found the same problem appears in Google's Camera2 example

You are right.

**Comment by ShenJack** [comment]
@opendatakit-bot claim

**Comment by ShenJack** [comment]
@grzesiek2010 
Things got much more clearer.
I guess the cause is the incorrect use of Google's example, the example is only used for back camera.
When switching the code from back into front camera, some code hasn's been changed thoroghly, thus making some device seem allright while some produce error.

After fix, Test cases has passed on 
samsung   s6                7.1.1     front camera 270°
oppo         a53             5.1.1                           270°
meizu        m1 metal    5.1                              270°

I still wonder the stability on other devices whose front  is not 270°, but 270°  is mainstream.
Maybe more tests are needed.

I'll open a PR soon.
