### ISSUE TITLE
Class cast exception in FormController getSubmissionMetadata

### ISSUE THREAD

**Issue by lognaturel** [getodk/collect#1560]
From Play Store crashes ([here](https://play.google.com/apps/publish/?account=6923365842552008664#AndroidMetricsErrorsPlace:p=org.odk.collect.android&appVersion=2453&clusterName=apps/org.odk.collect.android/clusters/dfddbf49), requires credentials)

`StringData sa = (StringData) v.get(0).getValue();` is the line that causes problem. Could it be because the value is null? I can't remember whether that can cause a class cast exception or not. It would be good to try to repro this because I'm not sure what would cause the value not to be `StringData`.

**Comment by grzesiek2010** [comment]
@lognaturel 
Everything is ok if the value is null. The problem is if the value has a different type than `StringData`.
I've found report on firabese https://console.firebase.google.com/project/api-project-322300403941/monitoring/app/android:org.odk.collect.android/cluster/1f36b0be?reportTypes=FATAL_JAVA&duration=2592000000&appVersions=2453
which contains more information. Ther you can see that the value has `IntegerData`, `DateData` or `BooleanData` type what is really strange since it should be always `StringData` as I understand.

I wasn't able to reproduce the issue but I think it's the Javarosa side.

**Comment by lognaturel** [comment]
Aha! So probably if we build a form that references a non-string field in the instance name we get that crash. Could you please give that a try, @grzesiek2010? If that gives a reproduction then I think we can probably file an issue on the JR side to cast whatever fields are used in the instance name to strings.

**Comment by lognaturel** [comment]
Interesting note -- I've never run into this because I always build up an instance name through concatenation to include the form name and make it nicely formatted. But now that I think about it I can imagine someone just wanting to use a date or just a number.

**Comment by grzesiek2010** [comment]
@lognaturel I created the issue on the JR side https://github.com/opendatakit/javarosa/issues/210

**Comment by lognaturel** [comment]
Would something like the following work?
```
IAnswerData sa = v.get(0).getValue();
if (sa != null) {
    instanceName = sa.getDisplayText();
}
```
