### ISSUE TITLE
Refactor activities using google sheets and google drive apis

### ISSUE THREAD

**Issue by shobhitagarwal1612** [getodk/collect#1568]
Activities such as `GoogleDriveActivity`, `GoogleSheetsUploaderActivity` and `InstanceGoogleSheetsUploader` use Google Drive / Google Sheets API and have a lot of common code. So these classes must be refactored to as they are already very large in size and hence not easy to maintain.
So I propose that we should create 3 classes :
 - GoogleAccountsManager - handling google accounts
 - SheetsHelper - google sheets api and dependent methods
 - DriveHelper - google drive api and dependent methods

@opendatakit-bot claim

**Comment by lognaturel** [comment]
@shobhitagarwal1612 I know you mentioned that you were going to be really busy for a couple of weeks and since you're close to completing this I think you should stay assigned to it. @jknightco made some suggestions on how to increase testability and is ready to work with you to put some tests in when you're around!

**Comment by shobhitagarwal1612** [comment]
@lognaturel Thank you for the reminder. I will keep updating the PR with the recently added changes and the changes suggested by @jknightco. Then I will start adding tests soon

**Comment by lognaturel** [comment]
That's going to be great, @shobhitagarwal1612!

**Comment by lognaturel** [comment]
#1569 is awaiting final review.
