### ISSUE TITLE
Update translations for October 2017 causes lint errors

### ISSUE THREAD

**Issue by grzesiek2010** [getodk/collect#1573]
I've noticed that `./gradlew lint` command finishes with errors due to this commit https://github.com/opendatakit/collect/commit/08bdef0b9801875c752472db48928c16f30cd4ce

**Comment by lognaturel** [comment]
We need to be sure to always lint after updating translations. Would be good to document that whole process!

The issue seems to be that Arabic translations don't all use placeholders. @NaderBeshr I know you were involved with Arabic translations recently, could you please help us fix these? 

The problem is that translated strings need to have the same placeholders as the original strings. For example, if the string is `View Sent Form (%s)`, then translated strings should also include `%s` so that the number of sent forms can be included in the text. Right now the translation for that string is `عرض الاستمارات المرسلة` but it should be something like `(s%) عرض الاستمارات المرسلة`. Transifex lets you click on the placeholder which has a pink background to insert it where it should go.

The way to fix them would be to go to https://www.transifex.com/opendatakit/collect/translate/#ar and update the following strings:
بيانات اعتماد مصادقة الخادم
تمت عملية المسح.
حدث خطأ اثناء معالجة قالب الاستمارة
الهاتف لايحتوي على خاصية Base64
عنوان غير صحيح
عنوان غير معروف
حقل خاطئ في اوراق جوجل
حقل خاطئ في مصدر اوراق جوجل
خطأ اثناء رفع الوسائط
عرض الاستمارات المرسلة

Someone who knows Arabic will need to do it!

**Comment by grzesiek2010** [comment]
@lognaturel 
So maybe we should remove those translations for now because we are blocked with our prs.

**Comment by lognaturel** [comment]
Agreed @grzesiek2010

**Comment by NaderBeshr** [comment]
i will fix the translation.

**Comment by lognaturel** [comment]
Thank you @NaderBeshr!! Let me know if you have any questions about how the placeholders work or what they're for. 😊

**Comment by NaderBeshr** [comment]
no this is my fault, and i feel responsible about it.

thank you for you @lognaturel  and you @grzesiek2010 

Best Regards

**Comment by NaderBeshr** [comment]
done.

**Comment by NaderBeshr** [comment]
@lognaturel (This is so embarrassing) LEN.# 😊

i didn't yous it before.

but now i know why we us it.

**Comment by lognaturel** [comment]
😊

Thanks so much for getting it fixed for we non-Arabic speakers! Open source, open life, right? ✨

**Comment by NaderBeshr** [comment]
yep. ( open life, open mind, open source ) 😊. i have a great teacher she✨ told the same meaning before , in fact she have a beautiful inspiration.
see you in our galaxy soon.
i all most done.
