### ISSUE TITLE
Can not download media files using Google Drive

### ISSUE THREAD

**Issue by grzesiek2010** [getodk/collect#1591]
#### Software and hardware versions 
Collect v1.11.0

#### Problem description
The option to download media files from GD is not implemented.

#### Steps to reproduce the problem
1. Upload a form and with additional files to you GD
2. Try to download the form

#### Expected behavior
The form and media folder are downloaded.

#### Other information 
https://forum.opendatakit.org/t/dynamically-loaded-multiple-choice-data-with-google-drive/10404/2

**Comment by yanokwa** [comment]
Are you sure it's not implemented? https://github.com/opendatakit/collect/issues/290 suggests that it was at some point.

**Comment by grzesiek2010** [comment]
@yanokwa Hey you are right. I only returned to v1.5.0 and it wasn't implemented in that version but it was in 1.4.16. Looks like it was removed when we implemented new API. I'll try to find out why but @shobhitagarwal1612 maybe you remember https://github.com/grzesiek2010/collect/commit/4673b97e98971e1ca8a9d1094c6f49fc3d38673b looks like it was your part.

**Comment by shobhitagarwal1612** [comment]
@grzesiek2010 Yes you are right. It was me who updated it to google drives API but didn't implement the download of media files with the form as I did not knew about this feature back then. Sorry for the inconveniences caused.

I have submitted #1569 to refactor the classes I updated at that time (updating sheets and drives api)

**Comment by grzesiek2010** [comment]
> I have submitted #1569 to refactor the classes I updated at that time (updating sheets and drives api)

but this refactoring doesn't contain the fix right?

**Comment by grzesiek2010** [comment]
@opendatakit-bot claim

**Comment by shobhitagarwal1612** [comment]
> but this refactoring doesn't contain the fix right?

Yes, it doesn't. But it makes those classes more lightweight and modular

**Comment by DataStrategist** [comment]
Hi all. @shobhitagarwal1612 @lognaturel does this mean that Google Drive will *NOT* be able to host media files? This is really regrettable. Let me try to convince you with my use case: https://forum.opendatakit.org/t/picture-output-from-barcode-scan/19121

It seems there's a decent way... I could also even optimize upon the method listed thre, but we DO need to be able to get the media folder onto the phone. If this won't work, perhaps it should be listed as a limitation on this page: https://docs.opendatakit.org/collect-connect-google/?

**Comment by shobhitagarwal1612** [comment]
This issue was fixed about 1 year ago. I'm pretty sure that this works in the latest version. Please consider checking that first and if you face any problem then we can discuss it over here or in the forum

**Comment by DataStrategist** [comment]
Sorry, I did indeed check... I only came here when the behavior was incorrect. I have identified the exact problem. Everything works as expected when I'm downloading the app FROM MY OWN GOOGLE DRIVE... however, it breaks if the form is created in a seperate account and then shared with me. My steps to replicate the problem: 

 1. I have used [THIS form](https://opendatakit-a3b1.kxcdn.com/uploads/default/original/2X/a/aa47db652f6012e1cb4fbf7f35de3346067ce973.xls), which I copied to google Drive `A`. 
 2. I also created a folder in google drive `A` called `picturecheck-media`, and added one image inside called `john.jpg`.
 3. So now, with both the survey and the media folder in my google drive `A`, I ASSIGN PERMISSION to both the form and the folder to the enumerator account `B`. I have confirmed that the image inside the folder in GD `A` inherits the share to account `B`, and it does. 
 4. My phone is authenticated to google drive account `B`. I am able to download the form to my phone, but already here it doesn't download the image. I can verify that: start filling the form, and feed this to the QR-code reader:
![image](https://user-images.githubusercontent.com/8094091/55990821-aecbd100-5c76-11e9-9554-037747af5a54.png)

(this maps to `001`). 

 5. As soon as I move to the next screen, I get the following error: 

`File: /storage/emulated/0/odk/forms/picturecheck-media/john.jpg is missing`. 

Now I have looked in my phone and I *have* noticed that this folder is being created: 

`root/sdcard/odk/forms/picturecheck-media`

but the jpg is not being copied in from google drive. If I specifically copy the image into the above folder (the root one), then the image does display as expected in the app.... but obviously we can't rely on that.

HOWEVER, if I copy the form and the folder to the google drive of account  `B`, then everything works as intended.... so clearly the problem is in the fact that the share of contents inside the folder `*-media` are not being passed on.

Can I provide more details?

Testing on a Google Pixel 1 phone running ODK Collect v1.21.1

**Comment by shobhitagarwal1612** [comment]
Thank you for the detailed information. I'll try to look into it tomorrow.

**Comment by grzesiek2010** [comment]
Yeah, I can confirm that the behavior here is not perfect. From my quick investigation I know that it works well if you shared the entire folder where you have that form and media folder but if you share an xml file and the folder with media files separately then only your form will be downloaded.

@DataStrategist could you confirm that it's ok if you share the parent folder?

**Comment by DataStrategist** [comment]
@grzesiek2010 Confirmed! Everything works as expected if I place both into a parent folder and share that. I will say that the first time I tried it it didn't work, but when I deleted the form, and redownloaded it all worked correctly! Thanks to both! 👍

**Comment by grzesiek2010** [comment]
Great. I think the behavior is ok but it should be documented so I filed the issue https://github.com/opendatakit/docs/issues/1009
