### ISSUE TITLE
Make offline basemaps available from general settings

### ISSUE THREAD

**Issue by lognaturel** [getodk/collect#1610]
When Google Maps SDK is selected as the Mapping SDK, if there are offline basemaps available, after the built in basemaps (Streets, Satellite, etc), display a "Offline Layers" heading and a list of offline layers. This will allow enumerators to set the offline layer once for use across multiple forms/instances. Offline map tiles are described in links from https://github.com/opendatakit/docs/issues/3

The dialog will need to scroll to fit all. This should be resilient to things like manual deletion of the selected offline base map. In that case, the selected basemap should default back to Streets.

**Comment by grzesiek2010** [comment]
So it will look like eg:

**Online Layers**

- Streets

- Satelite

- Terrain

- Hybrid

**Offline Layers**

- layer1

- layer2

- layer3

It might be confusing because it would be two separate lists but only one selected option allowed.

So maybe one list like now but with tags: Online/Offline?
something like that:

**Basemaps**

- Streets (Online)

- Satelite (Online)

- Terrain (Online)

- Hybrid (Online)

- layer1 (Offline)

- layer2 (Offline)

- layer3 (Offline)

what do you think @lognaturel ?

**Comment by lognaturel** [comment]
I like it, @grzesiek2010. I think we can leave the standard ones as they are now -- Streets, Satellite, etc without any parentheses -- and only add the parenthetical for offline layers. Do you think `(offline)` is the right text? We could also do `(custom)` or `(custom, offline)`.

**Comment by grzesiek2010** [comment]
@opendatakit-bot claim
