### ISSUE TITLE
Memory leak : GeoPointMapActivity

### ISSUE THREAD

**Issue by mmarciniak90** [getodk/collect#1646]
#### Software and hardware versions 
Collect master

#### Problem description
![screenshot_20171116-133751](https://user-images.githubusercontent.com/3907554/32891859-8e5d4f3c-cad4-11e7-809d-deaafeeaf8ec.png)

#### Steps to reproduce the problem
1. User opens Geopoint Widget
2. User clicks on device back button

**Comment by dcbriccetti** [comment]
@opendatakit-bot claim

**Comment by dcbriccetti** [comment]
This one is harder than the other leak. I’ve narrowed it down to here, in GeoPointActivity.

```
@Override
public void onClientStart() {
    locationClient.requestLocationUpdates(locationListener);
}
```

If requestLocationUpdates is called with *anything*, even a static field with an instance of a separate, top-level class with empty methods, it leaks.

**Comment by lognaturel** [comment]
CC @jknightco since you're in this code for #507

**Comment by heyjamesknight** [comment]
@dcbriccetti I can claim this as it'll likely get overwritten by the Geo refactors.

**Comment by heyjamesknight** [comment]
(Also it looks like it was my code that caused it in the first place).

**Comment by zestyping** [comment]
It looks like the problem is that `requestLocationUpdates()` is called but `stopLocationUpdates()` is never called, so the listener stays attached forever.  In fact, `stopLocationUpdates` never appeared anywhere in GeoPointMapActivity, GeoShapeActivity, or GeoTraceActivity back in 2017 when this issue was opened.

Today, this is handled in GoogleMapFragment for all three activities, and it's an easy fix there.
