### ISSUE TITLE
Automatically generate commas in value fields for every 1000

### ISSUE THREAD

**Issue by yanokwa** [getodk/collect#1674]
From the post at https://forum.opendatakit.org/t/automatically-generate-commas-in-value-fields-for-every-1000/10633

* Display thousand separators in ODK collect, while enumerators type (so don’t actually store them)
* If possible, but not necessary: use the system-specified thousand separator (so comma or period depending on the language used on the phone or tablet)
* Perhaps users can specify this option in the appearance column when creating an XLSForm.

**Comment by dr0pdb** [comment]
@yanokwa I would like to work on it !
Here is what i intend to do:
1. Display thousand separators using a custom ```TextWatcher```
2. Provide a method to remove the separator from the ```EditText``` string and get plain double string.
3. By-default use the system-specified thousand separator.
4. Users can specify the option(in appearance column) to chose which character(comma or period) to use as thousand separator.

**Comment by dr0pdb** [comment]
@opendatakit-bot claim

**Comment by lognaturel** [comment]
Awesome, @srv-twry!!

I think the appearance should be to determine whether or not to display the delimiter, not for which delimiter to use. This is because some locales don't commonly use thousands separators and they can look strange. I think the default behavior for numeric input should be unchanged and then when the appearance is on the delimiter matching the locale should be used. 

What do others think?

**Comment by dr0pdb** [comment]
> I think the appearance should be to determine whether or not to display the delimiter, not for which delimiter to use 

Yes, i misunderstood it.

**Comment by dr0pdb** [comment]
@lognaturel Should i wait for other's suggestions or start working on it ?
