### ISSUE TITLE
Setting to prevent backwards movement can be bypassed

### ISSUE THREAD

**Issue by lognaturel** [getodk/collect#1675]
#1457 added a setting to prevent backwards movement in forms. From @kkrawczyk123, this can be bypassed under certain conditions:
- When minimizing throws user out to main collect menu, it happens sometimes but it can be difficult to reproduce.
- The same happens when user restart phone or turn it off during filling form which user can do accidentally.
- In case of incoming call during filling form.
- And when user’s phone discharge during filling survey.

I believe this is all because it then recovers from a savepoint and displays the hierarchy view/jump screen, allowing the user to select an arbitrary question to start from.

What are options for preventing this? Can we find out the last question that was edited and go straight there?

**Comment by grzesiek2010** [comment]
@lognaturel 
You are right it's because of recovering from a savepoint.
What can we do? `FormIndex implements Serializable` so maybe we can try to save last known FormIndex to file and then read that file. The file should be saved in .cache dir like savepoint file.

Here is an example, it works but it isn't tested well so let me know if you like it and then I can go ahead.
https://github.com/grzesiek2010/collect/commit/c9e9fe2cb21ccbccb5ecfbb4ef0b5a156315394e
