### ISSUE TITLE
Should sending form with correct url contain “/submission” in the end of url address?

### ISSUE THREAD

**Issue by kkrawczyk123** [getodk/collect#1686]
I have a question connected to [#1672](https://github.com/opendatakit/collect/pull/1672) When I investigated that case I tested form with correct url address and I wasn’t able to send it to aggregate until I add at the end of url “/submission”. After that, sending worked properly. So, You want to validate url in form, should “/submission” after url without which you are not able to send form to aggregate be validated too? Or maybe I misunderstand something? @lognaturel @yanokwa ?

**Comment by lognaturel** [comment]
Good question. You do in fact need the full submission URL. Unfortunately, we can't really validate it because some servers may use endpoints other than `/submission`. That's why there's an `Other` category in the server settings -- it allows people to use custom servers with their own submission and form listing URLs. I don't know how common this is in practice but it is currently supported. Does that make sense?

**Comment by kkrawczyk123** [comment]
Yes. it does :)
