### ISSUE TITLE
Problem with two forms with the same id and form version

### ISSUE THREAD

**Issue by grzesiek2010** [getodk/collect#1693]
#### Software and hardware versions 
Collect v1.11.1

#### Steps to reproduce the problem
1. Download any form from Aggregate
2. Delete that form from Aggregate
3. Edit the form (without changing form id or form version) and upload again
4. Download the form again

#### Problem description
I can see two forms with the same id and version number on your device. We can't use both of in that case:
![screenshot_2017-12-08-17-44-26](https://user-images.githubusercontent.com/3276264/33775709-8327c97c-dc3f-11e7-9a56-bf40398dec44.png)

#### Expected behavior
An older form should be removed automatically.

any thoughts?

**Comment by grzesiek2010** [comment]
@opendatakit-bot claim

**Comment by lognaturel** [comment]
An alternative would be to use form hash to uniquely identify forms rather than a combination of form and version. Ultimately, the requirement that users manually specify a version name is a little arbitrary. What makes forms different is that their contents are different. Maybe even simpler is to use the hash as a tie breaker if there are duplicates for id/version. This would require storing the form hash in the instances table.

Using the hash information would set us up to eventually allow and work with deeper, structural form changes. Some servers already allow these (e.g. Ona).

**Comment by grzesiek2010** [comment]
@lognaturel 
We can't use md5Hash in this case. If the form we try to download is identical (the same md5 hash) we just skip downloading. As I described in step 3 we need to change something in such a form (eg. question text).

Then we have the same id, the same version number but different hashes and in a result two forms, we can't use. 

To sum up: we need to use form id and version (for example as a UNIQUE with ON CONFLICT REPLACE).

**Comment by grzesiek2010** [comment]
@lognaturel 

I investigated this issue deeper and my first idea was to use:
`UNIQUE (jrFormId, jrVersion) ON CONFLICT REPLACE`
but unfortunately, it doesn't work well with nullable columns like `jrVersion`. It would be risky to make `jrVersion` not null and a bit pointless.

So my second idea is to delete existed form with the same id and version number like we try to add. Here is an example: https://github.com/grzesiek2010/collect/commit/b5255a371d09c7721b851902d0cdf883718654fb

Let me know if you like this approach and I should go ahead.

**Comment by lognaturel** [comment]
What I was trying to say is that if forms were uniquely identified by their hashes (and instances kept track of what form hash they correspond to rather than id+version), this case wouldn't be a problem.

If I understand correctly, what currently happens is that the XML is replaced but two db records are created, is that right? What you're proposing is to remove the older db record. What happens when there are editable instances still on the device? I suppose those can't be edited anymore unless the new form is a superset of the old one?

I imagine this isn't a super common case. I propose we wait until a user reports this so we can get insights on what they're trying to accomplish.

**Comment by grzesiek2010** [comment]
> If I understand correctly, what currently happens is that the XML is replaced but two db records are created, is that right?

No. We have both forms and both records in the database.

> What you're proposing is to remove the older db record. What happens when there are editable instances still on the device?

I can still edit and send such forms.

> I imagine this isn't a super common case. I propose we wait until a user reports this so we can get insights on what they're trying to accomplish.

Ok.

**Comment by lognaturel** [comment]
#4237 is related. https://forum.getodk.org/t/downloaded-two-different-forms-with-the-same-form-id-and-version/31275 and https://forum.getodk.org/t/collect-v1-28-2-error-about-two-different-forms-with-same-formid-and-version-and-constraints-not-accepting-valid-values/30645/17 describe some scenarios that lead users to this (they're not common).

**Comment by lognaturel** [comment]
This is a painpoint for Central drafts. Let's say we have formid form1 and version 1 as a draft. Then we make changes to the form def and update the draft without changing the version (typical for drafts). Collect will internally represent those two form defs differently. It will work fine for creating new instances. But finalizing an instance will fail with an error about how the formid and version are the same. This is not a good user experience.

As far as I can tell, our two options are
1) change the instance db schema to join using something unique like the form db id or form hash (as I described above)
2) when receiving a formid/version match, fully replace the existing one

I think 2 is the most useful. Given that Central will only allow a formid/version match for entity list updates, drafts or deleted and recreated forms, it seems like the expected behavior. 1 is a bigger change and would also require addressing opening saved instances or savepoints with the latest form def (some of this was discussed at https://github.com/getodk/collect/issues/4879). E.g. if you are working on a draft, fill out a form and save it, the next time you open it, you'd like for it to open with the latest form def.

For whatever reason, we've also been getting more reports of this on the forum.

@grzesiek2010 what do you think of option 2? Seems like it would be a small change?

**Comment by grzesiek2010** [comment]
> what do you think of option 2? Seems like it would be a small change?

Yes that would basically mean updating our `DatabaseFormsRepository#save` method which already decides whether a new form should be added or just updated based on `dbId` presence. So we would need to add one more if statement to check if the database already contains a form with the same id and version and call update in this case too instead of insert.

You are right there are more and more reports on the forum so it would be good to fix it once and for all. It's not only a problem with Central drafts... some time ago I played with `ONA` and they have an option to replace a form and you can just add a form with the same id and version but it's their problem.

**Comment by lognaturel** [comment]
Thanks, let's do it.

**Comment by lognaturel** [comment]
A test from @seadowg found in notes: https://gist.github.com/seadowg/6314b7fc3887d30c016eea85928680ac . He also said "I think we can even just soft delete the "old" version to get it working" but I'm not sure that's necessary.

We were talking about this in the context of entities. In Central, when testing a draft entity registration form, we'll want to verify that draft entities are actually created which will require a draft form submission. That won't generally be possible unless we address this issue, that's why it's more pressing now (@grzesiek2010 I had kind of lost track of the root reason why this was feeling more important, here it is).
