### ISSUE TITLE
Notification icon is not consistent on all Android versions 

### ISSUE THREAD

**Issue by mmarciniak90** [getodk/collect#1753]
#### Software and hardware versions 
Collect v1.12.2

#### Problem description
Notification icon depends on Android version

#### Steps to reproduce the problem
1. Notification appears
2. User sees notification icon

#### Expected behavior
Notification icon looks the same on all Android versions

#### Actual behavior
Colorful notification icon is visible on Android: 4.1, 4.2, 4.4, 5.1, 7.0
![screenshot_20171222-143939](https://user-images.githubusercontent.com/3907554/34300111-e1b1fcb4-e726-11e7-93cc-7b38dfd40d1c.png)

White notification icon is visible on Android: 6.0, 8.0
![screenshot_20171222-143930](https://user-images.githubusercontent.com/3907554/34300125-f4e06fbe-e726-11e7-8ab8-8e7701938a89.png)

**Comment by grzesiek2010** [comment]
@mmarciniak90 @lognaturel 

I think it's because we use our icon as a small icon https://github.com/opendatakit/collect/blob/master/collect_app/src/main/java/org/odk/collect/android/receivers/NetworkReceiver.java#L227 and an info icon as a large icon https://github.com/opendatakit/collect/blob/master/collect_app/src/main/java/org/odk/collect/android/receivers/NetworkReceiver.java#L232
 it should be the other way around I guess but it might be really related to different android versions.

@opendatakit-bot label "needs discussion"

**Comment by lognaturel** [comment]
This only becomes relevant if there are possibly notifications, right?

**Comment by lognaturel** [comment]
To reproduce this, set forms to "Auto Send" from form management settings (see https://docs.opendatakit.org/collect-settings/#form-management-settings), fill and finalize a form and then let it auto send. You should receive a notification.

Try this on emulators running different Android versions and try @grzesiek2010's proposed fix.

**Comment by arundhatigupta** [comment]
@opendatakit-bot claim

**Comment by Lereena** [comment]
@opendatakit-bot claim

**Comment by Lereena** [comment]
The guildines (http://www.androiddocs.com/design/style/iconography.html) says that starting with Android 5.0 the icon should be entirely white, and the"flat and simple" style of it should be used. The icon is simply rendered in white. 
Apparently, the application should change the design of the icons so that it meets the requirements of new versions. For versions 21+, use the white notification icon in the svg format. For versions below, this is not possible, so it is worthwhile to simulate it in PNG format, using the same image that is specified in the SVG.  It is possible to do checking the current API level before creating NotificationCompat.Builder, and if it is below 21, assign a PNG to the icon, otherwise SVG.  I made a suitable image for the notification icon, but it's in the PNG format, and I could not find a way to convert it to SVG without using paid software. It will be good if someone can convert it and use the described method.
My image can be downloaded from Google Drive: https://drive.google.com/file/d/17tmmJ_25H6p6cvF9Zu7pNZ6p68HQ_zb3/view?usp=sharing

**Comment by Lereena** [comment]
@opendatakit-bot unclaim

**Comment by lognaturel** [comment]
That icon is great, @Lereena! 

One tool someone could consider for the conversion is Inkscape: https://inkscape.org/en/doc/tutorials/tracing/tutorial-tracing.en.html

**Comment by ravi808** [comment]
@lognaturel  the web page you mention above is not working.

**Comment by ravi808** [comment]
@opendatakit-bot  claim

**Comment by ravi808** [comment]
@lognaturel hello!
The different notification was due to two different images in different android version. I have since removed the different images with the same with the single image but the notification has ceased to appear. 
`        NotificationCompat.Builder builder = new NotificationCompat.Builder(Collect.getInstance())
                .setSmallIcon(R.drawable.notes)
                .setContentTitle(Collect.getInstance().getString(R.string.odk_auto_note))
                .setContentIntent(pendingNotify)
                .setContentText(message.toString().trim())
                .setAutoCancel(true)
                .setLargeIcon(
                        BitmapFactory.decodeResource(Collect.getInstance().getResources(),
                                R.drawable.notes));`

**Comment by ravi808** [comment]
@opendatakit-bot  unclaim

**Comment by grzesiek2010** [comment]
@opendatakit-bot claim
