### ISSUE TITLE
Name is shown instead of label in hierarchy view for external itemsets

### ISSUE THREAD

**Issue by lognaturel** [getodk/collect#1758]
#### Software and hardware versions 
Collect v1.12.2

#### Problem description
Name is shown instead of label in hierarchy view for external itemsets.

#### Steps to reproduce the problem
Load a form with external itemsets such as [cascading_select_external_itemsets.xml.txt](https://github.com/opendatakit/collect/files/1591522/cascading_select_external_itemsets.xml.txt) and
[itemsets.csv.txt](https://github.com/opendatakit/collect/files/1591523/itemsets.csv.txt). Select some options and go to the jump screen / hierarchy view. Notice that the value names rather than the labels are shown. For that specific form above, the first choice (state) is from internal choices so it works properly. The following cascading choices are from the external csv. Choose Texas > Cameron > This is a test to see the problem clearly.

#### Expected behavior
The labels should be shown in the jump screen / hierarchy view.

**Comment by codedsun** [comment]
@lognaturel how can I load the form, I am unable to reproduce the problem. Can u tell me how to do that plz

**Comment by lognaturel** [comment]
Hi @codedsun! You can start with step 3 at https://github.com/opendatakit/collect#testing-a-form-locally. In this case, you'll push the form to `/sdcard/odk/forms` and you'll also need to push the csv file to a media folder. What I usually do is `adb shell` to go into the device and then `mkdir /sdcard/odk/forms/cascading_select_external_itemsets-media` to create the media folder. Then you can `adb push itemsets.csv /sdcard/odk/forms/cascading_select_external_itemsets-media`

**Comment by codedsun** [comment]
@lognature in the hierarchy view, we are getting city as test1? is this the issue as far as I have understood, it should be showing the value?

**Comment by lognaturel** [comment]
Yes, that’s right.

**Comment by codedsun** [comment]
@lognaturel Could you guide me more on which class file corresponds to showing name from datasets :( I am unable to track

**Comment by akshay-ap** [comment]
@opendatakit-bot claim

**Comment by akshay-ap** [comment]
Initial analysis show that in `org.odk.collect.android.utilities.FormEntryPromptUtils.getAnswerText()` is returning `name`. i.e if Label is `This is a test` then its name `test1` is returned.
This is due to `FormEntryPrompt.getAnswerText()`
In given ` cascading_select_external_itemsets.xml.` form, this happens for `county` and `city`. But, works correctly for `state`.

**Comment by akshay-ap** [comment]
The issue needs a bit of understanding of javarosa library source code. I would need more time to find the cause of the problem. I am learning gradle build process to make changes in javarosa and easily test it on collect.
There has been discussion on it here :
https://opendatakit.slack.com/archives/C389J6X0W/p1516726596000326

**Comment by akshay-ap** [comment]
Flow goes like this:
To display the selected labels :
In `FormHierarchyActivity`
      line 304 :
                          `String answerDisplay = FormEntryPromptUtils.getAnswerText(fp, this);`

In `FormEntryPromptUtils`
The method `getAnswerText(FormEntryPrompt fep, Context context)`
uses `javarosa` API `org.javarosa.form.api.FormEntryPromt` 

In `org.javarosa.form.api.FormEntryPromt.java`
Line 176 onwards :

            if(data instanceof SelectOneData) {
                //This is Excecuted for selecting `state` (for the mentioned form cascading_select_external_itemsets.xml.txt )
                text = this.getSelectItemText((Selection)data.getValue());
            } else if(data  instanceof SelectMultiData) {
                StringBuilder b = new StringBuilder();
            List<Selection> values = (List<Selection>)data.getValue();
                for(Selection value : values) {
                    b.append(this.getSelectItemText(value)).append(" ");
                }
                text = b.toString();
            } else {
                //This is Excecuted for selecting `city` and `county`
                // `data` is an instance of `StringData` class
                text = data.getDisplayText();
            }


In `StringData` class `name` is stored and `getDisplayText()` method returns it. This is the reason why `name` is displayed in hierarchy view.

Hope I am able to explain the senario.

The solution is to query the `label` instead of `name`. I am working on it to find where and how `label` is stored. @lognaturel Do you know how `label` is stored during form loading?
