### ISSUE TITLE
Submission is doubled on Google Sheets if the user minimize app during sending and `Do not keep activities` option is turned on

### ISSUE THREAD

**Issue by mmarciniak90** [getodk/collect#1777]
#### Software and hardware versions 
Verified Collect v1.11.1

#### Problem description
Submission is doubled on Google Sheets if the user minimize app during sending and `Do not keep activities` option is turned on

#### Steps to reproduce the problem
1. `Android Settings` -> `Developer options` -> `Do not keep activities` option is turned on
2. User sends finalized forms to Google Sheets
3. User sees dialog 
<img src="https://user-images.githubusercontent.com/3907554/34775916-ca389f9e-f60c-11e7-8312-1b88b1354a64.png" height="40%" width="40%" >

4. User minimize app
5. User opens app again and sees main page
6. User goes to `Send Finalized Form` page
7. Submission is doubled on Google Sheets

#### Expected behavior
Submission is not doubled

#### Other information 
Discovered during testing https://github.com/opendatakit/collect/pull/1569
I used form : [OnePageFormSubmission.xml.txt](https://github.com/opendatakit/collect/files/1618984/OnePageFormSubmission.xml.txt)

**Comment by dr0pdb** [comment]
I'll take a look at it.
@opendatakit-bot claim

**Comment by lakshyagupta21** [comment]
@opendatakit-bot claim

**Comment by lakshyagupta21** [comment]
Whenever user triggers the "Send Selected" button it passes the instanceIds to the `GoogleSheetsUploaderActivity`, in its `onCreate() `method `runTask()` is triggered to upload the forms.
The issue is that if we turn on  "Do not keep activities" option then it calls the `onDestroy()` of an Activity whenever we move to another activity or minimizes the app. If we again resumes the app then it is going to call `onCreate()` method which will call `runTask()`, this leads to double submission or may be even more if minimizing and resuming happens again and again because  `instanceGoogleSheetsUploader = (InstanceGoogleSheetsUploader) getLastCustomNonConfigurationInstance();` gives null so it creates its instance and execute again.
I came up with one solution that whenever Activity is destroyed stop uploading the forms to Google Sheets whenever user resumes the app again start uploading the form rest of the forms.
@lognaturel @grzesiek2010  Any Suggestions?
