### ISSUE TITLE
Problem with printing from the Zebra iMZ220 printer

### ISSUE THREAD

**Issue by mmarciniak90** [getodk/collect#1800]
#### Software and hardware versions 
Collect v1.12.2

#### Problem description
Zebra iMZ220 printer do not print

#### Steps to reproduce the problem
1. ODK Zebra Printed is installed on device
2. ODK Sensors is installed on device
3. Zebra iMZ220 is correctly connected with device
4. User uses 'All widgets' form and tries to print
5. User clicks on 'Print' button on ODK Zebra Printer
6. The printer is not responding 

#### Expected behavior
The printer prints

#### Other information 
Useful links:
https://play.google.com/store/apps/details?id=org.opendatakit.sensors&hl=en
https://play.google.com/store/apps/details?id=org.opendatakit.sensors.drivers.zebra.bt&hl=en
https://opendatakit.org/use/sensors/zebra-printer-driver/
I checked also on this form:
[print.xml.txt](https://github.com/opendatakit/collect/files/1642935/print.xml.txt)

**Comment by grzesiek2010** [comment]
@lognaturel I can take a look at it since we have this device (but when I'm free not now).

**Comment by lognaturel** [comment]
Very cool that you could try this @mmarciniak90 and that you will be able to look into it @grzesiek2010! It will be interesting to find out whether this issue happens with all Android versions or just some.

**Comment by lognaturel** [comment]
FYI, The code for the Zebra Printer app is at https://github.com/opendatakit/sensordrivers/tree/ce9cb29262c51beeebd96d045fbf6410d9953046/ZebraMzSeriesPrinter

**Comment by grzesiek2010** [comment]
@lognaturel

Printing works, the form was wrong. Here is an example: 
[pinting.xlsx](https://github.com/opendatakit/collect/files/1688587/pinting.xlsx)
(You need to add all answers otherwise Zebra Printer crashes).

I also updated https://docs.google.com/spreadsheets/d/1af_Sl8A_L8_EULbhRLHVl8OclCfco09Hq2tqb9CslwQ/edit#gid=0

@yanokwa 
As I said it works but I also noticed some crashes additionally both apps (Zebra Printer and Sensors) look a bit old-fashioned since the last version was released in 2013. I would like to review those repositories and refresh them / solve problems.
Let me know if it's a good idea. I think it's worth taking a look since we have a printer and maybe in we can work on printing itself too (add something etc).

**Comment by grzesiek2010** [comment]
@mmarciniak90 Please close the issue.

**Comment by yanokwa** [comment]
@grzesiek2010 This isn't a huge priority, but I agree that we should leverage the fact that you the printer and perhaps modernize the app. Some quick questions I have:

1. Are there turnkey Zebra printer drivers that we can use or does this really have to be custom?
1. If it does have to be custom, does it make sense to strip it out sensors and put it in a smaller standalone app that is easier to maintain?
1. DId you know about https://github.com/dimagi/zebra-print-android?
