### ISSUE TITLE
Save Cached Form Asynchronously

### ISSUE THREAD

**Issue by dcbriccetti** [getodk/collect#1820]
#### Software and hardware versions 
Collect v1.12.2

When a form is loaded and parsed for the first time, Collect saves a serialized version of the form (`FormDef`) in a cache in the file system. See `FormLoaderTask.cacheFormDefIfNew`.
In the table below you can see that this can take a long time.

Change Collect to do this work without blocking the user interface. 

Consider events that might happen concurrently, such as the user deleting the form, loading it again, closing Collect or powering off the device.

![comparison of reading and parsing xml to deserializing from cache nexus 7](https://user-images.githubusercontent.com/55099/35587805-b14febac-05b3-11e8-9ee7-47848b115758.png)

**Comment by dr0pdb** [comment]
@dcbriccetti I am interested in this, but i have a query. Isn't ```FormLoaderTask``` an ```AsyncTask``` which means it is already working on a background thread without blocking the UI thread ?

Or do you mean we should make sure it doesn't block the form loading task because it is blocking the form loading task to return the form even after the form has been loaded successfully ?
We should return the form as soon as it is loaded and leave the job of caching on another background task. Right ?

**Comment by dcbriccetti** [comment]
Hi @srv-twry. Yes, the latter. Let’s see if we can dismiss the modal dialog when all that is left to do is serialize the form and write it to the cache.

**Comment by dr0pdb** [comment]
I'll give it a shot.
@opendatakit-bot claim

**Comment by dr0pdb** [comment]
@dcbriccetti Can you please upload ```Nigeria Wards``` form if you can ? It isn't available on the default server.
It takes a long time to cache hence will be helpful in testing.
