### ISSUE TITLE
Feature request: include plus.codes? 

### ISSUE THREAD

**Issue by zorbathegreek** [getodk/collect#1850]
This is a feature request to include plus.codes. 
I have watched this video https://www.youtube.com/watch?v=LPdG3rKDzpo/ and searched both open and closed issues here (https://github.com/opendatakit/collect) for "plus.codes", and googled "open data kit plus.codes" without finding anything. 
I would like to use ODK collect, but require an area, not a position. Something like what plus.codes provides. Any chance to include that as an option?
Thanks!

**Comment by akshay-ap** [comment]
@zorbathegreek Can you provide more details about how this feature will be helpful?
How would this feature look like in ODK collect?
I would like to work on this feature.

**Comment by akshay-ap** [comment]
Through a quick look I found this link helpful :
https://github.com/google/open-location-code/wiki/Plus-codes-API

**Comment by akshay-ap** [comment]
According to me,
On ODK collect, a google map will be shown to the user. The user will pinpoint the location.
In the background, Plus code will be obtained using api and loaded in the answer field(String).
There might be changes needed in tools that help form designing so that  `Collect` can show `PlusCode` widget.
@lognaturel what do you think?

**Comment by zorbathegreek** [comment]
Hello, thanks a for looking into this. 
re: "Can you provide more details about how this feature will be helpful?"
Well, I was planning to ask people details about an area (location of their agricultural fields, and roughly, the extent of the fields), and by adding several plus.code "areas" that's quite easy. 
Re: "How would this feature look like in ODK collect?"
plus.codes can be used online or offline; like in a map, where you can pick a longitude/latitude position, one could enter a code that corresponds to an area. It is not as easy as a geographical position that comes as one value from the built-in GIS sensor. But every geographical position is within a determined plus.code area (unless it sits on the edge - hmmm). Could it then be imported from plus.codes? But I am just realizing that this would have to be done by the user, as in copy and paste. Because scaling a plus.codes map changes the plus-code result (additional alphanumerics at the end) and this can't really be tackled e.g. by using a default scale (if this would be made a "feature")  - that could be too large or too small for the individual case. So, copy and paste... but do we then need all the effort?! That's just another field in the form that the user could create, right?

**Comment by zorbathegreek** [comment]
Sorry I didn't want to close this. Didn't realize that I did!

**Comment by lognaturel** [comment]
@zorbathegreek Thanks for filing this feature request! Would either of these two alternatives work for you:
- use a text field and a constraint so that only valid plus codes can be entered
- use an offline map and have enumerators select locations on that

I'm closing this issue in favor of an existing thread on the forum that I just remembered exists: https://forum.opendatakit.org/t/use-of-plus-codes-for-gps-capture-in-odk-collect/11465 Please continue the conversation there!
