### ISSUE TITLE
Play Console require target SDK 26+ in november 2018

### ISSUE THREAD

**Issue by mdmahendri** [getodk/collect#1992]
#### Problem description
Current `build.gradle` only target SDK 22. New policy require updates to existing application target latest SDK, each year the target SDK will increase

> August 2018: New apps required to target API level 26 (Android 8.0) or higher.
November 2018: Updates to existing apps required to target API level 26 or higher.
2019 onwards: Each year the targetSdkVersion requirement will advance. Within one year following each Android dessert release, new apps and app updates will need to target the corresponding API level or higher.

#### Source
[Android Developer Blog](https://android-developers.googleblog.com/2017/12/improving-app-security-and-performance.html)

#### Status
- [ ] API 24 Remove usage of `MODE_WORLD_READABLE` #2533 
- [ ] API 24 Replace reliance on CONNECTIVITY_ACTION broadcasts #2499 
- [ ] API 26 Full QA pass to see if there is anything else to address

**Comment by lognaturel** [comment]
Thank you for filing this issue @mdmahendri, it's indeed an important date to be aware of. The current target SDK version is 22.

It would be helpful to start by understanding what code changes will be necessary to change this target. The following pages describe changes for each version:
- https://developer.android.com/about/versions/marshmallow/android-6.0-changes.html
- https://developer.android.com/about/versions/nougat/android-7.0-changes.html
- https://developer.android.com/about/versions/oreo/android-8.0-changes.html#o-apps

I believe the biggest challenge will be supporting [runtime permissions](https://developer.android.com/about/versions/marshmallow/android-6.0-changes.html#behavior-runtime-permissions). **A permission check will be required every time an action needing that permission is performed.** #644

I think it would be helpful to approach each permission separately so that it can be thoroughly verified. For example, all code requiring camera access permissions could be updated in one PR.

CC @ArmenApresyan8 who was also interested in this

**Comment by ArmenApresyan8** [comment]
Yes! We should do that, because if someone denies some permission, it will cause runtime crashes.

**Comment by jd-alexander** [comment]
We could make a checklist of all the changes that will need to take place inside the Collect codebase to meet the requirements based on the target apis so that we can track when these changes are being done and possibly create seperate issues to address them. November is right around the corner :dancer: 

Update : Just saw that there's a checklist of the permissions on the runtime permissions issues so we could utilize that and other another section for other changes as well.

**Comment by lognaturel** [comment]
I've gone through https://developer.android.com/about/versions/nougat/android-7.0-changes and https://developer.android.com/about/versions/oreo/android-8.0-changes and don't see anything other than the items in the original issue under "status" that we need to handle. 

I think it would be a good idea to do a full QA pass with the target API set to 26 on an Android 8.0 device to see whether there might be any other crashes or issues to address.
