### ISSUE TITLE
Exception java.util.IllegalFormatConversionException: %d can't format java.lang.String arguments

### ISSUE THREAD

**Issue by grzesiek2010** [getodk/collect#2003]
Collect v1.13.2 and v1.12.2

#### Problem description
I've noticed this issue while investigating crash reports. No more logs than mentioned in the title:
`Exception java.util.IllegalFormatConversionException: %d can't format java.lang.String arguments

the problem is related to Indonesian language and it might be related only to Samsung devices with Android 5. Don't know where it takes place but I guess it might be related to date/time pickers since I remember a similar issue a few months ago.

If someone wants to try please go ahead. The first step is to reproduce the crash.
`
@opendatakit-bot label "needs reproduction"

**Comment by grzesiek2010** [comment]
@opendatakit-bot label "quick win"

**Comment by huangyz0918** [comment]
@opendatakit-bot claim

Hi ~
I have reproduced this issue for several times and found a possible reason, but I'm not sure for that.
I would like to work on this issue, and try to figure it out.

**All I know:**
1. It's a bug with some of Samsung device, It affects Galaxy S4, S5, Note 3 and probably more devices.
2. It caused by the inappropriate implementation in their Lollipop UI ( Android 5+ ) with DatePicker Dialog.
3. The issue only occurs on de_DE and de_AT languages and French ( as System Language ) and other languages we don't know.

And I think we need to add some devices-check codes in `CustomDatePickerDialog.java ` to prevent this problem, but we have already added a `isBrokenSamsungDevice()` method to check if it is a Samsung device in `DateWidget.java` ( related issue #1424 ), so I was wandering if there are any inappropriate strings in language Indonesian cause this exception.

**Comment by huangyz0918** [comment]
@opendatakit-bot claim

**Comment by huangyz0918** [comment]
@opendatakit-bot unclaim

**Comment by lognaturel** [comment]
@huangyz0918 Oh, I hadn't noticed that you successfully reproduced this! Were you able to confirm #2150 fixes it?
