### ISSUE TITLE
App parameters with embedded colons in ExPrinterWidget

### ISSUE THREAD

**Issue by yanokwa** [getodk/collect#202]
In https://github.com/opendatakit/collect/pull/19 @batkinson notes that there are some colon parsing errors. We need to confirm this fix also works with ExPrinterWidget.

**Comment by batkinson** [comment]
@yanokwa, is the intent here to enable the widget to work with app parameters, or to verify that any existing parameter handling doesn't suffer from the same defect described in #19?

If the latter, it appears that there is no issue to address here. The reason is that the only behavior supported through the appearance hint is specifying the activity class. No additional parameters are supported. You can see that here:

https://github.com/opendatakit/collect/blob/master/collect_app/src/main/java/org/odk/collect/android/widgets/ExPrinterWidget.java#L125-L127

It is worth noting that if additional parameter support is added to this class, intent handling should probably be unified between these Ex\* widgets.

**Comment by yanokwa** [comment]
It was the latter, so sounds like all is well. Agreed, @chartung?
