### ISSUE TITLE
Improve audio widget

### ISSUE THREAD

**Issue by shobhitagarwal1612** [getodk/collect#2028]
#### Problem description
Clicking on play button in `Audio Widget` opens a new app to play the audio file. Instead, an audio player should be embedded within the widget to play and control the audio.

#### Steps to reproduce the problem
1. Open any form containing audio widget.
2. Choose any audio file 
3. Click on play button 

#### Expected behavior
If the audio file is available then a player should appear within the audio widget

#### Proposed solution
![image](https://user-images.githubusercontent.com/8918023/37554273-16fd8ec0-29fc-11e8-9416-7cf11830c8c9.png)

@opendatakit-bot claim

**Comment by akshay-ap** [comment]
I have worked with recording audio on Android. As an improvement for audio widget, I can add a basic functionality that will start, pause, stop recording. I know that `Collect` depends on external apps because those apps are specialized for recording audio. But, adding this feature will make `collect` self-reliant.
Another reason to justify my purpose is that some phones don't have default app to record audio. What if such situation occurs during data collection process and there is no internet connectivity? 
As an option, there will be a button to launch external audio recording app.
