### ISSUE TITLE
Move ODK Collect data to SD card

### ISSUE THREAD

**Issue by yanokwa** [getodk/collect#208]
From bobachgill@gmail.com (https://forum.opendatakit.org/t/odk-community-re-move-odk-collect-data-to-sd-card/4600)

"Our team is working on adding a general settings option to ODK Collect that will be a data path for where to store Filled Forms data.  We were running out of room on internal memory due to all of our filled forms media.  Adding the flexibility to save forms data on the external SD is our last resort.

The Forms data path option in the General Settings will open a File Chooser so that the user can search for the external SD location.  Once the User locates the path to the external SD and presses enter then the existing filled forms data will be moved over (if there is enough room).  Any subsequent reads and writes to forms will follow the new saved path.

Hopefully, getting the user involved in identifying the location of the ext-SD using the File Chooser will remove ambiguity... as different devices name their path to ext SD differently making it impossible to determine programmatically."

See also: https://forum.opendatakit.org/t/move-odk-collect-data-to-sd-card/3886

**Comment by nribeka** [comment]
Is this still an issue @yanokwa? So I'm assuming this would be a preference setting and then all the reference to the INSTANCE_PATH need to be read from the preference setting.

**Comment by nribeka** [comment]
I think we should be able to keep on changing the INSTANCE_PATH directory location and leave existing instances in the original location after changing the INSTANCE_PATH to new directory location since we record the instances using full path in the database.

**Comment by lognaturel** [comment]
Do you know if the person who wrote this initial message ever finished the feature? Would be great if they could contribute it!

**Comment by yanokwa** [comment]
I have an email out to Bob to check. Let's give it a week and then we can revist.

**Comment by lognaturel** [comment]
@zestyping talked to a user at FOSS4G Tanzania running into filled internal storage. Looking at this more closely, it's not clear to me under what conditions internal storage would be used by default. `Collect.ODK_ROOT` is built with [`Environment.getExternalStorageDirectory()`](https://developer.android.com/reference/android/os/Environment#getExternalStorageDirectory()). It sounds like on some devices this could be internal storage even if an SD card is available. At what level is that set -- is it an Android version thing, a manufacturer thing, ???

On all devices I've seen it does seem to default to an SD card when one is available. If we can identify the conditions under which that isn't the case, we might have a better idea of the most appropriate way to address the issue.

**Comment by lognaturel** [comment]
> On all devices I've seen it does seem to default to an SD card when one is available.

Or maybe not? I just realized that the device I thought had an external SD card does not. It seems on modern Android `/sdcard/` may actually be internal storage and `/mnt/extsd` external storage but I'm not finding definitive documentation on this. *Edit*: [this Stackoverflow post](https://stackoverflow.com/a/22221533/137744) strongly suggests it's the case.

I see `installLocation="auto"` in the manifest but it sounds like the app can't actually be moved probably because support isn't fully there. It seems like allowing the user to move Collect through Android settings would be the right approach but some of the conditions described [in the docs](https://developer.android.com/guide/topics/data/install-location#ShouldNot) may be problematic. Also, it looks like the db stores all full paths so this is not a small issue. Perhaps the original poster's suggestion of making the location of only instances is viable.

**Comment by grzesiek2010** [comment]
Since we have to prepare our app for [scoped storage](https://developer.android.com/training/data-storage/files/external-scoped) so we can close it. We will be able to move the app between internal storage end sd card.
