### ISSUE TITLE
Select One and Select Multiple with map appearance

### ISSUE THREAD

**Issue by khalifeserge** [getodk/collect#2084]
I am proposing to have the choice list be displayed as geometries on a map that can be selected. One off the use case that require this feature is whenever you need to collect data on previously geolocated data. where the gps accuracy alone is not enough. This feature along with offline maps would make the workflow a lot easier. Rightnow the way I achieve this is to create mbtiles of the points and then ask the user to zoom   all the way in and put a marker on the point. This is not an easy workflow as creating the mbtiles for large area and transferring the data to all the tablets is not trivial.

Regards

**Comment by lognaturel** [comment]
@khalifeserge are you familiar with the `image-map` feature recently added? See https://docs.opendatakit.org/form-widgets/#image-map-select-widget for documentation. There are many svg maps already available that can be used in this way.

If you need to work with true geometries, please add a feature description to https://forum.opendatakit.org/c/features. We try to keep new feature discussions there since the majority of ODK users are not developers!
