### ISSUE TITLE
Autocomplete without showing options

### ISSUE THREAD

**Issue by rnaneliu** [getodk/collect#2164]
Hi,  I have been working on creating a collection form and what I have discovered is that I will have a list of 7000 dispositions and a few hundred plants on my survey which I don't want to scroll down or see at all, I just want to start autocomplete and have it pop up.   "Search" is the right concept but I don't want to see the long list dispositions or plants at all. It just defeats the purpose.

Cheers and all the best

Ryma

**Comment by yanokwa** [comment]
Hi @rnaneliu! One option you can try is to filter those options in a series of selects. https://docs.opendatakit.org/form-logic/#filtering-options-in-select-questions has an example. Would that work for you?

**Comment by lognaturel** [comment]
Agreed with @yanokwa that it's often possible to restructure the input so that it "cascades" between several smaller selections (country to state to city to neighborhood, for example). 

That said, sometimes there is a reason to show all options at once. I'm guessing that this is undesirable because it takes a while to load the options. As of Collect v1.17, loading options will be near instant. @rnaneliu you can try this [in beta now](https://forum.opendatakit.org/t/odk-collect-v1-17-beta/15196) or when it's released next week.

If that doesn't address your issue, consider posting a feature request [on the forum](https://forum.opendatakit.org/c/features).
