### ISSUE TITLE
Multiple submissions when finalized form is edited and saved again

### ISSUE THREAD

**Issue by lakshyagupta21** [getodk/collect#2175]
#### Software and hardware versions 
Collect v1.14

#### Problem description
User is able to see multiple submissions of form when edits the finalized form

#### Steps to reproduce the problem
1. Set forms to `Auto send` from `General settings`>`Form management`
2. Fill a form, save and finalize it (Attach some images so that it takes time to upload)
3. `Edit Saved Form`
4. Open the same form (Will be shown when upload is complete)
5. Again mark it as finalized and save.

Multiple submission happens of same form on server, but only one form submission is shown in Collect.

#### Expected behavior
Multiple submission shouldn't happen.

#### Other information 
Found while working on #1972

**Comment by DreamyPhobic** [comment]
@opendatakit-bot claim

**Comment by lognaturel** [comment]
Thanks for filing, @lakshyagupta21 and for looking into it, @dreamyphobic. It might be good to discuss the underlying issue and a possible approach before deciding whether this is worth addressing now. 

The fundamental issue is that during an ongoing submission, finalized forms are still visible in Edit Saved Form even though their status will change to submitted shortly. There is currently no mechanism for Edit Saved Forms to know that certain finalized forms are already queued for submission or currently being transmitted. I’m not currently thinking of a way to address this issue narrowly without changing the whole approach for representing and sharing the state of instances. @dreamyphobic, what are your ideas?

**Comment by DreamyPhobic** [comment]
I noticed that if the sending process is ongoing, then no matter what form we are opening, it will not get opened and always show loading dialog box until the sending process gets completed. So, first of all, this should not happen otherwise what will be the advantage of using the background process. I don't know it is intentional or not. If it is intentional then we can solve the above issue just by disabling the item click in "edit save form" section. If it is not intentional then I think we need to do a lot of work on it.

**Comment by grzesiek2010** [comment]
Now it's not possible to edit finalized forms so I'm closing this issue.
