### ISSUE TITLE
Replace pngs we use in General Settings with vectors

### ISSUE THREAD

**Issue by grzesiek2010** [getodk/collect#2196]
#### Software and hardware versions 
Collect v1.14.2

#### Problem description
Replace pngs we use in `General Settings` with vectors

#### Other information 
**It should be done once we stop supporting android 4 since there is no easy way to replace these icons with vectors (android 4 would require doing that programmatically).**

Icons we should replace:

ic_cloud
ic_phonelink_setup
ic_assignment
ic_face

![screenshot_2018-05-14-10-26-04](https://user-images.githubusercontent.com/3276264/39986199-454d8a2c-5761-11e8-8a9e-aeef1a25b1cf.png)

**Comment by grzesiek2010** [comment]
@opendatakit-bot label "quick win"

**Comment by jaindiv26** [comment]
@opendatakit-bot claim

**Comment by CRMinges** [comment]
@opendatakit-bot claim

**Comment by CRMinges** [comment]
@opendatakit-bot unclaim

**Comment by SaumiaSinghal** [comment]
@opendatakit-bot claim

**Comment by SaumiaSinghal** [comment]
Hie @grzesiek2010, we can have vectors in lower versions, but for that we need to use AppCompatImageView instead of ImageView, which is there in the headers in Preference Activity, by default. If i go about using a RecyclerView adapter or some other adapter and parse the data of headers from Xml files, then, it is possible. But for that do i really need to parse the data, as then, i can simply feed the data in Header class.

**Comment by SaumiaSinghal** [comment]
Should i do that @grzesiek2010 ..?

**Comment by grzesiek2010** [comment]
I don't think it makes sense... sooner or later we will stop supporting Android 4 and then we can just replace pngs with vectors.

**Comment by SaumiaSinghal** [comment]
Okayy @grzesiek2010...

**Comment by SaumiaSinghal** [comment]
@opendatakit-bot unclaim

**Comment by shobhitagarwal1612** [comment]
Fixed in #2404
