### ISSUE TITLE
Forms from Ona accounts appear to always have new versions available

### ISSUE THREAD

**Issue by lognaturel** [getodk/collect#2203]
Following up from https://github.com/opendatakit/collect/pull/2095#issuecomment-388354205

@ukanga and @jasonrogena have verified that the formList response doesn't have any differences. This happens with forms that don't have any attachments (and thus no `manifestUrl`).

**Comment by lognaturel** [comment]
I can't reproduce from https://ona.io/lognaturel/. I downloaded the form with ID `timestamp-tests` to Collect, then verified that no new version was shown as available from Get Blank Form. Then I added a media attachment and verified that a new version was shown as available from Get Blank Form. I downloaded that new version and then verified no new version was shown as available from Get Blank Form.

**Comment by grzesiek2010** [comment]
I asked @ukanga about `xformsList` https://github.com/opendatakit/collect/pull/2095#issuecomment-388780577 because I'm curious what value we receive: For example in our (ODK Aggregate) case it's:
`<hash>md5:29a492009d35c1515886ddd307521819</hash>`
Is it possible that ONA sends the same hash but without `md5: `prefix?

**Comment by ukanga** [comment]
No, Ona includes `md5:` prefix. See https://odk.ona.io/lognaturel/formList and https://odk.ona.io/lognaturel/xformsManifest/223348.

**Comment by grzesiek2010** [comment]
@lognaturel 

yes but @lognaturel is not able to reproduce the issue so I'm asking about your instance. Could you share it also?

**Comment by ukanga** [comment]
@grzesiek2010  Check https://odk.ona.io/ukd/formList,  the form with the name `idm`.

**Comment by lognaturel** [comment]
I don't see a form with name `idm`. Any chance there could be something different going on with private forms? I haven't tried one of those.

Are all the forms in your account showing that updates are available or only some? If it doesn't seem to be a private/public issue, any other pattern you can see?

**Comment by grzesiek2010** [comment]
I made a quick test:

1. Go to https://odk.ona.io/ukd/formList
The first form is:

```
<xform>
<formID>a9h6EeMhbM9BXj8BYaGej2</formID>
<name>idm</name>
<version/>
<hash>md5:8384506fd51c00a94a6c30074fca1e96</hash>
<descriptionText/>
<downloadUrl>https://odk.ona.io/ukd/forms/305256/form.xml</downloadUrl>
<manifestUrl/>
</xform>
```
2. Download the firs form using downloadUrl: https://odk.ona.io/ukd/forms/305256/form.xm
3. Calculate md5 hash using an online tool like http://onlinemd5.com/
4. My result is: `C08154A4E4F23C4A9E0DAC009FC2ABAF` but the hash recived (and visible above) is `8384506fd51c00a94a6c30074fca1e96`

Then I performed the same steps using lognaturel's https://ona.io/lognaturel/formList using also the first form:
```
<xform>
<formID>geowidgets-demo</formID>
<name>Geowidgets Demo</name>
<version>201702161003</version>
<hash>md5:99f85297be2c2ea9fbc90fbd09b8d74f</hash>
<descriptionText/>
<downloadUrl>https://ona.io/lognaturel/forms/182486/form.xml</downloadUrl>
<manifestUrl/>
</xform>
```
After downloading and calculating md5 hash it's the same like the recived one.

So looks as if there is something wrong on the ONA's side with calculating md5 hashes since in the first case hashes are not equal.

**Comment by jasonrogena** [comment]
The issue was with how Onadata generates the MD5 hash for the xform (https://github.com/onaio/onadata/issues/1417) which @ukanga has just fixed.

I think this issue can be closed.

**Comment by lognaturel** [comment]
Thank you for the detective work, @grzesiek2010 -- was good to get those repro steps. 🔎 

And great to know it's fixed for Ona users, @jasonrogena and @ukanga!
