### ISSUE TITLE
ArrayOutOfBoundsException in FileArrayAdapter.getView

### ISSUE THREAD

**Issue by lognaturel** [getodk/collect#2214]
`holder.onBind(items.get(position));` is the line the crash happens on.

This code was recently added in #1970 to add a dynamic search bar to Google drive.

**Comment by grzesiek2010** [comment]
I tried to reproduce the issue but without success. Can't even see anything wrong in the code. There is only one report so hopefully, it's not a common problem.

**Comment by jdhollen** [comment]
Hey folks! Looks like the pre- #1970 version of `GoogleDriveActivity` never cleared the list passed into `FileArrayAdapter`--seems likely that this is some kind of goofy race due to `filteredList` being cleared in `getResultsFromApi()` without a call to `adapter.notifyDataSetChanged()`?

In the same vein, there's a double-call to `notifyDataSetChanged()` at the bottom of `updateAdapter()`.

I haven't contributed before--not sure what your policy is on perceived fixes to hard-to-repro bugs--but that's my hunch.

**Comment by lognaturel** [comment]
Hi @jdhollen and welcome!

For crashes like this that we see happening with some frequency in crash reporting, I personally think it's worth trying to find a fix even in the absence of a reproduction. 

We'd ask that the reasoning behind the change is well-documented in the pull request description and/or the commit message details and then would do a manual QA pass to check for any regressions. 

These hunches sound very promising so if you're up for putting something together and submitting a pull request, it would be much appreciated.

**Comment by grzesiek2010** [comment]
Duplication of https://github.com/opendatakit/collect/issues/2928
