### ISSUE TITLE
logo design contribution

### ISSUE THREAD

**Issue by masudr4n4** [getodk/collect#2217]
i am not seeing any logo for your project.so i  want to make a logo for your project.if you have any requirements then lety me know.its free for open source project.

**Comment by lognaturel** [comment]
Thank you, @maaudrana! The ODK logo is currently the one used for example for the Twitter account: https://twitter.com/opendatakit

There is some interest in developing a new one. The discussion is at https://forum.opendatakit.org/t/develop-a-new-logo/9632 but not very active because there are a lot of other projects going on right now.
