### ISSUE TITLE
Add changelog after upgrade or first launch

### ISSUE THREAD

**Issue by shobhitagarwal1612** [getodk/collect#2219]
#### Software and hardware versions 
Collect v1.x.x, Android vx.x.x, device used...

#### Problem description
Display a changelog dialog after every app update/new install

Sample changelog ui

![changelog-demo-gif](https://user-images.githubusercontent.com/8918023/40218008-f8b8e7e0-5a8c-11e8-884c-25d695d241b2.gif)

**Comment by lognaturel** [comment]
The challenge with these kinds of "first launch experiences" is that Collect's end users are often not the people who need to be aware of these kinds of changes. A lot of enumerators are lightly trained to perform very specific data collection tasks and do not have broad technology know-how or sometimes even high literacy. In fact, some users are illiterate which is why the media questions are so important. Things that pop up sometimes but not other times are likely to be more confusing than helpful. 

To make matters worse, new features will not always be available to enumerators because the admin menu allows for locking down large parts of the app.

I think something that pops up on launch is going to cause problems. However, maybe we could have a "New in this version" menu option added or something like a red dot that shows up next to the version name on first launch after an update that when tapped provides details about the version.

**Comment by shobhitagarwal1612** [comment]
I have the auto update feature enabled in play store so it updates the apps in background. So if I clear the notification of successful update, then while opening the app, I forget that it has upgraded and once it's updated then the chances of one to open play store to see the features added is likely to be less

**Comment by shobhitagarwal1612** [comment]
Only keeping the "new in this version" sounds good to me

**Comment by lognaturel** [comment]
> I have the auto update feature enabled in play store so it updates the apps in background.

I think that's true for most people. And what's important is that updates be for the most part completely seamless for enumerators. If their organization wants to leverage new features, they will tend to do a retraining.

**Comment by jd-alexander** [comment]
I agree with @lognaturel on this. Most apps just put changelogs on their Settings screen so if a user is interested in what has been changed after an update they can navigate their and view it.

**Comment by grzesiek2010** [comment]
I think we could just have a link to https://github.com/opendatakit/collect/releases in `About` section. I agree that something that would show up on first launch is not a good idea.

**Comment by lognaturel** [comment]
This really should be more of a forum discussion and a spec will need to be reviewed/approved by the TSC. It's related to https://forum.opendatakit.org/t/faq-or-guide-section-in-odk-collect-android-application/9684. Let's close for now.
