### ISSUE TITLE
Revert using hyperlink for gsheets attachments

### ISSUE THREAD

**Issue by lognaturel** [getodk/collect#2221]
As of Collect v1.14.0, gsheet attachments show the filename without the path in the results sheet. That filename is hyperlinked to the file itself. That change was included in #1851 and not discussed as far as I can remember.

The change is problematic because it means users can't do things like easily write scripts to pull all media files. Since the filenames are not terribly meaningful, the change only makes the spreadsheet a little prettier but reduces functionality. Gsheets recognizes links as such and they are made clickable so the original approach was sufficient.

https://forum.opendatakit.org/t/data-comes-wrapped-in-excel-formula/13150 for a user's experience.

CC @grzesiek2010 @yanokwa

**Comment by grzesiek2010** [comment]
Only two users complained about that feature and I wrote a script that extracts all hyperlinks https://forum.opendatakit.org/t/theres-a-way-to-import-photos-on-google-sheet-in-such-a-way-that-i-have-the-link-to-the-photo-with-jpg/12560/4?u=grzesiek2010 

maybe we should a new option in settings to let users decide?

**Comment by lognaturel** [comment]
I don't see any benefit to the hyperlink approach, though! And two users complaining in such a short time is a lot -- that probably means a lot more are experiencing problems with it.

**Comment by grzesiek2010** [comment]
Do you think we should get rid of that in repeat-group names or only in media files? You know if you have a repeat group it's in a separate sheet and you have a hyperlink in the main sheet.

**Comment by lognaturel** [comment]
Ahh, I see, that's where the change came from, that makes sense. Using a hyperlink for the repeat sheets seems totally fine to me. Sheets aren't downloadable entities so having the full link directly available isn't as helpful. Can you think of something a user would be able to do with the direct sheet hyperlink? I can't.

**Comment by grzesiek2010** [comment]
> Can you think of something a user would be able to do with the direct sheet hyperlink? I can't.

me neither, I agree.

**Comment by nodarik** [comment]
I will note one thing here

@grzesiek2010 thank you for the script but it handy if the user has not big date, in my case where we have more than 10000 rows script was not succeeded because of timeout and it did not do his job actually, also there is other problems, i cant run script every time we receive new data, that's not possible .
Overall, dealing with raw data is much easier, everyone can write simple formula then to display it as a link or display it as an image in a the cell like I did it, at this moment i can't find any solution to extract link property from hyperlink formula, so i removed them by search and replace and downgraded all our apps to older versions

Thank you guys,

**Comment by lognaturel** [comment]
Thank you very much for that extra context @nodarik. Thanks to @grzesiek2010 the change has been reverted and when 1.15 comes out next week you'll be able to use that version and get the raw URL in media columns.

**Comment by nodarik** [comment]
you guys are simply awesome!

**Comment by yanokwa** [comment]
@nodarik You aren't so bad yourself. Thank you for reporting the issue!
