### ISSUE TITLE
Zero at the beginning of version number is removed on 'Get Blank Form' page

### ISSUE THREAD

**Issue by mmarciniak90** [getodk/collect#2296]
#### Software and hardware versions 
Collect 1.15.0

#### Problem description
`0` at the beginning of version number is removed on `Get Blank Form` page

#### Steps to reproduce the problem
1. The user wants to download form with version="00001" [multi-warning.xml.txt](https://github.com/opendatakit/collect/files/2098181/multi-warning.xml.txt)
2. The user goes to `Get Blank Form` page
3. The user sees that form has `Version 1`

|![screenshot_20180613-155143](https://user-images.githubusercontent.com/3907554/41353008-904d4894-6f0a-11e8-82af-3621549469bf.png)|![screenshot_20180613-155208](https://user-images.githubusercontent.com/3907554/41353029-9b7d060a-6f0a-11e8-9d42-a4c4994dfb49.png)|![screenshot_20180613-155212](https://user-images.githubusercontent.com/3907554/41353035-9f2a63ec-6f0a-11e8-9fb4-34de70c5646a.png)|
|---|---|---|

#### Expected behavior
* The user should see the correct version number, zero should not be removed
* `Fill Blank Form' page and `Delete Saved Form` page show correct version number

**Comment by grzesiek2010** [comment]
@opendatakit-bot label "good first issue"

**Comment by SaumiaSinghal** [comment]
@opendatakit-bot claim

**Comment by grzesiek2010** [comment]
Hey @SaumiaSinghal I think you solved enough `good first issues` an you are ready to take something more complex so maybe please leave it for someone completely new

**Comment by SaumiaSinghal** [comment]
Yes okay @grzesiek2010, I was also thinking it to be my last good first issue. I'll unclaim it.

**Comment by SaumiaSinghal** [comment]
@opendatakit-bot unclaim

**Comment by surajdubey** [comment]
@opendatakit-bot claim

**Comment by surajdubey** [comment]
@opendatakit-bot claim

**Comment by surajdubey** [comment]
@opendatakit-bot claim

**Comment by surajdubey** [comment]
@opendatakit-bot claim

**Comment by surajdubey** [comment]
@opendatakit-bot claim

**Comment by MikeMikerson** [comment]
@opendatakit-bot claim

**Comment by cooperka** [comment]
@opendatakit-bot claim

**Comment by cooperka** [comment]
Turns out this isn't a Collect issue, it's an Aggregate issue. The response sent back from the server for the Multi Warning form is:

```xml
<xform>
  <formID>multi warning</formID>
  <name>Multi Warning</name>
  <majorMinorVersion>1</majorMinorVersion>
  <version>1</version>
  <hash>md5:c1983e6a874af5cb49b4e484bfadb92d</hash>
  <downloadUrl>https://sandbox.aggregate.opendatakit.org/formXml?formId=multi+warning</downloadUrl>
</xform>
```

Whereas `<version>500001</version>` is correct when the leading character is non-zero. I'm leaving soon for a weekend out of town but I'll come back and set up Aggregate on Monday to dig deeper.

**Comment by lognaturel** [comment]
Thank you, @cooperka! That makes sense. I think it would have been slightly higher priority as a client-side issue but seems to me as pretty low priority on the Aggregate side.

I'll leave you the honor of filing the issue there and we can see if anyone else thinks it's something to prioritize. Since you're all set up for Collect I'd recommend sticking around here for a bit! Getting an issue like this closed is super helpful. 🙏
