### ISSUE TITLE
Geolocation data are lost after changing device orientation while filling answer

### ISSUE THREAD

**Issue by mmarciniak90** [getodk/collect#2310]
#### Software and hardware versions 
Collect v1.15

#### Problem description
Geolocation data are lost after changing device orientation while filling answer

#### Steps to reproduce the problem
1. The user starts one of Geo Widget: GeoShape, GeoTrace, GeoPoint
2. The user adds location, depend on question
<img height="40%" width="40%" src="https://user-images.githubusercontent.com/3907554/41658235-4789bee6-7485-11e8-912e-5375315e811e.png">
3. The user changes device orientation.
4. The user needs to fill location again because all data were lost.
<img height="40%" width="40%" src="https://user-images.githubusercontent.com/3907554/41658234-476ac6bc-7485-11e8-8872-7faaa52ed5f3.png">

#### Expected behavior
Changing the orientation of the device does not cause loss of geolocation data

**Comment by SaumiaSinghal** [comment]
It seems changing device orientation is causing a lot of issues here, because i worked on a similiar issue earlier, @mmarciniak90, I'd like to work on this one too. Maybe if i dig a little more deeper, i can come up with a better solution for that issue as well.

**Comment by SaumiaSinghal** [comment]
@opendatakit-bot claim

**Comment by lognaturel** [comment]
Thanks for filing, @mmarciniak90! This is starting to veer into issues discussed in https://forum.opendatakit.org/t/collect-geotrace-and-geoshape-improvements/10160 and in the summary at https://docs.google.com/document/d/1r3wJrOVDeFQkk4kWMoW29LtLI1vbBChqJ65w1Jyg4YU/edit. I haven't been so sure how to track these issues at the repo level because they're fairly tightly coupled. Fundamentally, we want to use the various bugs and limitations that exist in the geo widgets to guide a refactor that will make them less buggy, more harmonized and generally easier to maintain and evolve.

That work has had some false starts but @zestyping who was part of the team that initially proposed and addressed many of them has taken it up again. I think we should probably hold off on other changes to geo for now to minimize conflicts.

**Comment by SaumiaSinghal** [comment]
Oh okay @lognaturel, just inform me when i can start working on this issue.

**Comment by lognaturel** [comment]
Some additional notes in #2145.

**Comment by zestyping** [comment]
#2640 fixes this problem for GeoTraceActivity and GeoShapeActivity.

This issue is remaining open because the GeoPoint activities still need to be fixed.

**Comment by zestyping** [comment]
#2806 fixes this problem for GeoPointMapActivity.

That's all of them, so we can close this issue now.

**Comment by zestyping** [comment]
@yanokwa I think we can close this issue now.

**Comment by yanokwa** [comment]
Fixed by #2806
