### ISSUE TITLE
Bulk configure devices over-the-air

### ISSUE THREAD

**Issue by yanokwa** [getodk/collect#232]
You can currently bulk configure devices by following these steps: "From the main screen, tap the menu button. Tap Admin Settings, tap the menu button again, tap Save Settings to Disk. This will save your general and admin settings to /odk/settings/collect.settings. Copy this settings file to /odk/collect.settings of any other device running ODK Collect v1.3, and when you re-launch ODK Collect, it will automatically load those settings, and delete that file."

It would be much better if we could find a way to update settings over the air (or maybe bundled with the app).

**Comment by shobhitagarwal1612** [comment]
We can bulk configure devices OTA by sharing the QRCode image and importing them from `Admin Settings` > `Select code from SDCard`.

**Comment by akshay-ap** [comment]
@yanokwa @lognaturel @shobhitagarwal1612 Is it possible to do it this way :
Assuming Organizations have their own servers.
1. Admin will configure a device, save its settings in Image on QRCode.
2. On click of a button by admin, this image/settings will be sent to server.
3. Other users will have to add a url to download settings. On click of button, those image/settings will be downloaded and settings will be automatically changed.
(To accept admin settings and serve those to other devices we can provide a small script which admin will run on a web-server.)
I am saying to use QR code Image because I think the complete implementation is already present. I just propose a way to share that image and automate whole process.
This would give advantage to configure devices remotely and reset settings to admin settings whenever needed. Also, there will be no need of other apps to share the ORCode.

**Comment by lognaturel** [comment]
This is under discussion at https://forum.opendatakit.org/t/openrosa-spec-proposal-add-optional-client-settings-endpoint/25140/ roughly with what @akshay-ap has described.
