### ISSUE TITLE
Auto-send with SMS

### ISSUE THREAD

**Issue by lognaturel** [getodk/collect#2370]
Currently, the auto-send options are 
```
Off
Wifi only
Cellular only
Wifi or cellular
```

In order to support auto-send via SMS, we need to decide what setting to add.

`SMS only` makes sense to me. I'm not sure if users would want `Wifi, cellular or SMS`.

CC @yanokwa @jd-alexander

**Comment by yanokwa** [comment]
I agree that `SMS only` is an obvious choice.

I think `Wi-Fi, Cellular, or SMS` should be added because it's what a user would expect. Or rather, I don't know why SMS should be excluded.

I think what we might want to do is re-work this menu so it's a multi-select. I'm not sure how the migration would work. @jd-alexander, any ideas?

**Comment by jd-alexander** [comment]
Yes, what could be done is, a new `SharedPreferences` key could be introduced and then inside the `Application` class a migration method could be run; one that's similar to `FormMetadataMigrator`. It would basically grab the current `AUTOSEND` setting and migrate it to the value of the new key. This would leave the existing key intact in the case of a downgrade and the new implementation that contains the multi select list would then use the latest key in all it's conditions.

**Comment by jd-alexander** [comment]
@opendatakit-bot claim

**Comment by lognaturel** [comment]
For the sake of completeness, here are some notes I wrote on #2378:

> It's still not clear to me that a user would ever want to auto-send via Wifi, cellular or SMS. This would mean that as an enumerator is collecting data, they would sometimes end up sending over one transport and other times over the other. The data may be going to completely different places and the data may be subsetted over SMS while it would be complete over HTTP. This would make it really hard to reconcile, especially since it won't be easy for the enumerator to tell where the data went. Generally I think if there's the option to send via either, it's something the enumerator would want to decide. For example, it doesn't make sense to send a form via SMS if they could walk 200 meters away and then be able to send the full form over HTTP.
> 
> It also seems confusing to show auto-send options for a transport that may not be configured. What should the expected behavior be if I set auto-send to SMS but don't have SMS settings? Or have "send via" set to Internet? I see here it just silently doesn't autosend.

**Comment by jd-alexander** [comment]
Those are some really good points @lognaturel :)
They go really well with the discussion we had about how to create a comprehensive spec for the auto-send functionality.

- How does the auto-send option treat the transport setting since it can be set to SMS at one point and then changed at another? How does the whole functionality and language react to that?

- For SMS auto-sends, when should we go about performing a retry if the SMS fails? Should we just utilize exponential backoff or should it be a case where it tries once and then only retries each time the app is reopened?

- We need to think of a clear use case for using multiple types of transport with auto-sending. Figuring this out will help us to determine the approach to building the functionality since having multiple types of transport raise a lot of questions about how the statuses on the upload list will be shown and also when would each transport perform a send i.e not sending them both because that might be confusing.

- What should the configuration dialog look like? Should we use a multi-select control? How does this dialog react to if SMS is configured are not?

These questions and others, we will discover answers for as we spend the next week identifying decision points and options. Once we have a solid idea of what the use cases are via user stories and a bit of discussion on the forum with potential users then we can create a spec as to how this feature can come to life.

**Comment by jd-alexander** [comment]
@lognaturel Hi! We can probably close this issue for now since we’ve mostly decided that there’s no easy way to do this. During the weekly update meeting, I suggested that we can close the PR but leave the Auto-send branch associated with this issue because it has a working implementation of the`MultiListPreference` control and that might come in handy when we need to have multiple options for one setting.

**Comment by lognaturel** [comment]
Closed the PR as suggested. @jd-alexander, you should also be able to close your own PRs.

**Comment by lognaturel** [comment]
I suppose it makes sense to also close the issue since the feature isn't designed. It can be reopened if needed.
