### ISSUE TITLE
When resending form to server after sending via SMS, status is not updated

### ISSUE THREAD

**Issue by lognaturel** [getodk/collect#2372]
#### Software and hardware versions 
Collect v1.15.0-163-g26cde0de0

#### Problem description
When resending form to server after sending via SMS, status is not updated

#### Steps to reproduce the problem
1. Send SMS Test form from default server via SMS
1. Change submission destination to Internet
1. In Send Finalized Form, change view to Show Sent and Unsent Forms
1. Send same form again

Form is received but the status still says "Sent as SMS on <date>". 

#### Expected behavior
The latest status should show.

**Comment by lognaturel** [comment]
It's unfortunate that we don't have a log of these status changes but I think for now I think replacing the status is the best we can do.

As we discussed in the SMS comment thread, it would be very useful to eventually have another DB table for statuses separate from the instance table.

**Comment by jd-alexander** [comment]
Yes, I was just thinking about this and saw this issue. The statuses are being persisted to the same `instance` table, the only difference is that because that table can't store the progress etc. the `SubmissionManager` is being called for it's current data so it's overwriting the status for all submissions so what I think can be done here is I simply check the transport settings and if it's `internet` then I show the status for that protocol. Should it still save the state? 
Meaning if I was trying to submit a SMS form and it failed and then I did a submission via the web and it was successful, when I switch back to SMS should it show that failed state? meaning should it continue where I left off? That's the behaviour that I think would be best.

**Comment by lognaturel** [comment]
I expect it to show the latest state. That is, if the latest attempt was via SMS, it should show SMS results. If the latest attempt was via HTTP, it should show HTTP results.

**Comment by jd-alexander** [comment]
Okay! makes sense.

**Comment by jd-alexander** [comment]
Another question @lognaturel say you are doing a SMS submission where you are sending 4 messages and one (1) of them failed. Then  you switch to using internet and make a successful submission. If you switch back to SMS submissions and make a submission should it only the one (1)  that failed or should it start over?

**Comment by lognaturel** [comment]
Hmm, that's an interesting case. I think the switch to Internet shouldn't affect anything -- it should just try the one that failed like it would if there had been no transport switch. What did you think?

**Comment by jd-alexander** [comment]
Yes, I think that would be the better approach. I am gonna see how I can get that done.

**Comment by lognaturel** [comment]
What does it do now? I would have expected it to do what I described.

**Comment by jd-alexander** [comment]
Yeah, that's the expected way.So it seems this is a bug that needs fixing.
