### ISSUE TITLE
Automate versionCode increments and remove it from the interface

### ISSUE THREAD

**Issue by yanokwa** [getodk/collect#238]
It's not clear to me why build number needs to be front and center. It should auto-increment and probably be moved to settings or made smaller.

**Comment by grzesiek2010** [comment]
I'm working on this.

**Comment by lognaturel** [comment]
We have PR #281 that nicely automates what we have been doing which is to increment the build number on each release.

Seeing it codified got me thinking that perhaps it's not the most helpful way to update the build identifier. Ideally, a build identifier should make it possible to trace the origin of any install whether it's an official release or not. This can be particularly helpful in the testing process where knowing exactly what code is running is important.

Some alternate options for the build identifier that use git are described in [this SO post](https://stackoverflow.com/questions/17097263/automatically-versioning-android-project-from-git-describe-with-android-studio-g). There are two potentially interesting plugins mentioned: [gradle-android-git-version](https://github.com/gladed/gradle-android-git-version) and the [gradle-git integration](http://stackoverflow.com/a/32245036/137744), as well as implementations that don't require dependencies.

I don't really think that the plugins add a whole lot over directly calling `git`. My preferred strategy is to use `git describe --tags --dirty` for the version name and `git rev-list --first-parent --count master` (the number of commits on master since the first commit) for the version code. [This code](http://stackoverflow.com/a/24121734/137744) does exactly that. With that strategy, the version name currently displayed on the main menu could potentially be quite long (e.g. `v1.4.12_rev_1063-24-g6d75b06-dirty`) so there would have to be some intelligent wrapping there or perhaps a split on dash so the commit count, short commit hash and commit state (dirty/not) could be displayed with the build number.

Any alternate suggestions for a useful build number or issues with the approach outlined above?

**Comment by lognaturel** [comment]
We had some good discussion about this on the Slack. The change in `versionName` was filed separately at #305.

For `versionCode`, we will remove it from the user interface and use `git rev-list --first-parent --count master` so it is automatically incremented as needed. The `gitVersionCode()` method [here](http://stackoverflow.com/questions/17097263/automatically-versioning-android-project-from-git-describe-with-android-studio-g/24121734#24121734) does that. It should probably be called `getMasterCommitCount()` for us.

The catch is that the current build number is 1063 and that future build numbers have to be higher. When a branch is created off the latest version of master, run `git rev-list --first-parent --count master`. Subtract that value from 1063 to get the required offset. Create a constant called something like `LEGACY_BUILD_NUMBER_OFFSET` to hold that value and put a comment on it like "Build numbers were manually set until 1063. This constant is required to make sure build numbers are always increasing." Then `versionCode` can be `LEGACY_BUILD_NUMBER_OFFSET + getMasterCommitCount()`
