### ISSUE TITLE
The user is not able to select a splash screen from Google Drive

### ISSUE THREAD

**Issue by mmarciniak90** [getodk/collect#2390]
#### Software and hardware versions 
Noticed on Collect v1.16 beta 4 but probably it was from the beginning

#### Problem description
The user is not able to select a splash screen from Google Drive

#### Steps to reproduce the problem
1. User opens `User interface` settings
2. User selects checkbox for `Splash screen`
3. User selects an image from Google Drive
4. An image is not loaded
 
#### Expected behavior
* The user is able to select a splash screen from Google Drive

**Comment by mmarciniak90** [comment]
@opendatakit-bot label "good first issue"

**Comment by kaftand** [comment]
@opendatakit-bot assign

**Comment by kaftand** [comment]
@opendatakit-bot  claim

**Comment by kaftand** [comment]
@mmarciniak90 , it seems maybe the best way to make drive photos work on the splash screen requires downloading them. Otherwise, it wouldn't work offline - how I primarily use ODK. 

In light of this, I see three ways of moving forward.

1. Perhaps we should remove the feature to use a Drive photo to avoid confusion. If people want to use a photo from their drive, they can download it themselves and add it.

2. When a drive photo is selected, it is automatically downloaded and the downloaded path is used for the photo.

3. We ignore the problem with being offline and find a way to load drive photos into the splash screen.

Do you have any input?

**Comment by kaftand** [comment]
@opendatakit-bot claim

**Comment by kaftand** [comment]
I am not sure why the "claim" is not working, but I want to make it clear that I am not working on this issue right now. I would love to work on it in the future, but I would need a little more direction since I have no experience working on open source project (I would LOVE to gain some!). In the meantime, I will be without internet for the next 2 weeks. If anyone wants to pick up this issue, please feel free!

**Comment by kaftand** [comment]
@opendatakit-bot unclaim

**Comment by mendell** [comment]
@opendatakit-bot claim

**Comment by konishon** [comment]
@opendatakit-bot claim

**Comment by konishon** [comment]
@opendatakit-bot  claim

**Comment by konishon** [comment]
@kaftand 
using ACTION_PICK would restrict the image selection to device folders and that would satisfy the first point you said

I will send a PR and see if any agree

**Comment by muarachmann** [comment]
@shobhitagarwal1612 i see this has been claimed several times and not yet resolved can i work on this  😃 of course i count on you to guide me.Let me know your thoughts before i claim this thanks

**Comment by muarachmann** [comment]
@opendatakit-bot claim

**Comment by muarachmann** [comment]
@huangyz0918, @yanokwa , @garglakshya18  could you please help me here. I have a hard time figuring out how to retrive the selected image from google drive. I tried and it retured something like this `acc=x,doc=319`. How can this be useful opening the doc in the SplashActivity

**Comment by kaftand** [comment]
Hello @mmarciniak90 , something @nishontan and I discussed was that perhaps we should disable the google drive option for splash screen images. For an app that is so often used without internet connection, it didn't make sense to us to have a minor feature require internet.

see @nishontan last WIP PR https://github.com/opendatakit/collect/pull/2712

**Comment by shiv07tiwari** [comment]
@opendatakit-bot claim

**Comment by shiv07tiwari** [comment]
@kaftand Can I pick this issue and solve it, or someone is working on it ?

**Comment by grzesiek2010** [comment]
I'm closing this issue because it's more likely we remove the splash screen at all.
The first step to check if the splash screen is used https://github.com/opendatakit/collect/pull/2808
and the issue  issue https://github.com/opendatakit/collect/issues/254
