### ISSUE TITLE
The user should see pop up with phone number fields if user tries to send submission via SMS if a phone number is not set

### ISSUE THREAD

**Issue by mmarciniak90** [getodk/collect#2459]
#### Problem description
The user should see pop up with phone number fields if the user tries to send submission via SMS if a phone number is not set

#### Steps to reproduce the problem
1. The user goes to `General Settings` -> `Server` and selects that submissions are sent via SMS
2. The user does not add a destination phone number 
3. The user sends a finalized form and sees `Failed` status

#### Expected behavior
1. Pop up with phone number field appears and the user is able to add a missing phone number
2. The added number is auto-filled in Settings

#### Notes
It is a similar case when the user selects Google Drive as a server but does not set a Google account. Google account pop up appears if the user tries to send submissions.

**Comment by jd-alexander** [comment]
@opendatakit-bot claim

**Comment by jd-alexander** [comment]
@opendatakit-bot label "needs-discussion"

**Comment by jd-alexander** [comment]
@opendatakit-bot label "needs discussion"

**Comment by jd-alexander** [comment]
I was thinking we could probably have a popup inside the setting that asks the users to supply the number than to put it on the upload screen. Thus we could keep settings related functionality in one area.

**Comment by jd-alexander** [comment]
So if a user ignores that then when they get the failure message it won't be alarming. We could also disable/rollback if the number isn't entered but I am thinking that might be too much.

 @yanokwa what do you think about these proposed ideas? Which would be the best?

**Comment by mmarciniak90** [comment]
@jd-alexander, good propositions! 
@yanokwa, I suggested to add the pop up during sending forms because we have similar behavior in case:
1. The user selects Google sheets as a server 
2. The user does not set Google Account
3. User tries to send submissions
4. Pop up with Google accounts appears

I figured that it will be consistent behavior for a case with sending SMS.

**Comment by yanokwa** [comment]
I was able to reproduce this on a fresh install, but it doesn't happen if you had set a phone number previously.

I agree with @jd-alexander that we should have some dialog/toast in the settings and not have it entered at submission. Doing it at submission feels high-risk (e.g., enumerators can make mistakes when entering the number). 

Since we currently show a toast when there is a bad number, maybe we should do the same thing on a fresh install. That is, if you hit the back button, we show the same toast, "Invalid phone number!" and you can't leave until you add a phone number or toggle the transport.

@jd-alexander Pointed out to me that it's possible to background/quit the application without setting a phone number and that would also be the source of a crash, so we should have something that prevents submissions if there isn't a phone number.

@mmarciniak90 Can you please file an issue abou tthe Google Sheets behavior? It feels different to me and I'm not sure that that behavior is ideal.
