### ISSUE TITLE
Improve behavior when the user selects Google Sheet as a server but the user does not add Google Account

### ISSUE THREAD

**Issue by mmarciniak90** [getodk/collect#2464]
#### Problem description
Improve case when the user selects Google Sheet as a server but the user does not add Google Account

#### Steps to reproduce the problem
1. The user selects Google sheets as a server
2. The user does not set Google Account
3. User tries to send submissions
4. Pop up with Google accounts appears

|Step 1, 2 | Step 3 | Step 4|
|---|---|---|
|![screenshot_20180809-131241](https://user-images.githubusercontent.com/3907554/43892965-fe5df93a-9bbc-11e8-83be-0ec4d7ac05cd.png)|![screenshot_20180809-131346](https://user-images.githubusercontent.com/3907554/43892963-fe3e1d68-9bbc-11e8-9fb0-5af49176eb18.png)|![screenshot_20180809-131353](https://user-images.githubusercontent.com/3907554/43892962-fe1d9e1c-9bbc-11e8-9a77-8f19e582cfa2.png)|

#### Expected behavior
In discussion under #2459 was suggested that we should improve this behavior.
The expected result need to be defined.

**Comment by mmarciniak90** [comment]
@opendatakit-bot label "needs discussion"

**Comment by jd-alexander** [comment]
@opendatakit-bot claim

**Comment by jd-alexander** [comment]
@yanokwa should the same approach that was taken for the SMS Phone Number Dialog validation be done?

**Comment by lognaturel** [comment]
@jd-alexander what options are you seeing? What do you think would be most effective for users and most consistent? Would be helpful to have a summary of all cases (e.g user sets an account when first configuring gdrive as the destination, form sets a destination, etc).

**Comment by jd-alexander** [comment]
In the meeting I had with @yanokwa we discussed the current approach where if an account isn't set then a user is able to select whichever user account they want for submissions. This basically bypasses the admin setting because if an admin sets up Google sheets as a destination and forgets to set an account then the user can log into any Google account they want on their device and then select that account at submission.  That's basically what led to the idea that this could be revisited. I am working on a summary now.

**Comment by jd-alexander** [comment]
**Title**

An enumerator should only be able to select a Google account if the admin has enabled the Server settings.

**Business/User Value**

Currently the enumerator can set a Google account if the transport is configured but the account was left deselected. Having this functionality only accessible in the Server settings also administrators to lockdown access if they want to. 

**Acceptance Criteria**

GIVEN I want to ensure that a Google account is set
WHEN I choose Google Sheets as a transport type and no account is selected
THEN upon navigation away from the settings screen a dialog should prompt me that no account was selected.

**Dev Notes**

A validation dialog was created for the SMS phone number setting so that code could be reused to trigger a similar dialog when the back pressed action is triggered.

**Design Notes**

The UI would look similar to that of the validation dialog for the SMS.

**Comment by jd-alexander** [comment]
For the different cases, if a user sets an account the first time they are configuring the Google sheets transport then this issue won't occur because once the first account is set there's currently no way to deselect/clear the account selection. The functionality only allows you to switch between multiple accounts.

For the form sets destination @lognaturel could you expound a bit on that case? since I might not be familiar with all the functionality as yet.

**Comment by lognaturel** [comment]
I don't exactly remember how Collect determines whether it needs to prompt for a username/password. Does it try to send anonymously since some sheets could allow anonymous writes and then prompt? Or are anonymous writes not allowed? If it's possible currently to submit anonymously, it should continue to be.

In general, forms meant to be submitted to gsheets have a destination set in the form. Sometimes it's set in settings instead and that overrides whatever's in the form. I'm not sure that makes a difference in terms of when the check for a Google account is made but it's something that came to mind as worth doing a quick check on.

Other than those things to verify, matching the new SMS behavior seems good!

**Comment by jd-alexander** [comment]
Okay, awesome! So we can remove `needs discussion` now? Verifying to be safe 😄
