### ISSUE TITLE
No animation on swipe between select questions when lists are long

### ISSUE THREAD

**Issue by lognaturel** [getodk/collect#2554]
#### Software and hardware versions 
Collect v1.17.0-beta.1, Android 7.0, Motorola G4

#### Problem description
When two select questions with the same choices are one after the other, swiping from one to the other does not result in an animation.

#### Steps to reproduce the problem
1. Launch a form with select questions that have many choices such as [select-screen-transitions.xml.txt](https://github.com/opendatakit/collect/files/2399539/select-screen-transitions.xml.txt)
1. Swipe between those questions and see there is no animation
1. Swipe to questions that have a shorter choice list and see there is an animation

#### Expected behavior
There should be an animation between all questions.

#### Other information 
Confirmed this works as expected in 1.16.4 so it has to do with the recent `RecyclerView` refactor.

**Comment by grzesiek2010** [comment]
> when choices are the same

It doesn't matter. I tried a form with different choices and it's the same.
Here are my forms I used:
[animationTest10Items.xml.txt](https://github.com/opendatakit/collect/files/2405230/animationTest10Items.xml.txt)
[animationTest20Items.xml.txt](https://github.com/opendatakit/collect/files/2405231/animationTest20Items.xml.txt)
[animationTest30Items.xml.txt](https://github.com/opendatakit/collect/files/2405232/animationTest30Items.xml.txt)

I can reproduce the issue on my Galaxy S4 Android 5. I can see the animation only using the form with 10 items and sometime (but hardly visible) using the form with 20 items.

What's interesting everything works perfect on Androi 4.2 (Samsung Duos)
and on emulator Android 7.

That's right that it's caused by implementin the recyclerview but I can't see any mistake on our side and probably it's an Android bug. What device do you use?

**Comment by lognaturel** [comment]
Interesting! It looks like I misinterpreted what I experienced -- you're right it has to do with the list length and not the contents. That makes a lot more sense. I've updated the issue to include the latest information including that this was found on a Motorola G4 running Android 7.0. It seems to has to do with when items need to scroll.

I'd be ok to close this since I think you're right there's not likely to be anything we can do.

**Comment by grzesiek2010** [comment]
> I'd be ok to close this since I think you're right there's not likely to be anything we can do.

It might be difficult but I remember @huangyz0918 likes such strange Android bugs. Do you want to take a look @huangyz0918?

**Comment by huangyz0918** [comment]
I have tried several emulators, but I cannot reproduce the issue. I think it's a bug from system, and I will  take a deeper look at this so it's not so hurry for us to close it.

**Comment by lognaturel** [comment]
Good to know it's not reproducible on most devices. Let's close!
