### ISSUE TITLE
Sorting/filtering of filled up forms for editing and submisison

### ISSUE THREAD

**Issue by alfikim** [getodk/collect#258]
### Software and hardware versions
ODK Collect 1.4.11

### Problem description
there is no easy way to sort/filter filled forms for editing and submission through the edit save form 

### Steps to reproduce the problem
go to edit saved form and locate any of your saved forms

### Expected behavior
easily identify the form you want to edit for action

**Comment by grzesiek2010** [comment]
I think we need a section with an EditText (for filtering) and a button for (sorting). I attached my proposal how it might look. 
The list should be filtered automatically when user adds something into EditText. Popup dialog should be shown after clicking on "sorting button" of course.
![proposal](https://cloud.githubusercontent.com/assets/3276264/22151544/c062e692-df1e-11e6-888d-f22b42371843.png)

Any other ideas? Mybe other sorting options?

**Comment by lognaturel** [comment]
Looks good! I think it makes sense to split this up into two PRs since the functionality is independent. Let's start with sort and then add search/filter next. 

For the sort icon, you can use the [Google alphasort icon](https://material.io/icons/#ic_sort_by_alpha). I think it would be good to try putting it in the app bar (like the save and go to buttons on the form edit screen).

The sort options are great to start. I'd put "By name, A-Z" or "By date, newest first" to make it a bit easier to use than ASC and DESC.

@alfikim does that meet your needs?

**Comment by lognaturel** [comment]
👏👏 @grzesiek2010 👏👏

@alfikim Please look for this functionality in the Sunday 3/26 release!
