### ISSUE TITLE
Fast forward and rewind options in AudioWidget use a constant amount of seconds.

### ISSUE THREAD

**Issue by grzesiek2010** [getodk/collect#2596]
#### Software and hardware versions 
Collect v1.17.1 and older versions

#### Problem description
Fast forward and rewind options in AudioWidget use a constant amount of seconds (5s) what doesn't work well if a recorded sound is long or very short. In such cases, the change is almost not visible (long sound) or move us to the end of the sound (short sound).

#### Steps to reproduce the problem
1. Open any form with AudioWidget and record any sound.
2. Try to fast forward or rewind.

#### Expected behavior
The best solution would be to calculate the value we use to forward and rewind based on the sound duration. It should be for example `soundDuration / 5`.

**Comment by lognaturel** [comment]
The 5s behavior matches other audio players. It is there so that even if the audio track is quite long, it's possible to go back or forward just a little bit. I use it to do things like find the beginning of a sentence. This is hard to do with the scrubber.

It's not as relevant with a short track but that's ok because the scrubber makes it easy to go back or forward a little bit.

`soundDuration / 5` has a completely unpredictable behavior to a user and I don't see when it would be useful! For a very short track, seeking is not that useful anyway. For a long track, the point of seeking is to be able to go back and forth by small amounts.

**Comment by lognaturel** [comment]
Let's close and if a user reports an issue with the scrubbing behavior we can reopen.
