### ISSUE TITLE
Clicking quickly on a list item from one of the main menu lists has no effect

### ISSUE THREAD

**Issue by lognaturel** [getodk/collect#2642]
#### Software and hardware versions 
Collect v1.17.1, Android v7, Moto G4 and I am pretty sure I have experienced this on every device I've used, just thought it was me not tapping correctly

#### Problem description
Tapping quickly on a list item from one of the main menu lists has no effect

#### Steps to reproduce the problem
1. Open one of the activities from the main menu (e.g. Fill Blank Form)
1. Tap on a list element immediately when the list loads
1. The tapping animation is shown but the item is not selected as intended

#### Expected behavior
Tapping on a list element once it has loaded always works, regardless of how quickly the tap happens after the list load.

**Comment by ondri124** [comment]
Hello, can i take this one?

**Comment by grzesiek2010** [comment]
It was implemented in order to fix https://github.com/opendatakit/collect/issues/1630 I also noticed sometimes it's annoying but at least it fixes the bug. Maybe we can try to make the min interval shorter.

**Comment by cooperka** [comment]
Here's [the diff](https://github.com/opendatakit/collect/pull/1765/files?w=1) for the PR disabling multiple clicks within 500 ms. Would a simple `lastClickTag` help, e.g. pass in the name of the activity on which `lastClick` took place?

1. Refactor `allowClick()` => `allowClick(String tag)`
2. Always allow clicks if the tag is **different** from the last tag, otherwise continue to respect the 500 ms throttle for clicks on the same activity

I'm happy to implement this if it sounds feasible (edit: @ondri124 gets first dibs!)

**Comment by lognaturel** [comment]
Thank you, @grzesiek2010 for remembering that history! I completely forgot we used time to debounce clicks.

@cooperka your approach sounds like a good one. Is it really the case that there's no standard Android built-in way to deal with these click issues? Another option might be to disable the button on click but that would require being super careful to re-enable it for every possible re-entry point.

**Comment by cooperka** [comment]
Nothing aside from sub-classing Button and ensuring all past and future instances use the subclass instead of the built-in. iOS has the same problem. It seems like it would be simple enough for Android to offer global debounce contols, but no :crying_cat_face: 

@ondri124 you had wanted to tackle this, feel free to claim it -- otherwise I'll come by tomorrow and grab this one.

**Comment by ondri124** [comment]
@cooperka you can take it, but I would like to work on this issue too, just because I want to try to contribute on opensource project but on the other hand, I can see that you have an idea how to solve this issue and I dont want to be the one to interrupt or stall. Maybe we can then share our results and see which would be Appropriate as a whole. :)

**Comment by cooperka** [comment]
Okay, good plan. I'll share my solution here when it's ready. @opendatakit-bot claim

**Comment by cooperka** [comment]
Feel free to take a look @ondri124: https://github.com/opendatakit/collect/pull/2657
