### ISSUE TITLE
Not clear from docs if non-relevant data will be submitted

### ISSUE THREAD

**Issue by alxndrsn** [getodk/collect#266]
> #### 6.1.4 The relevant Property
> 
> Description: indicates whether the model item is currently _relevant_. Instance data nodes with this property evaluating to `false` are unavailable in the user interface and can be removed from submission serialization.
> — _http://www.w3.org/TR/xforms/#model-prop-relevant_

It's not clear from the docs whether fields whose `relevant` attribute evaluates to `false()` will be the case for data submitted via ODK Collect or not.  It appears that non-relevant fields are **excluded** from submission.  It would be helpful to document this behaviour.

**Comment by yanokwa** [comment]
ODK tools aren't always XForms compliant, so there's that. In this case, non-relevant data is not submitted. 

I believe the most up-to-date documentation is at https://bitbucket.org/javarosa/javarosa/wiki/xform. What would be ideal is that we move that wiki over to Github and make sure it's up-to-date.

Since you are poking around the Javarosa stuff, is that an effort you'd be interested in helping with?

**Comment by alxndrsn** [comment]
Interesting, I'd always assumed the up-to-date spec was at https://opendatakit.github.io/odk-xform-spec/!  Given that, I'm not sure this is something I could provide definitive help with, unless it's just a copy/paste job?  FWIW I vote `gh-pages` over github's wiki functionality, as the latter seems to be entirely un-searchable.  And the link above would seem to already be `gh-pages`...

**Comment by yanokwa** [comment]
Unfortunately, this won't be a copy and paste thing. We'll have to hold on this issue until we get a better sense of the state of Javarosa. I'm hoping we can do that in a few weeks.

**Comment by lognaturel** [comment]
I think that this has now been addressed by a combination of the [odk-xforms spec](http://opendatakit.github.io/xforms-spec/#bind-attributes) and opendatakit/xforms-spec#46.
