### ISSUE TITLE
Feature request - Add a function / API to return what language is currently selected

### ISSUE THREAD

**Issue by joeflack4** [getodk/collect#2672]
## Current behavior
There doesn't seem to be a way to programmatically declare in an XForm / XLSForm an ODK Collect client-specific function to determine the language that is currently selected in the client.

## Desired behavior
A way to programmatically declare in an XForm / XLSForm an ODK Collect client-specific function to determine the language that is currently selected in the client, e.g.

`if(client-language() = 'English', 'hello!', if(client-language() = 'Spanish', 'hola!', ''), '')`

**Comment by lognaturel** [comment]
Thanks, @joeflack4! In general, please describe feature requests on the forum so that they can be prioritized, turned into a closeable issue and then filed on the appropriate repo. In, this case, there would be details to figure out like what the function name should be, what language codes are used, etc. Once the behavior is specified, it would become a JavaRosa issue.

**Comment by joeflack4** [comment]
@lognaturel Hey Helene. Thanks for the response. I'll go ahead and do that.

Should we update the default text of new issues to suggest going to the forum? Right now it says:

> For feature requests, please include the problem description (what problem do you have that can't currently be solved?) and a proposed solution if you have one in mind (optional). You can delete the template. 

If you want it updated, I can make a PR.

**Comment by lognaturel** [comment]
> If you want it updated, I can make a PR.

That would be awesome, thank you!

**Comment by joeflack4** [comment]
@lognaturel Waiiiiit a minute. You already touched on this in a PR today on the readme file, haha. Ok, I'll use some of that text.
