### ISSUE TITLE
App refuses to build on Android 3.2.1 if Crashlytics Gradle plugin version is not >= 1.25.4 

### ISSUE THREAD

**Issue by muarachmann** [getodk/collect#2749]
#### Software and hardware versions 
Collect v1.x.x, Android v3.2.1, 

#### Problem description
Project refuses to build nor sync if  Crashlytics Gradle plugin version is not 1.25.4 and higher

#### Steps to reproduce the problem
Get a fresh install of the project and build. 

#### Expected behavior
It should build if plugins are correct

If this is valid i can upgrade the `build.gradle` to the necessary version file and make a PR

**Comment by huangyz0918** [comment]
The "Crashlytics Gradle plugin" is found in gradle in the `io.fabric.tools:gradle` package as mentioned on https://firebase.google.com/docs/crashlytics/get-started

You should find that in your projects root `build.gradle` file. Similar to this

    buildscript {
        repositories {
            jcenter()
            google()
            maven { url 'https://maven.fabric.io/public' }
        }
        dependencies {
            classpath 'io.fabric.tools:gradle:1.25.1'
            ...
        }
    }
    
    allprojects {
        ...

Once you change it to `classpath 'io.fabric.tools:gradle:1.25.4'` that error should go away.

The versions of a maven dependency can also be found in its maven repository under 

> https://maven.fabric.io/public/io/fabric/tools/gradle/maven-metadata.xml

That trick should work for all maven repositories once you know the url: 

> `<repo-base-url>/${groupId.replace('.','/')}/${artifactId}/maven-metadata.xml`

You can also use a gradle plugin such as https://github.com/ben-manes/gradle-versions-plugin to have it lookup the latest versions in those `maven-metadata.xml` files for you.

If you simply want the latest you can also define the version with a wildcard, e.g.

    classpath 'io.fabric.tools:gradle:1.+' // or even ...:gradle:+'

That would always give you the latest version that starts with `1.`. It's rarely done in production since builds become less deterministic when dependency versions change from one moment to the next. But it's good to check whether gradle downloads a newer version.

Furthermore, Android Studio does check versions too, however you don't see the difference between there being no new version and when the check wasn't done yet. But when it did, you'll get an inspection hint and it can be quick fixed.


You can refer to this from [here](https://stackoverflow.com/questions/52506288/the-android-gradle-plugin-supports-only-crashlytics-gradle-plugin-version-1-25-4). If you'd like to file a PR, I think it's ok, let's wait for other's opinion.

**Comment by yanokwa** [comment]
I haven't had a chance to look closely at this, but I think https://forum.opendatakit.org/t/collect-18-0-1-wont-build-in-android-studio-3-2-1/16392 is related.

My preference is to have explicit versions and the most minimal version increase that will allow the build to work.

I would welcome a PR, @muarachmann and perhaps @huangyz0918 can review it.

**Comment by muarachmann** [comment]
@yanokwa , @huangyz0918  thanks for your replies i made the changes and my project successfully built up. Will make a PR then
