### ISSUE TITLE
Crash when the user rotates device many times and quickly on GeoWidgets

### ISSUE THREAD

**Issue by mmarciniak90** [getodk/collect#2856]
#### Software and hardware versions 
Collect v1.19.0, older versions were not verified
Android 7.0, 6.0, 5.1, 4.4

#### Problem description
Crach when the user rotates device many times and quickly on GeoWidgets

#### Steps to reproduce the problem
1. User starts form with GeoWidgets with maps appearance
2. User opens question with map
3. User rotates a few times, increasing the speed of rotation
4. App crashes
![crash](https://user-images.githubusercontent.com/3907554/52413034-af15e780-2ae0-11e9-8e2f-91effd97524c.png)

#### Expected behavior
App does not crash

#### Other information 
Discovered during testing #2806

**Comment by zestyping** [comment]
The exception in the screenshot here looks similar to the one in https://stackoverflow.com/questions/5768857/weird-exception-when-livewallpaper-is-set-in-android. 
 However, I'm suspecting that this RuntimeException in WallpaperService is not what causes the crash, because it's shown as only a warning ("W" in front of WallpaperService) in the screenshot above, not an error ("E").

I'm able to cause a crash by rotating the device rapidly about 10-20 times, though the exception is different from the one shown in the screenshot above.  When I crash the app this way, this is the exception I see in logcat:

        java.lang.NullPointerException: Attempt to invoke interface method 'org.odk.collect.android.map.MapPoint org.odk.collect.android.map.MapFragment.getCenter()' on a null object reference
            at org.odk.collect.android.activities.GeoPointMapActivity.onSaveInstanceState(GeoPointMapActivity.java:161)
            at android.app.Activity.performSaveInstanceState(Activity.java:1298)

@mmarciniak90 Was there a reason that you posted this as a new issue, instead of a comment on #2806?  There isn't quite enough detail for me to know exactly what you did (which form question, which map API, how you rotated the phone).  Can you try to replicate this issue under the same conditions you used originally, and when you look in the log for the crash, look for an exception reported as an error ("E") and post the exception message that you see?  I'd like to confirm if the crash you experienced has the same root cause, or if we are encountering two separate issues.  Thank you so much!

**Comment by mmarciniak90** [comment]
@zestyping I did not add this to #2806 because it was also visible on v1.19, it is mentioned in the description.

> There isn't quite enough detail for me to know exactly what you did (which form question
* I used `All widgets` form
* All Geo widgets crashes 

> which map API

Both, Google maps and OSM

> how you rotated the phone

* From the vertical orientation to horizontal orientation and vice versa
* Few times
* I try to rotate the device faster and faster

**Comment by grzesiek2010** [comment]
@zestyping The crash @mmarciniak90 discovered is visible in our reports:

```java
Fatal Exception: java.lang.NullPointerException
Attempt to invoke virtual method 'int org.odk.collect.android.spatial.MapHelper.getSelectedLayer()' on a null object reference
keyboard_arrow_up
arrow_right
org.odk.collect.android.activities.BaseGeoMapActivity.onSaveInstanceState (BaseGeoMapActivity.java:39)
org.odk.collect.android.activities.GeoShapeActivity.onSaveInstanceState (GeoShapeActivity.java:104)
android.app.Activity.performSaveInstanceState (Activity.java:1502)
android.app.Instrumentation.callActivityOnSaveInstanceState (Instrumentation.java:1308)
```

so I hope it will help you.

> how you rotated the phone

don't ask it could be like https://www.youtube.com/watch?v=qd9DogTgCEI&t=73s :wink:

**Comment by zestyping** [comment]
Ahh, _that's_ what @mmarciniak90 is doing when performing QA!  😆  Amazing skills!
