### ISSUE TITLE
GeoTrace saved as Polygon few times generates unexpected coordinates

### ISSUE THREAD

**Issue by mmarciniak90** [getodk/collect#2868]
#### Software and hardware versions 
Collect v1.19, older versions were not verified

#### Problem description
GeoTrace saved as Polygon few times generates unexpected coordinates

#### Steps to reproduce the problem
1. User saved Geotrace as Polygon
2. User opens widget again and user DOES NOT change the answer
3. User saved Geotrace as Polygon
4. User repeats these steps a few times
5. User sees more coordinates than expected

![geotrace](https://user-images.githubusercontent.com/3907554/52643520-807f7e80-2edd-11e9-8350-8a1aedbc11be.gif)

#### Expected behavior
Additional coordinates are not generated

#### Other information 
Discovered during testing #2865

**Comment by zestyping** [comment]
This is a known existing bug in the previous GeoTrace activity that is preserved in the new GeoTrace activity.  The [plan](https://docs.google.com/document/d/1r3wJrOVDeFQkk4kWMoW29LtLI1vbBChqJ65w1Jyg4YU/edit) is for GeoTrace to always save as a line (not a polygon) and GeoShape to always save as a polygon (not a line), so this behaviour will soon be removed anyway.  I am happy to fix it because the fix is very easy, though I am not sure it is worthwhile to expend reviewing and testing resources on the fix.
