### ISSUE TITLE
Last question in Edit Saved Form view is hidden by Go to Start/End buttons

### ISSUE THREAD

**Issue by yanokwa** [getodk/collect#2871]
#### Software and hardware versions 
Collect v1.9.0. Also happens in Collect v1.18.2

#### Problem description
Last question in Edit Saved Form (or Jump) is hidden by Go to Start/End buttons

#### Steps to reproduce the problem
* Download this two question form [basic.xml.zip](https://github.com/opendatakit/collect/files/2857520/basic.xml.zip). The first question in this form has a very very long label.
* Try to fill out out.
* Hit Jump button
* Scroll to bottom.
* Notice you can't see the second question.

#### Expected behavior
I expect to see the second question.

#### Other information 
When I hit Jump from the second question (which exists), I don't see it in the Jump view
![bug](https://user-images.githubusercontent.com/32369/52666279-ba8f5700-2ec2-11e9-9f19-2ce54b19ef11.gif)

**Comment by grzesiek2010** [comment]
The last question is not covered by buttons it just doesn't exist in the list...
you can test `All widgets` from there everything is fine. It's a bug, in this case, it takes place because your first question is in another group. If I remove the group everything works fine [basic2.xml.txt](https://github.com/opendatakit/collect/files/2860028/basic2.xml.txt)
@cooperka since you implemented all those changes and know the code better could you take a look?

**Comment by cooperka** [comment]
I confirmed that this is a bug since at least November, v1.18.0 (before any of my changes). I'll look into a fix since I'm familiar with the logic.

**Comment by cooperka** [comment]
Open PR is ready for review but lower priority. Just avoiding spam: @opendatakit-bot unclaim

**Comment by mjthompson2** [comment]
Is this still available?

**Comment by grzesiek2010** [comment]
> Is this still available?

No. There is a pr which is waiting for review/testing.
