### ISSUE TITLE
Browsing Google Drive on a fresh Gmail account causes crash

### ISSUE THREAD

**Issue by yanokwa** [getodk/collect#289]
#### Software and hardware versions 
ODK Collect v1.4.12, Android v6.0.1, Nexus 5

#### Problem description
ODK Collect crashes when trying to load My Drive 

#### Steps to reproduce the problem
1. Create a totally new Gmail account.
1. Add the Gmail account to the device
1. Change settings in Collect to Google Drive/Sheets platform and add the Gmail account as Google account
1. In the Main Menu, tap Get Blank Form, tap My Drive.
1. Collect crashes with a GoogleAuthIOException.

#### Expected behavior
Collect should not crash. You should get a pop-up dialog asking for OAuth permissions.

#### Other information 
In my tests, if instead of My Drive, you use the magnifying glass and try to search for a form, then the application shows the pop-up dialog asking for OAuth.  You can deny that dialog, and the My Drive works. 

If this is not reproducible, it might be because you are not using a new account, or this bug is caused my something server-side.

```
12-08 15:54:44.592 17965 18054 W System.err: com.google.api.client.googleapis.extensions.android.gms.auth.GoogleAuthIOException
12-08 15:54:44.596 17965 18054 W System.err: 	at com.google.api.client.googleapis.extensions.android.gms.auth.GoogleAccountCredential$RequestHandler.intercept(GoogleAccountCredential.java:286)
12-08 15:54:44.596 17965 18054 W System.err: 	at com.google.api.client.http.HttpRequest.execute(HttpRequest.java:859)
12-08 15:54:44.596 17965 18054 W System.err: 	at com.google.api.client.googleapis.services.AbstractGoogleClientRequest.executeUnparsed(AbstractGoogleClientRequest.java:419)
12-08 15:54:44.597 17965 18054 W System.err: 	at com.google.api.client.googleapis.services.AbstractGoogleClientRequest.executeUnparsed(AbstractGoogleClientRequest.java:352)
12-08 15:54:44.597 17965 18054 W System.err: 	at com.google.api.client.googleapis.services.AbstractGoogleClientRequest.execute(AbstractGoogleClientRequest.java:469)
12-08 15:54:44.597 17965 18054 W System.err: 	at org.odk.collect.android.activities.GoogleDriveActivity$RetrieveDriveFileContentsAsyncTask.doInBackground(GoogleDriveActivity.java:564)
12-08 15:54:44.597 17965 18054 W System.err: 	at org.odk.collect.android.activities.GoogleDriveActivity$RetrieveDriveFileContentsAsyncTask.doInBackground(GoogleDriveActivity.java:528)
12-08 15:54:44.597 17965 18054 W System.err: 	at android.os.AsyncTask$2.call(AsyncTask.java:295)
12-08 15:54:44.597 17965 18054 W System.err: 	at java.util.concurrent.FutureTask.run(FutureTask.java:237)
12-08 15:54:44.597 17965 18054 W System.err: 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1113)
12-08 15:54:44.597 17965 18054 W System.err: 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:588)
12-08 15:54:44.597 17965 18054 W System.err: 	at java.lang.Thread.run(Thread.java:818)
12-08 15:54:44.597 17965 18054 W System.err: Caused by: com.google.android.gms.auth.GoogleAuthException: Unknown
12-08 15:54:44.598 17965 18054 W System.err: 	at com.google.android.gms.auth.GoogleAuthUtil.getToken(Unknown Source)
12-08 15:54:44.598 17965 18054 W System.err: 	at com.google.android.gms.auth.GoogleAuthUtil.getToken(Unknown Source)
12-08 15:54:44.598 17965 18054 W System.err: 	at com.google.api.client.googleapis.extensions.android.gms.auth.GoogleAccountCredential.getToken(GoogleAccountCredential.java:255)
12-08 15:54:44.598 17965 18054 W System.err: 	at com.google.api.client.googleapis.extensions.android.gms.auth.GoogleAccountCredential$RequestHandler.intercept(GoogleAccountCredential.java:279)
12-08 15:54:44.598 17965 18054 W System.err: 	... 11 more
12-08 15:54:44.600 17965 18054 E AndroidRuntime: FATAL EXCEPTION: AsyncTask #2
12-08 15:54:44.600 17965 18054 E AndroidRuntime: Process: org.odk.collect.android, PID: 17965
12-08 15:54:44.600 17965 18054 E AndroidRuntime: java.lang.RuntimeException: An error occurred while executing doInBackground()
12-08 15:54:44.600 17965 18054 E AndroidRuntime: 	at android.os.AsyncTask$3.done(AsyncTask.java:309)
12-08 15:54:44.600 17965 18054 E AndroidRuntime: 	at java.util.concurrent.FutureTask.finishCompletion(FutureTask.java:354)
12-08 15:54:44.600 17965 18054 E AndroidRuntime: 	at java.util.concurrent.FutureTask.setException(FutureTask.java:223)
12-08 15:54:44.600 17965 18054 E AndroidRuntime: 	at java.util.concurrent.FutureTask.run(FutureTask.java:242)
12-08 15:54:44.600 17965 18054 E AndroidRuntime: 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1113)
12-08 15:54:44.600 17965 18054 E AndroidRuntime: 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:588)
12-08 15:54:44.600 17965 18054 E AndroidRuntime: 	at java.lang.Thread.run(Thread.java:818)
12-08 15:54:44.600 17965 18054 E AndroidRuntime: Caused by: java.lang.NullPointerException: Attempt to invoke virtual method 'java.lang.String com.google.api.services.drive.model.File.getId()' on a null object reference
12-08 15:54:44.600 17965 18054 E AndroidRuntime: 	at org.odk.collect.android.activities.GoogleDriveActivity$RetrieveDriveFileContentsAsyncTask.doInBackground(GoogleDriveActivity.java:572)
12-08 15:54:44.600 17965 18054 E AndroidRuntime: 	at org.odk.collect.android.activities.GoogleDriveActivity$RetrieveDriveFileContentsAsyncTask.doInBackground(GoogleDriveActivity.java:528)
12-08 15:54:44.600 17965 18054 E AndroidRuntime: 	at android.os.AsyncTask$2.call(AsyncTask.java:295)
12-08 15:54:44.600 17965 18054 E AndroidRuntime: 	at java.util.concurrent.FutureTask.run(FutureTask.java:237)
12-08 15:54:44.600 17965 18054 E AndroidRuntime: 	... 3 more
12-08 15:54:44.609   778  3228 W ActivityManager:   Force finishing activity org.odk.collect.android/.activities.GoogleDriveActivity
```

**Comment by swang0221** [comment]
Hi, Hope you can help me here, I am getting the same issue, did you find the fix for it yet?

**Comment by yanokwa** [comment]
@swang0221 It is in the queue to be fixed. If you are a developer, we'd appreciate a pull request that fixes the issue. If you are not a developer, we ask that you wait.

**Comment by grzesiek2010** [comment]
Hi!
I investigated this issue deeply on Samsung Galaxy S4 (Android 5.0.1) and using Genymotion (Android 6.0). What I noticed is different than an above mentioned description. I got the same exception but I've not noticed differences between a fresh and an old account or between "magnifying glass" and "My Drive" buttons. Both accounts and both buttons cause an exception BUT to my surprise I was able to reproduce this exception only when I install the app by Android Studio (sometimes it works in this case well too but only sometimes). Otherwise when I use the apk from Google Play everything works well everytime.

As you can see it works really randomly so I have no idea what is the reason. 
@swang0221 maybe you can add some more information? If not I can only try to catch this exception to avoid a crash. The main question is: which source did you use? If it works well on signed apk from Google Play (as I noticed) the issue is less important.

**[Edit]**
I discovered that the app crashes sometimes when I install the app from Google Play too but less often (for me). I'm really confused. It's so randomly.

**Comment by lognaturel** [comment]
I agree, @grzesiek2010, this is quite a confusing issue. @swang0221 can you please let us know how you installed Collect before getting this issue? Was it from source or from the Play Store? As @grzesiek2010 says, this will help figure out how much of a priority the issue is.

From the small amount of testing I've done, I've never gotten a crash on an install from the Play Store and always gotten one on the emulator from source. Maybe the retry like @grzesiek2010 has in #331 is worth a shot after all.

**Comment by swang0221** [comment]
I git clone odk collect from github and compiled it on android studio. The
one from play store doesn't have the same issue.  Anyway , I am using
GoogleApiClient instead, You can download this package
com.google.android.gms.drive.sample.demo
to see all sample codes.

**Comment by lognaturel** [comment]
Thanks, @swang0221, that's very helpful. @yanokwa, is it possible that you simply experienced this because you were running from source?

Each dev's debug cert must be registered to allow using the Google Drive API locally. You can set that up with instructions [here](https://developers.google.com/drive/android/auth). The link to the dev console is broken, use [this one](https://console.developers.google.com) instead. I only followed the instructions to "Generate the signing certificate fingerprint and register your application" and then I enabled the Drive API [here](https://console.developers.google.com/apis/api/drive/). I believe this fixes the problem. It would be very helpful if you could verify @swang0221, @grzesiek2010 and @yanokwa. I will write this up for the readme.

**Comment by lognaturel** [comment]
I should add that I've also tried this with a brand new Google account with no problems.

**Comment by swang0221** [comment]
Hi, I think the issue why it crashed probably caused by google drive API
registration.  you probably should compile the source and register your app
to google console. if you do it properly, it may fix the problem,  however,
if you just like to use ODK Collect without messing any codes, you can just
download a apk from play store, I tried that one and it works pretty good.

**Comment by lognaturel** [comment]
@grzesiek2010 and @yanokwa when you get a chance, can you please let us know whether the local configuration solves the problem for you?

**Comment by grzesiek2010** [comment]
@lognaturel I've just verified that and it worked.
But it's still strange... it worked then I reverted my personal API key and it still works :) don't know why. Additionaly as I mentioned before I noticed the crash using the app from Google Play too - three times at most but still... I hope it was an accident only. 
So what about my "try again" option. Do you want to keep this option? I can remove that if you want.

**Comment by lognaturel** [comment]
That's great, thank you! There is no API key needed for this API, the app is authed based on the app ID and your key.

Let me think a bit about the try again thing. It might be good to say something like "If you are running from source code, make sure to follow the instructions on enabling the GDrive API in the README." That could save someone some headaches.

**Comment by lognaturel** [comment]
#334 adds instructions to the README. I think that's sufficient.
