### ISSUE TITLE
Fatal Exception: java.lang.IndexOutOfBoundsException

### ISSUE THREAD

**Issue by grzesiek2010** [getodk/collect#2928]
#### Software and hardware versions 
Collect v1.20.0 and older versions

#### Problem description
https://console.firebase.google.com/u/0/project/api-project-322300403941/crashlytics/app/android:org.odk.collect.android/issues/5b58da6f6007d59fcdbf0172?time=last-seven-days&sessionId=5C78DC2F01F8000134CAA0ADC5D0C786_DNE_4_v2

```
Fatal Exception: java.lang.IndexOutOfBoundsException
Invalid index 30, size is 0
keyboard_arrow_up
java.util.ArrayList.throwIndexOutOfBoundsException (ArrayList.java:255)
java.util.ArrayList.get (ArrayList.java:308)
arrow_right
org.odk.collect.android.adapters.FileArrayAdapter.getView (FileArrayAdapter.java:97)
android.widget.AbsListView.obtainView (AbsListView.java:2937)
android.widget.ListView.makeAndAddView (ListView.java:1945)
android.widget.ListView.fillUp (ListView.java:755)

```

**Comment by shobhitagarwal1612** [comment]
I believe the problem is because the list `filteredList` which is created and mutated in `GoogleDriveActivity` is referenced directly instead of copying the content in the `FileArrayAdapter` as well.

One of the possible solutions would be to copy the list items into a new list within `FileArrayAdapter` instead of using the same list instance

**Comment by grzesiek2010** [comment]
I'm not sure. If you used a new array notifyDataSetChanged() wouldn't work. Let's merge my change first and then we will see.
