### ISSUE TITLE
Geo: Collect averaged points

### ISSUE THREAD

**Issue by zestyping** [getodk/collect#2950]
(This item is moved here from the [ODK Geo roadmap document](https://docs.google.com/document/d/1r3wJrOVDeFQkk4kWMoW29LtLI1vbBChqJ65w1Jyg4YU/edit#).)

Allow the enumerator to collect several points and use their average as the result.  By waiting for several points to be collected, the enumerator can improve the accuracy of the final result.

Some discussion is needed as to the exact featureset and UI.

To prompt discussion, below is an example of a previous implementation:
![2019-03-16 23-18-49](https://user-images.githubusercontent.com/236086/54482867-3b65a980-4807-11e9-9c70-503713c82a67.png)

Points are continuously collected, and the user sees continuous feedback on the accuracy level.  During collection, the user can adjust the desired accuracy threshold (which defaults to 5 m) to include more points or fewer points.  The dialog gives feedback on the number of collected points so far that meet the threshold.  When the user is happy with the number of points and the accuracy setting, they can tap "Save", which computes the average of all the points that meet the threshold.

**Comment by danbjoseph** [comment]
It's great that you are continuing to improve and build out the geo functionality of ODK Collect!

Would this be a control that is toggled in the survey form? Automatically something that the user would be able to do for a geopoint question? Or a new geo question type?

If the user adjusts the accuracy down/up, does it affect which points are included in the calculation looking at all those that have been collected since the question started? Or does it only affect which points are stored and used for the calculation going forwards?

I find the previous implementation example a little confusing. Is the "required accuracy" for the individual points or for the averaged location? Is the "GPS accuracy" the calculated average accuracy or the accuracy of the current sensor reading? Would it be useful to know the total number of collected points in addition to the number of acceptable points?

**Comment by zestyping** [comment]
Thanks for these questions!

We're thinking of this as a feature of a GeoPoint question.  Whether it's enabled by the app user or by the form designer (or both) is not yet determined.

In the example:
- The GPS accuracy shown is the accuracy of the current sensor reading.
- The "required accuracy" threshold is for the individual points.
- When "required accuracy" is adjusted, it changes which of the already collected points are included in the average.  In other words, all the points are stored, and all of them are filtered according to this adjustable parameter.

That's how this particular prototype implementation worked, though I don't claim that it's the best design.  It does give you a clue as to how it works because you can see how the number of acceptable points changes when you adjust the accuracy threshold, but still, I can see how the display would be ambiguous for someone who wasn't familiar with it.

**Comment by zestyping** [comment]
Moved this over to [an ODK Forum topic](https://forum.opendatakit.org/t/geo-collect-averaged-points/18943/3).
