### ISSUE TITLE
The first option is not chosen as default on Choose Google account dialog on Android 8.1, 9.0

### ISSUE THREAD

**Issue by kkrawczyk123** [getodk/collect#2955]
#### Software and hardware versions 
Collect v1.20.x, Android v8.1, 9.0, device used...

#### Problem description
The first option from the list on "Choose account for ODK Collect" dialog window is not chosen as default. Screenshot attached:
![Screenshot_20190320-115353](https://user-images.githubusercontent.com/33342488/54679896-baf5c000-4b08-11e9-8727-0fed35104669.png)

#### Steps to reproduce the problem
1. Go to Server Settings
2. Choose Type Google Drive/Google Sheets
3. Click on Google account

#### Expected behavior
The first choice should be selected for default on that dialog message.

#### Other information 
It works properly on other Androids, it doesn't matter if the light or dark mode is chosen.

**Comment by grzesiek2010** [comment]
It's because `GoogleAccountCredential.getAllAccounts()` returns an empty array on tthe mentioned device.
That's strange, according to the comment:
`/** Returns all Google accounts or {@code null} for none. */`
it should be an array with accounts or null.
If I select the account once (manually) and then reset settings it works well. I'm not sure if it's an issue on our side. I would rather say it might be a bug in google api.

Since it's not serious I'm not going to spent time on it. If there is someone here who likes such detective work please claim.

**Comment by breakbusyloop** [comment]
I have this same experience using Google apps like Hangouts on a device where I only have one account signed in. I regularly see the same prompt to select an account to use, where the only account presented to me is not selected by default. As @grzesiek2010 mentioned this may be behavior in the Google API that is out of our control.

**Comment by lognaturel** [comment]
Good to know, @OpenDataNerd. Let's close.
