### ISSUE TITLE
Update submission analytics to include form ID

### ISSUE THREAD

**Issue by yanokwa** [getodk/collect#2965]

**Comment by lognaturel** [comment]
Thanks, @grzesiek2010, for taking this on! I had to rethink through it since there's no description to the issue. So for posterity:
- the goal is to get a sense of how many different projects are using the various submission options. Right now we can't differentiate between a single huge deployment relying on e.g. Google Sheets autosubmission or many small ones doing the same.
- we don't just want to include formID, we want to include the privacy-preserving identifier from `Collect.getCurrentFormIdentifierHash`
- in the submission case, we're not dealing with just the current form that the form controller keeps track of so we need to be able to build an identifier hash for an arbitrary form.
