### ISSUE TITLE
export to google drive table: change separator '-' or disable form/group/field separation

### ISSUE THREAD

**Issue by enricofer** [getodk/collect#298]
#### Software and hardware versions 
Collect v1.x.x, Android vx.x.x, device used...

#### Problem description
I'm working on a table syncronization system with ODK collected data and I'm having some troubles with retrieved fieldnames.
Exporting a collected form to google drive  I get a table where column names are formatted as:
formname-groupname-fieldname.
When using field names containing '-' (minus chars) the resulting colums names become impossible to decode or split by separator char.
It would be useful to change separator char (Perhaps a double minus '--' ?) or disable formname-groupname-fieldname leaving only fieldname.
What do you think?

Anyway thanks for your huge work!!!

#### Steps to reproduce the problem
common behaviour

#### Expected behavior
common behaviour

#### Other information 
Things you tried, stack traces, related issues, suggestions on how to fix it...

**Comment by lognaturel** [comment]
Thanks for filing this issue! Can you please add the steps to reproduce to make it easier to address? When you're saying you export the form, is that from Aggregate or are you talking about using sheets as your "server"?

**Comment by enricofer** [comment]
Hi Helene,
The XForm has been generated by pyxform.py from a json structure and uploaded to google-drive
You can find it here: 
https://drive.google.com/open?id=0B350e2U7rvyva3VBNGwxazBqbGs
The data collection table for which odk-collect is configurated is the following:
https://drive.google.com/open?id=1Q3lZWEnT0zU-k6L_u3bCe_IGWodG4qxev51Zcj4cGK8

As you can simply verify the nodeset in xml form has the following structure: "/form/group/field" while in the collected data table the fields become "form-group-field"

At this point it would very useful to choose exporting field name format and even it would be wonderful to browse google drive for available void or field-compatible sheets avoiding to let the user insert that complicated google sheet URL.

![15-odk-collect3](https://cloud.githubusercontent.com/assets/7544963/21385974/f2f9a714-c770-11e6-8b16-69ad1d37afe9.png)

I hope I was clear, thanks for you kind attention.

**Comment by lognaturel** [comment]
Thanks, @enricofer! I see what you're talking about now. 

Regarding the sheet that the data is submitted to, this should be specified in the form itself rather than in the settings. @yanokwa filed #310 to verify what precisely the Google Sheets URL setting does and document it. [Here](https://www.google.com/intl/en/earth/outreach/tutorials/odkcollect_drive.html) are complete instructions on using the google sheets feature from the Google Earth Outreach team if you want to review how to embed the data destination path. If you're interested in submitting a fix for either this or to look into #310, that would be much appreciated!

**Comment by enricofer** [comment]
I didn't know that awesome solution. You made my day! I will test as soon
as possible and report back.
For the fix submitting, I am not Android nor java expert but if you point
me to the right place in the code I will try to have a look.
Thanks.

2016-12-21 19:11 GMT+01:00 Hélène Martin <notifications@github.com>:

**Comment by lognaturel** [comment]
Awesome! Before we look at a fix, it'd be good to understand whether there was a reason to format the column as `formname-groupname-fieldname`. @yanokwa do you know?

**Comment by yanokwa** [comment]
fieldname alone is not a good idea because those aren't guaranteed to be unique. XLSForm prevents duplicates in fieldnames, but not all form designers do that.

There's a nasty bug in the Sheets API and it doesn't let you use special characters like underscore, slash, colon and probably others for the header. If we try to post those characters the API rejects it (or at least it did). The only reliable allowable characters seem to be dashes and alphanumeric characters.

To fix this, we should test to see what characters are allowed these days and choose one that's is not valid as a fieldname (e.g., no letters, numbers, colon, dashes, and periods). Maybe space or comma or pipe?

**Comment by enricofer** [comment]
I tried to change single cells with [HTTP API](https://developers.google.com/sheets/api/reference/rest/v4/spreadsheets.values/get) interface but I didn't find any problem with other characters separators from dashes ("-"). I would give more help but I can't find in which Sheet API  the "nasty bug" is. 
Anyway, from my point of view, a pipe "|" separator should be good, better than comma that in some locales, in IT.it for example, means decimal separator. Anyway if those are rejected by API a simple double dash ("--" ) should suffit to separate field name components.

**Comment by lognaturel** [comment]
I think the big challenge with changing the separators is that we'd have to be able to continue supporting the existing convention so that we don't break existing forms. We'd have to have a really solid approach to that before making any changes.

The class to look at is `GoogleSheetsAbstractUploader`. The path is built in [`getPath()`](https://github.com/opendatakit/collect/blob/35ad3e4e56b8cf6552876b9fa60db12f38268172/collect_app/src/main/java/org/odk/collect/android/tasks/GoogleSheetsAbstractUploader.java#L866).

**Comment by lognaturel** [comment]
Circling back to this because there has been work in this code recently by @grzesiek2010.

@enricofer How about a configuration option in the Google Sheets settings such as 
`[ x ]  Include form and group names in column names`

By default, this would be checked and the behavior would be the same as it is now.

If unchecked, only the field name would be included in the column headers. As @yanokwa mentioned, these are generally unique. If a form had duplicate field names, the form would not be able to be sent to Google Sheets.

**Comment by enricofer** [comment]
@grzesiek2010, @lognaturel, As I understand we are speaking about adding an option to google sheets settings in ODK collect; unchecking it, the form would be uploaded to GSheets preserving the provided field name, no matter if containing uppercase, lowercase or other allowed chars; 

In this case this could be definitively interesting because would free me from expunge groupnames from Gsheets column names output.

It would be great to have this behaviour less interactive: for example keeping fieldnames in groupless forms or setting the option in case the form contains a predefined metadata or a xform element

thanks for the involvement.

**Comment by lognaturel** [comment]
> As I understand we are speaking about adding an option to google sheets settings in ODK collect; unchecking it, the form would be uploaded to GSheets preserving the provided field name, no matter if containing uppercase, lowercase or other allowed chars

That's right.

Perhaps including the setting at the form level could be considered at some point but it doesn't really match any other kind of form-level setting so I'm not sure we'd be able to get that into the spec. 

Note that there are two ways to quickly share settings between devices: http://docs.opendatakit.org/collect-import-export/

**Comment by enricofer** [comment]
cool feature!
so I can invite someone sending a qrcode attachment.

**Comment by breakbusyloop** [comment]
This discussion seems oriented around which sentinel to use to handle the requirement for uniqueness. Any legal sentinel should do, since the column name is built to disambiguate, not to encode information about the fieldname. The fact that it's somewhat human readable (but clearly not parsable) just masks the actual problem.

The sentinel implies the naming within "formname-groupname-fieldname", but it is not explicit. I suggest that ODK generate a metadata table that explicitly defines the connection between a column name and the original form/group/field it came from. The ODK metadata table could have a schema like the following:
`sheet name, column name, form name, group name, field name`
... where sheet name and column name refers to a specific Google sheet and column, and the other three fields represent the original ODK identifiers. Post-processing work like ETL (or in this thread, table synchronization) would be able to reference the metadata table for the appropriate naming information, rather than trying to reverse engineer it from the uniquified column name.

**Comment by seadowg** [comment]
We're not currently focused on improving Google Drive flows so closing this.
