### ISSUE TITLE
Some toasts are visible in the language selected on the device, not on Collect

### ISSUE THREAD

**Issue by mmarciniak90** [getodk/collect#3029]
#### Software and hardware versions 
Verified on Collect v1.19
Android v8.1, v7.0
device used: Nexus 5X, Samsung S7

#### Problem description
Some toasts are visible in the language selected on the device, not on Collect on Android 8.1

#### Steps to reproduce the problem
1. **Spanish** language is set on device
2. **English** language is set on Collect
3. User fills form and clicks on Save icon -> `Formulario guardado correctamente` toast is visible
4. User goes to Form Metadata and adds incorrect email -> `Email inválido`  toast is visible
5. User imports settings -> `Ajustes importados exitosamente` toast is visible

|![Screenshot_20190419-142003](https://user-images.githubusercontent.com/3907554/56424552-07bbea80-62b1-11e9-849a-f12eb161e6b7.png)|![Screenshot_20190419-141700](https://user-images.githubusercontent.com/3907554/56424553-07bbea80-62b1-11e9-8d18-984d0ce49778.png)|![Screenshot_20190419-141819](https://user-images.githubusercontent.com/3907554/56424554-07bbea80-62b1-11e9-88df-c5447a63260b.png)|
|---|---|---|

#### Expected behavior
All toasts are visible in the language selected on Collect

**Comment by grzesiek2010** [comment]
Sometimes we get strings using the application context like `Collect.getInstance().getString(R.string.data_saved_ok);` (becuase an activiti context is not available)) and in those cases (depending on android version) the problem occurrs.

According to https://proandroiddev.com/change-language-programmatically-at-runtime-on-android-5e6bc15c758
`Another pitfall of using createConfigurationContext is that you can’t actually update the resources for Application after you change the language at runtime since attachBaseContext is never called again. Therefore, you have to restart the application to update the resources.`

resources are not updated after changing the language so getting a string using the application context as I described above cause that we receive wrong translations.

So the solution would be to restart the app after changing the language not only closing all activities. What do you think about this solution @lognaturel

**Comment by mmarciniak90** [comment]
I'm closing this issue because the mentioned problem no longer exists.
Verified on released version **1.30.1**, on Android **7.0, 8.1, 10.0** 

Toasts are consistent and are presented in the language selected in Collect's settings, even if a completely different language is set on the device.
