### ISSUE TITLE
Add About screen for open source licenses, tell your friends, leave a review

### ISSUE THREAD

**Issue by yanokwa** [getodk/collect#304]
We need a place in the app to list acknowledgments, open source licenses, and version information. This place needs to be out of the way, but also easy to find.

I propose adding About as the first item on the hamburger menu on the Main Menu. This About activity would open up a list view with the following.

* ~~ODK Collect 1.2.34 (Build 5678)~~
  * ~~opens offline changelog~~
* ~~Contributors~~
  *  ~~opens offline contributor list~~
* Open source licenses
  * opens offline licenses
* Tell your friends
  * launches share dialog pointing back to the app
* Leave a review
  * goes to https://play.google.com or wherever they can leave review

**Comment by marcos-lg** [comment]
Hi, I'd like to work on this issue but I have some doubts, where can I get the changelog and contributor list from? I can't find files with this information in the project :(

**Comment by grzesiek2010** [comment]
@asturcon
I believe you need this https://github.com/opendatakit/collect/graphs/contributors and https://github.com/opendatakit/collect/releases or maybe it should use git if it's possible?

**Comment by marcos-lg** [comment]
Ok thanks! I just was expecting that there would be any files in the project with this info already, since it's wanted to be displayed offline

**Comment by lognaturel** [comment]
@asturcon We're thrilled to have you work on this with us! I would suggest starting with the About menu item with Tell your friend and Leave a review since those are new and really good to have. You can issue a PR for that and we can get it in right away. Then we can in parallel have a discussion here about what the offline changelog and contributor list should look like.

When we do the changelog at https://github.com/opendatakit/collect/releases, we know people can get more information by clicking on the issue if they want. For something offline we may want each bullet to be a bit more self-explanatory. We probably don't want the contributor name and link to the issue (or do we? @yanokwa?).

For the contributor list we need to decide how we want to sort and present it. Perhaps we want to list individual contributors first and then institutional contributors by organization.

**Comment by yanokwa** [comment]
Agreed with @lognaturel that we haven't put a ton of thought into the change log and contributors, so I propose we leave those off for now.  

@asturcon Let's focus on a PR that adds a menu item for leaving a review, tell your friends, and moving the open source licenses from the General Settings.

**Comment by marcos-lg** [comment]
I just realized that there is an about section with open source licenses information at the bottom of the General Settings menu:

![image](https://cloud.githubusercontent.com/assets/25691745/22905345/3aa67034-f240-11e6-8da3-dc1ff6f3d603.png)

@yanokwa I understand this has to be moved to the new About screen, right?

**Comment by yanokwa** [comment]
@asturcon Yes, it has to be moved. Thanks for confirming before starting work!
