### ISSUE TITLE
tool to change the line width in the annotate and draw widget

### ISSUE THREAD

**Issue by mitchellsundt** [getodk/collect#3089]
Originally reported on Google Code with ID 971

```
What tool are you using?
Annotate widget & Draw widget

What is frustrating, troubling, annoying or lacking?
I'd like to see an option to change the line width or at least have the line width
default to a thinner line.

How would you like it to work?
next to set color have an option for change line width.


NOTE: the core team has limited ability to make software enhancements.
We rely heavily on community-contributed enhancements to the tools. If this
is something you very much need, consider hiring a developer to make the
changes with the stipulation that they work with the core team to specify
the details of the change and contribute the change back to the project
under an Apache 2 license.

```

Reported by `oconnorholmesbailey` on 2014-02-05 03:14:44

**Comment by SaumiaSinghal** [comment]
@opendatakit-bot claim

**Comment by SaumiaSinghal** [comment]
Hie @seadowg, @grzesiek2010! we have the following solutions:

Either, we can continue with FAB and simply, provide Confirmation Dialog that provides understandable options like Small, Medium, Large, or here I am thinking, we can also go with Range Slider [like](https://material.io/components/sliders/#anatomy).

Or we can continue using the same library that we use but, make changes in it, either ourselves or by filing an issue in the repo first, so that we can have the option to set stroke width in the Color Picker dialog itself, as suggested by @grzesiek2010. We can have a slider to set the stroke width by the side of the color picker, to set the stroke width, which shows the user the thickness and appearance of the stroke there itself, as shown.

![color-Picker](https://user-images.githubusercontent.com/35730054/72404652-15d56380-377c-11ea-8b9a-9718a8ee0796.jpg)

I am also seeing things [like](https://github.com/thisIsAnil/FingerPaintView), but that would mean changing the complte UI of the Draw View, and discarding the FAB.

At this moment, the second option seems the best to me.

**Comment by seadowg** [comment]
@SaumiaSinghal thanks for looking into the options. My only concern with the slider on the color picker dialog is that it will be fairly small on the screen. I think we'd just need to make sure it's tall enough to be easily tappable. Otherwise I like it! It's nice to contain the line settings in one place.

All that said, it does feel like a dialog with 3 options might be simpler to implement (as opposed to having to potentially also update a 3rd party library). I'm happy for you to make that call based on what you think you have the time for!

**Comment by SaumiaSinghal** [comment]
Yes @seadowg, having a confirmation dialog is a lot easier, in comparison to editing a third library. I am open to both options. I am waiting for @grzesiek2010  to present his views.

**Comment by seadowg** [comment]
@lognaturel closing this. Please reopen if you think it's still something that people need.
