### ISSUE TITLE
Add setting for captured location format

### ISSUE THREAD

**Issue by florianm** [getodk/collect#3093]
#### Software and hardware versions 
Collect v1.21,2 and earlier versions
Any android device

#### Problem description
Once captured, location is shown as DMS. It would be great to have the option to show captured coordinates as decimal degrees.

**Comment by ABHISHEK-AMRUTE** [comment]
@opendatakit-bot  claim

**Comment by ABHISHEK-AMRUTE** [comment]
@opendatakit-bot  claim --force

**Comment by grzesiek2010** [comment]
should it be a setting or an appearance?

**Comment by lognaturel** [comment]
I think this really needs more conceptual discussion. Is configuring the coordinate display the most useful thing we can do? Or could we try to show a map if connectivity is available? Perhaps truncate the DMS values so that there's more space and multiple formats can be displayed? What are data collectors going to do with this information? This kind of discussion should go on the forum.

**Comment by florianm** [comment]
Quick answer to @lognaturel 
We capture some data on tablets, and some on paper datasheets. When transcribing / reconciling / comparing, we need to see the captured coordinates from Geopoints in decimal degrees WGS84. A map won't help much as we'll be offline. For us, it's about the digits.

**Comment by lognaturel** [comment]
I see, that makes sense, @florianm, thanks! Next step will be to take these various suggestions about location display and put together a proposal for the forum.
