### ISSUE TITLE
Time is not updated when timezone was changed

### ISSUE THREAD

**Issue by mmarciniak90** [getodk/collect#3099]
#### Software and hardware versions 
Collect v1.22

#### Problem description
Time is not updated when timezone was changed

#### Steps to reproduce the problem
1. User fills the answer in `Time widget`
2. User changes device timezone
3. User returns to time questions
4. Question is not updated

#### Expected behavior
The default date displayed by picker should be the same as device time.

#### Other information 
Related to #1309

**Comment by grzesiek2010** [comment]
@lognaturel 

It's caused by this commit https://github.com/opendatakit/collect/commit/ee784a1c98e4c274ff808e69d86ff02a7d6beeae
this line: https://github.com/opendatakit/collect/commit/ee784a1c98e4c274ff808e69d86ff02a7d6beeae#diff-03ff45091550285dd88b56927010c457L2185

The problem is only if we set the timezone during filling a form. Times in saved forms are updated properly so I don't think it makes sense to bring that change back just to support such a rare case.

What do you think?

**Comment by grzesiek2010** [comment]
I know that it comes from your regression list @mmarciniak90 but I would transform this test and check saved forms since as I said changing timezone during filling a form sounds like a very rare case.

**Comment by lognaturel** [comment]
@grzesiek2010 Good find. I tend to agree that it sounds like a rare case though I suppose a user could try to set a time, notice that their clock is off, try to change the timezone and then be annoyed that it doesn't change the picker. Did I understand correctly that this could happen?

**Comment by lognaturel** [comment]
Does this also mean that the behavior when a user changes the device language is different? That is, did it use to change immediately if the Collect setting was set to "use device language" and now it will change on swipe?

**Comment by grzesiek2010** [comment]
Changing language works fine because then refreshCurrentView() is called here https://github.com/opendatakit/collect/blob/master/collect_app/src/main/java/org/odk/collect/android/activities/FormEntryActivity.java#L451
If you change language something more happens and apps are refreshed what doesn't happen in case of changing time, but it would be good to test some different devices/Android versions.
It doesn't make sense to add that additional refreshment again because the case is too rare and it would be useless in 99.99999999999999999999999999999% cases.

I can try to create a listener which would refresh the view if time is changed. I don't know if it's possible but it should be https://stackoverflow.com/questions/31398324/is-there-an-android-event-listener-for-change-in-the-timezone-of-the-device

**Comment by lognaturel** [comment]
> 99.99999999999999999999999999999% cases

That is a lot of significant figures. 😅

I think it's ok to leave as-is and see if users run into the case unless @mmarciniak90 or someone else thinks of a scenario where a user would experience it. I think you're right that it's unlikely.

**Comment by lognaturel** [comment]
We can re-open if a user reports.
