### ISSUE TITLE
Double checkbox is visible on `Reset application` dialog on Android 4.x

### ISSUE THREAD

**Issue by mmarciniak90** [getodk/collect#3150]
#### Software and hardware versions 
Collect v1.22.0,
Android v4.x

#### Problem description
Double checkbox is visible on `Reset application` dialog on Android 4.x

#### Steps to reproduce the problem
1. The user goes to `Admin Settings` > `Reset application...`
2. The user sees the dialog with two checkboxes

![Screenshot_2019-06-11-14-49-43](https://user-images.githubusercontent.com/3907554/59269893-5a31db80-8c50-11e9-953e-b8d4a59cde07.png)

#### Expected behavior
One checkbox is visible

**Comment by grzesiek2010** [comment]
We haven't changed the related code recently so I guess the reason is migrating to Android X. I tried but I can't see any easy way to fix it so maybe we could stop forcing checkboxes to be at the right side? It would look like:
![Screenshot_1560258668](https://user-images.githubusercontent.com/3276264/59278599-98d09180-8c62-11e9-9d27-46970292bc38.png)
![Screenshot_2019-06-11-16-09-44](https://user-images.githubusercontent.com/3276264/59278613-9e2ddc00-8c62-11e9-8951-ce179bc211da.png)

and it would fix the problem with doubled checkboxes.
