### ISSUE TITLE
Unexpected error while saving form. Failed to insert row.

### ISSUE THREAD

**Issue by mmarciniak90** [getodk/collect#3224]
#### Software and hardware versions 
Collect v1.23 beta

#### Problem description
Unexpected error while saving a form
Failed to insert row into content://org.odk.collect.android.provider.odk.instances/insrances

<img height="40%" width="40%" src="https://user-images.githubusercontent.com/3907554/61536858-ee544700-aa35-11e9-9c2e-c7a288d6fd2b.png">

![Screenshot from 2019-07-19 15-01-21](https://user-images.githubusercontent.com/3907554/61536934-23609980-aa36-11e9-8282-e415e3908e77.png)

#### Steps to reproduce the problem
1. User fills a form (visible on different forms)
2. User clicks on `Save` icon or `Save Form and Exit` button

#### Notes
* QA Team was not able to detect exact repro steps

**Comment by lognaturel** [comment]
I've run into this as well. I believe it happens when you go to a version after the changes for form and instance subtext translations and then downgrade again.

I did a quick debugging session and it looks like `onDowngrade` may not be doing what I would expect.

If it doesn't sound like that's the right reproduction, let me know, @mmarciniak90. I'll take a deeper look.

**Comment by grzesiek2010** [comment]
I installed v1.22.4 -> master -> v1.22.4 so it was upgrade->downgrade and everything was fine
but I was able to reproduce the issue installing master branch on a device I used to run espresso tests so I guess the problem is related just to tests
I saw that instances db had version 5 but still contained displaySubtext column which was not null and caused the issue (we try to pass null to not null column)

The cause is that sometimes instances_tmp table is not removed and it exists when we try to upgrade to v5 https://github.com/opendatakit/collect/blob/master/collect_app/src/main/java/org/odk/collect/android/database/helpers/InstancesDatabaseHelper.java#L181 and it causes a failure (database is not recreated, displaySubtext column exists).

I don't know why sometimes that table exists we always try to remove it after using. I think it's a random issue and not our fault.

What we can do?
We can try to drop that table if exists before https://github.com/opendatakit/collect/blob/master/collect_app/src/main/java/org/odk/collect/android/database/helpers/InstancesDatabaseHelper.java#L181 but it also might fail somehow if it fails sometimes in other cases so it's not super safe.

The second option would be to generate a random temporary table name instead of using instances_tmp (random or instances + current_date to have a unique temporary table every time). Then if it fails somehow it won't cause any problem because next time we would try to us a different table.

**Comment by lognaturel** [comment]
I tried removing `instances.db`, installing v1.23.0, installing v1.22 three times and all three times, I ended up in a corrupt state with `instances_tmp` not having `displaySubtext` and containing all user data and `instances` having `displaySubtext`.

Digging deeper, the problem is that v1.22's `onDowngrade` tries to select `displaySubtext` from the v5 database but it doesn't exist. 

Normally, `onDowngrade` is run in a transaction and so any exception causes all database changes to be rolled back and the database version not to be changed. But `onDowngrade` (and `onUpgrade`) swallows all exceptions so the rollback doesn't happen.

I will be sending in fixes soon.
