### ISSUE TITLE
App crashes when Geo question tries to open Mapbox on Android 4.x

### ISSUE THREAD

**Issue by mmarciniak90** [getodk/collect#3246]
## Software and hardware versions 
Collect v1.23 - master
Android v4.x

#### Problem description
App crashes when the user opens some Goe question when Mapbox is set

#### Steps to reproduce the problem
1. The user goes to `General Settings` > `Maps`
2. User sets Mapbox
3. User opens GeoPoint / GeoTrace or GeoShape question
4. User clicks on the button to open map
5. App crashes 

![Screenshot from 2019-07-25 12-53-22](https://user-images.githubusercontent.com/3907554/61869948-2b5c8580-aedd-11e9-868c-445e49776333.png)

#### Expected behavior
Collect does not crash

#### Other information 
Probably missed during testing #3164

**Comment by zestyping** [comment]
Oh dear.   I didn't realize we couldn't use vectors.  @lognaturel  I assume this means we can't rely on vector drawables, and the solution is to use a bitmap instead?

**Comment by lognaturel** [comment]
@zestyping I'm really surprised by this and not immediately seeing the root cause. `ContextCompat.getDrawable` looks like it should handle all API levels.

Do you have a way of trying this out? Maybe https://developer.android.com/reference/android/support/v7/content/res/AppCompatResources.html#getDrawable(android.content.Context,%20int) does the trick?

**Comment by zestyping** [comment]
It took some doing, but I was finally able to get it up in a 4.4 emulator and replicate this crash.  Pushing a fix for your review now.
