### ISSUE TITLE
instance data in json format

### ISSUE THREAD

**Issue by SmartLayer** [getodk/collect#325]
This is a feature request.

Currently a filled form is an XML file. In our project context submission has to be in json. As I briefly looked at XForms2 it includes submission in json and CSV format.

Do you look forward to include json as an optional submission format for the Android client, without having to transform it from XML instance data?

Thanks.

**Comment by anticlimactic** [comment]
To my knowledge, ODK Collect uses XForm 1 which does not support the json or CSV out of the box. If you need require json/CSV, you will have to do some processing on the XML output.

**Comment by lognaturel** [comment]
@vncnttrn is correct that ODK XForms is based on XForms 1. More info in [the spec](https://opendatakit.github.io/xforms-spec/).

@MartijnR, @yanokwa is this something either of you have thought about before?

**Comment by MartijnR** [comment]
This has come up occasionally for Enketo. Since XPath is the core logic language, the internal model would have to remain in XML. So, we've always recommended pre- and post processing to/from XML by the non-OpenRosa server, or custom app that requires that format. E.g. [this old repo](https://github.com/enketo/enketo-json) was (and maybe still is?) used by [OpenSRP](http://smartregister.org/)/[Dristhi](https://play.google.com/store/apps/details?id=org.ei.drishti&hl=en).

**Comment by yanokwa** [comment]
Agreed with @MartijnR that the transformation should be done on server side.

If @colourful-land responds to this issue with a description of an implementation that does the transform on the device in a thoughtful way (e.g., https://www.w3.org/MarkUp/Forms/wiki/Json#JSON-based_instances_and_submissions) or submits a pull request, I'd be glad to reconsider.
