### ISSUE TITLE
User is not able to change Collect's language on Android 7.x

### ISSUE THREAD

**Issue by mmarciniak90** [getodk/collect#3387]
#### Software and hardware versions 
Collect v1.24.0 beta.0
Android 7.0, Android 7.1

#### Problem description
User is not able to change Collect's language

#### Steps to reproduce the problem
1. User goes to `General Settings` -> `User Interface`
2. User changes language
3. User is moved to the main view but language stays unchecked 
4. The selected language is visible in settings

#### Expected behavior
User is able to change Collect's language to different than device language

**Comment by lognaturel** [comment]
Is this a regression, @mmarciniak90?

**Comment by mmarciniak90** [comment]
@lognaturel Unfortunately yes
This problem is not visible on v1.23.3

@opendatakit-bot label "regression"

**Comment by seadowg** [comment]
@opendatakit-bot claim

**Comment by seadowg** [comment]
Took a guess and found this is fine before bee6f771c47b40c455e1b633f89b78303b8bf640. Next step is to try and understand what exactly about the dependency update causes or language changing to fail.

From playing around with installing/reinstalling broken and working versions it looks like this is most likely an issue with how we try and make Android load alterantive resources (to the system language) rather than something to do with how we set the language in prefs. As far as I know setting a custom language (not the one the system is using) in an app "works" but is a bit of a hacky feature of Android.

**Comment by seadowg** [comment]
@mmarciniak90 did you try this on Android 6? I'm not seeing the bug there (just 7.0/7.1). Just double checking it's just a 7 thing and not everything below 8.

As a side note: we have tests that capture this (`FillBlankFormTest#sortByDialog_ShouldBeTranslatedAndDisplayProperIcons` for instance). We could look at running our tests againt a bunch of versions (probably at a time interval rather than on every commit) to catch these things earler.

**Comment by mmarciniak90** [comment]
@seadowg, yes, I'm totally sure that this problem is visible only on 7.0 and 7.1. I've just recheck this case on all available devices.

My devices with Android 7.x are:
* Samsung Galaxy S7 SM-G930F - Android 7.0.0
* Motorola Moto G Play - Android 7.1.1

**Comment by seadowg** [comment]
@mmarciniak90 thanks so much! Just wanted to make sure it wasn't an emulator issue.

**Comment by seadowg** [comment]
It looks like it's a problem with `appcompat`. I managed to walk through the versions and found we're fine with `1.1.0-rc1` so can change to that for now providing everything else is ok at that version.

Interestingly we can see that [1.1.0](https://developer.android.com/jetpack/androidx/releases/appcompat#1.1.0) of `appcompat` only has [3 commits](https://android.googlesource.com/platform/frameworks/support/+log/16509068d2009cdd24134b48887e3d8abd6b7109..f48ce15dc1716809f45fa761daa26ba7a838ca55/appcompat) so I'd imagine the culprit is [26079d8](https://android.googlesource.com/platform/frameworks/support/+/26079d87c79a64829f036236353fac1dae4e0613). I'm going to try and work out how I make a bug report/chat to the team about (other than grabbing them at Dev Summit next week).

**Comment by lognaturel** [comment]
> We could look at running our tests againt a bunch of versions

@opendatakit/testers how about doing this as the first step in regression testing so any issues caught by tests on specific API levels can be caught and filed immediately?

**Comment by seadowg** [comment]
@lognaturel I like that idea!

**Comment by mmarciniak90** [comment]
@lognaturel I added this to our basic criteria.

**Comment by mmarciniak90** [comment]
@getodk-bot label "Specific to Android version"
