### ISSUE TITLE
Unintentional Saving form dialog and app freeze after input, save and screen rotation 

### ISSUE THREAD

**Issue by kkrawczyk123** [getodk/collect#3519]
Software and hardware versions 
Collect v1.x25.x, Android v5, 7 probably all.x.x, device used...

#### Problem description
Saving dialog is displaying and freezing the screen after text input, saving and screen rotating, it is also causing crashes 

#### Steps to reproduce the problem
1. Open any form on any text question (I have used All wigdets)
2. Input text
3. Click on Save icon
4. Rotate the screen

#### Expected behavior
Saving Form dialog should not show up and it should not freeze an app on that view, User should be able to use app. 

#### Other information 
The issue is not visible on Collect 1.24 and 1.23, so it is a regression.

**Comment by seadowg** [comment]
I can look at this. @opendatakit-bot claim

**Comment by seadowg** [comment]
Ach this is because of some really dumb code that I wrote. Basically I have the `FormEntryActivity` that triggers a save based on a LiveData observation. Of course LiveData observations are rerun when the Activity resumes so that absolutely does not work. Similar problem to using LiveData to trigger a toast - don't use them for ephemeral things or "actions". 

In the past a way I've seen this modelled is to take the reactive value and use a consumer esque pattern where it only uses each "value" from the reactive value once. I'll have a look ath that with this as a way forward to solve this but really the nicer solve is to have the ViewModel take control of the "action" here (saving the form) so that LiveData is only communicating "state" back to the Activity. I might just end up throwing a standard listener on it for the moment.
