### ISSUE TITLE
Answer is lost for the rank widget which is based on another list if a user opens saved form

### ISSUE THREAD

**Issue by mmarciniak90** [getodk/collect#3554]
### Software and hardware versions 
Collect v1.24.1 (older versions were not verified)

#### Problem description
The answer is lost for the rank widget which is based on another list if a user opens saved form

#### Steps to reproduce the problem
1. User fills form [filter-rank.xml.txt](https://github.com/opendatakit/collect/files/3988155/filter-rank.xml.txt)
2. User finalizes form with all answers
3. User goes to `Edit Saved Form`
4. User opens saved form 
5. Answer for Rank Widget is not visible

#### Expected behavior
Added answers are visible. Rang Widget's answer is not lost.

#### Other information 
Noticed while testing #3487

**Comment by grzesiek2010** [comment]
The form contains a mistake and this is a problem in line 66 you have:
`<bind nodeset="/filter-list-based-on-list/fav_school" type="select1"/>`
where type is `select1` but it should be rank since it's for rank widget. Once you fix it everything is fine. I'm closing but please confirm when you are free.
