### ISSUE TITLE
Generate install-specific uuid and display it in form metadata settings

### ISSUE THREAD

**Issue by lognaturel** [getodk/collect#3595]
Starting in fall 2020, we will be required to target SDK 29 which means we will no longer be able to use the IMEI as `deviceId`. See https://forum.opendatakit.org/t/collect-will-need-to-stop-using-imei-as-deviceid-and-making-simserial-and-subscriberid-available/24157 and https://github.com/opendatakit/collect/issues/3360 for context.

We have agreed to replace it by generating and managing a uuid to identify the current install. The UUID should be a RFC 4122 Version 4 UUID generated by https://developer.android.com/reference/java/util/UUID.html#randomUUID() encoded to base64. That should bring it to 22 characters. It should be prefixed by `uuid:`.

That UUID should be lazily created the first time that it is requested and stored in general preferences. It should be made visible in the Form Metadata settings below `Device ID` with the label: "Install ID - will replace Device ID in August 2020"

It should be possible to copy this ID to the device clipboard.

Marking as `needs discussion` as long as the forum discussion is still running.

**Comment by seadowg** [comment]
After talking about it a bit more @lognaturel  have decided to go with a 16 character random alpha numeric string prefixed with `collect:`.

**Comment by seadowg** [comment]
It looks like for us to have copying on non selectable preferences (see the `enableCopying` parameter [here](https://developer.android.com/reference/androidx/preference/PreferenceFragmentCompat)) we need to switch to using the new `androidx.preferences` dependencies rather than the deperecated one's we are using now.

That feels like it might be nice to break out into another issue as adding that dependency in could be quite disruptive. I think the best thing to do is for me to create a new issue and submit a PR with the install ID being displayed. I'll go ahead with that but let me know if you disagree @lognaturel.
