### ISSUE TITLE
Replace KEYS_WE_SHOULD_NOT_RESET with "meta" shared preferences

### ISSUE THREAD

**Issue by lognaturel** [getodk/collect#3669]
In https://github.com/opendatakit/collect/pull/3640/files#diff-bf808238c0e5c486c12b05f9477c0fb2, @seadowg introduced a new preference file named `meta` to hold values relevant to Collect's behavior but not surfaced as a user preference. This makes for a nice separation and ensures that we won't do something like accidentally reset those preferences with the reset utility or allow users to change them with preference files. Currently the `KEYS_WE_SHOULD_NOT_RESET` collection is used for this purpose but that requires remembering to manually update it which is error-prone and makes the code more complex.

This will require migrating the prefs in `KEYS_WE_SHOULD_NOT_RESET`.

Marking as `needs discussion` until @seadowg has a chance to review and make sure I captured the intent. @seadowg, it probably makes sense for you to take this on?

**Comment by seadowg** [comment]
Just unassining this until I start it. It's in my "to do" so I will be getting to it at some point!

**Comment by lognaturel** [comment]
Ok, I just want to make sure that if you do plan to do it someone else doesn't pick it up because it looks easy. If you do want someone else to pick it up if they have time, please tag as `help wanted`.

**Comment by seadowg** [comment]
Right I see what you're saying. For me assigned means "in progress" and our project board is a nicer way of queuing up work that someone is going to pick up. You're totally right though that someone just browsing the issues won't see that this is "mine". I wonder if we could have our buddy opendatakitbot ping us when people want to "claim" rather than just assigning issues. That way we could prevent things from getting picked up that shouldn't and also avoid people picking up issues we actually needed to close.

**Comment by seadowg** [comment]
![](https://media.giphy.com/media/3ornk57KwDXf81rjWM/giphy.gif)

@getodk-bot still working on it my little friend
