### ISSUE TITLE
Unable to download form with external secondary CSV instance for the second time. 

### ISSUE THREAD

**Issue by kkrawczyk123** [getodk/collect#3682]
#### Software and hardware versions 
Collect current master, Android probably all, device used...

#### Problem description
When testing #3666 I have noticed one special case when a form with external CSV file becomes unuseable after trying to download it for the second time. 

#### Steps to reproduce the problem
1. Scan the code with Central access (same as attached in #3666 :
![75826614-b566a980-5d5c-11ea-8e00-1071faf90336](https://user-images.githubusercontent.com/33342488/75986504-79fbe480-5eee-11ea-8f72-b0c18142bacd.gif)
2. Download Form with external CSV files.xml
3. You should be able to fill it
4. Go to Get Blank Form and download the same form again - you will see error message: 
![Screenshot_20200305-142548](https://user-images.githubusercontent.com/33342488/75986694-d9f28b00-5eee-11ea-9a0a-162b499906db.png)
5. If you go to Fill Blank Form and try to open it you will see:
![Screenshot_20200305-143824](https://user-images.githubusercontent.com/33342488/75986818-05757580-5eef-11ea-9df0-620996dc01e6.png)

#### Expected behavior
The User should be able to download that form more than once, as he can do with other forms. 

#### Other information 
I am aware that it is not a very common scenario - but possible especially when using Select All option on Get Blank Form view. I wasn't able to reproduce it for other forms with external CSV files.

**Comment by lognaturel** [comment]
Good one. In that case all of the metadata discovery should be skipped. The crash is because the reference manager points to the download directory but the csv wasn’t downloaded again.

**Comment by grzesiek2010** [comment]
> Good one. In that case all of the metadata discovery should be skipped. The crash is because the reference manager points to the download directory but the csv wasn’t downloaded again.

@lognaturel you know that part of code better so it's better to ask. Does that mean we need to download media files every time and disable skipping them if nothing has changed?

**Comment by lognaturel** [comment]
@grzesiek2010 What I had in mind was pulling the code that detects whether a given form definition is new out from `downloadXForm` to `processOneForm` and to skip the call on `getMetadataFromFormDefinition` if the form is not new. That way, it doesn't matter where the media files are because a `FormDef` doesn't need to be built. I make that suggestion thinking that if a file with the same md5 hash already exists, its metadata must have been written to the database already. That way any new media files can be downloaded to the temp directory and existing ones can be skipped.

**Comment by grzesiek2010** [comment]
> What I had in mind was pulling the code that detects whether a given form definition is new out from downloadXForm to processOneForm

You don't need to pull out anything since `downloadXForm` returns `FileResult` object that contains a boolean variable isNew: https://github.com/opendatakit/collect/blob/master/collect_app/src/main/java/org/odk/collect/android/utilities/FormDownloader.java#L522 so you can just use it.

~~The problem is that what you want to do is check whether you are downloading a new xml file but there is a possible case when the form doesn't contain any changes just media files are updated. In such a case it won't work.~~

~~Am I missing something?~~

Ok I think I figured it out. Is that what you expected? https://github.com/opendatakit/collect/commit/3ac586b942a549c4992e0863091af2948571d92f

**Comment by lognaturel** [comment]
> Is that what you expected? 

Yes, exactly. That makes sense, right?

**Comment by grzesiek2010** [comment]
> Yes, exactly. That makes sense, right?

Yes, thanks.
