### ISSUE TITLE
Removed Geopoint does not disappear from the MapActivity view immediately

### ISSUE THREAD

**Issue by mmarciniak90** [getodk/collect#3696]
#### Software and hardware versions 
Collect v1.26.0 beta

#### Problem description
Removed Geopoint does not disappear from the MapActivity view immediately

#### Steps to reproduce the problem
1. User opens new MapActivity
2. User sees marker for each form instance
3. User clicks on some marker
4. User removes response for Geopoint widget
5. User leaves the form and saves it
6. User is moved to MapActivity
7. **Removed point is visible**
8. User leaves map and opens it again -> point is not visible

#### Expected behavior
* When response for GeoPoint is removed, point disappears from the map
* Bottom bar shows the correct number of points and filled submissions

![map](https://user-images.githubusercontent.com/3907554/76196418-7ddb7f80-61ea-11ea-8825-2529ec4c10a5.gif)

@opendatakit-bot label "regression"

**Comment by mmarciniak90** [comment]
@opendatakit-bot label "regression"

**Comment by lognaturel** [comment]
@grzesiek2010 I'm going to take this one because I have all the context and it'll be really fast for me. I'm thinking we should generally give the author of the code with a bug a first pass for that reason? There's definitely value in different people working with the same code but perhaps we should focus on getting that value in review.
