### ISSUE TITLE
Gaps in translation

### ISSUE THREAD

**Issue by mmarciniak90** [getodk/collect#3718]
#### Software and hardware versions 
Collect v1.24.1 
Older version wasn't verified

#### Problem description
Noticed dialogs/toasts that have not been translated

#### Steps to reproduce the problem

| | ||
|---|---|---|
|![Screenshot_20200317-100829](https://user-images.githubusercontent.com/3907554/76844559-c247ca80-683d-11ea-83cf-26f166f810e5.png)|![Screenshot_20200317-101712](https://user-images.githubusercontent.com/3907554/76844574-c83dab80-683d-11ea-808b-a41c46392e99.png)|![Screenshot_20200317-101351](https://user-images.githubusercontent.com/3907554/76844589-cbd13280-683d-11ea-96ee-d105195f5828.png)|
|![Screenshot_20200317-102225](https://user-images.githubusercontent.com/3907554/76847172-eefde100-6841-11ea-87f9-57da5d11b66a.png)|![Screenshot_20200317-101909](https://user-images.githubusercontent.com/3907554/76847176-f02f0e00-6841-11ea-90d0-c3dc314ce00e.png)|![Screenshot_20200317-101419](https://user-images.githubusercontent.com/3907554/76847178-f0c7a480-6841-11ea-88f4-cfd6394ed0cb.png)|

**Comment by grzesiek2010** [comment]
It's because those messages are not even translatable:
https://github.com/opendatakit/collect/blob/master/collect_app/src/main/java/org/odk/collect/android/upload/InstanceGoogleSheetsUploader.java#L95

https://github.com/opendatakit/collect/blob/master/collect_app/src/main/java/org/odk/collect/android/upload/InstanceServerUploader.java#L175

https://github.com/opendatakit/collect/blob/master/collect_app/src/main/java/org/odk/collect/android/preferences/AdminPreferencesFragment.java#L151

@lognaturel what do you think about them? I know you sometimes prefer to keep some error messages just in English.

**Comment by mmarciniak90** [comment]
During the weekly meeting, we decided that we do not want to spend time to translate these messages.
