### ISSUE TITLE
Appearance="autocomplete"

### ISSUE THREAD

**Issue by MartijnR** [getodk/collect#372]
I'm trying to figure out how we should correct the XLSForm.org documentation (and then implement it) => https://github.com/XLSForm/xlsform.github.io/issues/79

It looks like there used to be support for appearance="autocomplete" in ODK Collect but that this was removed in 2011. 

Was the desired functionality to be different from the currently-supported appearance="search" or the same?

**Comment by yanokwa** [comment]
There is a select one with search? Even I didn't know that existed. Sad! We need better docs.

Autocomplete was removed because it had subtle data loss.

> The problem is that the autocomplete is currently implemented as a select1, which works for filling out a form. However, when you load a saved form JavaRosa checks to see that the saved value matches a value in the select one, and when it doesn't match it silently throws it away, which seems like bad behavior. We could implement it as a "string" instead of a select1, but then we have to figure out where to store the list and how to reference where the list is stored. https://code.google.com/archive/p/opendatakit/issues/289


It looks like this search attribute does what we called "closed autocomplete". That is, you choose from a closed list of options, so that's great. 

There is likely still a need for open auto-complete where you accept anything that is typed as an answer, but that should be another feature request.

What does Enketo support as far as autocomplete?

**Comment by MartijnR** [comment]
Ha, well it seems to work!

I am about to implement closed autocomplete. Appearance=autocomplete is the one that was documented on xlsform.org (and therefore was implemented by another client). I have to match this, so I think we'll have to consider "search" to be an alias of "autocomplete" and document them as such on xlsform.org.

I imagine the XForms syntax for an open select will be different so we can probably re-use the autocomplete appearance if we ever get to that. It probably will entail more than just an appearance.

P.S. There is still the mystery of autocomplete_chars. I'll propose to remove that one if nobody objects: XLSForm/xlsform.github.io#79
