### ISSUE TITLE
Limitations in capturing Geo-coordinate on ODK collect 

### ISSUE THREAD

**Issue by imran3may** [getodk/collect#375]
#### Software and hardware versions 
Collect v1.4.14, Android v5.1 device used...

#### Problem description
Feature is not available to hide button to capture Geo-Coordinates, which means there is no options are available to capture Geo-coordinate without the interaction of an user.    

#### Expected behavior
For the need of a project, a funchtionality of auto capturing of Geo-coordinate is required. Which means, the location of the user should automatically captured withous having a button to capture Geo-coordinate.

#### Other information
Forms developer may have an option to hide the button while designing the xls form. For example, change some behaviours, constraints are used or a condition used under appearance. I would suggest, this feature may help resolving issues of may ODK users.

**Comment by yanokwa** [comment]
@imran3may Why do you need to capture GPS coordinates without user interaction? Is it a training issue of GPS being hard to capture? Is it because you don't trust that your enumerators to know GPS is being captured? The reasons why inform the design, so we should discuss them.

**Comment by chrislrobert** [comment]
FYI, in SurveyCTO we have a "background" appearance for geopoint fields. We also added a Collect option to pre-warm GPS for up to x seconds and/or y meters accuracy at the beginning of any form that contains a geopoint field.

Reason: smart enumerators, rather than filling out all forms at home, visit every actual household, capture the GPS position of each from the street, save, move on, capture, capture, then go home or sit in a tea shop and complete all of the tiresome surveys. This is how they adapt to GPS positions being captured and monitored. So okay, then the next adaptation is to scatter these invisible/background GPS positions between modules, throughout the form. Using distance-between(), can then calculate distance between the different points and flag cases where they seem to have moved a lot. Etc.

Also supports accuracy threshold.

<img width="1050" alt="screen shot 2017-02-03 at 6 43 39 am" src="https://cloud.githubusercontent.com/assets/8631326/22590239/3042250a-e9dc-11e6-81cd-a2e801b8f1cf.png">

**Comment by imran3may** [comment]
@yanokwa I am currently working on a project for a country Government health agency and in one of their forms, they are looking for this hidden GPS-coordinates capturing feature. I assume they simply want to hide this feature in order to make this form more acceptable to their staffs. Though on the declaration it is clearly mentioned that their location will be recorded. Thanks

**Comment by lognaturel** [comment]
Related to #24

**Comment by yanokwa** [comment]
@chrislrobert I have a few questions...
1. Given the problem described, why not capture a trace of where the phone has been instead?
1. Where is this background GPS saved (e.g. sidecar file, data model)?
1. What do you do when the user swipes past the background location, but you haven't gotten lock?
1. What happens when the user is indoors and there is no lock?

**Comment by yanokwa** [comment]
@imran3may Android does not let you hide the menu icon that shows GPS is being fetched. Is that acceptable?

**Comment by imran3may** [comment]
@yawanoka Thanks for the information.


A N M AL IMRAN (Imran)
Brossard, QC
Canada
Cell: +1 (438) 501 3576

**Comment by nap2000** [comment]
I think this should be added as an option to the timer log issue #257 .  If track GPS is set then for each question the GPS will be recorded and logged. 

Because the coordinates captured at each question have to be the best available at that point in time then I suggest we record what we have including accuracy.

**Comment by jnordling** [comment]
So whats the verdict on this? We doing it or no. @yanokwa

**Comment by lognaturel** [comment]
Yes! I believe @nap2000 is getting close to a timing-only implementation for #257. @nribeka is working on #508. Once those pieces are in place we can discuss the final design but it will likely be something like what @nap2000 describes.

**Comment by nap2000** [comment]
Yep a draft approach for the timing log is nearly done.

**Comment by steverichards** [comment]
I may be a bit late to the party on this one. Muy use case is recording observations from a helicopter where time to collect is an issue. I'm looking for a one tap solution. 
Form is open
Select observation from radio button 
GPS location is collected automatically
Record is saved
Ready for next observation

**Comment by imran3may** [comment]
Fiverr
    
    
            
      {
          "@context": "http://schema.org",
          "@type": "EmailMessage",
          "action": {
            "@type": "ViewAction",
            "url": "https://www.fiverr.com/s2/d6f4bc2e1d",
            "name": "Browse Services on Fiverr"
          },
          "description": "Browse Services on Fiverr"
      }
    

        
            
                
                    
                        
                            
                                
                                    
                                        
                                    
                                
                                
                                    
                                    
                                
                                
                                    

                                        
    

    
        A.n.m is tired of keeping Fiverr a secret.
    

    
        Fiverr is the world’s largest marketplace for services,where you can get everything you need at an unbeatable value.
    

    
        Sounds too good to be true? See for yourself!
    



                                        
                                            
                                                
                                                    
                                                        
                                                            Browse Services On Fiverr
                                                        
                                                    
                                                
                                                
                                                    
                                                        

		
			
			
			The Fiverr Team
		
                                                    
                                                
                                            
                                        
                                    
                                
                            
                        
                    
                
                
                    
                        
                            
                                

                                    © Fiverr International Limited 2010-2016, Fiverr Inc. | 401 Broadway, Suite 1600 New York NY, 10013 USA.
                                    Your personal information will not be stored or used for any marketing purposes.
                                
                            
                         
                    
                
            
        
            

    

If you would like to unsubscribe and stop receiving these emails click here.
