### ISSUE TITLE
Margin on `Form Metadata` is larger than on other views

### ISSUE THREAD

**Issue by mmarciniak90** [getodk/collect#3757]
#### Software and hardware versions 
Collect v1.26

#### Problem description
Margin on `Form Metadata` is larger than in other views

#### Steps to reproduce the problem
1. User opens General Settings -> User and device identity -> Form metadata 

| |Form metadata| to compare |
|---|---|---|
|v1.26.1 |![Screenshot_20200402-161739](https://user-images.githubusercontent.com/3907554/78271547-9189b580-750c-11ea-91a9-8cc4df6d9dda.png)|![Screenshot_20200402-161753](https://user-images.githubusercontent.com/3907554/78271573-9b131d80-750c-11ea-990e-7cb07e92911d.png)|
|master with #3680| ![Screenshot_20200402-165505](https://user-images.githubusercontent.com/3907554/78271612-a6fedf80-750c-11ea-9d3b-6a38dc61f10e.png)|![Screenshot_20200402-165458](https://user-images.githubusercontent.com/3907554/78271634-ab2afd00-750c-11ea-97b0-f0bc90357e07.png)|

#### Expected behavior
Margin is consistent on all settings views

**Comment by grzesiek2010** [comment]
It's not just the top margin but also start(left) margin is different...
Those margins are not set in our app directly. The problem stems from the fact that in all preference screens we use `android.preference.PreferenceFragment` but just in tat one `FormMetadataFragment` it is `androidx.preference.PreferenceFragmentCompat` so it's something that just changed in Android.
Generally we should go for `androidx` in all places and it would fix the issue because all margins would be consistent, however it's not that easy there are some bigger changes, removed methods we are using so it's not just possible to replace `android.preference` with `androidx.preference` everywhere and that's it.
Since it's something that has changed in new `androidx` I would rather keep it as is for now and avoid forcing behavior from the old preferences or vice versa, we should rather migrate to `androidx` and that would fix the problem but as I said it's not trivial.

**Comment by grzesiek2010** [comment]
This is now fixed thanks to switching to androidx.preference.
