### ISSUE TITLE
User is not able to change Collect's language on Android 7.x

### ISSUE THREAD

**Issue by mmarciniak90** [getodk/collect#3774]
#### Software and hardware versions 
Collect current master
Android 7.0

#### Problem description
User is not able to change Collect's language

#### Steps to reproduce the problem
1. User goes to `General Settings` -> `User Interface`
2. User changes language
3. User is moved to the main view but language stays unchanged
4. The selected language is visible in settings

#### Expected behavior
User is able to change Collect's language to different than device language

#### Other information 
Issue is NOT visible on released v1.26.1

**Comment by grzesiek2010** [comment]
The problem is caused by dagger which we updated to v2.27 (the problem is visible on v.26 as well) recently: https://github.com/opendatakit/collect/pull/3728/files#diff-c197962302397baf3a4cc36463dce5eaR50

I tested how it affects different android versions and here are my findings:
| API  | Result |
| ------------- | ------------- |
| 22 | language changed but if I close the app and open it again (doing that two times might be required) it gets back to the previous language |
| 23 | language changed but if I close the app and open it again (doing that two times might be required) it gets back to the previous language |
| 24 | language not changed |
| 25 | language not changed |
| 26 | seems fine |
| 27 | seems fine |
| 28 | seems fine  |
| 29 | seems fine  |

**Comment by mmarciniak90** [comment]
@getodk-bot label "Specific to Android version"
