### ISSUE TITLE
Start programmatic testing of core functionality

### ISSUE THREAD

**Issue by lognaturel** [getodk/collect#392]
As we start making bigger changes to the codebase, having some programmatic testing would help us avoid regressions. There's nothing worse than functionality that used to work suddenly breaking in a new release! (See #360 for a recent example 😧)

There was a [conversation on the dev mailing list](https://groups.google.com/forum/#!searchin/opendatakit-developers/testing/opendatakit-developers/JNwzuuIlhrg/4-f_6BTVBwAJ) about the topic.

@srsudar recommended [Robolectric](http://robolectric.org/) and has some [example tests](https://github.com/srsudar/MamasDelRioAndroid/tree/master/app/src/test/java/org/mamasdelrio/android) in a Collect fork he worked on. Robolectric was added to the code base by #204

@mitchellsundt pointed out that different tools are appropriate for different layers of tests. He says [instrumented unit tests](https://developer.android.com/training/testing/unit-testing/instrumented-unit-tests.html) have been very helpful for identifying regressions.

Clayton from Dimagi [explained their Android testing strategy](https://groups.google.com/d/msg/opendatakit-developers/JNwzuuIlhrg/-uRm1wYzAQAJ) using jUnit, Robolectric and [Calabash](http://calaba.sh/).

Let's start with two specific things to test: getting a list of blank forms from an Aggregate instance that does have blank forms and downloading the first form in the list. What is the best approach for getting that basic functionality tested programmatically? How much should be stubbed, what's the best tool, etc.

**Comment by grzesiek2010** [comment]
I've been reading up on this and I added a small test for mentioned scenario (getting a list of blank forms from an Aggregate) using Espresso as it's really good tool. I implemented changes in order to run this test on CIrcleCi but it doesn't work and returned error is really strange: https://circleci.com/gh/grzesiek2010/collect/192
Here is the branch: https://github.com/grzesiek2010/collect/tree/COLLECT-392_4
Does anyone know what is wrong?

> at org.odk.collect.android.activities.MainMenuActivity.onResume(MainMenuActivity.java:289)

**Comment by lognaturel** [comment]
I want to try to be a little bit more specific about what I think we want to achieve and what kinds of questions we need to answer. It probably makes sense to agree on some high-level principles before we pick tools.

First, I would say the overall goal is to get a better feedback loop in place for learning about issues with Collect. Currently, we identify problems when users report them or when we see crashes in the Google Play Console. Given that goal, desirable characteristics of tests are:
- run fast: tests that run fast get run often
- offer targeted feedback: tests should help pinpoint the source of a problem quickly
- future-proof: tests that need to be updated often to match the evolution of the software are brittle

Given the goal and desired characteristics, I think we should start with smaller unit and integration tests rather than with UI tests. The Google testing blog has a great post titled [Just Say No to More End-to-End Tests](https://testing.googleblog.com/2015/04/just-say-no-to-more-end-to-end-tests.html) that describes some concrete reasons why that might be a good way to go.

There are two projects that I see as somewhat different: **(1) test existing code** and **(2) develop a test-driven culture**. I think they present somewhat different questions:
1. Testing legacy code.
- What tests will provide the most useful feedback for the least amount of up-front effort?
- Should testing be its own project or do we approach it as we work with and modify existing code?
- How much refactoring can and should we do as we test? The existing codebase is not very testing-friendly because it has a lot of monolithic components with lots of dependencies.

2. Developing a test-driven culture.
- In an ideal world, what kinds of tests should be part of a pull request?
- What guidelines for testing can we provide for contributors?

I think that in the short term we mostly want to focus on (1) but we should keep (2) in mind as a longer-term goal and potentially start including tests for PRs now to help shape (1).

Any high-level feedback would be greatly appreciated!

**Comment by mitchellsundt** [comment]
Test-driven culture comes first. One reason ODK Collect doesn't have tests is because there was hostility in the culture at UW for introducing tests. 

The groundwork begins with first setting up a framework for people to add tests of any type 

- unit
- integration
- partial-stack
- full-stack / UI

The Google testing blog has it wrong. The natural precedence order is:

(1) establish full-stack / UI tests. These give the biggest code coverage and user scenario coverage for the time spent on them.  These need to be implemented in a manner where you don't depend upon clicking at a pixel offset of ( 125, 200 ) but instead search for the semantic element that you need. That is a key failing of many "record-then-playback" quick UI test generation frameworks. This allows the UI look-and-feel to change independent of the semantic verification of that UI. You still need human eyes to verify the look-and-feel.

(2) as things fail, developers take the initiative to develop tests that segment the full-stack to isolate the failures, then CHECK THOSE INTEGRATION TESTS IN. The key failing in SW organizations is to not have the framework available to easily add unit, integration or full-stack tests.  This includes mechanisms to pre-load data for these tests.  Developers should "own" the tests. An SDE / SDET split is counterproductive, especially in Open Source projects.

(3) as developers fix individual issues or extend functionality, encourage a culture where they also check in unit tests for that functionality.

-------------
The Google blog is biased and misleading because it sounds like all the developers are taking a day off when the overall build failed at account verification. If the developers focused on (2) above, then on subsequent days the overall-blocking stall would be eliminated.

This fluidity allows you to develop tests that give a narrow but wide-ranging coverage of your application (full-stack / UI tests). And as failures are identified, developers create deeper less-wide-ranging tests AND CHECK THOSE IN. And then as new features are added or bugs fixed, create unit tests to verify those features.

Focusing on coverage at the unit test level is  a throw-back to the waterfall development cycle and is contrary to a rapid prototyping culture.  Developers need to own the code and own the tests, and be able to fluidly add the tests they needed to isolate an issue back into the dev cycle. 

Most code that is written is dead simple. And most code is bug free. Unit testing those lines is a waste of time and effort. Buggy code is where the effort should be focused, creating a nested web of tests to verify the code functions in isolation and in the context of the overall app. By starting with the app context, then elaborating the tests into an isolated state that mimics the app context, you can develop meaningful unit tests in the areas of code that are tricky and fragile.

**Comment by srsudar** [comment]
Mitch makes a good case for the value of integration tests.

In general, though, I tend to agree with the Google blog post. All the benefits they outline of unit tests seem real to me. I'll try not to rehash them specifically as much as talk about why I think a unit test-based approach would make sense for ODK projects.

I think that unit tests would be great for the existing ODK projects because it would allow tests to be introduced gradually to the codebase. I like @lognaturel 's idea of expecting tests to be checked in with changes. Including unit tests with checkins would be a relatively low lift way of starting to verify code. The developers doing the checking in are likely doing some manual verification that things are behaving like they expect (and if they're not, they shouldn't be checking it in). Getting them to invest this time (plus undeniably a little extra) in runnable tests is reasonable in my opinion.

I also think that the burden of testing is greater at the integration test level. As you introduce code, it might be a non-trivial task to add an integration test that generates all the possible inputs you need to consider for a unit. Writing tests for the API of the module you are working on is typically less effort. If something is very hard to unit test, there's a good chance it could be restructured in a way that both accommodates testing and pays off down the road in a cleaner, more modular codebase.

Going along with testing burden, if I am a newcomer to the project and want to fix something relatively contained, like a string parsing error in a single function, it could be a very small PR to introduce that change and a small unit test to ensure that bug doesn't crop up again. If anyone issuing a PR has to understand the full stack enough to modify an integration test, I think that increases the barrier to entry and steepens the learning curve to the point that it could turn away infrequent but helpful contributors.

Tests also help project collaborators, including code reviewers and consumers of the code, as it gives some examples of usage that can make the new code easier to understand and easier to catch errors.

Unit test failures are more informative, allowing quicker fixes. For example, with an ODK Survey form I ran into an issue where the geopoint prompt wasn't working. The dialog was popping up, everything looked like it was working, except that it didn't populate the values in the UI after returning. It turned out this error was due to the way I began the form, skipping a screen and breaking a Survey invariant. Faced with a failing integration test, a developer might naturally start debugging this at the geopoint prompt. This would be the wrong place to look. A unit test isn't sure to catch this, but after encountering the bug a unit test could be introduced to catch this precise behavior, saving time in the future.

Mitch makes another good point about how testing can slow down prototyping. If something is being prototyped, I certainly wouldn't argue that it should be well-tested. However, if it is expected to work, I think it needs to be tested. I think things that are checked into the main branch should be expected to work and be robust, not be a prototype.

To sum up, I would argue for unit tests to be a valuable component of an ODK testing solution. I think they:
1. Allow gradual introduction of code verification
1. Require less of developers, making it easier to contribute code
1. Lead to cleaner code
1. Are easier on newcomers
1. Help document code and make it easier to understand
1. Are more informative, allowing quicker fixes

As for @lognaturel 's original points of: 1) testing legacy code, and 2) developing a test-driven culture:
1. Testing legacy code
  * This is the harder part, I think. New commits will invariably touch older, untested portions of the code. This will likely expose things that are hard to test, but it will also allow the code to become more modular, eventually making it easier to start unit testing things.
1. Creating a testing culture
  * A great first step to this is expecting that new commits include tests. Mitch makes another great point that it is important to ensure that there is a system in place to support tests. Deciding on a framework will help toward this, I think, and will be an initial lift. Once it is up and running, however, I think expecting tests with commits is a good way to go.

**Comment by lognaturel** [comment]
@mitchellsundt @srsudar Thanks for your insights! @mitchellsundt do you have some reading material we could check out that advocates for a UI-testing-first approach? It's a very intuitively appealing idea since that kind of test would be most like what a user's experience is but I have not come across a project that emphasizes UI testing first. I understand what you're saying about using semantic elements (that's what @grzesiek2010 did with [his Espresso example](https://github.com/grzesiek2010/collect/tree/COLLECT-392_4)) but one of the eventual goals is to almost entirely replace the UI layer without maintaining its semantics.

I think one of the things that makes this conversation challenging is that terms are not defined very precisely or consistently. "Unit testing" can mean something pedantic and far removed from reality and I certainly agree we should stay away from that. "Coverage" should not be a goal in and of itself. But unit testing at the class level with carefully considered mocks can add a lot of confidence in the well-functioning of parts of the code while also promoting much better design. I may have been quoting @srsudar there.

@mitchellsundt said

> Buggy code is where the effort should be focused, creating a nested web of tests to verify the code functions in isolation and in the context of the overall app. By starting with the app context, then elaborating the tests into an isolated state that mimics the app context, you can develop meaningful unit tests in the areas of code that are tricky and fragile.

I very much agree with that and I believe we can do it without needing a UI testing layer (at first). We already know which parts of the code are brittle and mission critical (for example, we keep finding different creative ways to break the Google Sheets integration).

Another thing that occurs to me -- I don't think there's much debate around the tooling for unit testing in Android, right? Seems that jUnit 4 + Mockito (for ODK class mocks) + Robolectric (for Android class mocks) is the way to go. That's already all included and we have one glorious test from @lindsay-stevens. As we continue the discussion on which testing layers to focus most on and pick specific tools, can we also work on getting canonical examples of pure local unit tests, unit tests with Mockito stubs and unit tests with Robolectric stubs that we can discuss? I don't know if this is the right breakdown but it sounds like we agree that it would be useful to have solid examples of tests on different kinds of units. I think having something concrete to look at is always helpful.

**Comment by PatrickDale** [comment]
When developing a testing strategy, I think it is very important to remember the [testing pyramid](https://martinfowler.com/bliki/TestPyramid.html). An example of this pyramid is in the [Translation Cards](https://github.com/translation-cards/translation-cards) project. We have used Appium for our "UI" tests, Robolectric for our "Service" level tests, and JUnit + Mockito for our unit tests. I am happy to go into more details about what we have liked and disliked in each framework, as well as why we chose these specific testing frameworks.

>  As we continue the discussion on which testing layers to focus most on and pick specific tools, can we also work on getting canonical examples of pure local unit tests, unit tests with Mockito stubs and unit tests with Robolectric stubs that we can discuss? I don't know if this is the right breakdown but it sounds like we agree that it would be useful to have solid examples of tests on different kinds of units. I think having something concrete to look at is always helpful.

I will be pulling examples for the following from our [Add Deck](https://github.com/translation-cards/translation-cards/tree/develop/app/src/test/java/org/mercycorps/translationcards/addDeck) flow for Translation Cards. More specifically the Enter Deck Title step.

[Unit Testing w/ JUnit & Mockito](https://github.com/translation-cards/translation-cards/blob/develop/app/src/test/java/org/mercycorps/translationcards/addDeck/presenter/EnterDeckTitlePresenterTest.java):
The first thing you may notice, is that this test is under a Presenter class. We found that truly implementing unit tests in our codebase required us to break away from the MVC design pattern to MVP. This is a conversation I would love to go in further depth about, but at a high level the Android framework gets tightly coupled with your code when production code is written in an Activity class. This results in you needing to boot up the Android framework whenever testing code in an Activity. Leveraging different [design patterns](https://medium.com/ios-os-x-development/ios-architecture-patterns-ecba4c38de52#.9ad4x6mo5) helps us break away from a framework when writing mobile code. This naturally takes us to Robolectric...

[Integration Testing w/ Robolectric](https://github.com/translation-cards/translation-cards/blob/develop/app/src/test/java/org/mercycorps/translationcards/addDeck/activity/EnterDeckTitleActivityTest.java): 
I intentionally am calling Robolectric an integration testing framework rather than a unit testing framework. This is because we are testing how our code works when placed into the Android framework rather than how it works in isolation of the Android framework. We have found Robolectric tests to be slightly more expensive (time consume to write and run) than unit tests. But they do have their place in an app. Anything that we have found to be business critical that cannot be covered by unit tests we have placed in our Robolectric suite. This specific example highlights us only wanting a button to be clickable if text is entered. 

After these two examples, it is important to note that our happy and sad path tests are covered in unit tests, but only happy path tests are covered in our integration tests. This is because unit tests are significantly quicker to run and easier to write as compared to integration tests.

Finally, [UI testing w/ Appium](https://github.com/translation-cards/translation-cards/blob/develop/Appium/src/test/java/com/thoughtworks/translationCards/FunctionalTests.java):
UI tests are VERY slow to run, and can also be more complicated to maintain. Because of this, we should only cover the most critical user journeys in them (aka the one path that would make your app useless when broken). The benefit of UI tests over Robolectric tests is that they can be ran on real devices (we all hate those samsung specific bugs...). They also test how all your activities flow and interact with one another. When first adding tests to a codebase, I always recommend adding UI tests, this is because you will get the largest amount of code coverage with the fewest number of tests. Refactoring can be very scary when you have no tests to validate that no new bugs have been introduced!

I can ramble on about testing strategy, but I think a face to face conversation could be more beneficial :). Excited to see this project start tackling this challenge, and would love to help wherever possible!

**Comment by mitchellsundt** [comment]
To be clear: 
- I'm not saying "UI-testing-first -- that you must have UI tests for a section of code before you write integration tests or unit tests"
- I'm not saying "don't unit test."
- I'm not saying "do not require developers to provide a test for whatever change they've checked in." This is necessary for bootstrapping into a tested app. At a minimum, it serves to begin to build out and validate your testing framework.

I AM saying:

- the choice of the type of test that is provided should be up to the developer. 
- the testing framework should accept all varieties of tests (unit, integration, UI) with equal ease.
- the code coverage measure for a code change and its corresponding test should not be rigidly fixed (e.g., "you must submit a test that covers 80% of the code change path" -- I
am against that).

-----------------
End-to-end tests, which are often UI tests, are the quickest way to achieve code coverage; you just need to avoid non-semantic UI test frameworks. 

For example, write a UI test that exercises a form with all current widgets. Huge coverage. Yes, you'd need a test framework that either exercises a real device -- not an emulator -- or you'd need a test framework that allows you to mock geolocation services, external image capture apps, media services, etc. 

That's where a fully capable test framework comes in. If that isn't easily available, coverage will always skew away from these hard test areas.

Yes, I know, even better would be a suite of single-widget form tests; but that would require a lot of repetitive work copying-and-pasting and with slight modifations to get an equally big bang. Yes, as bugs are uncovered in each widget, the UI tests should then be restructured to remove that widget from the mega form, and create an isolated UI test and widget form, and a test just for that (both for the benefit of the developer fixing the bug and for posterity).  And as new widgets are added (or new appearances or behaviors), add isolated UI tests for those.

This is the fallacy @srsudar -- test suites are not static. Sure, tracking down that geolocation bug was a pain in the ass. But is that a failure of having a UI test, or is that a failure of having undocumented dependencies and poor code coverage?  

Yes, unit tests and integration tests provide valuable usage examples. I agree with that. 

I'm not saying that these are not the Holy Grail.

Background tasks are candidates for integration tests, such as form submission.

ODK Collect has 100's of classes. You will never get significant code coverage if all you do is gather unit tests for the methods impacted by individual bug fixes. This, @lognaturel is why I argue for UI tests and integration tests as necessary components of a test framework.  Not always the first component, but necessary components.

Checking in unit tests for bug fixes automatically provide increased coverage for areas of code that have been brittle in the past. The more those areas change, and the more developers work to add and improve their tests, the better the behavior will be characterized.

Some of this is also dependent upon your definition of terms. 

Asserting you should "refactor until it is mock-able" is naive and not realistic or appropriate for system or 3rd party services. Yes, you could have someone write a MediaServices service, and a configuration for it, that mocks the real one, and adds that to the testing framework for use by many tests. But, if, instead, each test were to configure a mock for this service independently, it quickly gets unmanageable -- either by injecting a class layer into the production code to support this mocking, or by bloating each test's preamble to set up the mock.  The test framework must be easy to configure and use, and minimally impact the production code. Mocking does not always satisfy those criteria.

Furthermore, writing such a MediaService mock and configuration, or coding up individual mocks for this service would not pick up the behavior changes in this system-provided service that occurred between Android 2 and Android 7, or anything in between (and there were quite a few changes in this service). 

Mock'd tests would falsely indicate that everything worked, when, in fact, they don't. You sometimes HAVE to do integration tests.

And, in a sufficiently large system, the same applies -- at some point an abstraction or service layer becomes too complex to mock. You have to interact with it as if you are writing an integration test. And trust that that layer is itself sufficiently well tested.

**Comment by srsudar** [comment]
@mitchellsundt I was mostly trying to rebut what I interpreted as your initial claim, that the linked Google post was wrong/inverted, and that the natural hierarchy was UI tests first. Maybe you were speaking about what makes sense for Collect, as an existing largely un-tested codebase, rather than testing in general. I agree with your amended bullet points (with a caveat for number 2, that if it takes more work to write an integration test I think that's ok and not necessarily a failing).

To clarify my position a bit more, I'll add that I certainly don't think maintaining tests is work-free. Sometimes when you refactor something you have to throw away or modify tests, and sometimes adding functionality you really have to scratch your head about how to test it.

I also agree that, in Collect's case, having one mondo form that tests a lot of the widget functionality does seem like a good idea and a relatively easy way to start validating that things work. This is precisely how I think Collect has managed to work so well for so long without testing--you can test most base cases with a single form. Automating this could be a good place to start.

The point of testing in my mind is not to achieve high coverage. The fact that a UI test provides high coverage doesn't particularly compel me. I think the point of testing is verification. When writing code I like being able to trust that different components that I'm interacting with work as expected. A UI test is a good way to test that user-input to user-output works as expected, but it doesn't provide confidence that things worked as expected along the way. Maybe you aren't handling null inputs effectively, but this has been hidden by the fact that your XML writer has been handling them for you by accident, and if you change that your UI tests start failing and you realize you've had a larger problem lurking in the code that has gone unnoticed. In this way I think UI testing is like black box testing. For a user that might be fine--as long as it works for the user, that's what really matters. For a developer that's not what I want.

As for refactoring until it is mock-able--there are certainly cases where this can't be done, or where an integration test (e.g. for Android version vagaries) is what you want. In the vast majority of cases, however, as evidenced by the number of testing articles emphasizing the value of unit testing, refactoring to make things mock-able is feasible and a good idea for providing cleaner interfaces between components. It is a benefit of testing that it impacts the production code in so far as leading to a cleaner codebase.

@PatrickDale , I really like your approach (though I've never used Appium, only Espresso). I used the MVP pattern in my last project and agree that it worked like a dream for separating logic and UI code. [Here is a link](http://engineering.remind.com/android-code-that-scales/) to a post explaining MVP that I found helpful when I was trying to understand it. My Robolectric tests were then mostly to ensure that my UI state was correct, that I fired the correct Intents, etc.

How do you guys currently verify a new version of Collect before releasing it? Is there a form or series of forms you go through?

Trying to automate a few of those forms with Espresso (or Appium?) could be a way to start verifying things. Encouraging unit tests with commits would be also be a good step, in my opinion. I would be fine if these "unit" tests had to run using Robolectric, however. In an ideal world I think @PatrickDale is right, and unit tests would run on bare JUnit. Refactoring to something like MVP in order to allow this would be a big challenge. [`FormEntryActivity`](https://github.com/opendatakit/collect/blob/master/collect_app/src/main/java/org/odk/collect/android/activities/FormEntryActivity.java) is my favorite example. That thing is a beast. Separating the logic and UI there would be a big task. If someone touched something there and had to write a Robolectric test to verify the new piece, that is still unit-y in my mind and would be worth it.

**Comment by mitchellsundt** [comment]
I think that is where my perspective differs from yours: I absolutely do not see testing as primarily a verification activity.  I see testing, overall, as a proof-of-capability activity; only at the level of unit testing, is it simply a verification-of-conformance-to-a-specification activity.

And keep in mind that publication quantity and frequency does not strictly imply importance! 

Checking-in unit tests along with code is good practice, but unless you have a surrounding development methodology, testing philosophy, and management that is focused on completing and verifying **end-to-end goals**, unit-testing can lead to a code-first variant of analysis-paralysis.  It can be just as ineffective as if you had strictly followed a waterfall development model from the 70's.

Integrating early and often is critically important. And if that integration is all done through hand-testing, without any checked-in integration tests, then you haven't really moved the needle much from the current low-development-maturity-level that ODK Collect has.

Proof-of-capability is what gets a product shipped.

Verification-of-compliance is what makes a product bug-free.

Accomplishing both while minimizing costs is where the management challenge lies.

**Comment by lokeshkvn** [comment]
Hello Everyone , 

I think Adding the testing framework in ODK is most challenging and interesting project in GSoC 17.
And I would like to contribute to this project.

As per my thoughts Junit4 with mockito framework for ODK classes and Robolectric for android classes would be the better option for Unit testing/Integration Testing as the UI of the ODK will change (suggested by @lognaturel ). After final UI/UX of ODK is completed we can integrate Espresso for UI testing as well.

**Comment by stefanches7** [comment]
Hello dear OpenDataKit contributors,

this issue sounds very interesting. From what I understand now, there are plenty requirements to the testing framework, and most difficult is really this choice between frameworks, because there should be one and only chosen at the end, but chosing one framework happens "on the cost" of losing another frameworks' functionality. 

As far as I understood, the situation that project now has is following: there are really big changes planned, especially in UI sphere as a part of plan of improving UX. So the main and first-priority requirement seems to be flexibility of testing: we don't want to couple testing with current implementation, since this could change drastically with time. From what is mentioned in project ideas, tests' main purpose is to avoid regressions with new releases, i.e., check, that main and needed functionality is still there.

Keeping all those aspects in mind, I would really choose Roboelectric. It allows so to say "blackbox testing", what is really needed here, as mentioned before. What I also really like that it requires no mock framework, and I vote for avoiding mocking as far as possible, since it turns to "reverse implementation" fast, which would be a dead end in the context of rapidly changing implementation.

From what I still wonder about is testing UI or doing unit tests. I think, to evaluate the measure of those one should really evaluate the grade of future changes, and I'm glad to discuss this further. I am also glad to hear some feedback on my understanding of a project and problem and exclamated ideas, since it would really help me to understand project better and excellence the ideas accordingly.

Sincerely yours,
Stefan.

**Comment by lognaturel** [comment]
There are now some tests of the different varieties mentioned in this thread. Establishing a testing culture continues to be a work in progress but I would like to close this issue in favor of more targeted ones or forum discussions for higher-level issues.
