### ISSUE TITLE
Select one external relies on name and label for uniqueness

### ISSUE THREAD

**Issue by yanokwa** [getodk/collect#394]
#### Steps to reproduce the problem
 1. Download [select_one_external.xlsx](https://github.com/opendatakit/collect/files/760466/select_one_external.xlsx) form.
 1. Convert the form to XML.
 1. Push the XML to `/sdcard/odk/forms/select_one_external.xml`. 
 1. Push the CSV to `/sdcard/odk/forms/select_one_external-media/itemsets.csv`

The form is available in English and French (English words with "le" or "la" prepended). The form has identical choices, but one set is internal (`choices` sheet) and another is set is external (`external_choices` sheet). 

For the first three external questions, there is broken behavior.
 * If you select Washington, then Pierce, you should get Tacoma/Puyallup. 
 * If you select Washington, then Pierce 1, you should get nothing. 
 * If you select Washington, then any of Kings, you get nothing. If you select the first King and swipe forward and back, it moves your choice to the second King.

For the last three internal questions, the behavior works as expected. 

#### Expected behavior
For external choices, if you select Washington, then any of Kings, you should get Seattle/Redmond for one and nothing for the other. 

It seems that Pierce 1 works because its name and label are different. King doesn't work because only its name is different. Uniqueness should be determined by name, not a combination of name and label. The filtering with external choices should be the same as internal choices.

#### Other information
I have not tested if the broken external uniqueness is determined by all labels (French + English as a key) or just the first language that loads.  I also have not tested if this problem exists on the second select_one (cities), but I bet it does.

I'm pretty sure #161 is the same issue.

**Comment by AngeloLazzari** [comment]
@yanokwa yep, it's the same problem! Great work!! Thnk you very much

**Comment by grzesiek2010** [comment]
Unfortunately we can't fix this problem as it's related to javarosa. Internal choices work well because SelectOneWidget is used in that case. SelectOneWidget use SelectOneData to store answers and when we create the widget we have all choices as a list in our prompt. If we use external choices we use ItemsetWidget which is DATATYPE_TEXT and this data type use string to store answers (we don't even have such list in the prompt like in SelectOneWiget). So we can't force ItemsetWidget to work the same as SelectOneWidget.

On the other hand I don't think it's a bug. Why does someone want to have two identical options? The app doesn't crash, the behaviour is not perfect but in my opinion it's not a problem it doesnt' work only for external choices, only when someone adds two identical options and only on the second and lower levels (as I guess because the first level in ecternal choices is represented as SelectOneWIdget so it should work).
