### ISSUE TITLE
When try to record video an error is displayed "The external application did not provide expected information"

### ISSUE THREAD

**Issue by atl2017** [getodk/collect#3962]
#### Software and hardware versions 
Collect v1.27.2, Android v9, device used... Moto g6
![image](https://user-images.githubusercontent.com/29519901/86850619-31f4f600-c077-11ea-95b2-2f25fa3b61d3.png)

#### Problem description
![image](https://user-images.githubusercontent.com/29519901/86850454-e9d5d380-c076-11ea-9ea7-21cc68981a22.png)

#### Steps to reproduce the problem
Fill "All widgets" question Video

#### Other information 
This issue is very specific, related with hardware.

**Comment by lognaturel** [comment]
This has to do with the video application that is being launched by default. What application is that? Can you please try installing another video recording application and seeing whether that works? I'm surprised that a default video app wouldn't return data via intent.

In general, please start with a support question on the forum so that your questions contribute to searchable user resources!

**Comment by grzesiek2010** [comment]
It's not our fault and we can't fix it so I'm closing.

**Comment by atl2017** [comment]
Thanks
