### ISSUE TITLE
Update AllWidgetsFormTest

### ISSUE THREAD

**Issue by SaumiaSinghal** [getodk/collect#3963]
Currently, `AllWidgetsFormTest` checks the behaviour of almost all widgets. There is a lot of scope to simplify it. As the behavior of all the widgets ranging from displaying intents to changing answers can be verified in corresponding unit tests, `AllWidgetsFormTest` can be just used to verify whether all the widgets are rendered on screen or not.

Performing a simple swipe to check whether the next widget appears on the screen would be enough rather than navigating to the widgets using the Form Heirarchy menu.

**Comment by lognaturel** [comment]
Reducing the test to verifying that the widgets are rendered and swiping through rather than going to the hierarchy sounds good to me. The major advantage is that it will significantly reduce the run time of the test.

I think doing this now will reduce coverage somewhat because not every widget type has unit tests yet. That seems ok to me, though, since we're adding unit tests as changes are made and intend to rework the test suite for all widget types soon.

While there, it would be great to update the form definition to the latest version: https://docs.google.com/spreadsheets/d/1af_Sl8A_L8_EULbhRLHVl8OclCfco09Hq2tqb9CslwQ/edit#gid=0

**Comment by SaumiaSinghal** [comment]
@getodk-bot claim
