### ISSUE TITLE
Display guidance hint icon in line with question text if there's a collapsed guidance hint but no primary hint

### ISSUE THREAD

**Issue by lognaturel** [getodk/collect#3972]
#### Software and hardware versions 
Collect v1.27 and prior

#### Problem description
Currently, the collapsed guidance hint icon is displayed after the hint text. This looks good and makes sense when there's hint text:
<img width="369" src="https://getodk-a3b1.kxcdn.com/uploads/default/original/2X/3/3b1155b5daccb32901c979c5db6a1d5e2a1b8196.png">

However, it's also possible to have a guidance hint without a primary hint. In that case, the guidance hint icon takes up an extra line, is hard to tap, and looks confusing:
<img width="250" alt="Screen Shot 2020-07-14 at 10 41 40 AM" src="https://user-images.githubusercontent.com/967540/87458302-a15e6e80-c5be-11ea-8b3a-cf414cbd3751.png">

#### Steps to reproduce the problem
1. General Settings > Form management > Show guidance for questions set to "Yes - collapsed"
2. Go to a question with label text and a guidance hint but no main hint such as the question from [guidance-hint.xml.zip](https://github.com/getodk/collect/files/4920335/guidance-hint.xml.zip)

#### Expected behavior
The guidance hint icon should be next to the label text. Ideally tapping anywhere on the label would expand the guidance hint.

**Comment by SaumiaSinghal** [comment]
@getodk-bot claim

**Comment by SaumiaSinghal** [comment]
@lognaturel when the form has both primary hint and guidance hint, then both will be in separate lines, right? I was unable to create such a form.

**Comment by lognaturel** [comment]
> when the form has both primary hint and guidance hint, then both will be in separate lines, right

This case is the first screenshot I shared. Once the user taps the (i), the guidance hint expands on a third line. So yes, the hint and guidance hint text are always on separate lines. This issue is about where the (i) icon should be. 

>  I was unable to create such a form.
You should be able to add `hint` and `guidance_hint` columns in XLSForm. Did you try that and if so, what happened?

You've got a lot going on with all the widget refactors and this is very far from urgent so also consider leaving this for a new contributor to pick up!

**Comment by SaumiaSinghal** [comment]
Yeah right @ln I'll come back later, meanwhile, any new contributor can give it a try

**Comment by SaumiaSinghal** [comment]
@getodk-bot unclaim

**Comment by anadi198** [comment]
@getodk-bot claim

**Comment by anadi198** [comment]
Hello, I'm new here and wanted to give this issue a try. Since I'm not familiar with the codebase, I want to make sure I'm doing it right. 

So far I've taken the `help_icon` from `help_layout.xml` file and put it inside `question_widget.xml` alongside `question_label` inside a horizontal LinearLayout with 10:1 weight ratio. I've made the necessary change inside `QuestionWidget.java` to change the container from which we initialise the `help_icon`. 

This results in the help_icon moving to the right of question_label and when you click on it, it behaves as before. I also set the `layout_gravity` for help_icon to `center_vertical`. 

> Ideally tapping anywhere on the label would expand the guidance hint.

I had a look at `AudioVideoImageTextLabel` and it has its own `onClick()` defined, for example playing video if label is clicked. I'm not sure if I've got this right, but adding another onClick to the label might break things in case of video and such I think?

**Comment by grzesiek2010** [comment]
Hi @anadi198 
thanks for taking a look at this issue. I'm not sure about the expected behavior here so let's make sure we are on the same page first

> The guidance hint icon should be next to the label text. Ideally tapping anywhere on the label would expand the guidance hint.

by next to the label text you mean after the label text right? That would require adding it to the AudioVideoImageTextLabel what would make that view even more complex. Is that what we really want? @lognaturel

**Comment by anadi198** [comment]
Okay I will wait to get the confirmation. @grzesiek2010

**Comment by lognaturel** [comment]
Thank you so much for looking into this, @anadi198! Sounds like you're finding your way around the codebase nicely.

> I had a look at AudioVideoImageTextLabel and it has its own onClick() defined

Thank you, I did not remember this behavior. So it's clear it wouldn't make sense for tapping on the label to also have anything to do with guidance hints.

> by next to the label text you mean after the label text right? That would require adding it to the AudioVideoImageTextLabel what would make that view even more complex.

Next to the label text is what I had in mind. I had not considered how the different layouts are separated and you're right that this change may not be worth making. Ideally both the regular hint and guidance hint would stay in `help_layout` and all the logic would remain where it is now. The only difference would be that if the `help_layout` only had a guidance hint icon (no hint text), it would be displayed on the same line as the question label. That may not be possible.

> taken the help_icon from help_layout.xml file and put it inside question_widget.xml alongside question_label

This means the icon would always be next to the label, even if there is a regular hint, right?

**Comment by anadi198** [comment]
> This means the icon would always be next to the label, even if there is a regular hint, right?

Yeah, I'm afraid so.

**Comment by lognaturel** [comment]
Thanks for the reminder, @getodk-bot, I'm the one who dropped the ball here.

I think that given the way hints are laid out this is not actually realistic. Thanks for looking into it, @anadi198, it's much appreciated!
