### ISSUE TITLE
start=0 in range widget starts with 1

### ISSUE THREAD

**Issue by dmenne** [getodk/collect#3973]
Collect 1.27.3

```
type     parameter
range    start=0 end=10 step=1
```

This gives a scale from 1 (sic!) to 10.

**Comment by seadowg** [comment]
Hey @dmenne 👋. Would you be able to post the form you're using? I'll have a look and see if I can reproduce but it might be useful to see the form as well.

**Comment by dmenne** [comment]
Nothing special, just a line:

type   | name | label | parameter
range | sibb | Sibblings | start=0 end=10 step =1 |

**Comment by seadowg** [comment]
@dmenne I couldn't reproduce. It looks like you're using `parameter` rather than `parameters` so the start/step/end are being ignored. Could you try fixing that and see if it solves your problem?

**Comment by dmenne** [comment]
Apologies, my fault. It should be parameters, and I did not notice it because it simple reverted to the default numbering when parameter was not recoginized.

Thanks.

**Comment by lognaturel** [comment]
Thanks for bringing it up, @dmenne. We've talked a few times about throwing a form conversion error when we see a column/row name that is close but not an exact match to a "known one." It's a big lift to do across the board but `parameters` might be a good one to specifically target because as this illustrates, it can be hard to spot when parameters are not being set as expected.
