### ISSUE TITLE
Regression on grid widget with autoplay 

### ISSUE THREAD

**Issue by kkrawczyk123** [getodk/collect#4043]
#### Software and hardware versions 
Collect v1.28.x, Android v all, device used...

#### Problem description
I have noticed regression on gridwidget with autoplay: the first thing is that audio is not played after selecting an answer, toasts informing about missing media file or invalid one are not showing up. (1st question in the attached form) the second thing is that audio files are visible for a second question which is a regular select one question and moreover they are also overlapping answers.
Form that I have used: [gridwidget.zip](https://github.com/getodk/collect/files/5124232/gridwidget.zip)
The comparison of the same screens:
| Collect 1.27.3 | Collect 1.28 |
| ----- | -----| 
| ![Screenshot (Aug 25, 2020 4_08_46 PM)](https://user-images.githubusercontent.com/33342488/91185672-6a679680-e6ee-11ea-96d8-6d3b123e8401.png) | ![Screenshot (Aug 25, 2020 3_30_40 PM)](https://user-images.githubusercontent.com/33342488/91185709-72273b00-e6ee-11ea-9219-4d4f7ec980c6.png) |

#### Steps to reproduce the problem
1. Open the attached form on 1.27.3 and fill it
2. Open the attached form on 1.28 and fill it 

#### Expected behavior
- autoplay should work for gridwidget
- media files should not be visible on select one question in that kind of form

#### Other information 
Things you tried, stack traces, related issues, suggestions on how to fix it...

**Comment by grzesiek2010** [comment]
Let's wait with this until we merge https://github.com/getodk/collect/pull/3964

**Comment by grzesiek2010** [comment]
I wouldn't call those two issues regression because:
- playing audio files (in no-buttons mode) after selecting a choice has never worked in selects that use recyclerview (now all selects use recyclerview) it worked in that way only in GridWidgets which we removed replacing them with recyclerview.
- columns-pack (old compact) used in GridWidgets displayed only buttons (labels) not image/video/audio then we switched to recyclerview and it tries to use it even in case of columns-pack appearance even though it doesn't look good

I fixed the issue with playing audio files in no-buttons mode, but I'm not sure about the second one... It's column-pack appearance so I think it should work like it worked in old GridWidgets - display only buttons without media files.
I think it would be a good solution because:
- displaying such big elements in columns-pack doesn't make sense
- fixing that to display everything properly would be difficult because the layout manger used for that appearance doesn't work well with such complex views

Would you agree @lognaturel

**Comment by lognaturel** [comment]
Thinking about it more, I agree that it’s ok (and should be expected) for columns-pack not to support choice audio. It’s not very likely anyone would even try this so I don’t think this needs to be in v1.28. Fee free to remove it or put in a fix to ignore audio.
