### ISSUE TITLE
"Check for update" option

### ISSUE THREAD

**Issue by grzesiek2010** [getodk/collect#405]
It would be good to have "Check for update" option. In my opinion such option should be placed in "General Settings" under "ODK COLLECT Tap to visit...". 
When user clicks on this option we should display a dialog with appropriate information for example:
"Your have the newst version" or "The newer version of this app is available. Do you want to update?" (Cancel/Update options).
If user clicks on "Update" then the app should be updated automatically.

Any thoughts?

**Comment by lognaturel** [comment]
Good idea! It seems there is no official API for this but there are a couple of good approaches [here](http://stackoverflow.com/questions/7298106/how-to-allow-users-to-check-for-the-latest-app-version-from-inside-the-app) and [here](http://stackoverflow.com/questions/25201349/programmatically-check-play-store-for-app-updates).

Could we instead just have a button that says "update available" if an update is available (and the device is online) and is hidden otherwise? If the device is offline, there's no real useful information to give. If it's online, the user only cares if there is an update, I think.

**Comment by grzesiek2010** [comment]
@lognaturel I'm not sure... Do you only wanto to infor about update or as I mentioned to give a possibility to download the newer app and update automatically as well?

**Comment by lognaturel** [comment]
Is it possible to update automatically? As far as I know, that is a Play Store setting. All that we can do is launch the Play Store with ODK Collect shown. I'm imagining that clicking on "update available" when it is shown would do that.

**Comment by grzesiek2010** [comment]
I'm not sure maybe it's possible too but if not we can for example store the newest app somewhere then using the link we can download the app using notification progress bar to show the progress and then update the app automatically. 
But if you think the game isn't worth the candle we can just implement the scenario you described.

**Comment by lognaturel** [comment]
I've never heard "the game isn't worth the candle"! That's a great expression. 😊

I talked to @yanokwa about this and he pointed out a number of issues:
- not all devices have the Play Store
- if someone installed an APK, there may be a reason for it and it wouldn't be good for them to then install from the Play Store
- it's generally a project tech lead rather than an enumerator who will make update decisions
- an enumerator may not have a google account and get confused by the Play Store process or create an account they shouldn't be creating

Given the nature of this app and how it's used (field data collectors have the devices but tech leads make decisions), it might not be a good idea after all to say anything about versions available and instead let tech leads decide whether automatic updates should be turned on at the Play Store level or not.

**Comment by grzesiek2010** [comment]
> I've never heard "the game isn't worth the candle"!

It's often useful expression in programing I think :) It's popular in my country I know it's in English too so I thought it's popular there as well.

Ok let tech leads decide.

**Comment by lognaturel** [comment]
I will definitely use it now!

Good conversation. Closing for now and if someone has more to add they can re-open.
