### ISSUE TITLE
Don't always save media captured through Collect to the Media Store

### ISSUE THREAD

**Issue by lognaturel** [getodk/collect#4070]
Placeholder issue for https://forum.getodk.org/t/remove-previously-taken-images-from-gallery-via-setting/26593 so it can be put in milestone.

**Comment by racetiger** [comment]
Hi, as this issue will probably need refactoring of [this code](https://github.com/getodk/collect/blob/482c63404d0bf318e4e52df5d3b59728a2fc86b5/collect_app/src/main/java/org/odk/collect/android/widgets/ImageWidget.java#L165) ,  why not simply follow [the recommendations](https://developer.android.com/training/camera/photobasics#TaskPath) from andoid.com, either about using MediaStore.Images or getExternalFilesDir() ?

It looks like the existing code is using an absolute filename/path which might well be the root cause of the duplication behaviour observed in the forum post. And the reason for this , mentioned in the code comment, was fixing an issue with Android 1.6 :-)

**Comment by lognaturel** [comment]
Yes, this should be a great opportunity to remove old code, you're absolutely right!

There's currently an explicit call to register files to the `MediaStore`. What we are proposing to do is only save images to Collect's scoped folder ("if you'd like the photos to remain private to your app only" in the excellent page you linked to). This means images taken through Collect would **not** be available to other applications (unless the camera app happens to also save a copy). From what we've heard from users so far, having Collect's images indexed in the `MediaStore` is confusing and not generally useful.

**Comment by racetiger** [comment]
> having Collect's images indexed in the MediaStore is confusing and not generally useful

This is certainly correct. 

If you go for this option, I suggest you also check how well it will work together with the "choose image" button behaviour in the Image widget, which is [currently](https://github.com/getodk/collect/blob/1fcb0579fe6bc4f382beb537cfc8484dc4d2dbb4/collect_app/src/main/java/org/odk/collect/android/widgets/BaseImageWidget.java#L292) using a very generic [ACTION_GET_CONTENT](https://developer.android.com/reference/android/content/Intent#ACTION_GET_CONTENT) activity, retrieving media from a very wide scope of sources.
