### ISSUE TITLE
Deleting filled forms and then redownloading from Google Drive or adding via adb doesn't work

### ISSUE THREAD

**Issue by mmarciniak90** [getodk/collect#4103]
#### Software and hardware versions 
Collect master

#### Problem description
The re-downloaded form from GD is not visible on the Fill Blank form page if this form was filled and deleted

#### Steps to reproduce the problem
1. User uses Google Drive as a server
2. User downloads form
3. User fills downloaded form
4. User goes to `Delete Saved Form` and removes the form 
5. User goes to `Get Blank Form` and download the same form again
6. Form is not visible on the `Fill Blank Form` list

or

1. Copy form to device using `adb`
1. User fills form
1. User goes to `Delete Saved Form` and removes the form 
1. Copy form to device again using `adb`
1. Form is not visible on the `Fill Blank Form` list

#### Expected behavior
The form is visible, user is able to fill it

**Comment by mmarciniak90** [comment]
@getodk-bot label "regression"

**Comment by seadowg** [comment]
Hmm this seems related to some earlier issues (#4028 for instance). I can take a look.

**Comment by lognaturel** [comment]
I think I ran into something that might be related. I pushed a form manually to the device. Then I deleted all blank forms (there were many others and I wanted to clear clutter). Then I tried to push the same form as original and it wasn't showing up in Fill Blank Form. I have finalized but unsent instances for that form so it makes sense there would still have been a db record for the corresponding blank form. Ideally the task that syncs from disk would recognize that an identified XML file is newer than when the soft delete happened. I think it's the same thing with GDrive.

**Comment by seadowg** [comment]
@lognaturel yeah likely. The problem is that all these different import paths are handled by completely different code (`MultiFormDownloader`, `GoogleDriveActivity` and `FormsDirDiskFormsSynchronizer`). 

Thinking about it I'm actually a little worried we can't handle the case you've brought up and soft delete (in its current implementation). If we want to have a form be "deleted" and keep the definition around there is no way to then differentiate between a soft deleted form and one that has soft deleted and then imported on the device via adb.

@kkrawczyk123 @mmarciniak90 would you be able to play around with the case @lognaturel has brought up?

**Comment by seadowg** [comment]
Ok as far as I can see Google Drive downloads just use the `FormsDirDiskFormsSynchronizer` to get the form into the DB so I now understand that (I think @lognaturel) is suggesting changing the implementation of the disk sync so it "un-deletes" forms if the file is newer than when the form was deleted.

**Comment by seadowg** [comment]
@kkrawczyk123 @mmarciniak90 I've confirmed that there is a problem with manually adding forms after deleting them so no need to check that.
