### ISSUE TITLE
RuntimeException in FormController.java:922

### ISSUE THREAD

**Issue by grzesiek2010** [getodk/collect#4145]
#### Problem description
https://console.firebase.google.com/u/0/project/api-project-322300403941/crashlytics/app/android:org.odk.collect.android/issues/960eea5fd9eed2e302699052950fdaee?time=last-seven-days&versions=v1.28.1%20(3923)&sessionEventKey=5F7B186800E50001483327869100C764_1458566851285633918

```
Fatal Exception: java.lang.RuntimeException: Only questions and regular groups are allowed in 'field-list'.  Bad node is: /aGgNSwSLxKcrJWY8NtVfjt/Section_B/B_chitralada/asset
       at org.odk.collect.android.javarosawrapper.FormController.getQuestionPrompts(FormController.java:922)
       at org.odk.collect.android.activities.FormEntryActivity.updateFieldListQuestions(FormEntryActivity.java:2708)
       at org.odk.collect.android.activities.FormEntryActivity.access$1900(FormEntryActivity.java:200)
       at org.odk.collect.android.activities.FormEntryActivity$10.run(FormEntryActivity.java:2681)
       at android.app.Activity.runOnUiThread(Activity.java:5289)
       at org.odk.collect.android.activities.FormEntryActivity.widgetValueChanged(FormEntryActivity.java:2678)
       at org.odk.collect.android.formentry.ODKView.widgetValueChanged(ODKView.java:621)
       at org.odk.collect.android.widgets.QuestionWidget.widgetValueChanged(QuestionWidget.java:499)
       at org.odk.collect.android.widgets.items.SelectMultiWidget.onItemClicked(SelectMultiWidget.java:85)
       at org.odk.collect.android.adapters.SelectMultipleListAdapter.lambda$createButton$0(SelectMultipleListAdapter.java:106)
       at org.odk.collect.android.adapters.-$$Lambda$SelectMultipleListAdapter$apSaKhIavlUfvDCnua9cTtxGgo4.onCheckedChanged(-.java)
```

**Comment by lognaturel** [comment]
Let's make sure this goes to a dialog rather than crashing.

**Comment by grzesiek2010** [comment]
@lognaturel 
I'm thinking about this issue and I'm not sure what solution we should have here.
We use `FormController.getQuestionPrompts(`) (which might throw `RuntimeException`) in multiple places and in the future we may even add new calls. That means if we want to follow the same way of handling the issue like now (catching `RuntimeException`, displaying a dialog and moving to next screen) we need to catch that exception everywhere. Even if I catch it now in `FormEntryActivity.java:2708` it might happen somewhere else.

Do we really need to do that maybe we could just skip those unsupported questions (repeat groups in this case I guess) and just display the rest of questions with a toast/snackbar. It would look like:
https://github.com/getodk/collect/compare/master...grzesiek2010:COLLECT-4145?expand=1

I understand that for users who made a mistake such toast is something less prominent than a dialog and skipping the whole screen but for us it's much more convenient.

Additionally we could add maybe checking this scenario when a form is validated (during converting)?

**Comment by lognaturel** [comment]
> display the rest of questions with a toast/snackbar

This would mean having display code (for building a toast) in the Controller layer. I'm not feeling very comfortable with that.

> it might happen somewhere else

I think fundamentally the problem is that this has no business being a `RuntimeException`. Since it's a `RuntimeException`, there's no check from the calling side to make sure it's being handled. What do you think of https://github.com/getodk/collect/compare/master...lognaturel:formdesign-crash? This introduces a `FormDesignException` and makes sure it's actually handled everywhere it should be.

As a side note, it's really unfortunate that these exceptions can happen at any time. There's no static analysis pass on a form design so these kinds of issues can be undetected if the whole section is not relevant without data being entered, for example. I would really like to one day add a verification pass through the whole form that catches this kind of problem so Collect never has to deal with it. (Edit: really this is a Collect limitation so wouldn't be appropriate to catch in form design. See below for more.)

**Comment by grzesiek2010** [comment]
> This would mean having display code (for building a toast) in the Controller layer. I'm not feeling very comfortable with that.

That's right.

If you want to keep the solution with throwing exceptions and displaying a dialog your code seems fine. The thing I don't like about it is that it pollutes our codebase with all those try/catch blocks. It's not our fault that users do something that is not supported and it's described in the documentation in more than one place as a I remember so that's why I wanted to have a cleaner fix maybe less informative for users but better for us.

I don't know I expected that you would be skeptical because probably long time ago we had a similar discussion about the same part of code. I would rather prefer spiking those unsupported elements like I proposed but if you are sure it's better to notify users about that fact in a prominent way like we do now you can create a pr I'll accept it.

**Comment by lognaturel** [comment]
> we had a similar discussion

Honestly I go back and forth. To me the most compelling argument in favor of dealing with the exceptions on the caller side is to keep user interface code out of a controller. I agree that the user experience doesn't need to be particularly fantastic because it's unlikely to make it to a production form. 

However, I've seen more form designers end up with these kinds of issues and have more sympathy for them now. It's quite unexpected that the form design tools wouldn't catch something like this. There's no real reason repeats aren't supported in field lists other than we don't have a user interface for it. I thought briefly that maybe JavaRosa should enforce this limitation but now I realize it's truly just a Collect thing and other clients on top of JavaRosa could certainly support that.

I'll play around with it some more and put in a PR. Thanks for doing the bulk of the investigation!

**Comment by grzesiek2010** [comment]
I have another idea it's a bit late here in Poland so sorry if it's something stupid but... :) what about generating dynamically a [note](https://docs.getodk.org/form-question-types/#note-widget) which would serve as a warning (something like we do in selects where there is something wrong or an external file does not exist - there it's not a note but it's similar) it could be even styled to use red color, and adding it in place of such unsupported element.

**Comment by lognaturel** [comment]
I like the concept! Like I said in the PR, it does feel like a whole new type of transformation. Given that it really does feel like a temporary limitation, I'd rather just make sure the exception leads to a dialog everywhere.
