### ISSUE TITLE
Editing and then saving instances with shape|trace values results in invalid format

### ISSUE THREAD

**Issue by lognaturel** [getodk/collect#4179]
See Slack conversation: https://getodk.slack.com/archives/CB2UJJ6SF/p1603096069042400

From @TimonWeitkamp:

"All of the polygons are collected through the geoshape widget, and depending on the agricultural field they are sampling, either tap (if it is rectangle) or auto-record (if non-rectangular). None are prepopulated."

"I had a look at the csv from the manual download, and found this: there are two polygons near each other, collected by the same person on the same date, only half an hour difference and a few hundred meters from each other (see image).
The coordinates:
-25.041891420472602 33.6740592867136 0.0 0.0;-25.041891420472602 33.6740592867136 0.0 0.0;-25.041891420472602 33.6740592867136 0.0 0.0;-25.041891420472602 33.6740592867136 0.0 0.0;-25.042363462114455 33.674249053001404 0.0 0.0;-25.042071246074226 33.67517
and
-25.044823577656306 33.67414176464081 0.0 0.0; -25.044823577656306 33.67414176464081 0.0 0.0; -25.04530988431933 33.674252070486546 0.0 0.0; -25.045065364345714 33.67478650063276 0.0 0.0; -25.04461520331787 33.67461148649454 0.0 0.0; -25.044823577656306 3
The difference between these coordinates is the space after the semicolon, ";" in the first vs "; " in the second example, as mentioned above. Both polygons are tapped (they have perfectly straight lines), and no differences (except time). Could be a bug on the ODK collect side?
I found more of such examples in the csv file."

This really sounds like Collect is inconsistent about how it saves geo values. However, I can't reproduce. I see that `getDisplayText` put spaces between points but I can't see a place where that would determine the value. Maybe there's some sequence of events like going to the hierarchy or re-opening an instance that would lead us there.

@mmarciniak90 could you please work your magic and try to reproduce?

**Comment by mmarciniak90** [comment]
@lognaturel I spent a while on this issue and here are my observations. I wasn't able to reproduce it without manual interference in xml file.

- Both examples have 6 points, the first one is doubled. Rectangular field should have five coordinates.
- Both examples have exactly 255 characters. Example with space has lost the last coordinate ` -25.044823577656306 **3**` -> Can we receive the csv file? What app is used to analyze CSV file? I was able to open CSV with much more characters in GeoShape widget, that's why I wonder about 255 characters
- Is it possible that data collector opened the xml file?
- I was able to manually add space to xml. Spaces are visible on widget view. If I open the map view and click save to leave map view, spaces are removed. 
<img height="40%" width="40%" src="https://user-images.githubusercontent.com/3907554/100525414-f2af7900-31c0-11eb-9804-35ad38d0d072.png">

- I selected exactly the same field - I tried to reproduce issue on the same hemisphere of the world
- I selected area with current location to check automatic mode
- I checked the max zoom to receive the best accuracy

**Comment by TimonWeitkamp** [comment]
Hi @mmarciniak90 ,

Shall I send you the CSV file personally? I can open the coordinates in QGIS with [ODKTrace2WKT](https://plugins.qgis.org/plugins/odktrace2wkt/) with no problem (even if they contain the spaces).

Regarding if the collectors opened the XML file, I don't think so, and it's been a couple of months ago (+ many samples), so I don't think they would know what they did with each sample.

**Comment by lognaturel** [comment]
Thanks for chiming in, @TimonWeitkamp! I don't think the CSV is likely to help as it seems like the spaces are introduced before the Central export. Central streams its export and so performance is important and if possible we'd rather not have to handle spaces if they're not part of the spec. That's why we're really trying to identify where they're coming in.

> + many samples

And are there many with spaces like that? Has any pattern emerged (e.g. a specific data collector)?

**Comment by TimonWeitkamp** [comment]
The CSV i manually downloaded contained 405 polygons with "; " (with space), out of 693. This seems similar to when I download the data through ruODK -> there are more polygons with only 1 GPS value than there are polygons with multiple GPS values.  

I have not seen any patterns regarding date or collector. The same collector has both versions of polygons on the same day.

**Comment by lognaturel** [comment]
The "re-opening an instance" case I mentioned in the original issue turns out to be the source of problem. I really thought I had eliminated that but there must have been something wrong with my process. It's simply a matter of opening an instance for edit and saving it. There's no need to modify the shape|trace.

Now that we have a reproduction, we will fix it in the next Collect release.
