### ISSUE TITLE
Read-only binary questions have no spacing below the question text

### ISSUE THREAD

**Issue by lognaturel** [getodk/collect#4209]
#### Software and hardware versions 
Collect v1.28 and prior

#### Problem description
Binary widgets hide their buttons when they're read-only. Currently they leave no spacing below the question text which looks strange in field lists, especially when they're combined with text fields:
<img src="https://user-images.githubusercontent.com/967540/98043943-f4149e00-1dda-11eb-81eb-e24656354489.png" width=250/> <img src="https://user-images.githubusercontent.com/967540/98043949-f4ad3480-1dda-11eb-8ad1-d52fb20a4aa6.png" width=250 />

#### Steps to reproduce the problem
Load a form with a field list including one or more binary questions such as https://github.com/getodk/collect/pull/4188#event-3962296705.

#### Expected behavior
There should be spacing below question text for read only binary questions.

**Comment by grzesiek2010** [comment]
But then if answer is added we need to get rid of that space right? so as I said in https://github.com/getodk/collect/pull/4188#issuecomment-721673380 wee need that space only if we have read-only widgets without answer?

**Comment by lognaturel** [comment]
Right, the cases are:
* Not read only, no value
* Not read only, with value
* Read only, no value
* Read only, with value

The high-level goal in my mind is to visually separate different questions in a field list and to make the layout look less chaotic.

An option might be to add a bit of padding that goes below the media if an answer exists. It wouldn't probably make sense to add as much as in the EditText widget cases. Alternately, maybe the EditText widgets should also be rethought and not take up as much vertical space when read-only so the different question types look more balanced.

Maybe there's something clever that can be done like giving the answer container a minimum height.

I don't feel too strongly about the exact amount of spacing, only that it should be at least as much as above the question text. I think this is one where playing with the layouts and picking something that feels right and isn't too hard to implement is the best approach. Again, I think rethinking the EditText-based widgets should also be in play if that makes it easier to get a coherent feel.

**Comment by grzesiek2010** [comment]
@lognaturel 
What do you think about a solution like this: https://github.com/grzesiek2010/collect/commit/ec7a85f70e64186b0a1b33a7db939918eaf8a684

If a question is read-only and has no answer we would display empty space instead of `answer_container`. It won't require handling every widget separately.

**Comment by lognaturel** [comment]
From a visual perspective, I think having all the spacing even is a lot less distracting so I'm happy with it. We may want to do another pass at some point to reduce that spacing but what matters to me in the mean time is that it looks intentional. I'm a little unsure about the implementation and whether it works for all the many, many widgets we now have so hopefully you can reason through it and feel comfortable that it does.

**Comment by grzesiek2010** [comment]
I have one side question. I discovered that we can remove answers from read-only questions. Is that intentional? It's a bit strange to me at least but maybe you can explain.

**Comment by lognaturel** [comment]
> can remove answers from read-only questions

That definitely seems like a bug. I've never thought to try it. File an issue?

**Comment by grzesiek2010** [comment]
> I'm a little unsure about the implementation and whether it works for all the many, many widgets we now have

I prepared a test form with all widgets using read_only option and another one putting all of them into an intents group and everything seems fine.
The only problem is that it needs a small change in every widget: https://github.com/getodk/collect/pull/4228/files#diff-1e5bcfb621a7eef20f93986764ee04a628ce81c72437d882cc1f2376f7a16db3R89

but still it seems like the easiest solution.

> That definitely seems like a bug. I've never thought to try it. File an issue?

Fixed in https://github.com/getodk/collect/pull/4228/commits/94a906a105404e79af0d7c1456274c7c49ddf735

Tell me what you think about it if you agree that we can use this solution I'll go ahead and add some tests maybe.
