### ISSUE TITLE
Add support for external binary question types

### ISSUE THREAD

**Issue by lognaturel** [getodk/collect#4214]
https://github.com/getodk/collect/pull/4188 added support for binary files to be returned by external apps to intent field lists. This issue is to allow single-question media questions to call out to external applications. 

[Current documentation](https://docs.getodk.org/launch-apps-from-collect/#designing-an-external-app-to-return-a-single-value-to-collect) for external questions.

From [the specification document](https://docs.google.com/document/d/1JbKiwgBCuI2t3Cd8n5OnyrNce3woq20ncZbN3oGcPhU/edit):
If the field has a binary type, Collect will use the ClipData contents. If there’s more than one item in the ClipData, Collect will fail silently and clear the field.

Implementation notes:
* Currently each question type has its own widget class. Is it better to continue this pattern or could we pull everything to do with external applications out of the widget layer?
* Important to manage redundancy with the field-list implementation
* https://github.com/getodk/collect/pull/4208#issuecomment-724199226 has some cases to test

**Comment by grzesiek2010** [comment]
I'm thinking about the UI and this is something we should discuss.
In case of non binary questions like text/integer/decimal if there is an appearance that indicates that an external app should be used we display a button and if trying to open such an app it turns out it's not available we display a text box like in case of normal text/integer/decimal question.
So now what about binary questions? There are options like (let's take the image widget as a sample):
- we can display one launch button instead of Take picture and Choose image buttons, then if the external app is not available display those buttons below. The behavior would be similar to what I described above in case of text widgets
- we can display all three buttons at once without checking if the external app is available
- we can override Take picture button's behavior and try to start an external app if it's available otherwise start the camera app
- we can also display just that one (Launch) button and not to allow taking pictures or choosing it from the phone

I would like to hear from you @lognaturel @seadowg

**Comment by lognaturel** [comment]
The use case that led to this feature involves launching an app that goes through some process and then generates and passes back a file. My sense is that there's truly no reasonable backup if the app is missing. In the case of an integer value, I can imagine something like launching an app that takes some measurement but being able to fall back to a physical sensor if the app is not available. In the binary file case, it seems like if the desired app doesn't exist it shouldn't be possible to proceed. I like your last option the best.

**Comment by seadowg** [comment]
> The use case that led to this feature involves launching an app that goes through some process and then generates and passes back a file.

Yeah based on this I'd agree with @lognaturel that the last option feels best. Maybe we could add fallbacks in the future.
