### ISSUE TITLE
Warn users that audio recording has changed

### ISSUE THREAD

**Issue by seadowg** [getodk/collect#4223]
We want internal (`normal`) to be the default but people might update in the field or are set up new devices for an existing programme. If they rely on an external app the new default could be disruptive.

**Acceptance**

- [x] Given I've installed Collect 1.29 and have started a form with an audio question
When I move to the audio question's screen
Then I see a dialog warning me that recording now happens in app
When I click OK
Then the dialog is dismissed
And if I record it uses the in-app recorder

- [x] Given I've installed Collect 1.29 and have started a form with an audio question
When I move to the audio question's screen
Then I see a dialog warning me that recording now happens in app
When I click Change
Then I am taken to Form management settings
When I enable external recording
And press back
Then the dialog is dismissed
And if I record it uses an external app

- [x] Given I've installed Collect 1.29 and have started a form with an audio question for the second time
When I move to the audio question's screen
Then I see the question as normal

- [x] Given I've installed Collect 1.29 and have started a form with an audio question
And External app recording has been disabled from admin settings
When I move to the audio question's screen
Then I see the question as normal

- [ ] Given I've upgraded to Collect 1.29 and have started a form with an audio question
When I move to the audio question's screen
Then I see the question as normal
And if I record it uses an external app

**Comment by ignatiusgr** [comment]
@seadowg Looks great, just a one comments/question:

Even though it might not be a common occurrence, in some cases users might prefer to be aware of the changes before getting to the actual audio question screen. For instance in your example, where an organization relies on a specific external system, if the warning comes only when I get to the audio question it might be already too late, as I would be in the middle of an interview.

Is there a message, info banner or welcome window users could get once they update to the most recent version, so they can be informed of all the updates/changes, and update preferences right there after updating?

**Comment by lognaturel** [comment]
Thanks for your comments, @Ig-Rebollo! Sorry about my fat fingers closing the issue.

> if the warning comes only when I get to the audio question it might be already too late

Can you say more about what you feel the barrier would be to changing the setting in the middle of an interview? As the story is written, the user will be taken directly to settings and be able to change the audio source there. When they go back, they will return to the question and immediately be able to record from an external app. 

My recollection is that we thought it would be good for the user to go to settings so that they know where to find the functionality if they want to change again. However, another option would be for one of the dialog buttons to change the setting directly so it's even less disruptive. For example "< message about the change and where to find the setting > Do you want to keep using an external app?" "Use external app" "Use internal recording". I can see how this would be less likely to be disruptive.

> Is there a message, info banner or welcome window users could get

This is a concept that comes up periodically and so far we've always eventually come to the conclusion that it's not appropriate for most users. Perhaps you'll have a new perspective to share. 

One of the big challenges/opportunities with Collect is that our primary audience for feature changes is generally not the end user but rather their supervisor/project manager. A lot of end users (but certainly not all!) are narrowly trained to perform one data collection task and won't care about new features and may be thrown off by a message popping up, perhaps in a language they don't understand. These are typically our most vulnerable users. I personally feel very committed to them though I do acknowledge that their relative numbers are decreasing as technical savvy is more widespread.

Relatedly, it's hard for end users to tell what is "part of the app" vs. "part of the form". Mentioning something like audio recording might get people searching for audio recording functionality and getting frustrated that they can't find it. This is especially the case given that we know from analytics that a relatively small portion of users have forms with audio questions.

I think that in an ideal world we could do something like let users who have audio questions in one of their forms know about the change on app upgrade. @seadowg and I did discuss this and decided that the technical complexity and performance hit would not be worth it. At this time, we'd need to parse every form on the device to determine that one has an audio question. Depending on form size, this could be time consuming.

**Comment by lognaturel** [comment]
After thinking about this more and reviewing [the notes](https://docs.google.com/document/d/1KdUeiryViiPyiG8ajDC_snxSzDBBb-kwNauHvD_chfA/edit#) from [the last TAB call](https://forum.getodk.org/t/odk-tab-call-2020-11-25/31326) I now think we should not change the behavior for existing installs. Folks who currently use audio recording have had to train their staff to install an external app and use it. They have decided on audio settings that work for them. We should not interfere with their workflow.

Like I mentioned in the response above, we don't want to get field staff involved in deciding how audio should be collected, our audience for this new feature is really project managers. So I think our best bet is to change the default for new installs and do our best to get the word out about the new functionality.

Wish I'd gotten to that conclusion before you got to #4245, @seadowg. Let's maybe talk about it one more time before we finalize the direction.

**Comment by seadowg** [comment]
@lognaturel that does make sense to me. Honestly I could go either way, but we can chat more about this later.

**Comment by seadowg** [comment]
I'm closing this as we're planning to just have `external` as the default to avoid awkwardness for ongoing programs.
