### ISSUE TITLE
Radio buttons with short responses: allow two columns of responses

### ISSUE THREAD

**Issue by dalerhoda** [getodk/collect#426]
When radio button responses are very short (i.e., few characters per response), it would be nice to allow two columns of responses rather than make the user scroll.  In our recent date date entry experiment, we made a simple radio button interface for entering dates, and the amount of scrolling would be reduced if the days could be listed in two (or even 3) columns.  (With enough left-right space between that it is unlikely to hit one when aiming for the other)

e.g.:

o 1              o 16
o 2              o 17
o 3              o 18
o 4              o 19
o 5              o 20
...

**Comment by lognaturel** [comment]
@martijnr is this finally a reasonable use of `appearance`?! 😃 I think you have `horizontal` and `horizontal-compact` in Enketo, right? Do you have interest on adding community-standard `two-column` and `three-column` values or should we just do it for Collect and document it... somewhere?

**Comment by MartijnR** [comment]
> @martijnr is this finally a reasonable use of appearance?!

Yes, totally in my opinion!! Whoohoo! 🎉 :balloon:

I believe ODK has a `compact-n` appearance already (or at least a compact-2) because Enketo seems to have adopted this too (looking at the code for n=1 to 10) and it's on [this table](http://xlsform.org/ref-table/).

In Enketo `appearance=horizontal` is more intelligent and determines the number of neatly-lined-up columns based on the available screen width (appearance=horizontal-compact tries to squeeze all options to the minimum size without caring about lining them up in columns).

A good example of an appearance naming mess. Sorry about that. I'm open to streamlining this. E.g. we could make `compact-n` (with actual "n") the intelligent one and compact-2 (compact-3 etc) the specific ones. And then scrub all references to appearance=horizontal from docs and [example forms](https://enke.to/::widgets). I think appearance="horizontal-compact" could be replaced by just "compact".

**Comment by lognaturel** [comment]
Closing this in favor of spec discussions going on at https://github.com/XLSForm/xlsform.github.io/issues/125 and https://forum.opendatakit.org/t/spec-proposal-harmonize-compact-compact-n-horizontal-horizontal-compact-appearances/15565. Once there's agreement there we can open an issue with the specific action to take.

**Comment by dalerhoda** [comment]
Thanks Hélène !

**Comment by lognaturel** [comment]
Slow and steady wins the race, right?? (please say yes)

**Comment by dalerhoda** [comment]
Looks like progress to me...
