### ISSUE TITLE
Caught exception when Selection in SelectMultiWidget is cast to List

### ISSUE THREAD

**Issue by lognaturel** [getodk/collect#4282]
```
org.odk.collect.android.widgets.items.SelectMultiWidget.getSelectedItems (SelectMultiWidget.java:80)
org.odk.collect.android.widgets.items.SelectMultiWidget.setUpAdapter (SelectMultiWidget.java:54)
org.odk.collect.android.widgets.items.BaseSelectListWidget.<init> (BaseSelectListWidget.java:33)
org.odk.collect.android.widgets.items.SelectMultiWidget.<init> (SelectMultiWidget.java:43)
org.odk.collect.android.widgets.WidgetFactory.createWidgetFromPrompt (WidgetFactory.java:194)
org.odk.collect.android.formentry.ODKView.configureWidgetForQuestion (ODKView.java:266)
org.odk.collect.android.formentry.ODKView.addWidgetForQuestion (ODKView.java:226)
org.odk.collect.android.formentry.ODKView.<init> (ODKView.java:156)
org.odk.collect.android.activities.FormEntryActivity.createODKView (FormEntryActivity.java:1292)
org.odk.collect.android.activities.FormEntryActivity.createView (FormEntryActivity.java:1247)
org.odk.collect.android.activities.FormEntryActivity.animateToPreviousView (FormEntryActivity.java:1603)
org.odk.collect.android.activities.FormEntryActivity.showPreviousView (FormEntryActivity.java:1585)
org.odk.collect.android.activities.FormEntryActivity.lambda$onCreate$3 (FormEntryActivity.java:384)
org.odk.collect.android.activities.-$$Lambda$FormEntryActivity$jmqN8T7sEXgbZFB8hie7LXyU5ak.onClick (-.java:2)
```

This gets caught and presumably shown in a dialog but I think it still prevents users from making progress.

[Crashlytics](https://console.firebase.google.com/u/0/project/api-project-322300403941/crashlytics/app/android:org.odk.collect.android/issues/55ec99816fdf047b79c4d49d529f5a89?time=last-ninety-days)

**Comment by grzesiek2010** [comment]
I think I reproduced the issue:
1. Open this form: 
[brokenSelect.xml.txt](https://github.com/getodk/collect/files/5933833/brokenSelect.xml.txt)
2. Select one choice (only one it's important).
3. Save the form
4. Try to open the saved form.

The problem is that the form has a bug (type mismatch)
![Screenshot from 2021-02-05 17-23-46](https://user-images.githubusercontent.com/3276264/107060465-49e05400-67d7-11eb-880d-42d1e12ac311.png)

It might be a common mistake when users edit xml forms and don't use xls (or the use xls but then they realize they need to change select_one to select_multiple manually).

In this case I think we should leave it as is.

**Comment by lognaturel** [comment]
Interesting! Seems possible. We have 173 users affected in the last 90 days. I suppose that could be a single form with a bad edit. Or possibly there's a form designer that produces bad output. `select1` is not even supported as a bind type anymore (it's supposed to be `string`).

Regardless, I think we've spent enough time on this. Let's close and if it's really blocking users they need to report it.
