### ISSUE TITLE
Support for WMS as background (basemap)

### ISSUE THREAD

**Issue by shivareddyiirs** [getodk/collect#4338]
#### Problem description
I would like to display OGC WMS layer as background.
#### Other information 
By providing option for user to choose WMS as source in Setting-->User Interface-->Mapping-->Mapping SDK--> WMS Server
and similarly list of WMS server URLs can be displayed in basemap.

Or the default WMS server URL can be read from the form definition.

**Comment by florianm** [comment]
That sounds like a useful feature.

As a side thought:
If you want to reduce bandwidth and the need to be online (Collect is targeted towards offline data capture after all), you could always prepare a tilecache (e.g. see https://forum.getodk.org/t/generate-offline-background-imagery-for-odk-collect-mbtiles/31200). This would allow the option of multiple background layers, plus styled overlays (e.g. your own vector data).

**Comment by shivareddyiirs** [comment]
@florianm thanks. I am aware of it but offline layers need to transferred manually to each phone. 
If online maps ( currently google maps and OSM) can also be cached by the app itself, that would be a win-win. A

**Comment by florianm** [comment]
Agreed, that would be great. Interested to see how the extent and resolution of the intended cached area could be set by each user in Collect or maybe via settings from Central.

My mildly related feature wish would be if I could push a (once and correctly done) prepared tilecache to Collect from Central to be available to all (non GIS expert) enumerators.

**Comment by lognaturel** [comment]
Thanks! Because our community members are not typically on GitHub, we keep feature discussions on the forum at https://forum.getodk.org/c/9. Once a feature is designed and prioritized we file issues that can be closed by code. 

This concept is on our radar. You can see it mentioned in “the future” at https://forum.getodk.org/t/a-new-settings-screen-for-maps/19891. Is it something you would like to design, build or fund? I’ll close the issue for now but feel free to answer that question here and we can explore next steps. Also consider writing up a forum feature post.

**Comment by lognaturel** [comment]
Thanks for posting on the forum. I've pulled it out to its own thread at https://forum.getodk.org/t/add-generic-web-map-service-option-to-basemap-source-options/31994/2 for further discussion.

> Setting-->User Interface-->Mapping-->Mapping SDK--> WMS Server

Please make sure you pull from master because the menu structure changed over a year ago.
