### ISSUE TITLE
Remove form processing logic option from settings

### ISSUE THREAD

**Issue by yanokwa** [getodk/collect#434]
I'd like to move `Reset application` and `Form processing logic` to General Settings. I'd like to do this move because then the distinction between the two become very clear. General Settings are where all the settings are. Admin Settings are for when you want to show/hide things.

**Comment by mitchellsundt** [comment]
I am skeptical of moving Form processing logic -- unless "General Settings" are things that an ordinary data collector should never touch.

Changing this setting will change how the form is evaluated and can result in different behaviors. I.e., if a data collector randomly changes this setting, their forms may not operate correctly. This was placed in the admin settings screen because it should only be manipulated by the administrator and never the data collector.  And hopefully never altered off of the default.

This is only exposed to support backward-compatibility requirements for teams that have older forms and are blindsided by an update to ODK Collect that alters the form processing logic. Ideally this would be applied on a per-form basis, but there are a slew of challenges with that.

Another option, since this was added about 2 years ago, is to remove this settings concurrent with the sdk update.  I.e., just say that going forward, the older behaviors will not be supported. 

That's probably better than moving it to General Settings.

**Comment by lognaturel** [comment]
Removing the `Form processing logic` option with the minSDK update in the next release sounds great.

**Comment by yanokwa** [comment]
I think we should leave Reset in Admin Settings because the reset also resets the admin password :)

**Comment by lognaturel** [comment]
@yanokwa, how about changing the title of this to be "remove form processing logic option from settings."

**Comment by nmpatsal** [comment]
May I try it?

**Comment by yanokwa** [comment]
@nmpatsal Yes, please go ahead!

**Comment by shouryalala** [comment]
Hi @yanokwa this is Shourya Lala here. Do you mind if i give this a shot as well?

**Comment by yanokwa** [comment]
@shouryalala Please find an issue that hasn't been taken.

**Comment by pratikmjoshi** [comment]
@nmpatsal Have you made progress on this? If not, @yanokwa may I work on this?

**Comment by nmpatsal** [comment]
Yes I am still trying to solve in I believe until Monday i am going to end it! 

    Στις 4:26 μ.μ. Παρασκευή, 17 Μαρτίου 2017, ο/η Pratik Joshi <notifications@github.com> έγραψε:
 

 @nmpatsal Have you made progress on this?—

**Comment by nmpatsal** [comment]
Hello @yanokwa  I resolved the issue and removed the form processing logic from settings but when i run the code on my android studio i get errors because of `<<<<<<< HEAD

=======
>>>>>>> d118f43170d3d8fa17e074727a20898b2444fc25` this code, that gitadds to my code. Should I create a pull request?

**Comment by yanokwa** [comment]
@nmpatsal Sounds like you have a merge conflict. See https://help.github.com/articles/resolving-a-merge-conflict-using-the-command-line/
