### ISSUE TITLE
Information about location permission granted/not granted is not visible in audit when permission is changed during filling form

### ISSUE THREAD

**Issue by mmarciniak90** [getodk/collect#4436]
#### Software and hardware versions 
Collect v1.30
Correct behavior is visible on v1.29.3

#### Problem description
Information about location permission granted/not granted is not visible in audit when permission is changed during filling form

#### Steps to reproduce the problem
_Condition_: `Don't keep activities` is turned ON in Developer options 

1. Location permission is disabled
2. User starts form [AuditTestLocationBackground.xml.txt](https://github.com/getodk/collect/files/5995475/AuditTestLocationBackground.xml.txt)
3. User is asked about permission - user clicks on DENY
4. User goes to Android settings and adds location permission
5. User finishes form
6. Audit file is visible
7. First event - `location permissions not granted` - is visible
8. **Second event** - `location permission granted` - **is not visible**

#### Expected behavior
Both events are visible

#### Other information 
@getodk-bot label "regression "

**Comment by mmarciniak90** [comment]
@getodk-bot label "regression"

**Comment by grzesiek2010** [comment]
In my opinion, this is not a regression. I tried to reproduce it and everything worked fine, also investigating the code I can't see changes that could introduce such a regression.

I think that it's a small bug that has existed since we added the feature. The problem might stem from the fact that we check permissions in `onStart()` method in our activity. This method should be called (when a user gets back to Collect after changing something in settings) but apparently, on some devices, it is skipped (if our activity is was paused by not stopped yet, **it shouldn't be the case...**) and `onResume` is called() (the next method in the hierarchy)

![image](https://user-images.githubusercontent.com/3276264/108210829-509e8d80-712c-11eb-8527-23f6120005f5.png)

The solution would be to move that code from `onStart()` to `onResume()` but probably not for v1.30.
@mmarciniak90 do you know how common the issue is?

**Comment by mmarciniak90** [comment]
@grzesiek2010 Thanks for the investigation! Your comment prompted me to check developer options and that that was the case! 
When I unselect `Don't keep activities` everything works as expected.

I update the issue details and it's not a regression for sure.
I checked 1.29.3 with this option checked and I also saw this problem.

@getodk-bot unlabel "regression"

**Comment by grzesiek2010** [comment]
This issue does not seem to occur anymore even with enabled `Don't keep activities` so let's close.
