### ISSUE TITLE
Remove response/group menu appears if user swipes on the question title with more pressing force 

### ISSUE THREAD

**Issue by mmarciniak90** [getodk/collect#4508]
#### Software and hardware versions 
Collect v1.30.1 (older versions were not verified)

#### Problem description
Remove response/group menu appears if user swipes on the question title with more pressing force 

#### Steps to reproduce the problem
1. User swipes on line with question title
2. User needs to press harder during the swipe
3. Remove response/group menu appears but user is moved to a different question.

![ezgif com-video-to-gif](https://user-images.githubusercontent.com/3907554/113859745-90d1d200-97a5-11eb-975d-e675fc9e992a.gif)
![ezgif com-video-to-gif(1)](https://user-images.githubusercontent.com/3907554/113859753-929b9580-97a5-11eb-93e5-dac02700f7bc.gif)

#### Expected behavior
This behavior may be confusing and painful if user accidentally removes data

**Comment by lognaturel** [comment]
That's interesting, I had not experienced it this way but indeed, it's easy to reproduce. I think it has to do with the length of time the finger stays stationary on the question text. I'm not sure there's really much we can do in the case described in the issue because we truly can't tell whether the user intended to swipe but stayed on the question text for too long or truly intended to long press.

The case I'm more concerned about which I believe has the same root cause is when a user swipes on question text and then there's a required/constraint error. In that case, their swipe starts out fine but their finger lingers because they see a toast or just because on a swipe without a required/constraint error that's an ok thing to do. I think in this case it should be possible to identify that there was a required/constraint error and to ignore a continuing press or something like that.

**Comment by grzesiek2010** [comment]
I've investigated the issue and there is no one sequence of events, it's possible that:
1. Contextual menu is displayed then swiping is detected and handled
2. Contextual menu is displayed when swiping is being handled
3. Swiping is detected and handled and then contextual menu is displayed

That means there is probably no one perfect and easy solution... but I can at least:
- fix the case number 1 by closing contextual menu (`Activity.closeContextMenu()`) when swiping is handled
- fix the case number 2 by wrapping the body of `onCreateContextMenu()` with if `(!swipeHandler.beenSwiped())`
- fix the case number 3 by calling `odkView.cancelPendingInputEvents()` when swiping is handled

Any thoughts @seadowg @lognaturel? It would look like: https://github.com/getodk/collect/pull/4801

**Comment by seadowg** [comment]
All those sound like useful changes. It does feel like a lot to keep track of and hard to test, but I'm not sure if I have any better suggestions (other than rewriting how swiping works which is scary).

**Comment by grzesiek2010** [comment]
Cool so the pr is ready for review.
