### ISSUE TITLE
Wrong settings file path

### ISSUE THREAD

**Issue by grzesiek2010** [getodk/collect#456]
#### Software and hardware versions 
Collect v1.4.16

#### Problem description
When user saves settings to file this file is stored in odk/settings/collect.settings but then we try to load this file form odk/collect.settings and the file is not found of course. https://github.com/opendatakit/collect/blob/master/collect_app/src/main/java/org/odk/collect/android/activities/MainMenuActivity.java#L133

#### Other information 
We should try to load the file from  odk/settings/collect.settings not from odk/collect.settings

**Comment by lognaturel** [comment]
This is actually the intended behavior -- saving and loading settings are done from separate locations. This is because when you save settings, you're not saving them for this device but for some other one or mass configuration, etc. We don't want to load and delete those saved settings on next app launch.

That said, this is not very intuitive or well-documented. We should give some thought to how this can be made clearer.

**Comment by lognaturel** [comment]
Let's track at opendatakit/docs#5!
