### ISSUE TITLE
Manipulating in ODK files is more difficult on Android 11 - especially for offline layers

### ISSUE THREAD

**Issue by mmarciniak90** [getodk/collect#4583]
#### Software and hardware versions 
Android v11

#### Problem description
Manipulating in ODK files is more difficult on Android 11 - especially for offline layers

#### Steps to reproduce the problem
1. User opens the default file manager
2. User wants to add a new offline layer
3. User opens _/Android/data/_ direction and sees information -> **User is not able to add a new offline layer**

|![Screenshot_20210528-094103](https://user-images.githubusercontent.com/3907554/119954057-e7d27700-bf9e-11eb-909b-413e19942bf9.png)|![Screenshot_20210528-094045](https://user-images.githubusercontent.com/3907554/119954063-ea34d100-bf9e-11eb-9577-0b778dd6c8ba.png)|
|---|---|

#### Workaround
User needs to install another file manager app e.g. [X-plore File Manager](https://play.google.com/store/apps/details?id=com.lonelycatgames.Xplore&hl=pl&gl=US ) and gives additional access

|![Screenshot_20210528-102806](https://user-images.githubusercontent.com/3907554/119954732-9676b780-bf9f-11eb-9003-7fb2b1112682.png)|![Screenshot_20210528-102816](https://user-images.githubusercontent.com/3907554/119954738-98d91180-bf9f-11eb-865d-d30b4426c273.png)|
|---|---|

#### Expected behavior
We need to decide that we accept this change or do we want to add a different way to upload e.g. offline layers

**Comment by lognaturel** [comment]
It'd be helpful to understand your workflow a bit better, @mmarciniak90. Do you have a layers file somewhere on your device that you want to move into the layers directory? How did you get the layers file onto your device, did you download it?

As I understand it, the issue is that the default file management application on your device doesn't prompt for permissions when you try to navigate to app-specific folders. There's nothing we can do about that and the default file management app will vary between devices. [The docs](https://docs.getodk.org/collect-offline-maps) only mention pushing layers directly to the right directory using `adb` and that's what I'd recommend doing. Does that work as expected?

**Comment by kkrawczyk123** [comment]
@lognaturel After installing the newest update of this file management app we were able to access that folder. Adding layer using adb works well on our Android 11 device. We can close that issue.
