### ISSUE TITLE
[By Dec 2021] See how custom splash screen looks with Android 12 splash screen

### ISSUE THREAD

**Issue by lognaturel** [getodk/collect#4592]
With Android 12, [every app will get a default splash screen](https://9to5google.com/2021/04/21/android-12-dp3-all-apps-now-show-the-same-splash-screen-while-loading-gallery/). Collect already has a splash screen which can be dynamically user-defined. This is used to orient data collectors to the project they're working on and provide a bit of a branding opportunity for organizations. We believe the Android splash screen will be displayed followed by the Collect/user-defined one. It would be useful to get a gif of what this looks like.

We've been talking about removing the splash screen for some time (https://github.com/getodk/collect/issues/254) and plan to do so within the next year. If our current situation looks really bad on Android 12, we might accelerate that timeline a bit.

**Comment by grzesiek2010** [comment]
With the current implementation if we bump API version to 31 it looks like:
| Our Splash screen enabled  | Our Splash screen disabled |
| ------------- | ------------- |
| ![OurSplashScreenEnabled](https://user-images.githubusercontent.com/3276264/144206144-86ff2217-7b05-43a0-9d6a-47bfcb03b6b5.gif)  | ![OurSplashScreenDisabled](https://user-images.githubusercontent.com/3276264/144206149-b908b63c-e3b8-452f-ba35-a2fce43fcfa2.gif)  |

as you can see the new [Splash screen](https://developer.android.com/guide/topics/ui/splash-screen) provided by Android is not displayed at all so it doesn't look bad (no doubled screens).

It is not displayed because our `SplashScreenActivity` uses `android:theme="@style/Theme.Transparent"` (specified in the manifest file which has `<item name="android:windowIsFloating">true</item>`). If I remove it then we have doubled splash screens:

![RemovedTransparentTheme](https://user-images.githubusercontent.com/3276264/144206790-8ad02e51-5a95-4115-8830-18e801ce2a3d.gif)

Fortunately at least in API 31 it is somehow handled and it's not a big problem for us but we can't be sure how it is going to work in future APIs so sooner or later we need to do something. We can't disable the new splash screen and that trick with `<item name="android:windowIsFloating">true</item>` is not something described in the documentation so it might just not work well in API 32.

I've never liked a lot our Splash screen because I have always struggled to understand why we can specify custom logos in the app but not the displayed app name for example so I won't be against removing it. 

There is nothing we have to do in the current release cycle so I'm going to remove the issue from the milestone. Feel free to add it back if I missed something @lognaturel @seadowg @yanokwa and also please share your thoughts.

**Comment by seadowg** [comment]
@grzesiek2010 thanks for the write up! I reckon we should phase a removal of our splash screen based on this:

1. #254 (remove the option to show the default splash screen) as part of 2022.1
1. Announce on the forum that the ability to add a custom splash screen will be removed in 2022.2 (and a note to Collect settings)
1. Remove the custom splash screen entirely as part of 2022.2 (enabling the default Android one)
1. Use the Splash Screen API to keep the splash screen up until we've finished app initialization (https://developer.android.com/guide/topics/ui/splash-screen#suspend-drawing)

I'm assuming as part of this we still get the new Android 12 Splash Screen on Android 12 without bumping our target API (without the transparent activity). Thoughts?

**Comment by grzesiek2010** [comment]
Why do you want to remove the option from settings now in 2022.1 and not to do everything together in 2022.2?

**Comment by seadowg** [comment]
> Why do you want to remove the option from settings now in 2022.1 and not to do everything together in 2022.2?

My thinking was just to kill the "Splash Screen" setting as early as possible to stop people using it or getting used to it. As far as I can see it'll be pretty easy to remove, and I doubt anyone is "relying" on it so need to announce it. That said, it does seem easier for us to remove the whole thing in one go as you suggest, so I think we can just do that. I'll update #254 (and move it out of the milestone.
