### ISSUE TITLE
Unable to save form filled through shortcut when other project selected on Collect

### ISSUE THREAD

**Issue by kkrawczyk123** [getodk/collect#4668]
#### Software and hardware versions 
Collect v2021.2 Beta 2, Android v all device used...

#### Problem description
After creating form shortcut from project 1 I am able to fill and save the form. After changing project to another on Collect I am able to use shortcut, fill the form but I am unable to save the finalized form. Toast with error message displays:
![Screenshot (Jul 2, 2021 1_21_44 PM)](https://user-images.githubusercontent.com/33342488/124278643-c9840c00-db46-11eb-8c4e-1ef0cc77ac94.png)

#### Steps to reproduce the problem
1. Create form shortcut
2. Change project in Collect
3. Try to fill and save form through created shortcut

#### Expected behavior
Created shortcuts should work whatever project you have selected.

**Comment by seadowg** [comment]
Fixing this in a way that doesn't make our form load/save code worse will be pretty time-consuming (and also most likely quite risky). Instead, we're going to stop shortcuts from working regardless of project. The behaviour will be:

* Old shortcuts (made before v2021.2) opened when the current project is the first project will work
* Old shortcuts opened when the current project is **NOT** the first project will show a warning and then form entry will close
* Old shortcuts (made with v2021.2) opened when the form is in the current project will work
* New shortcuts opened when the form is **NOT** in the current project will show a warning and then form entry will close

I'll work on that as the fix for this issue, assuming we agree @lognaturel.

Talking about it with @lognaturel it seems like a way to deal with this kind of situation in the future (assuming people ask for more shortcut/project support) would be to have shortcuts switch projects (to the form's project) and then back again once form entry is complete. It would be great for form entry to work for any form in any project, but the current structure will make that a big job to implement.
