### ISSUE TITLE
1 security vendor flagged this file as malicious

### ISSUE THREAD

**Issue by masdar80** [getodk/collect#4680]
#### Software and hardware versions 
Collect v1.x.x, Android vx.x.x, device used...

#### Other information 
Things you tried, stack traces, related issues, suggestions on how to fix it...

i built an apk from the last version
and i sanned it on https://www.virustotal.com/
why it has thiss security issue?
Android.HiddenAds.576.origin
![image](https://user-images.githubusercontent.com/53126503/124890833-1a7d7f80-dfe1-11eb-8cd4-05b5f3b39528.png)

**Comment by seadowg** [comment]
Out of interest, I tried scanning the latest beta build using Virus Total and didn't find any problems: https://www.virustotal.com/gui/file/7b49fde429a2a979766899e0813bcd6a18f1d2045ee435cffa085ff82faebc1c/detection. I'm not sure how you ended up with a flagged build, especially since I have no idea in what way you might have modified it.

It could be that there is some heuristic on "DrWeb" that flags debug builds however, which no one (other than developers) should really be installing on their device anyway.

I'll close this for the moment, but please reopen/update if you find any release builds of Collect are flagged in any way.

**Comment by masdar80** [comment]
i modified absolutely nothing just clone then gradle sync then build apk.
the same i tried with kobo odk version and i got the same result on virustotal.
is there anything i must take care of befor i build apk???

**Comment by seadowg** [comment]
It sounds like it might just be a problem with debug builds getting flagged by that particular scanner. Are you worried that Collect might include some ad/spyware? If so, I think scanning signed builds intended for release makes more sense. Also, the code is available to audit here in this repo.

**Comment by masdar80** [comment]
i am sure that Collect doesn't include any ad/spyware , i try to understand what is going on with my build,
at first i built apk after few modifications "nothing in the functionality" then i scanned it , i thought that maybe my changes cause that adware flag.
so i tried to build it as i got it from github, and i got the same result.
i am pretty sure that DrWeb gets confused with something  related to the debug build.
