### ISSUE TITLE
Project delete does not fully clear state

### ISSUE THREAD

**Issue by lognaturel** [getodk/collect#4710]
- If the last project is deleted, the meta setting for current project id is still set. The implication is that getting the current project results in a different exception which is not the end of the world. I ran into this working on #4707 but I don't really know how important it is.

- There seems to be some settings retained. I don't yet have exact repro steps but I did something like create a demo project from the special link from the first launch screen, reconfigure that project, delete that project, then manually add the demo project URL and ended up with the reconfigured settings.

**Comment by lognaturel** [comment]
@grzesiek2010 I see you grabbed this one -- thanks! Please note I just updated the description. The second point seems possibly more concerning though maybe it only affects a pretty unlikely scenario, I'm not sure yet. I think the thing to do is explore this space a bit and think through whether there are any problems that would actually affect users.

**Comment by grzesiek2010** [comment]
Yeah I claimed it but now I see you didn't add it to v2021.2 does that mean it's less important?

**Comment by lognaturel** [comment]
I didn’t have time to dig in so I’m not sure. I think we should definitely do a sanity check before release.

The first point I can’t actually think of a user-facing problem from. The second seems worth exploring some more.

**Comment by grzesiek2010** [comment]
Yes we don't clear settings (general/admin) during removing a project so if we remove a project with id 1234 and then create a new one with the same id those old setting will be used. Of course in case of projects that we generate manually or using qr code it's very unlikely to end up having the same id for a new project because we generate it randomly BUT the demo project has always `DEMO` id and here it's very easy to reproduce.

I think it's a small bug but still it's something we should handle so I'm going to fix it.

To reproduced the issue you have to:
- install a fresh version of the app and choose 'Try a demo'
- change some settings
- delete the project and choose 'Try a demo' again
