### ISSUE TITLE
User is able to edit form when editing is disabled if user opens MapActivity view

### ISSUE THREAD

**Issue by mmarciniak90** [getodk/collect#4722]
#### Software and hardware versions 
Collect v2021.5

#### Problem description
User is able to edit form when editing is disabled if user opens MapActivity view

#### Steps to reproduce the problem
1. `Edit Saved Form` is unselected from Admin Settings
2. User opens new MapActivity
3. User sees marker for each form instance
4. User clicks on some marker
5. User is moved to hierarchy view
6. User IS ABLE to open question and EDIT it

---

1. `Moving backward` is unselected from the Admin Settings
2. User opens new MapActivity
3. User sees marker for each form instance
4. User clicks on some marker
5. User is moved to hierarchy view
6. User IS ABLE to open question and EDIT it

#### Expected behavior
User is not able to open question and edit it

**Comment by lognaturel** [comment]
This isn't related to the map activity -- View Sent Form now allows edits as well. I think an intent extra to `FormEntryActivity` got lost.

Update: first bad commit was d461b42a0. The problem is that previously, the `formmode` extra was used to differentiate between view and edit. That got lost when the proxy activity was introduced.
