### ISSUE TITLE
"Fast external itemsets" don't work after upgrade

### ISSUE THREAD

**Issue by lognaturel** [getodk/collect#4767]
#### Software and hardware versions 
Collect v2021.2

#### Problem description
https://forum.getodk.org/t/problem-on-external-choices-after-application-update/34546

#### Steps to reproduce the problem
1. Download a form with a "fast external itemset" in a prior version
2. Upgrade to v2021.2

#### Expected behavior
Choices are visible.

#### Other information 
This is some kind of path issue. If we'd caught this before release, the answer might have been to remove and rebuild like we did with the form cache. But now that the release has been out for a few days, I think we should consider something like try rebuilding the table if the path is not found.

**Comment by grzesiek2010** [comment]
Fast external itemsets are based on external csv files. For such a file we build a table in itemsets.db which look like:
![Screenshot from 2021-08-02 10-30-08](https://user-images.githubusercontent.com/3276264/127832253-e20abc84-3e89-4fec-9209-a2680f41fe52.png)

its name is generated automatically when the data is imported to the database (when we open such a form for the first time) and it is `itemset_+md5(itemsets.csv.getAbsoluePath())`. If a user opens such a form in v1.30.1 (and older versions) the path used to generate that md5 hash was like:
`/storage/emulated/0/Android/data/org.odk.collect.android/files/forms/Test-media/itemsets.csv`
but now it's
`/storage/emulated/0/Android/data/org.odk.collect.android/files/projects/b17da803-68b1-424b-b2c5-3f68de97f8a1/forms/Test-media/itemsets.csv`

so now when we try to read our data we try to find a table that does not exist because the hash is different.

I think the easiest and safest solution for now would be bumping the database version so that `onUpgrade()` is called which clears the database so that csv files are loaded again https://github.com/getodk/collect/blob/master/collect_app/src/main/java/org/odk/collect/android/fastexternalitemset/ItemsetDbAdapter.java#L57

a bit better long term solution would be to check if the table we try to read from exist during form loading. If not the files should be loaded again. This would be better but also it will require more changes and testing so I would rather do that later and for now just add that small fix to help our users ASAP.
