### ISSUE TITLE
Improve QR code scanning/project creation code flow

### ISSUE THREAD

**Issue by seadowg** [getodk/collect#4778]
We should timebox this to a 3/4 days at most but we've identified that it'd be nice to give this code some love now we've got the projects features out. Things to improve here would be:

- [x] Remove `ProjectImporter` - it's not clear that it has any responsibilities that don't fit into the `ProjectCreator`
- [ ] Deduplicate code that handles scanning QR codes with camera in `QRCodeProjectCreatorDialog` and`QRCodeScannerFragment` (this might involve making the permission/scanning flows consistent)
- [ ] Deduplicate code that handles loading QR codes from disk in `QRCodeProjectCreatorDialog` and`QRCodeScannerFragment` (this might involve making the permission/scanning flows consistent)
- [ ] Revise how QR code scanning/loading flows are tested and if we could have faster/less tests

**Comment by seadowg** [comment]
@grzesiek2010 we should discuss this

**Comment by grzesiek2010** [comment]
> Remove ProjectImporter - it's not clear that it has any responsibilities that don't fit into the ProjectCreator

I agree.

> Deduplicate code that handles scanning QR codes with camera in QRCodeProjectCreatorDialog andQRCodeScannerFragment (this might involve making the permission/scanning flows consistent)

Probably in `QRCodeProjectCreatorDialog` we should embed another fragment (that inherits from `BarCodeScannerFragment`) instead of having `com.journeyapps.barcodescanner.DecoratedBarcodeView` and handling scanning there so that the code responsible for scanning is shared.
![Screenshot_1629405471](https://user-images.githubusercontent.com/3276264/130141003-da17d95a-c36f-4fbd-aae0-ef3a335d3d70.png)

> Deduplicate code that handles loading QR codes from disk in QRCodeProjectCreatorDialog and QRCodeScannerFragment (this might involve making the permission/scanning flows consistent)

The only difference between loading an image with QR code in `QRCodeProjectCreatorDialog` and `QRCodeTabsActivity` is that
in the first class after reading settings we create a new project and in the second class we just load that new settings to reconfigure the current project. That means the first part which is about reading settings and handling all the possible exceptions is the same. It should be possible to have one class where that code is stored (maybe reuse `QRCodeActivityResultDelegate`) and just have a callback/pass function to handle that last step which is creating a new project vs reconfiguring the current project.

> Revise how QR code scanning/loading flows are tested and if we could have faster/less tests

Always true.

**Comment by seadowg** [comment]
We haven't touched this code for a while so I think it's best to refactor when we feel the pain - that could push us in a different direction from what we've laid out here.
