### ISSUE TITLE
Update play-services gradle dependency

### ISSUE THREAD

**Issue by shobhitagarwal1612** [getodk/collect#478]
#### Problem description
Play Services gradle dependency in `build.gradle` can be updated from `v10.0.1` to `v10.2`.
Since the `minSdkVersion` is now `16` and `v10.2.x` requires `API 14`, so it won't introduce any support issues.  

Google has added a new [SnapShotAPI](https://developers.google.com/android/reference/com/google/android/gms/awareness/SnapshotApi#getTimeIntervals(com.google.android.gms.common.api.GoogleApiClient)).
Using this we can get time intervals for current location and time. Since the app focuses on collecting data and this API can provide more contextual data.
As examples, some attributes are: 

> TIME_INTERVAL_MORNING, TIME_INTERVAL_AFTERNOON, TIME_INTERVAL_EVENING, TIME_INTERVAL_NIGHT, TIME_INTERVAL_WEEKDAY, TIME_INTERVAL_WEEKEND, TIME_INTERVAL_HOLIDAY.

[Google Play services 10.2 release](https://developers.google.com/android/guides/releases)

**Comment by lognaturel** [comment]
@shobhitagarwal1612 Thanks for describing in detail why this would be helpful and investigating potential version conflicts!

This version upgrade will require people who are currently running Google Play Services 10.0.1 to upgrade, right? It's a pretty big download so I think we should delay this as much as possible.

**Comment by lognaturel** [comment]
I accidentally came across an example of what happens when there's a Google Play Services version mismatch in #488. It looks like we don't do any version checking so the app will just crash on a version mismatch. 😳

In preparation for this eventual upgrade, it would be very useful to identify every place where Google Play Services needs to be installed and have a certain version and add a check with a user warning.

**Comment by shobhitagarwal1612** [comment]
@lognaturel Yes I think we should check whether google play services is installed or not before accessing any related feature (Google maps, Google Sheets or Google Drive API)

**Comment by shobhitagarwal1612** [comment]
Should I file a separate issue regarding the same?

**Comment by lognaturel** [comment]
That would be great. I encourage you to tag @Dvik and coordinate with him as I think he is interested in handling part of this as discussed in #312.

**Comment by lognaturel** [comment]
I propose we keep this issue open and push it out to a few releases from now. Sound ok?

**Comment by shobhitagarwal1612** [comment]
@lognaturel Sounds great :+1:

**Comment by lognaturel** [comment]
@shobhitagarwal1612 A lot has happened since this issue was filed, right?! And in particular, Google has changed the way that they version Play Services so this is no longer relevant. 🎉 Instead of a monolithic lib, we have many small ones that update at their own pace.

More at https://github.com/opendatakit/collect/pull/3329#issuecomment-529621560.
