### ISSUE TITLE
Different behavior using choice_filter with normal choices and choices from an external csv file

### ISSUE THREAD

**Issue by grzesiek2010** [getodk/collect#4795]
#### Problem description
I noticed different behavior using `choice_filter` with normal choices and choices from an external csv file.
I have a form that contains two select questions where the list of choices in the second question should contain only those selected in the first one.
It works well if I use normal choices but not with external choices.

#### Steps to reproduce the problem
Test the attached form: 
[choiceFilterTest.zip](https://github.com/getodk/collect/files/6992781/choiceFilterTest.zip)

#### Expected behavior
Filtering should work in the same way

**Comment by dimwight** [comment]
Hi @grzesiek2010, do you have an XLS source you could upload? Being able to quickly tweak the form makes it easier to explore an issue such as this.

**Comment by grzesiek2010** [comment]
Yeah I think it was this:
[choiceFilterTest.xlsx](https://github.com/getodk/collect/files/7017647/choiceFilterTest.xlsx)

**Comment by dimwight** [comment]
The key point seems to be that in `ItemsetDao`, `getSelectionStringAndPopulateArguments` expects `queryString` to contain '=', as do queries in _[selectOneExternal.xml](https://github.com/getodk/collect/files/7025462/selectOneExternal.zip)_ for instance.

Missing the '=', it in effect ignores the query so no filter is applied. 

I don't have the expertise to fill such a gap, unless we think it's worth adding a Timber message flagging it.

**Comment by lognaturel** [comment]
Let’s make sure we’re really explicit about which external csv feature is used when filing such issues — there are three with different expected behavior!

As @dimwight notes, “fast external itemsets” don’t use choice filters in a generic way. There’s no expectation that they work for anything other than equality expressions and I don’t think we should change that. 

The documented, standards-compliant way to use an external csv is with external secondary instances or select_one_from_file in XLSForm. That uses the same choice filter mechanism as internal selects so there should be no difference in behavior. 

I believe this issue can be closed. Thanks for asking good questions and investigating, @dimwight!

Alternately we could consider showing a dialog as a courtesy if a user does try to use an unsupported expression. This whole feature is not part of the official ODK docs so I think we should only do this if it’s quite straightforward.

**Comment by dimwight** [comment]
Thanks @lognaturel for these encouraging words and for clarifying the underlying issue. In the example from @grzesiek2010 the XLS tries to use `select_one_external` which of course calls up a fast external itemset. 

Perhaps a user tripped up here might be glad of an informative message about this gap in a largely undocumented feature. I'd be happy to have a go at this if someone can point me at a suitable model to adapt.

**Comment by grzesiek2010** [comment]
I thought that if it's possible to use the equality expressions I should be able to use other expressions as well.

> There’s no expectation that they work for anything other than equality expressions and I don’t think we should change that.

Ok so I'm closing the issue.

The amount of options and differences between them when it comes to selects is the biggest source of confusion for me in the whole toolset...
