### ISSUE TITLE
Multiple clicks on Settings open up unexpected views

### ISSUE THREAD

**Issue by mmarciniak90** [getodk/collect#4798]
#### Software and hardware versions 
Collect v2021.2.x
Android 5.1, 8.1, 9.0, 10.0

#### Problem description
Multiple clicks on `Settings` open up unexpected views

#### Steps to reproduce the problem
1. User opens a dialog with a list of added projects
2. User clicks multiple times on `Settings`
3. User is able to open view from the Main menu and goes to some view in settings

#### Expected behavior
User is not able to click multiple times on `Settings`

#### Other information 
![ezgif com-video-to-gif](https://user-images.githubusercontent.com/3907554/129745052-b25a76f3-490b-401d-89ea-48b93b1d4c00.gif)

**Comment by Unreal-Dreams** [comment]
@mmarciniak90  I would love to make this as my first issue, can I take this up?

I have identified the problem here. I think this issue can basically be resolved by disabling the button with setEnabled(false) until it is safe for the user to click it again or we can also save the last time the button was clicked and use that to resolve the issue.

**Comment by grzesiek2010** [comment]
@Unreal-Dreams 
You can work on this issue but you should use the same solution like we do in case of other clickable elements: `MultiClickGuard`/`MultiClickSafeButton`

**Comment by Unreal-Dreams** [comment]
Sure @grzesiek2010 I will keep that in mind.

**Comment by Unreal-Dreams** [comment]
@getodk-bot claim

**Comment by Unreal-Dreams** [comment]
@grzesiek2010 Can you please review my PR?
