### ISSUE TITLE
ReadOnly questions should not be required

### ISSUE THREAD

**Issue by grzesiek2010** [getodk/collect#4816]
#### Problem description
It is possible to make a question `read-only` and `required`. Everything is fine as along as there is also a `default` answer, otherwise it blocks filling a form.
The issue takes place if we make a `note` (which is `read-only` by default) `required` (see https://forum.getodk.org/t/form-unable-to-finalize-due-to-required-note-question-type/34780)

#### Steps to reproduce the problem
[ReadOnlyRequired.xlsx](https://github.com/getodk/collect/files/7065637/ReadOnlyRequired.xlsx)

#### Expected behavior
If a question is `read-only`, required should be ignored.

**Comment by grzesiek2010** [comment]
I'm adding `needs discussion` label because maybe this is something we should just handle during form conversion.

**Comment by lognaturel** [comment]
> we should just handle during form conversion.

I agree with this. `pyxform` could produce an error if a note field is marked as required. That would be a good issue to file. I think that's about the extent of what we can detect since both `required` and `readonly` are dynamic. That means there could be a perfectly valid combination of expressions there. I don't think Collect/clients should try to decide when to ignore the value of the required attribute.

**Comment by janna-rous** [comment]
Hi there, I've never before commented on an ODK Github thread, as I can contribute very little (eg, nothing) in terms of coding. But I did want to just say that this "required note" is something I exploit when deploying forms in the field. This is how I use it:

For example, if I ask "how many people in the training" and the response is 10, then I ask... 

How many men, and how many women, and how many unspecified gender, for example. Say they respond 4 men, 4 women, and 0 unspecified. 

Then I do a "calculate" to see if their breakdown equals the total number of people entered.

If there's a mismatch between the "total" (eg, 10) and the gender - disaggregated data (eg, 4+4+0 =8),then I display a "note" that says "you made an error somewhere, go back and fix it". I make the note "required" so they must correct the answer before submission. This helps me keep my data clean. Because the note is only relevant when there's a mismatch, it doesn't affect forms where the data makes sense. 

There are other ways to help people catch their mistakes, through constraints and constraint messages, however the reason I like using notes is that it allows me to show them what they've entered so far (using ${name} in the label) so they can easily see where they've made the mistake.  I actually use this method quite regularly. 

Thought I'd add it to the thread so that those of us who exploit this feature to catch errors in data entry might have a way to still prevent people from skipping required notes. Or maybe I learn a new or better way to do the same thing :) 

Hope this helps the discussion!

Janna

**Comment by grzesiek2010** [comment]
Thanks for sharing your use case @janna-rous that was helpful.
Now I understand that many users might do something similar and any change in this area could be dangerous because the risk could outweigh the benefits.

**Comment by lognaturel** [comment]
Thanks for sharing, @janna-rous! I think that’s a very good strategy. I’ve typically done this with a constraint on a note rather than a required but it’s true that either works at the moment. I think using a constraint that matches the relevance condition slightly better captures the semantics.
