### ISSUE TITLE
Update Mapbox SDK

### ISSUE THREAD

**Issue by seadowg** [getodk/collect#4893]
The Mapbox SDK has made two major changes in the last few updates:

1. Since 9.3.0, it uses a pre-built binary that's licensed under new Terms of Service ([changelog here](https://github.com/mapbox/mapbox-gl-native-android/releases/tag/android-v9.3.0))
1. Also since 9.3.0, the SDK is hosted in Mapbox's own maven repo which requires authentication via a Mapbox account to download ([docs here](https://docs.mapbox.com/android/maps/guides/install/))

I'll make two assumptions here around our reaction to this: we need to continue to support Mapbox, and we don't want to require contributors (or anyone building Collect) to have their own Mapbox accounts. Given that, before we update, we'll need to:

- [x] Confirm it's legally safe to use new versions of the SDK in the released versions of our app
- [ ] (At least) Allow Collect's `debug` build type to work without the Mapbox SDK dependency
- [ ] Add a way to do development with Mapbox (a build type/product flavour/build flag etc)

**Comment by seadowg** [comment]
@grzesiek2010 pointed this out to me, and it'd be good to get input from @yanokwa on this one. I think it'd be good to first discuss whether my assumptions are correct.

**Comment by yanokwa** [comment]
Your assumptions are correct. The change log says "The license of the Maps SDK for Android remains BSD-2" so I think we are fine as far as legality.

As to reaching out to Mapbox, I'd rather we poke around first to see if we get stuck, then have specific questions to bring to them.

I wonder how this will play with [packaging tricks](https://github.com/getodk/collect/blob/master/collect_app/build.gradle#L178) to keep Collect installable on all devices.

**Comment by seadowg** [comment]
> Your assumptions are correct. The change log says "The license of the Maps SDK for Android remains BSD-2" so I think we are fine as far as legality.

I've had a quick look over the [Terms of Service](https://www.mapbox.com/legal/tos) and nothing screams dangerous to me as well.

> I wonder how this will play with packaging tricks to keep Collect installable on all devices.

Yeah definitely wondering about that. I think we're going to need to pull all the Mapbox stuff out to a separate module and then reference it dynamically. You're right we're probably also going to have to review our `nbistubs` setup.

**Comment by grzesiek2010** [comment]
As I understand the configuration will be similar to google maps. Our users will need to create an account and generate their own key. So by default after cloning our repository both google maps and mapbox won't work am I right?

Do you think it makes sense to reach out to Mapbox and maybe ask if they provide any accounts for open source projects so that maybe with some limitations but something would be displayed (instead of a blank view like in case of google maps)?

Anyway if we want to upgrade mapbox this should happen along with other dependencies at the begging of the next cycle so I think we can remove the issue from the current milestone.

**Comment by yanokwa** [comment]
I think we should do the same thing as we do on Google Maps. We say there needs to be an API key and link to the Mapbox site. In general, I don't think we should take on tasks that are a fork's responsibilities unless they somehow benefit core.

**Comment by seadowg** [comment]
> As I understand the configuration will be similar to google maps.

Yeah exactly. It's just annoyingly more complicated though where the actually accessing the SDK itself needs the account, so we need to do the extra work to get the build to work without it. 

> In general, I don't think we should take on tasks that are a fork's responsibilities unless they somehow benefit core.

Agreed in principle. As I mention above, the app won't build without an API key as it's needed to pull the dependency down. I don't think we want to enforce contributors (our even ourselves) to have an API key setup for local development.

**Comment by yanokwa** [comment]
Not great that the app won't build without a key. No way to ifdef it or something? I'll reach out to our colleagues at Mapbox to see what they suggest.

**Comment by seadowg** [comment]
@yanokwa oh to be clear my plan is that we can make the app build without Mapbox **unless** a key is supplied. I just mean that wanted to make sure it was understood that the API key was adding a larger burden than the Google one. It would be great if they have a way of making this work so we don't have to work out the Gradle foo ourselves!

**Comment by yanokwa** [comment]
Word from Mapbox is there is no easy way to get a generic token, so let's proceed with the building without Mapbox unless a token is supplied.

**Comment by grzesiek2010** [comment]
Ok so as I understand we would need to create a special [flavor](https://developer.android.com/studio/build/build-variants#product-flavors) so that mapbox does not exist in the official releases. I don't love this option for me it's like the last resort. It would be an additional flavor that we would need to maintain and test but it wouldn't be a part of our releases. If I'm right it would be also not possible to build such flavor on CircleCI because building would require adding a valid token that shouldn't be shared publicly.
I'm wondering... Is mapbox really important for our users?
- if it is maybe let's keep the old version that works for now (we don't have any big problems with the current version) 
- if it's not maybe it doesn't make sense to put that much effort to keep it

What do you think @lognaturel @yanokwa @seadowg

**Comment by seadowg** [comment]
> Ok so as I understand we would need to create a special [flavor](https://developer.android.com/studio/build/build-variants#product-flavors) so that mapbox does not exist in the official releases.

I'm not sure if we'd use a flavour, build type or a gradle property, but the goal would be to include Mapbox in the released versions but not debug: "Allow Collect's debug build type to work without the Mapbox SDK dependency". In other words we want is so that I can do a fresh checkout and a `./gradlew assembleDebug` without needing to deal with a Mapbox API key.

I **think** the best way to do this is to add a product flavour (as you suggest) like `mapbox`, switch the Mapbox dependencies to being `mapboxImplementation` rather than `implementation` and read the Mapbox API key as a project property and only configure the repository if it's present. In that world I think we'd be able to build any of our build types with mapbox by doing something like `./gradlew assembleMapbox<build type> -PmapboxKey=<mapbox key>`.

> I'm wondering... Is mapbox really important for our users?

It's a good question. My assumption is that we can't drop it, but it does feel like it's consistently higher effort to support than Google Maps.

**Comment by grzesiek2010** [comment]
> I'm not sure if we'd use a flavour, build type or a gradle property, but the goal would be to include Mapbox in the released versions but not debug

I'm confused. How do you want to include mapbox in the released versions if we need a token to make it work. I rather thought the other way around that you wanted to keep mapbox in our codebase but exclude it from release versions so that people who build their projects based on our app could still use the code (they would just need to add their own token).

**Comment by lognaturel** [comment]
> My assumption is that we can't drop it

Agreed at this point. It does provide access to really nice basemaps and some folks do make use of the pbx mbtiles support as far as I know.

Meant to add this but apparently never did. @danbjoseph suggested we consider https://maplibre.org/. They forked right before the Mapbox changes went into place. I assume they'll diverge sooner than later but it is more spiritually aligned with what we're trying to do.

The risk I see with Maplibre is that they appear to have more commitment to the js variant. The native stuff might be a lot for them to maintain and I wouldn't be surprised if it stopped being updated.

**Comment by lognaturel** [comment]
https://github.com/mapbox/mapbox-events-android/issues/563#issuecomment-1085688127 for the way folks from Mapbox think about this.
