### ISSUE TITLE
Demo project is duplicated after updating app

### ISSUE THREAD

**Issue by kkrawczyk123** [getodk/collect#4927]
#### Software and hardware versions 
Collect v2021.3 Android all device used...

#### Problem description
When testing Collect's update I have noticed that demo project is duplicated when it's used before updating app.
![ezgif com-gif-maker (14)](https://user-images.githubusercontent.com/33342488/145028829-7828144b-7755-4f24-ab56-27551797efa1.gif)

#### Steps to reproduce the problem
1. Install Collect ex. v2021.3.1
2. Use demo project
3. Update Collect to v2021.3.2
4. See that you have 2 demo projects

#### Expected behavior
Projects should not be duplicated when updating the app. 

#### Other information 
I have tried also app update when using other project - demo project is also created but it's not a duplicate then.

**Comment by seadowg** [comment]
I think I can see what's going on here. Basically if you install a version of Collect with Projects (v2021.2+) and then upgrade, Collect will attempt to create a project out of the "existing one" (one that would exist in pre v2021.2) and because there won't be one, we end up creating a "Demo project" (this is to do with some small details in `ProjectDetailsCreator`). 

I'm going to confirm that I'm definitely right about all this, but it looks like we probably need to make our upgrade code smarter to avoid this - we not only want to just run the existing project migration once, but we also don't want to run it when upgrading from versions that don't need to do it.

**Comment by seadowg** [comment]
Ok yeah it really looks like the above is all true. Annoyingly I don't think there is a way for us to work out which project has been added by this problem (correct if I'm wrong here @grzesiek2010), so it's probably best we announce this on the forum and/or on social media when we have a fix.

I'll start working on a hot fix now.
