### ISSUE TITLE
If QR code scanning leads to run time exception, new project with Demo settings and no project name is created

### ISSUE THREAD

**Issue by lognaturel** [getodk/collect#5049]
#### Software and hardware versions 
`master`

#### Problem description
If QR code fails validation, new project with Demo settings and no project name is created

#### Steps to reproduce the problem
1. Make a release build of `master`
2. Try to scan a QR code, Collect crashes because of proguard issue
3. See that weird project is created

#### Expected behavior
Runtime exceptions are caught and handled. This particular issue we'll deal with but it seems like there are likely to be other possible runtime exceptions because of the camera doing something weird.

**Comment by seadowg** [comment]
I do think it's important to highlight that the issue we ran into occurred every time and was faulty code so isn't something we need to protect ourselves from in a working runtime version of the app. In fact, it can make it worse for us: if we had the level of defensiveness in the code that we're suggesting here then we would have ended up with a silent fail rather than a crash. I'm all for auditing the error handling in the import code (especially the QR scanning as you point out) but I don't think we want blank "catch alls" around this (or really any) part of the code.

It might be that what we want here is to make the way projects are created more "transactional"/"atomic" and remove any risk that projects get "half way" through creation. For me, that's a nicer route to get to a place that satisfies the title of the issue. I just don't agree with the suggested implementation laid out in the "Expected behaviour" section.

**Comment by lognaturel** [comment]
>  if we had the level of defensiveness in the code that we're suggesting here

I imagined the user getting a message like "QR code can't be scanned, use manual entry". Of course, I realize now that won't help with Central. Still, a catch-all message with instructions on what to do (e.g. email support@getodk.org) feels much better than a hard crash. If there is no reasonable way to bubble up a message, though, I suppose a hard crash is better than an entirely silent fail.
