### ISSUE TITLE
Crash when scanning a QR code on release build

### ISSUE THREAD

**Issue by lognaturel** [getodk/collect#5052]
#### Software and hardware versions 
Collect v2022.2-beta.0

#### Problem description
Scanning a QR code using a debug build works but with a release build a runtime exception is thrown: `class "com.github.fge.jsonschema.keyword.validator.common.AdditionalItemsValidator" has no appropriate constructor (keyword "additionalItems"; expected a constructor with a JsonNode as an argument)`

#### Steps to reproduce the problem
Scan any settings QR code with a release build.

#### Expected behavior
Scanning QR codes works with a release build.

#### Other information 
I addressed this for the beta by adding the following to the `collect_app` proguard rules:
`-keep class com.github.fge.jsonschema.keyword.validator.** { *; }`

It feels like this should be handled within the settings module, though.

Note: keeping `AdditionalItemsValidator` is not enough -- there's at least one other class that gets pruned.

**Comment by seadowg** [comment]
My assumption is that you'd be able to add your rule to `consumer-rules.pro` and because that's set as the `consumerProguardFiles` for the module `collect_app` would then use it (add it to it's own rules). However, [the Android Library docs](https://developer.android.com/studio/projects/android-library#Considerations) (in "A library module may include its own ProGuard configuration file") seem to suggest that you may just need to add rules to your app module for multi-module builds as no AAR is produced (we can experiment with this).
