### ISSUE TITLE
Unable to scan QR code with valid settings with old Server "Other"

### ISSUE THREAD

**Issue by kkrawczyk123** [getodk/collect#5089]
#### Software and hardware versions 
Collect v2022.2 Beta 2, Android all, device used...

#### Problem description
I am unable to scan QR code (add project and update settings) that contains valid settings with old selection Server Other with kobo server. I am having toast informing about qr code not containing valid settings. I know it's an old configuration but it works well on 2022.1.2 and server type is set to type ODK. 

Example of QR code:
![collect-settings](https://user-images.githubusercontent.com/33342488/162181317-5e6d29eb-67e4-49b8-ba38-1d665e95a9b5.png)

#### Steps to reproduce the problem
1. Scan attached qr code on add new project or reconfigure with qr code already existing project

#### Expected behavior
User should be able to scan QR code as it contains valid settings

#### Other information 
Things you tried, stack traces, related issues, suggestions on how to fix it...

**Comment by grzesiek2010** [comment]
The format of this old qr code is:
```
{
   "general":{
      "password":"koboCollect",
      "server_url":"https:\/\/kc.humanitarianresponse.info",
      "protocol":"other_protocol",
      "username":"kkrawczyk"
   },
   "admin":{
      
   }
}
```

but our new format should be:
```
{
  "$schema": "https://json-schema.org/draft/2019-09/schema",
  "$id": "https://getodk.org/client-settings.schema.json",
  "title": "ODK Client Settings",
  "type": "object",
  "properties": {
    "project": {
      "type": "object",
      "properties": {
        "name": {
          "type": "string"
        },
        "icon": {
          "type": "string"
        },
        "color": {
          "type": "string"
        }
      }
    },
    "general": {
      "type": "object",
      "properties": {
        "protocol": {
          "type": "string",
          "enum": [
            "odk_default",
            "google_sheets"
          ]
        },
        "server_url": {
          "type": "string"
        },
        "username": {
          "type": "string"
        },
        "password": {
          "type": "string"
        },
        "selected_google_account": {
          "type": "string"
        },
        "google_sheets_url": {
          "type": "string"
        },
        "appTheme": {
          "type": "string",
          "enum": [
            "system",
            "light_theme",
            "dark_theme"
          ]
        },
        "app_language": {
          "type": "string"
        },
        "font_size": {
          "type": "string",
          "enum": [
            "13",
            "17",
            "21",
            "25",
            "29"
          ]
        },
        "navigation": {
          "type": "string",
          "enum": [
            "swipe",
            "buttons",
            "swipe_buttons"
          ]
        },
        "showSplash": {
          "type": "boolean"
        },
        "splashPath": {
          "type": "string"
        },
        "basemap_source": {
          "type": "string",
          "enum": [
            "google",
            "mapbox",
            "osm",
            "usgs",
            "stamen",
            "carto"
          ]
        },
        "google_map_style": {
          "type": "string",
          "enum": [
            "1",
            "2",
            "3",
            "4"
          ]
        },
        "mapbox_map_style": {
          "type": "string",
          "enum": [
            "mapbox://styles/mapbox/light-v10",
            "mapbox://styles/mapbox/dark-v10",
            "mapbox://styles/mapbox/satellite-v9",
            "mapbox://styles/mapbox/satellite-streets-v11",
            "mapbox://styles/mapbox/streets-v11",
            "mapbox://styles/mapbox/outdoors-v11"
          ]
        },
        "usgs_map_style": {
          "type": "string",
          "enum": [
            "topographic",
            "hybrid",
            "satellite"
          ]
        },
        "carto_map_style": {
          "type": "string",
          "enum": [
            "positron",
            "dark_matter"
          ]
        },
        "reference_layer": {
          "type": "string"
        },
        "form_update_mode": {
          "type": "string",
          "enum": [
            "manual",
            "previously_downloaded",
            "match_exactly"
          ]
        },
        "periodic_form_updates_check": {
          "type": "string",
          "enum": [
            "every_fifteen_minutes",
            "every_one_hour",
            "every_six_hours",
            "every_24_hours"
          ]
        },
        "automatic_update": {
          "type": "boolean"
        },
        "hide_old_form_versions": {
          "type": "boolean"
        },
        "autosend": {
          "type": "string",
          "enum": [
            "off",
            "wifi_only",
            "cellular_only",
            "wifi_and_cellular"
          ]
        },
        "delete_send": {
          "type": "boolean"
        },
        "default_completed": {
          "type": "boolean"
        },
        "constraint_behavior": {
          "type": "string",
          "enum": [
            "on_swipe",
            "on_finalize"
          ]
        },
        "high_resolution": {
          "type": "boolean"
        },
        "image_size": {
          "type": "string",
          "enum": [
            "original_image_size",
            "small",
            "very_small",
            "medium",
            "large"
          ]
        },
        "guidance_hint": {
          "type": "string",
          "enum": [
            "no",
            "yes",
            "yes_collapsed"
          ]
        },
        "external_app_recording": {
          "type": "boolean"
        },
        "instance_sync": {
          "type": "boolean"
        },
        "analytics": {
          "type": "boolean"
        },
        "metadata_username": {
          "type": "string"
        },
        "metadata_phonenumber": {
          "type": "string"
        },
        "metadata_email": {
          "type": "string"
        },
        "background_location": {
          "type": "boolean"
        },
        "background_recording": {
          "type": "boolean"
        }
      }
    },
    "admin": {
      "type": "object",
      "properties": {
        "admin_pw": {
          "type": "string"
        },
        "edit_saved": {
          "type": "boolean"
        },
        "send_finalized": {
          "type": "boolean"
        },
        "view_sent": {
          "type": "boolean"
        },
        "get_blank": {
          "type": "boolean"
        },
        "delete_saved": {
          "type": "boolean"
        },
        "change_server": {
          "type": "boolean"
        },
        "change_project_display": {
          "type": "boolean"
        },
        "change_app_theme": {
          "type": "boolean"
        },
        "change_app_language": {
          "type": "boolean"
        },
        "change_font_size": {
          "type": "boolean"
        },
        "change_navigation": {
          "type": "boolean"
        },
        "show_splash_screen": {
          "type": "boolean"
        },
        "maps": {
          "type": "boolean"
        },
        "form_update_mode": {
          "type": "boolean"
        },
        "periodic_form_updates_check": {
          "type": "boolean"
        },
        "automatic_update": {
          "type": "boolean"
        },
        "hide_old_form_versions": {
          "type": "boolean"
        },
        "change_autosend": {
          "type": "boolean"
        },
        "delete_after_send": {
          "type": "boolean"
        },
        "default_to_finalized": {
          "type": "boolean"
        },
        "change_constraint_behavior": {
          "type": "boolean"
        },
        "high_resolution": {
          "type": "boolean"
        },
        "image_size": {
          "type": "boolean"
        },
        "guidance_hint": {
          "type": "boolean"
        },
        "external_app_recording": {
          "type": "boolean"
        },
        "instance_form_sync": {
          "type": "boolean"
        },
        "change_form_metadata": {
          "type": "boolean"
        },
        "analytics": {
          "type": "boolean"
        },
        "moving_backwards": {
          "type": "boolean"
        },
        "access_settings": {
          "type": "boolean"
        },
        "change_language": {
          "type": "boolean"
        },
        "jump_to": {
          "type": "boolean"
        },
        "save_mid": {
          "type": "boolean"
        },
        "save_as": {
          "type": "boolean"
        },
        "mark_as_finalized": {
          "type": "boolean"
        }
      }
    }
  },
  "required": [
    "general",
    "admin"
  ]
}
```

I don't remember any discussion about backwards compatibility so probably we just can ignore it? @lognaturel @seadowg

**Comment by seadowg** [comment]
> but our new format should be:

That's the **schema** (using [JSON Schema](https://json-schema.org/)) for the format we expect rather than the format itself. I think the problem will be that we have an `enum` on `protocol` that doesn't allow for any values other than `odk_default` or `google_sheets`. I'm guessing before we would accept anything and just default to `odk_default` if we didn't recognize the value. As far as I'm aware (jump in here to correct me if not @lognaturel) we definitely want to be backwards compatible so probably just need to remove our `enum` for `protocol`.

**Comment by grzesiek2010** [comment]
Right in this case it's juts because of that `other_protocol` which we no longer support.

> so probably just need to remove our enum for protocol

In the future we might have similar problems with other enums too so probably we should get rid of all of them and use defaults if something we do not support is present.

**Comment by grzesiek2010** [comment]
If we remove enums the problem for this particular case will be solved. The app will save `other_protocol` as protocol first and since this option was removed we have a case for it in `ODKAppSettingsMigrator` and it will be migrated to `odk_default`. Problems might take place when we do not only deal with preferences that contain old keys/values (cases that should be handled in `ODKAppSettingsMigrator`) but with preferences that contain wrong data (in this case for example `anything` for protocol instead of `odk_default`/`google_sheets`.
So for a small fix we can just get rid of those enums but for a long term we need to verify keys where options should have one of particular values and use defaults if the provided value does not belong to that set of accepted values.
What do you think @seadowg @lognaturel

**Comment by lognaturel** [comment]
Chatted briefly with @grzesiek2010 about this. I think the ideal behavior would be that if *any* key fails validation, there's feedback in the UI (e.g. a toast that says "Some keys have invalid values and were set to default: x, y, z") but the values fall back to default and the project is provisioned. I believe this would match prior behavior (but I'm not totally sure).

Ideally we wouldn't need to remove the enum there because it's useful for those who want to produce a QR code. In particular, we want Central to use this schema to build a tool that produces valid QR codes. The enum values would be in e.g. a dropdown.

**Comment by lognaturel** [comment]
@kkrawczyk123, this is a good case to keep around (I assume that's your plan).

**Comment by seadowg** [comment]
> I believe this would match prior behavior (but I'm not totally sure).

I think we'd fall back to defaults, but I don't think we showed a message as far as I can recall. I do think showing the warning would be a nice feature to add at some point though.

> Ideally we wouldn't need to remove the enum there because it's useful for those who want to produce a QR code. In particular, we want Central to use this schema to build a tool that produces valid QR codes. The enum values would be in e.g. a dropdown.

Great point. It might be that a simple solution for this release is to remove all the `enum` blocks and then tackle having them in but defaulting on failure for v2022.3. It feels like that might be a little tricky and we can always treat the addition of `enum` for keys as an iteration on the  spec.

**Comment by grzesiek2010** [comment]
> Ideally we wouldn't need to remove the enum there because it's useful for those who want to produce a QR code.

In https://github.com/getodk/collect/pull/5094 I handle that case with values not included in enums without removing those enums from the scheme. I just ignore that particular type of error.

> I think the ideal behavior would be that if any key fails validation, there's feedback in the UI (e.g. a toast that says "Some keys have invalid values and were set to default: x, y, z")

I agree but at this moment we don't have that functionality to save defaults if the value that we try to save is not supported. In case of the qr code attached above it worked well because the unsupported value was `"protocol":"other_protocol"` which we used to support in the past so we have a migration step for it. The flow is:
1. Save whatever value is provided in this case `other_protocol`
2. Perform migrations (one of the steps is to migrate `other_protocol` to `odk_default` so it works well

but if instead of `other_protocol` we had `anything` that `anything` would be saved to our prefs as it is.

I think what my draft pr contains would be enough to enable supporting old qr codes. Then in next release we can add handling unsupported values by converting them to defaults and displaying that toast.

**Comment by lognaturel** [comment]
> I think what my draft pr contains would be enough to enable supporting old qr codes. Then in next release we can add handling unsupported values by converting them to defaults and displaying that toast.

Agreed, thanks!

**Comment by grzesiek2010** [comment]
Cool I created a separate issue for next steps https://github.com/getodk/collect/issues/5096
