### ISSUE TITLE
Rotating the screen on automatic location recording in Geoshape/Geotrace (with about 30 points) on Mapbox, stops adding points

### ISSUE THREAD

**Issue by dbemke** [getodk/collect#5173]
**Software and hardware versions**

The issue will be visible after merging [#5141](https://github.com/getodk/collect/pull/5141)
Android all versions

**Problem description**

When Mapbox is used as a source of maps in Geoshape and Geotrace and automatic lacation recording is on, after about 30 points being added rotating the screen stops adding the points.

**Steps to reproduce the problem**

    1. Select mapbox in Settings -> Maps 
    2. Download all Widgets form with Geo widgets
    3. Go to Geotrace/ Geoshape widget
    4. Click Start
    5. Choose automatic location recording -> set recording interval to 1 second and accuracy requirement to none
    6. Wait until about 30 points are added
    7. Rotate the screen a few times
       
**Expected behavior**

After rotating the screen, adding points should be still in progress.

**Other information**

Checked on All widgets form. Works well on Google Maps on pr 5141. The unexpected behavior with Mapbox didn’t appear on master.

**Comment by seadowg** [comment]
@dbemke is this a regression? Sounds like it doesn't appear in older (than v2022.3.x) versions.

**Comment by dbemke** [comment]
@seadowg I’ve checked and Android 11 and 8.1 stops adding points after rotating in Collect v2022.3 beta2; in Collect 2022.2.3 works well

**Comment by seadowg** [comment]
This seems to be due to the fact that location updates sometimes do not start after rotating the device. The root cause of this is that `BaseLocationClient#setListener` stores the passed listener (that will get `onClientStart` calls that kick off location updates) as a `WeakReference` and [`LocationTrackerService` passes an anonymous Kotlin object to it](https://github.com/getodk/collect/blob/a33a12f4e7f7a71de2c1128d3bc6b6f2fbbfb8e8/location/src/main/java/org/odk/collect/location/tracker/ForegroundServiceLocationTracker.kt#L77). This means that it's possible for the listener to be garbage collected while the `BaseLocationClient` is starting up, meaning that there is no listener to call by the time it tries to call `onClientStart`. 

I'm pretty convinced this issue must exist for other map engines, and in previous versions of Collect given the explanation above. However, it seems that it's pretty hard to reproduce without using the newest version with Mapbox v10. My only theory there is that Mapbox's slowness when adding markers (which it will do on rotation to rebuild the trace/shape) creates enough CPU time/memory allocation to make garbage collection of the listener reference highly likely. I'm removing the regression tag from this, but I still think we should fix this before releasing seeing as it's much more likely to occur now.

Great find @dbemke!
