### ISSUE TITLE
Setting auto send to cellular only sends submissions without SIM card in phone while wifi is on

### ISSUE THREAD

**Issue by dbemke** [getodk/collect#5191]
**Software and hardware versions** 

Collect v2022.3, Android probably all

**Problem description**

User is able to send submissions to Central when in settings there is auto send with cellular only although there is no SIM card in the phone. It happens when wifi is turned on in the phone.

**Steps to reproduce the problem**

1. Take out SIM card
2. Go to Settings→ Form management → Auto send
3. Choose Cellular only
4. Go to All widgets form
5. Fill in some answers
6. Check Mark form as finalized
7. Click Save Form and Exit

**Expected behavior**

Submissions should not be auto sent to Central.

**Other information** 

Also on Collect v2022.2.2.

**Comment by grzesiek2010** [comment]
Yes the regression was introduced in v2022.2.0 so it's not a new thing. I could fix it but we also wanted to refactor that code https://github.com/getodk/collect/pull/5047
@seadowg what do you think? Since it's not new in v2022.3 and it's not something serious we can keep it and fix later along with the refactoring?

**Comment by seadowg** [comment]
> @seadowg what do you think? Since it's not new in v2022.3 and it's not something serious we can keep it and fix later along with the refactoring?

Ah so it's one of the "regressions" that escaped our regression pass for 2022.2 yeah? If so, agreed we can leave it for this release and prioritize for the next one.

**Comment by lognaturel** [comment]
It's not clear to me what the value of "Cellular only" is from a user/business standpoint. It makes perfect sense to me to want to limit to WiFi only. But I can't think of a case where Cellular only would make sense. My guess is that it's not very common and we could verify that with analytics if we want to think about removing the option instead of fixing it.

**Comment by seadowg** [comment]
> But I can't think of a case where Cellular only would make sense. My guess is that it's not very common and we could verify that with analytics if we want to think about removing the option instead of fixing it.

Great point. Let's come back to this when we're thinking of addressing the issue.

**Comment by seadowg** [comment]
We're going ahead with fixing this for the moment and will punt on whether to remove the "cellular only" option.
