### ISSUE TITLE
APK size has gone from 13MB to 16MB

### ISSUE THREAD

**Issue by lognaturel** [getodk/collect#5209]
Last release was [v2022.2.3](https://github.com/getodk/collect/releases/tag/v2022.2.3) at 12.9MB
[2022.3 beta 0](https://github.com/getodk/collect/releases/tag/v2022.3-beta.0) was 13.0MB
[2022.3 beta 2](https://github.com/getodk/collect/releases/tag/v2022.3-beta.2) is 16.2MB

The increase seems clearly related to Mapbox 10.

- [x] Is there an extra native library being included that we could exclude?
- [x] Is there anything else that could be excluded?

**Comment by grzesiek2010** [comment]
It is because of mapbox indeed and it looks like there is nothing we can do. New mapbox libs are just bigger:

mapbox v9:
![m2](https://user-images.githubusercontent.com/3276264/180983088-116a7a77-59ff-4ede-878a-4aa794fb335f.png)

mapbox v10:
![m1](https://user-images.githubusercontent.com/3276264/180983095-fb3d8225-069b-42b7-9f90-edd3407ee436.png)

and there is nothing we could exclude.

**Comment by lognaturel** [comment]
Too bad! It’s probably for supporting things like the new 3d views.
