### ISSUE TITLE
Range with picker appearance adds extra digit

### ISSUE THREAD

**Issue by lognaturel** [getodk/collect#5284]
Version: 2022.3 but said to have existed previously. 

From @mathieubossaert:
> When we choose a value and then change it, an extra digit is added to the value. This happens for values <= 10.

https://forum.getodk.org/t/display-bug-for-range-question-with-picker-appearence/38980

**Comment by grzesiek2010** [comment]
This is a bug in android sdk the same I reported long time ago: https://issuetracker.google.com/issues/72690635
This time I've spent some more time debugging the code and found the root cause (see my comment there). I've also played with some stuff trying to somehow make it work well but to no avail so we have to wait for the Android team or replace the `NumberPicker` with something else.

**Comment by grzesiek2010** [comment]
@lognaturel @seadowg any thoughts? Do you think we should rework that widget to use something less buggy than `NumberPicker`?

**Comment by lognaturel** [comment]
Good/annoying find! So it happens on all Android versions?

**Comment by grzesiek2010** [comment]
> So it happens on all Android versions?

All new versions I guess as I said in the bug report 6+.

We have a couple of different options:
1. Do nothing and wait for the android team to fix the bug
2. Rework the whole widget and use something else than `NumberPicker`. It would need to be similar because the appearance is `picker`.
3. Use java reflection to access private fields/methods and ignore applying the filter that contains the bug at all.
4. Always pass numbers to `NumberPicker` in the ascending order. No matter if in the form the range is set 1..10 or 10..1 the way it's displayed would be the same. It seems like the bug does not exist then.

I think the last option might be the best one for us. It would change the user experience a bit but it shouldn't be a problem?
