### ISSUE TITLE
Selecting approximate option for location doesn't work as expected

### ISSUE THREAD

**Issue by srujner** [getodk/collect#5299]
**ODK Collect version**
Reproducible both on Master and Store Version (2022.3.5)

**Android version**
Android 12, 13

**Device used**
Google Pixel 3a, Google Pixel 6a

**Problem description**

Selecting approximate location doesn't work as expected

**Steps to reproduce the problem**

https://user-images.githubusercontent.com/85225519/194090106-b5225a83-ef4e-4fdf-8dfe-b872408731e5.mp4

1. Click on the map icon next to the All Widgets form;
2. Select Approximate location and click on the button "While using the app";
3. Location permission dialog will appear.

**Expected behavior**

- App should still work when the user grants only approximate location access.
- Location permission dialog should not appear after selecting approximate location.

**Comment by seadowg** [comment]
@lognaturel I'm thinking we should fix this so that the behaviour is as @srujner describes and review in the future if we want special behaviour for approximate location.

**Comment by lognaturel** [comment]
This doesn’t feel so urgent to me! Android 13 is going to take a while to roll out. I’m pretty sure that it’s worse in most data collection cases to get coarse points rather than to have to talk to a supervisor to get out of an error state. 

I how about I bring this up with the TAB briefly to get their initial reaction.

**Comment by seadowg** [comment]
> I’m pretty sure that it’s worse in most data collection cases to get coarse points rather than to have to talk to a supervisor to get out of an error state.

That seems fair. Will move this to v2022.5.

**Comment by lognaturel** [comment]
What happens on Android 12?

Looks like the privacy changes came in with [Android 12](https://proandroiddev.com/android-12-privacy-changes-for-location-55ffd8c016fd). From what I understand, it will affect everyone when we target Android 12.

Forum thread to get user feedback [here](https://forum.getodk.org/t/dont-allow-access-to-geo-question-types-if-coarse-vs-fine-location-perms-given/39355).

**Comment by srujner** [comment]
I checked it on Android 12 and behavior is exactly the same as on Android 13, but it might be good to check it on a different device. I used Google Pixel 3a and 6a.

**Comment by seadowg** [comment]
We're going to go ahead with what @lognaturel suggested in her forum post: the app should continue to lock the user out of flows that require location permissions if they select "approximate" but additionally the user should see a dialog explain that they need to grant "precise" location if they select "approximate" to make it clearer what the problem is.

**Comment by grzesiek2010** [comment]
> additionally the user should see a dialog explain that they need to grant "precise" location if they select "approximate" to make it clearer what the problem is

Can we just update the existing dialog? It says:
> Without these permissions Collect can't record your location. Please try again when you are ready to grant them.

We could just update it:

> Without **precise location permission** Collect can't record your location. Please try again when you are ready to grant it.

Wouldn't that be enough?

**Comment by lognaturel** [comment]
@grzesiek2010 that sounds right to me.
