### ISSUE TITLE
Standardize Delete Blank Form layout to remove jerkiness

### ISSUE THREAD

**Issue by yanokwa** [getodk/collect#530]
As you switch between tabs, `Nothing available to display` and the `Scanning for forms` and `Finished scanning...` moves around. They probably shouldn't. The layouts should be the same.
![jerky](https://cloud.githubusercontent.com/assets/32369/23670289/3d98f13a-0335-11e7-9012-de436b526840.gif)

**Comment by shobhitagarwal1612** [comment]
I think we can replace those textViews for displaying status with `Croutons`
 https://github.com/keyboardsurfer/Crouton

![](http://www.grokkingandroid.com/wordpress/wp-content/uploads/2012/10/confirmation_crouton1.png)

![](http://www.grokkingandroid.com/wordpress/wp-content/uploads/2012/10/alert_crouton.png)

I also opened an issue #461 regarding refactoring the use of deprecated TabActivty in FileManagerTabs. So this issue can be handled in that as well since the UI elements are going to be altered in that process.
@yanokwa @lognaturel Any thoughts?

**Comment by yanokwa** [comment]
@nribeka Says, "we probably need to refactor that UI too to use slider / strip with fragments instead of TabHost. The fragments then can share the same layout. Currently they are on the same tab, but using different layout. One is form_manage_list.xml, the other is data_manage_list.xml. Both layout file have the exact same elements."

**Comment by yanokwa** [comment]
@shobhitagarwal1612 I'm generally not excited about introducing external libraries. Crouton seems to be deprecated by [Snackbar](https://developer.android.com/reference/android/support/design/widget/Snackbar.html). If that's something that can be done in #461, then I think we should do it there.

**Comment by shobhitagarwal1612** [comment]
1. We should replace the TabActivity with FragmentActivity and use PagerTitleStrip along with ViewPager to implement the views with a slider/strip.
2. We can use the Snackbar provided by the Android Sdk instead of any open source library to display the status messages. 
@yanokwa Any thoughts?

**Comment by nribeka** [comment]
If we're just planning to remove the jerkiness, we probably can change the code to share the same layout or make the layout have the same boundary (I would prefer to use the same layout file since they both have the same elements in them).

If we want to refactor, we probably need to approach it like @shobhitagarwal1612. Use fragments that share the same layout file and use slider / strip.

The first one will be short and much less work than the second part, but the second part is the much better approach I think 👍

**Comment by shobhitagarwal1612** [comment]
@nribeka @yanokwa I'm interested in doing the refactoring

**Comment by lognaturel** [comment]
@shobhitagarwal1612 the feature is merged. It's yours. You can work on the preference as well.

**Comment by shobhitagarwal1612** [comment]
@lognaturel Thanks
