### ISSUE TITLE
Forms get deselected in Delete Saved Form if the user rotates the screen and then minimizes the app

### ISSUE THREAD

**Issue by dbemke** [getodk/collect#5343]
~~Blocked by #5456~~
~~Blocked by #5521~~

#### ODK Collect version
v2022.4 Beta 2
#### Android version
10, 13
#### Device used
Redmi 9T, Pixel 6a
#### Problem description
Forms get deselected in "Delete Saved Form" if the user rotates the screen and then minimizes the app. If don’t keep activities is enabled forms are deselected after minimizing (without rotating).

#### Steps to reproduce the problem

1. Go to Delete Saved Forms.
2. Select some forms.
3. Rotate the screen.
4. Minimize the screen.
5. Return to the app (causing the app to reset to the device's "default" orientation)

#### Expected behavior
Selected forms shouldn’t be deselected.
#### Other information 
In collect v2022.3.0 the issue with rotating and minimizing (without don’t keep activities enabled) is not present, but if don’t keep activities is enabled form is deselected after minimizing.

**Comment by seadowg** [comment]
It looks like this is because we are using the (discouraged) `configChanges` attribute for `DeleteSavedFormActivity` to prevent Activity recreation on rotation. That allows us to cheat and not have to retain the list of selected forms between rotations. It doesn't work when you return to the app from a portrait launcher though as for some reason, that still causes Activity recreation to force the app back into portrait. This is why we lose the selected forms when minimizing from the opposite orientation of the phone itself. I'll update the steps slightly to make sure that's clear.

Don't think this is very high priority, but would be nice to clean it up in the next major release.
