### ISSUE TITLE
String number widget counting "spaces" as numbers

### ISSUE THREAD

**Issue by srujner** [getodk/collect#5359]
**ODK Collect version**
Current master https://github.com/getodk/collect/commit/6e836499110deb34377a8558cbc815fdc08ca25c, the store version v2022.4 Beta 2

**Android version**
10, 12, 13 (probably all)

**Device used**
Redmi 9T, Pixel 3a, Pixel 6a

**Problem description**
String number widget counting "spaces" as numbers.

**Steps to reproduce the problem**

1. Download form:  [stringWidgets.xml.txt](https://github.com/getodk/collect/files/10076978/stringWidgets.xml.txt)
2. Open StringWidgets form
3. Navigate to the tab StringNumberWidget - thousands-sep
4. Provide some numbers and click "space" multiple times

![Screenshot_20221123-163334~2](https://user-images.githubusercontent.com/85225519/203587239-8ea71607-9c61-42e9-9521-2454b95f12bc.png)
![thous](https://user-images.githubusercontent.com/85225519/203587245-8a1b6db1-acff-4d1a-ba33-ec4b3861c3ee.png)

**Expected Behavior**
- If user clicks on "space" this action should be ignored by the app. Only number should be possible to provide, just like in the other tabs e.g DecimalWidget - thousand-sep

**Comment by lognaturel** [comment]
There's a broader issue here. I just submitted `956 979798 -8989-9764.667,,` to a string number. Really, that widget should be doing more validation than it is, `thousands-sep` aside. Ideally it would be impossible to type more than one decimal separator in, negative signs could only go at the bottom, spaces would be forbidden. I'm not entirely sure that's exhaustive so the first step would be to define that.

**Comment by seadowg** [comment]
I've been chewing on this, and I actually don't feel like this is a bug. It feels to me that the string number widget (or the "number text widget" as it's referred to in [the docs](https://docs.getodk.org/form-question-types/#number-text-widget)) is really for two things:

1. A convenience option for string data that is easier to enter with a numeric keyboard (like serial IDs, phone numbers etc)
2. A workaround for rare cases where numbers are being collected that are larger than the constraints on the integer (9 digits) and decimal (15 digits) widgets

I think **1** makes it had for us to say what is and isn't valid within the set of characters available on Android's numeric keyboard (which includes ` `, `,`, `.` and `-`) and so both @srujner and @lognaturel's examples seem fine to me.

I propose that we close this and mark it as "won't fix", and update the docs to make it clearer that `,` and ` ` are supported characters. How does that sound @srujner and @lognaturel?

**Comment by lognaturel** [comment]
@seadowg I want to make sure that you saw that the commas are being inserted by the `thousands-sep` appearance, NOT by the user. The intent of using the `thousands-sep` appearance with a number string is clear to me: you expect a big number and you want thousands separators. Whether it's common is another question.

I am also pretty sure that this behavior varies by Android version and/or locale which is unfortunate.

We do have lots of other higher priority things to look at so fine to mark as wont fix until we get a specific request for it.

**Comment by seadowg** [comment]
> I want to make sure that you saw that the commas are being inserted by the thousands-sep appearance, NOT by the user. The intent of using the thousands-sep appearance with a number string is clear to me: you expect a big number and you want thousands separators. Whether it's common is another question.

You caught me. I did manage to entirely forget that while digging into how `StringNumberWidget` worked 😔. Was firmly lost down the rabbit hole. I still think that those strings should be allowed by the widget, but I understand that it's weird that we insert thousands separators into strings with spaces etc (and that that was actually the original problem).

I think what would make most sense to me is that we just avoid thousands separation in cases where it doesn't make sense:

- User enters "    "  -> "    " 
- User enters "1234" -> "1,234"
- User enters "1234.5" -> "1,234.5"
- User enters "1 23" -> "1 23"
- User enters "1234" then "1234 5" -> "1234 5"
- User enters "1234-" then backspaces to "1234" -> "1,234"

That said, I'm keen to see if anyone is actually using "thousands-sep" with text numbers before we bother with that complexity. For now, I'll stick in some analytics to track how often we actually see it in forms and move this issue to the next release. If it's not used often, we can potentially look at removing it.

**Comment by seadowg** [comment]
Moving this to v2023.3 so that we have time to learn from analytics.

**Comment by seadowg** [comment]
So far the analytics (last 90 days) look like this:

* Text number widget: has appeared ~12m times for ~72k users in 200+ forms
* Thousands separator: has appeared ~3k times for 184 users in 11 forms

That makes the text number widget "pretty well used" in my book with ~14% of total users (~512k) seeing one in the last 90 days. The `thousands-sep` appearance however is not something we're seeing a lot of out in the wild with it only being used in 11 forms globally. I suggest that we remove support for `thousands-sep` in v2023.4 rather than dig into the complexity of getting it working properly. What do you think @lognaturel? I think if we then see complaints, we could revisit this and potentially put the work in to a more robust version.

**Comment by seadowg** [comment]
We're going to leave this as-is and document it.

**Comment by lognaturel** [comment]
Some additional nuance added to https://github.com/getodk/collect/issues/5359#issuecomment-1671208421:
* `thousands-sep` applies to integers and decimals as well. We didn't track analytics on that but presumably it's much more used in that context and doesn't run into those issues.
* 11 forms in that timeframe used `thousands-sep` *with the string number widget*. This suggests we really don't need to do anything special for that case.

I still think the issue here has nothing to do with `thousands-sep`: it's doing what it it designed to be doing. The real question is whether the string number widget should have stronger guarantees about representing a number. @seadowg and I discussed and came to the conclusion that it would be really hard to do in a way that matches user expectations, especially across locales. So the docs we're going to add will warn about the possibility of badly-formed numbers and suggest using regex according to the domain needs.
