### ISSUE TITLE
Improve error handling and code flow for columns appearance on selects

### ISSUE THREAD

**Issue by lognaturel** [getodk/collect#5376]
There's a form that seems to have the appearance "columnscolumns-" and is causing a lot of Crashlytics noise: https://console.firebase.google.com/u/1/project/api-project-322300403941/crashlytics/app/android:org.odk.collect.android/issues/4bc6ee671a837984b0bc1fdd21792763?time=last-seven-days&versions=v2022.4.1%20(4543)&sessionEventKey=6393045A000000015B78CB196337837E_1753531330254806919

Let's stop logging that exception and also take a quick look at the flow around that area to see whether it can be simplified.

To be explicit, I think silently ignoring unsupported appearances is the right behavior. It's up to users to test their forms and make sure they're getting the look that they're going for.

**Comment by grzesiek2010** [comment]
> There's a form that seems to have the appearance "columnscolumns-" and is causing a lot of Crashlytics noise

actually, the appearance was `columns-` The error message was [Timber.e(new Error(EXCEPTION_PARSING_COLUMNS + columnsAppearance));](https://github.com/getodk/collect/pull/5378/commits/1da1a8033418cd5f2259063cd9832d7b3b28b568#diff-9d61b60c08d06f9ea304f59aae4c03777a3000629b9815eabb3baca7f40d414eL142) where `EXCEPTION_PARSING_COLUMNS` was `Exception parsing columns` and that's why `columns` word was duplicated.

There is nothing to improve there when it comes to code flow. Everything works as expected and if there is an unsupported appearance like "columns-" then 1 is returned.
