### ISSUE TITLE
Crash when zooming to fill screen in select from map

### ISSUE THREAD

**Issue by yanokwa** [getodk/collect#5379]
In Collect v2022.4.1, if I select a place, and hit the `[  ]` button in the map, I get a crash that reports `Unsupported zoom level: NaN`.  See video below.

https://user-images.githubusercontent.com/32369/207158249-4317ead3-0c3a-43e5-b9a6-f402e632dceb.mp4

To reproduce, scan the QR code at https://staging.getodk.cloud/#/projects/17/app-users

**Comment by seadowg** [comment]
@yanokwa could you post the form here please? I don't currently have access to staging.getodk.cloud.

**Comment by yanokwa** [comment]
You now have access to staging!

**Comment by seadowg** [comment]
> You now have access to staging!

No I don't 😭. I've hit up @lognaturel on Slack about getting access.

**Comment by seadowg** [comment]
I'm unable to reproduce this on an emulator with a debug build, but I can reproduce consistently using Yaw's form and dataset on my personal Pixel 6a using the Play Store version of the app. I gave it a try on my Nexus 5X (Android 8) using a debug build, and it crashed once. However, I couldn't reproduce a second time. 

My initial suspicion was that this could be a problem with having points that can't all be displayed on screen using the max zoom level. An example would be to go wide and have a point in North America, a point in Europe and a point in Australia. I'm going to try out a form like this on the Pixel 6a next to see if I can reproduce.

**Comment by seadowg** [comment]
> An example would be to go wide and have a point in North America, a point in Europe and a point in Australia. I'm going to try out a form like this on the Pixel 6a next to see if I can reproduce.

This didn't reproduce. I'm going to pass this to @ln and @grzesiek2010 to see if they have any ideas rather than me spinning my wheels on it. Worst case scenario, we can catch the exception that causes this crash and just zoom out to the max zoom level.

**Comment by lognaturel** [comment]
I can reproduce consistently on Moto G5 with the form and points Yaw shared. The `LatLngBounds` end up being

`LatLngBounds{southwest=lat/lng: (-46.66518987499998,-154.0106815), northeast=lat/lng: (90.0,145.7549435)}`

I'm guessing that something can't handle the `90.0`. I didn't dig any further because `CameraUpdate` and beyond is obfuscated Google code.

> catch the exception that causes this crash and just zoom out to the max zoom level

That sounds fine to me. Might be also worth looking at the osmdroid and Mapbox implementations to see if there are ideas there?

**Comment by seadowg** [comment]
> I'm guessing that something can't handle the `90.0`. I didn't dig any further because `CameraUpdate` and beyond is obfuscated Google code.

Ah good spot. It looks like it's not just `90.0` - we need the `south` (in `southwest`) to be a particular number as well. For `90.0` as `north` the crash will happen for any value of `south` less than or equal to `-21.0` (roughly). I think we should go ahead and fix this by catching the exception and doing a max zoom out rather than digging in any more. 

We could try and write some instrumentation tests against `GoogleMap` to nail down the problem enough that we could file an issue with Google Maps and massage our own code to protect from this, but both feel too time intensive* for us right now given how simple it would be to just zoom to the max level. If we start seeing bad "zoom to fit" behaviour for lots of different datasets, we can come back to it.

\* *Submitting issues to Google's Issue Tracker can be quite a lot of work. In my experience, they often require example projects zipped up and attached and very detailed instructions on reproduction (often including unexpected things like how to run a test using Android Studio). This can result in long back and forths before an issue gets taken seriously.*
