### ISSUE TITLE
Prevent creation of non finalized forms when "Edit Saved Form" is hidden

### ISSUE THREAD

**Issue by seadowg** [getodk/collect#5438]
## Acceptance

- [ ] Given that "Edit Saved Form" is hidden (in Settings -> Access Control -> Main Menu Settings)
And I'm filling out a form
When I press the back button
Then I do not see the "Save as draft" option

- [ ] Given that "Edit Saved Form" is hidden (in Settings -> Access Control -> Main Menu Settings)
And I'm filling out a form
When I navigate to the end of the form
Then the "Save as draft" button is disabled

**Comment by lognaturel** [comment]
Note: this could be legitimate in a 2-pass workflow. You might want data collectors to collect data in one pass and then not look at it again until they hand the device to a supervisor who can change settings, make edits and then send.

**Comment by grzesiek2010** [comment]
> Given that "Edit Saved Form" is hidden (in Settings -> Access Control -> Main Menu Settings)
And I'm filling out a form
When I navigate to the end of the form
Then I do not see the "Save as draft" button

I think in this case the button maybe should be disabled not hidden to match the behavior from https://github.com/getodk/collect/issues/5416 where:

> Given I'm in Access Control settings for a project
When I navigate to Form Entry Settings
And I toggle off "Save as draft"
And navigate to the end of a form
Then the "Save as draft" button is disabled

What do you think @seadowg @alyblenkin?

**Comment by seadowg** [comment]
> I think in this case the button maybe should be disabled not hidden to match the behavior from https://github.com/getodk/collect/issues/5416 where:

Yeah, sorry those should match. I'm actually now thinking we should be hiding buttons rather than disabling them when their turned off in settings. Let's just keep it consistent for the moment and we can change that later if we don't like it. I'll update the acceptance.

**Comment by grzesiek2010** [comment]
> I'll update the acceptance.

You have also updated this:

> Given that "Edit Saved Form" is hidden (in Settings -> Access Control -> Main Menu Settings)
And I'm filling out a form
When I press the back button
Then the "Save as draft" button is disabled

but I'm not sure... that button in the QuitForm dialog is hidden if you disabled `Save Form` in Settings -> Access control -> Form Entry Settings (current implementation), so either we want to hide it in both cases `Save Form` or 'Edit Saved Form' is disabled or disable in both. If we already hide it there I would choose hiding even if it's weird that in that dialog it's shown/hidden and in the EndForm screen enabled/disabled.

**Comment by seadowg** [comment]
>  If we already hide it there I would choose hiding even if it's weird that in that dialog it's shown/hidden and in the EndForm screen enabled/disabled.

Ah right that's true. Again, let's keep this consistent and review later - we'll hide that button for now.

**Comment by grzesiek2010** [comment]
@seadowg I think we should add even more criteria in this issue. This issue is only about hiding `Edit Saved Form` (now it's called `Drafts`). In fact, there are three options that should disable/hide the `Save as draft` option in the form:
- `Save Form` from `Access control` -> `Form Entry Settings`
- `Save as draft` from `Access control` -> `Form Entry Settings`
- `Drafts` from `Access control` -> `Main Menu Settings`

if one of these options is disabled the `Save as draft` option should be not displayed in the `QuitFormDialog` and disabled in the `End Screen`. I've implemented it in this way, see: https://github.com/getodk/collect/pull/5576/files#diff-45ba76f50a9fb29584713f24475f4a5a9812256a924309cf082430c9fddc5805R59 and https://github.com/getodk/collect/pull/5576/files#diff-49e6df691ba128d743f2ceaa263199095ebe5984a91ba640f43ffe2fd6ac3292R17

For now, I think it's ok but I have some doubts regarding the `Save Form` option from `Access control` -> `Form Entry Settings`... if it's enabled the save icon is displayed in the toolbar in a form and it's always possible to save a form (create a new draft). It's possible even if `Save as draft` from `Access control` -> `Form Entry Settings` is disabled or `Drafts` from `Access control` -> `Main Menu Settings` is disabled. I think the behavior, in this case, is inconsistent. What do you think?

**Comment by seadowg** [comment]
I hadn't actually noticed the "Save form" option somehow and didn't come up in our discussions when were planning this feature. Looking at the "current" (v2023.1.2) behaviour of "Save form", when it's disabled the "quick save" button (the floppy disk) and the "Save changes" button in the quit dialog are both hidden, but the user can still uncheck "Mark as finalized" to create a draft (un-finalized instance). Given that, I don't think we should hide the "Save as draft" button on the end screen when "Save form" is disabled. The behaviour does feel unclear/inconsistent, but I think we should preserve it for the moment. Maybe the setting needs to be renamed to something like "Quick save and save changes"?

It does sound like we need to additionally hide the "quick save" (floppy disk) button when "Drafts" is disabled in "Main Menu" settings though and should add acceptance for that. I'd like a second opinion from @lognaturel on that though, as I'm surprised we didn't add that here in the first place.

**Comment by alyblenkin** [comment]
Jumping in here with a few thoughts: 

- Renaming the settings is a good idea, so the user knows exactly what will change. 
- I agree with both of you; it would be inconsistent for the user to be able to hit the "quick save" (floppy disk) button when "Drafts" are disabled. 
- If we hide it at some point, we may want to consider adding an anchored prompt/tooltip (similar to the last screen in the flow, but pointed to the toolbar or perhaps in the settings) to let data collectors know this has changed. It could be disorienting if folks often use "quick save", and then it's suddenly gone.
- I should have asked this earlier, but do we have disabled buttons in the app already? I'm wondering if folks will think it's broken. If this is a new concept, we could similarly add a prompt/tooltip to let the user know why the button is disabled so there isn't any confusion.

**Comment by seadowg** [comment]
> I should have asked this earlier, but do we have disabled buttons in the app already? I'm wondering if folks will think it's broken. If this is a new concept, we could similarly add a prompt/tooltip to let the user know why the button is disabled so there isn't any confusion.

Yes we do have some disabled buttons. First example off the top of my head is the selection buttons in "Delete Saved Form".

**Comment by lognaturel** [comment]
I've discussed this with @alyblenkin some. My apologies, I intended to have a deeper discussion about this one and it slipped through the cracks. Thanks for highlighting all the issues here, @grzesiek2010.

The user-facing goal here is to prevent the case where Collect is configured to hide the drafts button but drafts can still be saved.

Currently, the settings section that the "Drafts" setting is in is called "Access control" with description "limit user interface." It's inside of "Main Menu Settings" with description "Show or hide buttons". Currently all buttons are shown/hidden independently of each other with one exception: "Moving backwards" is not really a show/hide setting and can control other settings if the user chooses.

I'm sure it's not common but it is possible that users have built legitimate workflows around limiting the ability to access drafts but keeping the ability to save drafts (https://github.com/getodk/collect/issues/5438#issuecomment-1466492832).

Some options:
- Do nothing and continue letting project leadership explicitly choose which buttons to show and hide. This leaves the possibility that a data collector could be saving drafts that they can't access later.
- Add a dialog like the "Moving backwards" dialog that asks a user whether they want to hide related settings when they choose to hide one of the three buttons related to drafts.
- Get rid of the three independent show/hide settings and replace it with a single option to enable or disable drafts.

I have a preference for the second option because I think it's helpful and explicit while honoring users' existing workflows. I don't think we should automatically link the settings without letting users know (the acceptance criteria in this issue).

As @seadowg highlights, the "Save as draft" button in the form exit modal is currently implicitly tied to "quick save". So really that setting is about whether a data collector can save DURING form entry. I think we can treat improving that setting as a separate issue: https://github.com/getodk/collect/issues/5580 As @seadowg/@alyblenkin mention, maybe a rename is all we need.

I think it makes some amount of sense for saving as draft during form entry and saving at draft at form end to be separate. A project manager may want to force/encourage data collectors to go through the whole form linearly once and then let them save as draft and edit later. I'm not totally convinced that the save icon and the dialog button should be linked and I've mentioned that in #5580.

For consistency with the setting category and the prior behavior, it feels like the show/hide settings should show/hide buttons instead of disabling them. Again, we can treat that as a separate issue: https://github.com/getodk/collect/issues/5581

**Comment by seadowg** [comment]
Thanks for the input everyone. As far as I can see, we don't need to update the acceptance for this issue as @lognaturel has captured the other things we want to do in #5580 and #5581. Is that correct? If so, @grzesiek2010 will be able to simplify the implementation in #5576.

**Comment by seadowg** [comment]
> Do nothing and continue letting project leadership explicitly choose which buttons to show and hide. This leaves the possibility that a data collector could be saving drafts that they can't access later.

We discussed it and are going with this option so that we don't cut any existing workflows off.
