### ISSUE TITLE
Remove the option to reconfigure the current project with QR codes

### ISSUE THREAD

**Issue by grzesiek2010** [getodk/collect#5477]
I was thinking about this before but only now when I'm working on https://github.com/getodk/collect/pull/5476 I spent more time doing that.
We have two classes responsible for scanning QR codes:
- `QrCodeProjectCreatorDialog` - it is used for creating new projects 
- `QRCodeScannerFragment` - it is used for reconfiguring the current project

I think now as we can easily add new projects scanning QR codes, the option for reconfiguring projects is redundant. Users can add a new project and delete the existing one if they want instead of reconfiguring it.
It would be easier to maintain just `QrCodeProjectCreatorDialog` than two similar classes.
@lognaturel @seadowg what do you think?

**Comment by seadowg** [comment]
Interesting idea! Let's discuss in release planning.

**Comment by seadowg** [comment]
Here are some interesting numbers relevant to this from analytics (last 90 days):

- QR reconfiguration has been used 15k times by 11k users (~3%)
- Projects have been deleted 21k times by 7.9k users (~2%)
- Projects have been created 145k times by 113k users (~27%)

I'm unable to create a funnel of delete to creation in Firebase which would be pretty useful here. @lognaturel could you look into giving me access to GA? 

Reconfiguration is certainly only used by a small percentage of users, but it does provide the only solution for updating project settings with unsent forms on device. I could see this being very important in resource constrained settings or in a scenario where a project has to change server URLs (without having to create a "duplicate" project or manually altering project settings). I do think we have a bunch of needlessly duplicated code that deals with this, but we should move towards unifying that rather than removing the feature.

I'm going to close this for the moment, but happy to reopen if anyone feels we should investigate this further.
