### ISSUE TITLE
Investigate navigation buttons for LTR languages

### ISSUE THREAD

**Issue by lognaturel** [getodk/collect#5486]
Can we make sure the < and > arrows stay in the same orientation?

Can we change the flip animation direction?

https://forum.getodk.org/t/when-using-a-rtl-language-in-collect-arrows-for-back-and-next-buttons-point-in-the-wrong-direction/40659

Once we figure out what's possible and rough level of effort we can morph this issue into actions to take.

**Comment by grzesiek2010** [comment]
> Can we change the flip animation direction?

It should be doable but when it comes to:

> Can we make sure the < and > arrows stay in the same orientation?

I think the problem is not that the arrows are moved from start to end position (this is actually the expected behavior) but the fact that the icons are not mirrored and as a result, we have `> Next` and `BACK <` (with English translations to make it easier to understand) instead of `< Next` and `BACK >`. Of course, mirroring does not make sense until we handle properly animations.
