### ISSUE TITLE
Main menu button redesign

### ISSUE THREAD

**Issue by lognaturel** [getodk/collect#5492]
https://www.figma.com/file/KFi9hIQdrRgo0rLqIC7Sg8/Finalized-flow---ODK?node-id=531%3A22316&t=PV5beJ2y8PxwWMuH-1

First just update the button style, then update the language after the rest of the form finalization changes go in.

**Comment by seadowg** [comment]
@grzesiek2010 I think it might be nice to experiment with a new app bar look and feel as part of this, as I've discussed over at https://github.com/getodk/collect/issues/5409. Definitely not wroth spending a lot of time on, but would be nice to do a visual refresh to the app bar along with the new Main Menu.

**Comment by grzesiek2010** [comment]
@alyblenkin I've implemented most of the changes and the new main menu looks like this:
![Screenshot_1680090945](https://user-images.githubusercontent.com/3276264/228564101-211a5022-b9ed-49ac-996d-fa8bb467e8a0.png)
Pretty close to what we have on Figma I guess. To me, close enough I would say but as you know we didn't have a designer before so it's my first time in ODK when I implement UI changes designed by a professional like you so I would like to know first how strict and close to what you designed I should be. A good example would be the shadow in buttons. Yours is darker but I used the default android color and also the size is consistent with what we have in other places so to me it's ok but maybe you don't agree. Maybe there are some other small differences like that so please let me know as I said above if I should try harder.

Some other things to discuss:
- The blue color used in the first button is not the same color we use as our accent color. You called it ODK blue and it's #5192C1 but the blue one we already use is #3e9fcc. I used the one we already have to style that button because otherwise, it would look a bit weird I guess to have two different blue colors. Should I still use your one? Or maybe replace our blue with your blue and use it across the app?
- I don't know if it made sense but I added the icons according to those from the screen I see when I open the link attached above (maybe we will need to change them later)
- The sizes of icons are not consistent on Figma so I used 24dp/24dp for all of them like we usually do
- There is nothing about the dark theme so I used the same blue color for the first button and the same color of buttons we used before:
![Screenshot_1680100056](https://user-images.githubusercontent.com/3276264/228571155-c588840a-69a4-4030-b15f-d77ab5245c1a.png)

Let me know what you think about it.

**Comment by alyblenkin** [comment]
Hey @grzesiek2010! This looks great!! 

- Button shadow - I was using the same elevation treatment as [Material 3](https://m3.material.io/styles/elevation/overview), but this looks perfectly fine to me! 
- Primary colour - I must have added the wrong colour - I just updated my styles in Figma. 
- Icons - 24dp is correct (I think the bounding boxes in figma make them appear like they are different sizes). 
- Dark theme - I should have mocked that up, but your version looks very similar to what [Material 2 suggests](https://m2.material.io/design/color/dark-theme.html#behavior), so I think that's good.

**Comment by alyblenkin** [comment]
In terms of the design process, I'm a fan of doing what works to convey the concept rather than making every detail pixel-perfect in Figma because that time could be spent working on another design story. For example, it might be faster to show an example of specific interaction referencing another app than me recreating the same thing or even sketching something on paper to capture the idea. My default is to pair on something quickly and ensure it's right in the code. Let me know if that works for you, though!

**Comment by grzesiek2010** [comment]
> In terms of the design process, I'm a fan of doing what works to convey the concept rather than making every detail pixel-perfect in Figma because that time could be spent working on another design story. For example, it might be faster to show an example of specific interaction referencing another app than me recreating the same thing or even sketching something on paper to capture the idea. My default is to pair on something quickly and ensure it's right in the code. Let me know if that works for you, though!

Sounds perfect to me. 

One more thing the grey color you used for the buttons (#F5F5F5) is a little bit different than the one we have used so far (#F7F7F7) was that intentional or like in case of the blue color we should use what we already have?

**Comment by alyblenkin** [comment]
Another case of colour picking and it not being 100% accurate. I'll update this in figma too :)

**Comment by alyblenkin** [comment]
Hey @grzesiek2010, I just realized you used an older version of the icons for "send finalized form" and "sent form". The screen is on the "dev ready" page. It looks like the wrong link was added above, it should have been this one - https://www.figma.com/file/KFi9hIQdrRgo0rLqIC7Sg8/Finalized-flow---ODK?node-id=531%3A22316&t=PV5beJ2y8PxwWMuH-1

**Comment by lognaturel** [comment]
Sorry about that! Amazing to see this coming together. 🎉

**Comment by grzesiek2010** [comment]
Not a problem at all if it's just about two icons.

**Comment by grzesiek2010** [comment]
@seadowg I've created a pull request with the redesign and now I'm looking at what you said about the app bar:

> I think Google Maps provides a great example of an app that benefits from edge to edge. For us, I think we should most likely look at revising our app bar design so that it shows "flat" compared to the status bar.

Could you elaborate on that because I'm not sure if I understand? Is it only about the color and making sure both the status bar and the app bar use the same color? If so it seems to be a problem only in the dark mode right?

| Light  | Dark |
| ------------- | ------------- |
| ![Screenshot_1680257312](https://user-images.githubusercontent.com/3276264/229091839-41e33c34-8a64-4330-a11c-2fb0e7e70820.png) | ![Screenshot_1680257323](https://user-images.githubusercontent.com/3276264/229091844-f9340ba9-7e7c-4cbc-b7f0-7d9e840fd8d7.png)|

**Comment by seadowg** [comment]
@grzesiek2010 yup! Looks like it already matches in light mode.
