### ISSUE TITLE
Only treat _ as markdown if separated by white space

### ISSUE THREAD

**Issue by lognaturel** [getodk/collect#5508]
Every once in a while we get a question on the forum from someone who has select choices that look like `SEA_774_BOB` and are surprised to see them rendered as SEA<i>774</i>BOB. I'd always thought we had to live with this but @eyelidlessness pointed out that Markdown is kind of loose and maybe it doesn't have to be that way.

Github only interprets _ as markdown if they are separated by whitespace: 
* `SEA_774_BOB`: SEA_774_BOB
* `SEA _774_BOB`: SEA _774_BOB
* `SEA_774_ BOB`: SEA_774_ BOB
* `SEA _774_ BOB`: SEA _774_ BOB

Daring Fireball does say Emphasis can be used in the middle of a word:

`un*frigging*believable`: un*frigging*believable
`un_frigging_believable`: un_frigging_believable

Oh and look at that, Github has an exception just for _. That feels like the ideal behavior. We should decide and then make sure it's consistent across Enketo and Collect.

**Comment by seadowg** [comment]
@lognaturel not sure if this is going to be high priority, but I think we should just go with your suggestion here.

**Comment by grzesiek2010** [comment]
I've investigated the issue and implemented some improvements around handling markdown italics. @lognaturel please take a look and let me know what you think see https://github.com/getodk/collect/pull/5685

**Comment by grzesiek2010** [comment]
I just wanted to add that it's not a huge change/improvement but still worth implementing. It doesn't even fix anything because using the last release version if a user wanted to display `SEA_774_BOB` it was possible but escaping underscores was required (`SEA\_774\_BOB`).
With this pull request, it's the other way around, `SEA_774_BOB` will be displayed as-is but if you want to emphasize text in the middle of a word you need to use HTML tags directly (`SEA<em>774</em>BOB` in this case).
I think it might be more common to display underscores in the middle of a word than emphasize a part of it so that should be the default behavior, and to achieve the other result users can add HTML tags as I said above.

**Comment by lognaturel** [comment]
>  if a user wanted to display SEA_774_BOB it was possible but escaping underscores was required (SEA\_774\_BOB)

Yes, that's true, but to be explicit, it's not practical when something of that shape is an ID. That is, you do NOT want the id to be the literal string `SEA\_774\_BOB`. And in all likelihood, you couldn't even make it that if you wanted because it comes from some other system. That's the reason this is actually a pretty big improvement.

**Comment by lognaturel** [comment]
What does GithHub do with _this_. Or _this_? Or _this_! Or _this_* or _this_& or _this_A or _this_a or _this_) or _this_8

GitHub excludes non-alphanumeric characters.

> Github has an exception just for _.

It turns out it's more general than that. I'm kicking myself for not making this part of the issue more clear.

@grzesiek2010 what do you think about reopening and making this change?

**Comment by grzesiek2010** [comment]
> @grzesiek2010 what do you think about reopening and making this change?

Let's reopen so that we don't forget and see what we can do.
