### ISSUE TITLE
Type Mismatch Error in the Repeat Groups Form

### ISSUE THREAD

**Issue by srujner** [getodk/collect#5512]
**ODK Collect version**
v2023.1 Beta 4, v2022.4.4

**Android version**
10, 13

**Device used**
Redmi 9T, Pixel 6a

**Problem description**
There is a type mismatch error when user is adding the second repeat group and goes to the end of the form.

- Start filling the form: [CalcTest.xml.txt](https://github.com/getodk/collect/files/11038537/CalcTest.xml.txt)
- Click on the Add button in the "Add Fishing type gear" window;
- Select Gillnet or Seinenet and go to the next question;
- Select any value and go to the next screen;
- Click on the Next button;
- Add Second group;
- Fill all the required fields and move to the Adding Repeat group for "Fishing type gear" window;
- Click on the "Do not add" button;
- There will be Type mismatch error
![Screenshot_20230321-123242](https://user-images.githubusercontent.com/85225519/226864243-b6145f8a-d159-492c-bc96-cbf03e0b6fc8.png)

**Expected behavior**
There should not be any errors after adding another repeat group

**Other information**
- In the version 2022.4.4 the error is also reproducing;
- There is no error when only 1 repeat group is added.

**Comment by lognaturel** [comment]
@srujner do you have a record of why this form was in your set of forms to try? I see that it has `f9b8151086797041b0c935152c991891fd87d4ca` as its context node which suggests it was built in an unusual way. I don't recognize where that would have come from.

This is the same form design issue as https://github.com/getodk/collect/issues/5507 but it's in the notes after the repeat (`Note2` and `Note3`) instead of the instance name. This one I think is entirely expected so let's close.

I do think we should rethink this error message.

**Comment by srujner** [comment]
@lognaturel The form was added to the Fill Blank form test from the pr: https://github.com/getodk/collect/pull/3375 but in the test step there is only that: 
Test step: User fills form CalcTest. User selects Gillnet or Seinenet. User goes to next question 3375 
Expected Result: Selected option is copied to other questions.
