### ISSUE TITLE
Unable to reopen a map in select one from map with appearance quick

### ISSUE THREAD

**Issue by dbemke** [getodk/collect#5540]
#### ODK Collect version
2022.4.4, 2023.1.2 ,the master version db8f7ec7342fa558fe43424909b5fb40fd0d5bc1
#### Android version
10, 13
#### Device used
Redmi 9T, Galaxy A32
#### Problem description
The user is unable to reopen the map when there was a point/trace selected and appearance quick is applied in the question. When the quick appearance is added to select one from map question, the form doesn’t advance immediately to the next question once a selection is made.
#### Steps to reproduce the problem
1. Go to Select fieldlist quick form.
[Select fieldlist quick.xlsx.txt](https://github.com/getodk/collect/files/11159267/Select.fieldlist.quick.xlsx.txt)
2. Go to questions with Map widget select one from geojson attachment.
3. Tap "Select place”.
4. Select a point on the map.
5. Try to reopen the map by tapping "Select place”.
#### Expected behavior

Select one from map with `quick` should skip the summary sheet when the user clicks on a point, and then skip to the next question (like other select widgets). If the user navigates back to a select one from map question, they should be able to change their selection by clicking "Select place" and then a point.

#### Other information 
I also created and checked appearance quick in a select one form map form with csv attachment and points and traces included in xlsx file. In all cases the map doesn't reopen.
[selectonefrommapwithgeojsoncsvquick.xlsx.txt](https://github.com/getodk/collect/files/11159255/selectonefrommapwithgeojsoncsvquick.xlsx.txt)
[pointandtraces.csv](https://github.com/getodk/collect/files/11159257/pointandtraces.csv)
[pointsandtraces.geojson.txt](https://github.com/getodk/collect/files/11159262/pointsandtraces.geojson.txt)

**Comment by seadowg** [comment]
The form should move to the next question instead of returning to the current one after they select a place if the `quick` appearance is used.

**Comment by dimwight** [comment]
Got as far as reproducing this in the store version, now stalled by lack of Maps functionality (just Google logo against a grey background) in the debug build both in the AS emulator and on my devices (A7 and A10). 

Any suggestions?

**Comment by seadowg** [comment]
> Got as far as reproducing this in the store version, now stalled by lack of Maps functionality (just Google logo against a grey background) in the debug build both in the AS emulator and on my devices (A7 and A10).

There's some extra steps to get Google Maps/Mapbox working in a local dev environment (documented [here](https://github.com/getodk/collect#using-apis-for-local-development) in the `README.md`). OSM works out of the box though, so you can switch to that in Collect settings.

**Comment by dimwight** [comment]
> OSM works out of the box though, so you can switch to that in Collect settings.

Doh, obvious once pointed out.

**Comment by seadowg** [comment]
@dimwight are you currently working this? If so, it's best to flag that so we can assign you to the issue.

**Comment by dimwight** [comment]
Definitely still looking at it, especially the _quick_ implementation.

**Comment by dimwight** [comment]
Having now explored this issue in detail, it turns out that appearance _quick_ leads a double life.

Most obviously, it enables auto-advance via `AdvanceToNextListener` in several of the classes returned in `WidgetFactory` from `getSelectOneWidget`, though not in `SelectOneFromMapWidget`.

In `SelectOneFromMapWidget` by contrast, _quick_ is used to skip the summary toast, with a side effect of preventing reopening that might be either a bug or a feature.

Looking at the code for `SelectOneFromMapWidget`, `SelectOneFromMapDialogFragment` and `SelectionMapFragment` (in particular `onFeatureClicked`), skipping the summary is clearly a considered feature. 

And the non-reopening behaviour has a certain logic - there's no reason to reopen the map unless you want to make a new  selection, in which case just press 
**Remove response** first. 

So do we want to treat this issue as worth further attention?

**Comment by seadowg** [comment]
> And the non-reopening behaviour has a certain logic - there's no reason to reopen the map unless you want to make a new selection, in which case just press Remove response first.
>So do we want to treat this issue as worth further attention?

`quick` indeeds skips the summary sheet, but it's unintentional that when you reopen the map it immediately closes (because you already have something selected). To the user, it appears like the map just doesn't open which could be really confusing. I realise it's not actually clear what the behaviour should be in the issue itself - I'll update it.

**Comment by seadowg** [comment]
@dimwight I've updated the "Expected behaviour" section:

>Select one from map with `quick` should skip the summary sheet when the user clicks on a point, and then skip to the next question (like other select widgets). If the user navigates back to a select one from map question, they should be able to change their selection by clicking "Select place" and then a point.
