### ISSUE TITLE
Styling the last screen before you finalize or send the form

### ISSUE THREAD

**Issue by alyblenkin** [getodk/collect#5570]
As part of our work with https://github.com/getodk/collect/issues/5416, we want to style the last screen so it looks more aligned with where we are heading with the hierarchy view. 

### Proposed solution:

- Buttons aligned to the bottom for consistency  
- Text in the middle, as opposed to aligned to the top, because we don't want the page to look like something hasn't loaded in the centre.
- I think we will sort out the button styling in this issue https://github.com/getodk/collect/issues/5567

<img width="840" alt="Screenshot 2023-05-04 at 10 57 31 AM" src="https://user-images.githubusercontent.com/7871340/236289306-345ab4a3-9557-4b1d-8e66-63d47cf42d34.png">

**Comment by lognaturel** [comment]
A few quick thoughts to ignore or consider:
- Maybe just making the buttons consistent with others in the app would be enough?
- If it still feels too bare, maybe we could consider doing something like writing a little bit of text to explain that finalize/send is final? That could also help with the transition.
- Having the buttons at the bottom of a mostly empty screen might feel very strange with a tall tablet.
- Without the bottom navigation bar, only people who know about swiping will be able to go back. That feels a bit unfortunate. I want to make sure that's a deliberate choice.
- Maybe the buttons could go in a bottom sheet over the last screen of the form? But that probably has its own usability risks associated so I'm not currently advocating for it.

**Comment by alyblenkin** [comment]
A few quick thoughts to ignore or consider:

* Maybe just making the buttons consistent with others in the app would be enough?

> Agreed! I think that works until we unify all the buttons. 

* If it still feels too bare, maybe we could consider doing something like writing a little bit of text to explain that finalize/send is final? That could also help with the transition.
* Having the buttons at the bottom of a mostly empty screen might feel very strange with a tall tablet.
* Without the bottom navigation bar, only people who know about swiping will be able to go back. That feels a bit unfortunate. I want to make sure that's a deliberate choice.

> We could bring the text from the confirmation dialog onto this screen and spell out the new terminology, but my thought was once we implement the dialog, we will still have this issue of it feeling too bare until we have the hierarchy view. Perhaps both of those stories (confirmation dialog and hierarchy view) will be delivered together, so that could work for now? 

> Another idea is we could use the tooltip/ prompt here and call out the new changes coming. Something like this but we will have the same issue once we implement the dialog.

<img width="801" alt="Screenshot 2023-05-04 at 1 11 20 PM" src="https://user-images.githubusercontent.com/7871340/236318442-02b0046f-feff-4ec4-8ac3-9b3c11945e6b.png">


* Maybe the buttons could go in a bottom sheet over the last screen of the form? But that probably has its own usability risks associated so I'm not currently advocating for it.

> I agree, that would be ideal to have the buttons on the last screen so we don't have such an empty screen, but I was also worried they might be in the habit of seeing the 'next' button and finalising without realising it. So I don't think it will work either.

**Comment by grzesiek2010** [comment]
A couple of my thoughts:
- initially, I liked moving the buttons to the bottom because it looked consistent with other screens like the list of forms to download/delete but I forgot about the navigation bottom bar. It looks weird when we have both hiding it is a little bit risky I think 
- I like more the option when both buttons are next to each other horizontally 
- I'm not sure about that explanation message. It looks good and maybe would make sense if we wanted to release what we currently have merged but after implementing this dialog it will be a duplicate:
![image](https://user-images.githubusercontent.com/3276264/236416562-a4793659-ef56-46fd-9510-1927b62f6c1d.png)

**Comment by alyblenkin** [comment]
@lognaturel @grzesiek2010 - summarizing our conversation so we have it for next week. 

We decided to: 

- Center everything in the middle of the screen with the two buttons and navigation at the bottom 
- We are going to add the tooltip as shown in the mockup above without the "learn more" link 
- We will share a screenshot in the forum next week so users know what's happening and can prepare 🫶
- Leaning towards no dialog until we consider the summary screen. With the summary screen, we have some concerns about performance issues. 
- We will still have a story for [unifying the older buttons](https://github.com/getodk/collect/issues/5567). I've also updated the [exit modal issue](https://github.com/getodk/collect/issues/5490) that's in flight with flat buttons.

Update:
- We are also moving forward with flat outline/ filled buttons instead of making all buttons elevated, like the main menu. I was originally concerned about learnability and consistency, so I was thinking we should make all buttons elevated to resemble physical buttons, which can be helpful for learning/ digital literacy. However, given the [material guide](https://m3.material.io/components/all-buttons) it seems like it's okay given the emphasis, and the fact that we already have flat buttons (the initial welcome/config screen and on the project selection dialog), so we think it will work and still be user-friendly. 

![End screen_new design](https://user-images.githubusercontent.com/7871340/236584619-f350d5db-f55a-48d1-b776-821813343566.png)




Let me know if I missed anything!

**Comment by seadowg** [comment]
> Leaning towards no dialog until we consider the summary screen. With the summary screen, we have some concerns about performance issues.

Are we just going to go with no dialog for this release then? We're not looking at attempting the summary yet anyway, so we definitely end up a duplicate warning. If so, I'll update our other issues.

**Comment by alyblenkin** [comment]
@seadowg, yes, that's the plan! What do you think?

**Comment by seadowg** [comment]
> @seadowg, yes, that's the plan! What do you think?

Sounds good. I'll update the issues.

**Comment by lognaturel** [comment]
I want to have a quick record of the rationale. The dialog came about partly because with the summary screen there isn't a good place to put information about the finality of finalization. The good thing about having a confirmation dialog is that it really encourages the user to think about whether they're done (good friction). But that comes at a cost: a user who is completing a lot of forms daily will constantly have this extra dialog to click through (imagine if your email client asked for confirmation each time). We think the inline notice will provide enough information but will explicitly ask about this during beta.

There are several cases here that I want to call out for @getodk/testers:
- If saving as draft is turned off in settings and autosend is off in settings, only a finalize button should be shown with no notice
- If saving as draft is turned off in settings and autosend is on in settings, only a send button should be shown with no notice
- If saving as draft is turned on in settings and autosend is off in settings, the Save as draft and Finalize buttons should be shown with the notice exactly like in the mockup
- If saving as draft is turned on in settings and autosend is on in settings, the Save as draft and Send buttons should be shown with the notice text mentioning sending, not finalizing
- I don't remember what the new setting combination is exactly but I think there's also a case where only the Save as draft button is shown

You likely verified all of these in https://github.com/getodk/collect/pull/5556 but I want to call them out again because you'll want to make sure the notice text is appropriate.

**Comment by lognaturel** [comment]
@alyblenkin do you have a good way to take a quick look at these on a tablet? Maybe landscape mode on your device is close enough? I do think we should make sure you look at all of the changes on a tablet before we release to see if anything needs to be updated (e.g. max widths added).

**Comment by alyblenkin** [comment]
Hey @lognaturel, I don't have a great way to check these on a tablet. I was looking at this in landscape mode this morning, and it wasn't too bad. Here is what it looks like on my device. I may need to look at screenshots?

![Screenshot_20230509-151257_ODK Collect](https://github.com/getodk/collect/assets/7871340/4b95ae6e-a41d-4109-b1e4-35b1dec237eb)

**Comment by seadowg** [comment]
@alyblenkin I reckon we probably want to center the text and the warning there and give them a max width on wider screens. We're going to do a quick design pairing session soon so we can have a play with that then.

**Comment by alyblenkin** [comment]
@seadowg - yes, I've added this to my notes for our pairing session tomorrow :)
