### ISSUE TITLE
Notifications don't work on Android 13

### ISSUE THREAD

**Issue by seadowg** [getodk/collect#5574]
#### ODK Collect version

Current `master` branch (7938500c89f538285add79b90b35b3ab68497c96)

#### Android version

Android 13

#### Device used

Emulator

#### Problem description

Notifications (like auto send success/failure, match exactly errors etc) do not work on Android 13. The user is never asked to grant Collect permission to show notifications the notifications are never seen.

#### Steps to reproduce the problem

1. Perform a fresh installation of Collect (to prevent pre granting of permissions)
1. Enable auto send
1. Fill out and complete a form

A notification (or permissions to show notifications) is never seen. In System settings, the option to enable notifications for the app is disabled.

#### Expected behavior

~~v2023.1 asks for permission to show notifications whenever a new notification channel is created. This is most likely because that version of the app targets API 31, so we get automatic (but uncontrolled) permission requests. I imagine we ideally want to show a permission request when a setting like auto send is enabled (and also when importing settings that contain it).~~

The team discussed this, and it was decided we'd ask for notification permissions the first time the user views the main menu (so after configuring the first project). We'll need to mock up how this will look.

#### Other information 

We most likely need to declare the notification permission and add runtime permission requests as detailed [here](https://developer.android.com/develop/ui/views/notifications/notification-permission).

**Comment by alyblenkin** [comment]
Hey @seadowg, I've [created a first draft of the flow](https://www.figma.com/file/KFi9hIQdrRgo0rLqIC7Sg8/ODK-user-flows?type=design&node-id=1416%3A54102&t=KeUDpd2AbXh2FFVz-1) based on our discussion last Friday. If you have any feedback we could quickly discuss after our call tomorrow.

Note: I don't think we will update the styling of the landing screen as part of this story. I think we would update the buttons and text as part of the story of the unifying buttons, which I hope we can pair on and clarify this week.

**Comment by seadowg** [comment]
> Hey @seadowg, I've [created a first draft of the flow](https://www.figma.com/file/KFi9hIQdrRgo0rLqIC7Sg8/ODK-user-flows?type=design&node-id=1416%3A54102&t=KeUDpd2AbXh2FFVz-1) based on our discussion last Friday. If you have any feedback we could quickly discuss after our call tomorrow.

Some quick thoughts:

* Love the look and feel of the permissions dialog ❤️.
* I think we should show the dialog after the user scans a QR code (so before seeing the Main Menu) and ask for camera permissions separately. I'm worried asking for everything before scanning might be confusing as the camera permission has a lot of relevant context but nothing else does.
* I think we'll want to start just doing this for notifications and then add the other permissions in there later.
* I'm not sure about the dialog title ("Permissions update"). That said, I'm drawing a blank on anything better.

I'm in between things at the moment, so I'll start working on an implementation of this that we can tweak rather than needing to do any further mocking up.

**Comment by seadowg** [comment]
One other thought: we'll need to tweak the language a little. The preable currently reads:

>  If you want to allow access, select “while using the app” on the next screen.

The "while using the app" button is specific to permissions that can be used in the background (like location). I think we'll just want that to say "Allow" for now (as that's what the notification permission button will read).

**Comment by alyblenkin** [comment]
> Love the look and feel of the permissions dialog ❤️.

Awesome! I wanted to make it visual, and I was inspired by some of the consent dialogs I've used in the past. I like when they single out each item so that you know what you're opting into. 

> I think we should show the dialog after the user scans a QR code (so before seeing the Main Menu) and ask for camera permissions separately. I'm worried asking for everything before scanning might be confusing as the camera permission has a lot of relevant context, but nothing else does.

Interesting - the system's permission popped up before I had the chance to scan, so I thought we would want to get the message in before. Also, do we need to ask for the camera permission before they scan? I'm pretty sure I was asked to allow access to my camera the first time I downloaded the app. 

>  I think we'll want to start just doing this for notifications and then add the other permissions in there later.

Okay!

> I'm not sure about the dialog title ("Permissions update"). That said, I'm drawing a blank on anything better.

I know, it's not the best! I had "Permissions" as the title, but I thought people would scan it/ not read the subtext. I was also concerned they may think they were allowing those permissions in this dialog, rather than more of an update. I'll keep thinking about it.


> I'm in between things at the moment, so I'll start working on an implementation of this that we can tweak rather than needing to do any further mocking up.

Sounds good.

**Comment by seadowg** [comment]
> Interesting - the system's permission popped up before I had the chance to scan, so I thought we would want to get the message in before. Also, do we need to ask for the camera permission before they scan? I'm pretty sure I was asked to allow access to my camera the first time I downloaded the app.

Yeah, we do need permission, but it feels to me like we don't need an explanation before as it's clear why we're using the camera and I think it'd be confusing to have other permissions (like notifications) asked for at the same time. So I think the onboarding sequence should be:

1. Click "Scan QR Code"
2. Get asked about camera permission
3. Scan QR code
4. See dialog about other permissions used by the app (just notifications for now)
5. Allow other permissions

Does that make sense?

**Comment by alyblenkin** [comment]
Yes, that makes sense! I agree we don't need to explain the camera because it's contextual. 

I think this flow works well if you are configuring one phone at a time. If someone is configuring a bunch of phones all at once it could get very repetitive, but I don't know if we can get around that. Maybe there could be an admin setting? I think we could come back to this later.

I played around with the [language a bit in Figma](https://www.figma.com/file/KFi9hIQdrRgo0rLqIC7Sg8/ODK-user-flows?type=design&node-id=1466%3A54796&t=wEHPkJJLunddN8tS-1). I also moved the screens to "dev ready" to keep things tidy.
