### ISSUE TITLE
Update the end screen warning text based on the available actions

### ISSUE THREAD

**Issue by lognaturel** [getodk/collect#5584]
Currently the warning text in the form entry end screen is the same no matter what actions are available. If only one of "finalize" or "save as draft" is available, it doesn't make sense:
![Screenshot_20230512_144702](https://github.com/getodk/collect/assets/967540/a641c930-5a27-4888-bd28-1c22621821e3)

I'd mentioned possible alternatives at https://github.com/getodk/collect/issues/5570#issuecomment-1540372063. This included no notice for the cases where only one action is available. @alyblenkin is working on possible alternatives to consider.

**Comment by alyblenkin** [comment]
I've written out a few possible alternatives below, let me know what you think, @lognaturel. 

**Finalizing**
I'm leaning towards option 1 because we have the space to give more context.

1. "You will not be able to make edits once you finalize. If you need to make any changes, go back and edit before finalizing your form."
2. "You will not be able to make edits once you finalize."

**Save as draft**
I think option 2 works better because we don't know if the managers want them to continue going back and editing. They may want to do that together, so we should keep it simple and go with option 2. 

1. If you have completed your form, save it as a draft. You can edit the form at any time from your drafts. 
2. If you have completed your form, save it as a draft.

**Save as draft and auto-send is turned on**
1. "You will not be able to make edits once you send. If you need to make any changes, "save as draft" until you're ready to send.

**Comment by alyblenkin** [comment]
I've written out a few possible alternatives below. Let me know what you think, @lognaturel.

### **If saving as draft is turned off in settings and auto send is off in settings, only a finalize button should be shown**
I'm leaning towards option 1 because we have the space to give more context.
> 
> 2. "You will not be able to make edits once you "finalize."
> 

### **If finalized is turned off and auto-send is turned off, only save as draft is shown**
I think option 2 works better because we don't know if the managers want them to continue going back and editing. They may want to do that together, so we should keep it simple and go with option 2.

> 1. If you have completed your form, "save as draft." You can edit the form at any time from your drafts.
> 2. If you have completed your form, "save as draft."

### If save as draft and auto-send is turned on, save as draft and send buttons are shown

> "You will not be able to make edits once you send. If you need to make any changes, "save as draft" until you're ready to send.

If saving as draft is turned on in settings and autosend is off in settings, the Save as draft and Finalize buttons should be shown with the notice exactly like in the mockup

**Comment by alyblenkin** [comment]
Updated based on our conversation.

**If saving as draft is turned off in settings and auto send is off in settings, only a finalize button should be shown:**
"You will not be able to make edits once you "Finalize." 

**If finalized is turned off and auto-send is turned off, only save as draft is shown:**
No message

**When auto-send is turned on and save as draft is turned off, only the send button is shown:** 
No message 

**If saving as draft and auto-send is turned on, save as draft and send buttons are shown:**
"You will not be able to make edits once you send. If you need to make any changes, "Save as draft" until you're ready to send.

**If saving as draft is turned on in settings and autosend is off in settings, the Save as draft and Finalize buttons should be shown:** 
The notice is exactly like in the mockup
