### ISSUE TITLE
Ability to change collect language from within the app

### ISSUE THREAD

**Issue by wonderchook** [getodk/collect#559]
Currently to change the language within collect you have to change the language for the phone. It would be nice to be able to select the language from a menu from within the app. Currently it just uses the local phone settings. This doesn't help if collect has been translated into a language not available on the phone. 

My phone does not allow you to add additional languages to it without rooting the device, it appears this is the case with many phones.

**Comment by lakshyagupta21** [comment]
Android by default uses locale of device to select appropriate language dependent resources. We can change Locale from our app manually also. When you want to create support for some language then we need to create a value folder appending a Hypen and language code. And we need to create separate files for each language support. And then programmatically we can change the language based on user preferences by passing language code in Locale to change the language for the app.

**Comment by shobhitagarwal1612** [comment]
@wonderchook Yes I totally agree with you. My local language (hindi) is also available in this app. But since the default language of the mobile is english so the app sets this language. There must be users who would like to change the language of the app.
The app should ask the user to select from a list of languages at the first launch of the application. This option should also be configurable from within the settings.

**Comment by lognaturel** [comment]
I don't love the idea of having a prompt at first launch but I do think it would be very nice to have in the settings! Maybe we can start with that and discuss the first launch idea separately. 

@lakshyagupta21 take a look [here](https://github.com/opendatakit/collect/tree/master/collect_app/src/main/res) to see the languages supported.

**Comment by lakshyagupta21** [comment]
@lognaturel Yes the language support is already there but what if there is some language which user wants to change but not supported in device then we should add some functionality so that we can explicitly use the corresponding language files to change our default app language to the user selected language.

**Comment by abdulwd** [comment]
@lognaturel @wonderchook May I work on this issue?

**Comment by yanokwa** [comment]
@abdulwd Absolutely! But before you send in a PR, please describe roughly how you'll be solving this problem...

**Comment by abdulwd** [comment]
@yanokwa I'll add a **Language** option in the **General Settings** under the header **USER INTERFACE** which will open a radio group dialog displaying the languages available. Selection of a language will change the locale of the app.

**Comment by yanokwa** [comment]
@abdulwd That sounds good to me. Looking forward to your PR!

**Comment by abdulwd** [comment]
@yanokwa Do I have to assign or claim this issue or I may start working on it? :)

**Comment by lognaturel** [comment]
Go for it, @abdulwd. Do keep in mind as someone mentioned previously that there are languages supported by Collect that may not be supported by the phone itself. You should make sure that all Collect translations are available in the list.

**Comment by lognaturel** [comment]
@wonderchook This is now available in the Play Store! I wanted to check in and make sure it's working as you imagined.
