### ISSUE TITLE
Limit width of main menu on tablets

### ISSUE THREAD

**Issue by lognaturel** [getodk/collect#5593]
Main menu buttons currently stretch to fill available space. On a wide screen:
![tablet_buttons](https://github.com/getodk/collect/assets/967540/57f71a82-87b3-41bb-a43b-0b203a8072cf)

@alyblenkin do you think this is best for usability? Maybe adding a max width and centering the buttons would be better?

Previously:
![old landing](https://github.com/getodk/collect/assets/967540/b0a25db2-c900-44ca-a47e-18e99afbf997)

**Comment by alyblenkin** [comment]
We certainly need to set a max width! I spoke with @seadowg about adding constraints so that text doesn't stretch out like this when we discussed adjusting the [notice message](https://github.com/getodk/collect/issues/5570#issuecomment-1540963268) on larger devices. 

Let's set a max width and keep it left aligned so it's easier to read when translated. My assumption is that it won't be easy to read with icons, long text, and numbers. We might have to see what it looks like on different devices, but I quickly [mocked up two versions.](https://www.figma.com/file/KFi9hIQdrRgo0rLqIC7Sg8/ODK-user-flows?type=design&node-id=1479%3A58288&t=dhMOg1pp8QVknvKX-1)

**Comment by alyblenkin** [comment]
- I spoke with @lognaturel about this issue this morning, and we decided against centering everything. I [mocked it up](https://www.figma.com/file/KFi9hIQdrRgo0rLqIC7Sg8/ODK-user-flows?type=design&node-id=1559%3A57273&t=HQ100SgGVMGHzIMI-1) and it's very hard to read. Material recommends [keeping elements grouped](https://m2.material.io/components/buttons#behavior); however, we are displaying 3 elements and it becomes overwhelming. 
- I was originally thinking about 640px max width, but I'm worried the elements are spaced out looking at it again today.

**Proposal:**
- Align the icon and text to the left and the number to the right 
- Max width 460px (within reason, not sure how this will work on all devices)
<img width="624" alt="Screenshot 2023-05-19 at 1 56 59 PM" src="https://github.com/getodk/collect/assets/7871340/e3560fe6-bf9e-4b75-bd49-969034463572">
