### ISSUE TITLE
No way to view a finalized form before sending

### ISSUE THREAD

**Issue by seadowg** [getodk/collect#5612]
#### ODK Collect version

v2023.2 Beta 1

#### Problem description

There is no longer a way to view a finalized form before it is sent. In previous versions, finalized forms would appear in "Edit Saved Form" where they could be edited to view the current data in them. The corresponding new "Drafts" page only shows non-finalized forms (as finalized forms can no longer be edited) and finalized forms only appear in "Ready to send" where they can be sent but not viewed. It feels likely that some workflows might require the ability to review a form before sending.

#### Steps to reproduce the problem

1. Disable auto-send (or disconnect from all networks)
2. Fill a form and finalize

There's now no way to view the finalized form.

#### Expected behavior

There should be a way to view the form before sending.

**Comment by seadowg** [comment]
@alyblenkin has put together an initial idea of how we might solve this by making the form name clickable (and bold):

![Screenshot 2023-05-26 at 2 25 35 PM](https://github.com/getodk/collect/assets/556280/ee276b9e-15a5-4247-9ce4-9807ba5b55ae)

I'm not sure that this will work as we currently use the whole form list item as a tappable area that toggles the checkbox (so that it's easier to select/unselect) and I don't think we want to lose this. So I wanted to explore some alternatives. 

Although I'm personally not a fan (as much as I'm used to it from being an Android user), Material 3 (and 2) favour [long pressing as a way of switching between viewing and selection for lists](https://m3.material.io/foundations/interaction/selection). Given that, if we were designing "Ready to send" from scratch following Material fanatically then clicking a list item would view the form and long pressing would switch us into a selection mode. I don't think that'd be right for this view either as (IMO) sending is really the primary action for the page and view is a secondary one. I'm wondering how people feel about adding a "kebab"/options menu to the list item with a view action:

<img width="360" alt="Screenshot 2023-05-27 at 11 27 36" src="https://github.com/getodk/collect/assets/556280/65ec0ac7-cfa7-4c1d-84f6-fbae253e0f0c">

I'm definitely operating under the assumption that this is very much a secondary action that people don't need to perform very often here - it's hidden away and a little fiddly to get to.

**Comment by alyblenkin** [comment]
@seadowg, thanks for adding this issue! I can see the challenge with the entire list item being tappable. 

I'm also not a massive fan of the long pressing action as a way to switch views, but it is effective. It might be hard to discover. That said, I do use this feature all the time...Once you learn the behaviour, it sticks. I worry about it being initially hidden, but I'm also not an Android user.

And you're right; sending is the primary action, so I thought making the list item tappable would be the least distracting and very much secondary. Similar to the affordance we use with viewing forms once they've been sent. However, there isn't a checkbox, so that isn't a component we can reuse. We are also unsure how often this scenario comes up –– strangely, nobody in the beta noticed! 

I was thinking of a similar idea in Figma using the "kebab" /more options button. My initial concern is that the checkbox and "veggie kebab" might be too close together and hard to tap. I thought of moving the checkbox to the left and the more to the right, but I was curious if that would be a lot of work. 

Eventually, we may explore a few configurable options at the form level, such as view, edit, and clone. So the "veggie kebab" solution could work well. It could also be a dialog with the different options, now that we have the new designs for the exit modal. But we still need to do some thinking on the other options. 

Whether we have the checkbox and more options button side by side, this might be a nice solution. 

<img width="400" alt="Screenshot 2023-05-27 at 10 23 16 AM" src="https://github.com/getodk/collect/assets/7871340/6b79c8a4-63c1-4e30-875a-84d1e964f2d9">

**Comment by lognaturel** [comment]
Good discussion on how to add viewing to “ready to send”. I feel like that’s likely the best option but I do want to mention that we’ve discussed a couple of alternatives. 

When it comes to viewing (and editing, etc), sent and “ready to send” forms are in the same state. It feels like they should be accessible from the same place and in the same way. Imagine for example that you have intermittent connectivity. You know you’ve visited tree 12 before but you don’t know whether you’ve been online since. It’s strange and unexpected to have to look in both “sent” and “ready to send.” The downside of making the two accessible from a single screen is that there isn’t an obvious good name for it. “Finalized” or “complete” are much harder to understand than “sent”. If we could find a clear name this seems like it would be ideal. 

We’ve considered removing individual selection of forms and going to a single “send” button. That would free up the primary action on a filled form row. However, we do know data collectors are sometimes trained to send the most important data yet, send filled forms without media first, etc. This kind of flexibility is why we decided not to make auto send default. 

One note about using a kebab or some other way of making the view/edit/etc actions accessible: it would be different from how drafts and sent forms are viewed/edited/etc. That feels awkward and possibly worse than requiring tapping on the checkbox to check/uncheck.

**Comment by seadowg** [comment]
After discussing, we're going to go with making the form item itself clickable (and only have the checkbox itself select the form).

**Comment by grzesiek2010** [comment]
Sorry for starting the discussion again but I'm still thinking about this... If we allow opening forms for review in the list of forms to send this will be possible for both finalized forms and sent forms because there is an option for displaying already sent forms in that list. That means we will have two places where opening sent forms for review will be possible. Does that sound ok to you? Why do we need the list of sent forms then?

I think I would prefer to display forms for review together in a separate list as I said yesterday but it's like 55% to 45% so I'm not strongly convinced.

**Comment by seadowg** [comment]
> That means we will have two places where opening sent forms for review will be possible. Does that sound ok to you? Why do we need the list of sent forms then?

This seems fine to me. The "Show Sent and Unsent Forms" seems pretty hidden to me, so I don't think we'd be able to remove the "Sent" page.

> I think I would prefer to display forms for review together in a separate list

I do actually agree with this, but I also think @alyblenkin is right that we'd need to test that approach out with people to make sure that it doesn't disrupt other workflows (confusing people about where they need to go for example). I think the current direction of making things the items clickable sacrifices a bit of usability when viewing finalized forms, but shouldn't affect anything other workflows, and it also feels to me like it'll be easier to change later.

**Comment by grzesiek2010** [comment]
> confusing people about where they need to go for example

don't you think that going to the list that is called `Ready to send` in order to review saved forms is more confusing than if we had a special button for it with a better name?

**Comment by seadowg** [comment]
> don't you think that going to the list that is called Ready to send in order to review saved forms is more confusing than if we had a special button for it with a better name?

Yeah, I do think I like that more, but it doesn't seem like we have a name that works yet. 

I'm personally not feeling very confident about any of the directions. It's feeling to me like we have to accept that we might unwind whatever we put in now, or we need to block releasing v2023.2 until we have time to test this out with users. I'm honestly pretty happy to go with the former as there's a lot of good stuff we want to get out to folks and I don't think this use-case is important enough to hold everything up. To my thinking, it feels less disruptive to unwind the click to view option than altering the options on the main menu. @grzesiek2010 are you happy to go with the click to view option for the moment with the understanding that we'll keep revising the flow, or does it feel like a no-go?

One thing to note is that it's hard for us to get an idea of how required viewing finalized forms before sending is using analytics, because the existing behaviour is so different (finalized forms are editable). We really only have anecdotal evidence of people's workflows to go on here.

**Comment by alyblenkin** [comment]
Hey @seadowg @grzesiek2010 - I think this is a valuable conversation to continue! However, I also don't think this should block us. I think we should still move forward with click to view form because we don't have a great solution or the confidence to change the main menu. We need more time to test a new workflow and design a thoughtful solution, which isn't possible with the Summit next week. 

**Other thoughts**

- Tapping to view the form doesn't seem too disruptive from my perspective. We could have a special button @grzesiek2010, but this would drastically change the workflow. 
- I would want that change to be communicated and tested, so we have the confidence to move forward. This would be an easier decision if we had the data to understand people's behaviour around viewing finalized forms. 
- I also wasn't aware until recently that you could view both sent and unset forms from at the same time - this is very hidden and I would love to know how often people use this feature. I was confused seeing both in "Ready to Send", but until we have a better name I think this is something we can address in the next iteration.

**Comment by seadowg** [comment]
We should add analytics as part of this:

- How often the "Change view" feature is used in "Ready to send"?
- How many people click on the list items "accidentally" (close the form again with X amount of time)?

**Comment by seadowg** [comment]
Just a heads-up from some early investigation here: the decided upon solution might actually be quite a chunk of work. The way the view is currently implemented is coupled heavily with Android's old `CursorAdapter` and our own `AppListActivity` hierarchy built around that. So we don't have to rebuild the whole thing, I'm going to try and detach the "Ready to send" page from the `AppListActivity` so I can make changes to that view alone, but if that ends up being a rabbit hole we might want to regroup and rethink.
