### ISSUE TITLE
Allow custom camera app to be specified in a question

### ISSUE THREAD

**Issue by seadowg** [getodk/collect#5621]
- [ ] Given I tap the `Take` button for an image question with a custom app specified through the `intent` body attribute
  And I have the custom app on my device
  Then I see the custom app

- [ ] Given I tap the `Take` button for an image question with a custom app specified
  And I don't have the custom app on my device or the app I specified doesn't respond to `ACTION_IMAGE_CAPTURE`
  Then I see an error toast (same as what [external widgets](https://docs.getodk.org/launch-apps-from-collect/) do)

- [ ] Given I took a picture with my custom camera app after launching it from the `Take` button on an image question
  Then I return to Collect and see the picture I took

- [ ] Given I am at an image question with both a custom app and the `new` appearance specified
  Then I do not see the `Choose` button

Testing considerations:
- Android 12+
- `annotate` should also combine with both this and `new`

Non-goals:
- We're not currently doing a bottom sheet to pick the app: https://github.com/getodk/collect/issues/5621#issuecomment-1645520802; we might later consider a special value for the `intent` attribute like `picker` to let a user pick an app
- We're not doing video because no one has asked for it

## Background
Prior to Android 11 users were allowed to select a camera app they wanted to use to capture image/record video. Then it was changed and now when using `ACTION_IMAGE_CAPTURE` action the default (built-in) camera app is started. This is a problem for users that want to use specific camera apps.
It turns out that if we know the package name of an app we can force starting it by adding it to the intent, eg.:

`            intent.setPackage("com.jeyluta.timestampcamerafree");`

I gave it a try and it works well with the[ Timestamp camera app](https://play.google.com/store/apps/details?id=com.jeyluta.timestampcamerafree&hl=en&gl=US) 

If it's possible to do the same with other apps too we can allow adding package names to the [ImageWidget](https://docs.getodk.org/form-question-types/#image-widgets) as an `appearance` (like in https://docs.getodk.org/form-question-types/#external-app-image-widget) or `parameter`.

P.S.
Adding queries in the manifest file might also be required:

```
<queries>
    <intent>
        <action android:name="android.media.action.IMAGE_CAPTURE" />
    </intent>
</queries>
```

**Comment by grzesiek2010** [comment]
@seadowg @lognaturel I've filled the description.
any thoughts? 
What should we use to pass package names? The `appearance` or `parameters` column?

**Comment by lognaturel** [comment]
If I were looking at this just from the ODK XForms spec perspective, I would say it should be specified as the value of a body attribute called something like `sourceApp`. Then in XLSForms it would be specified in the `parameters` column. I don't like using the `appearance` attribute for these kinds of things because `appearance` feels like it should be an optional client hint purely about display (here's the W3C description: "Author-optional attribute to define an appearance hint. If absent, the user agent may freely choose any suitable rendering."). That said, maybe it's an academic distinction. Collect just ignores an attribute it doesn't know, right? It won't error in any way? I'm asking because an advantage of introducing a new attribute could be if old clients would give an error when attempting to load a form. That would be a stronger guarantee to form designers that their directive would be followed.

Regardless, we do already have two ways of specifying apps to launch: [using an appearance with prefix `ex:`](https://docs.getodk.org/launch-apps-from-collect/#launching-external-apps-to-populate-single-fields) and [using an `intent` body attribute](https://docs.getodk.org/launch-apps-from-collect/#external-apps-to-populate-multiple-fields). I think we should use one of those existing patterns. Using the `appearance` with `ex:` feels like the most pragmatic choice.

Behavior we need to define:
- The app is not on the device. We could show a dialog with a prompt to go to the Play Store. We could fall back to the default camera app but I'm not sure that's what users would want.
- I think we want to hide the "choose" button and only show the button to capture a new image.
- The app doesn't respond to `ACTION_IMAGE_CAPTURE`? I think this could happen if a user specifies a non-camera app.

**Comment by grzesiek2010** [comment]
> Collect just ignores an attribute it doesn't know, right?

I think so but I would need to double-check to make sure

> Using the appearance with ex: feels like the most pragmatic choice.

Yeah, I don't like the fact that it's in `appearance` so doing that for image widgets in the same way doesn't seem perfect too but at least it would be consistent. I would prefer using body::intent like we do for populating groups of questions. Maybe at some point, we can handle external widgets in the same way instead of [using an appearance with prefix ex:](https://docs.getodk.org/launch-apps-from-collect/#launching-external-apps-to-populate-single-fields)

> The app is not on the device. We could show a dialog with a prompt to go to the Play Store. We could fall back to the default camera app but I'm not sure that's what users would want.

currently, we display a toast but if we want to have something more like a dialog probably we should do that for other cases where we start external apps so that there is one intent launcher that handles it in one place.

> I think we want to hide the "choose" button and only show the button to capture a new image.

I didn't think about it and to be honest I don't know if I agree. Users can still add `new` appearance if they want to hide that button.

> The app doesn't respond to ACTION_IMAGE_CAPTURE? I think this could happen if a user specifies a non-camera app.

Good point! I will test it during testing other camera apps.

**Comment by grzesiek2010** [comment]
This is a nice feature and we should definitely implement it but there is one other option that we might implement too (separately).
We could hardcode the list of supported camera apps for example [Timestamp Camera](https://play.google.com/store/apps/details?id=com.jeyluta.timestampcamerafree&hl=en&gl=US) and [Open Camera](https://play.google.com/store/apps/details?id=net.sourceforge.opencamera&hl=en&gl=US) and then start intent chooser with those camera apps + the default (built-in) one. Such a chooser would allow users to select the camera app they want as long as it's installed on their device of course. The chooser would look like this:
![image](https://github.com/getodk/collect/assets/3276264/69d3274f-d514-4c6a-8c70-57f3db404d1b)
The only limitation is that since Android 10 we can add only two other camera apps to that chooser so in total with the default one it's 3 but I"ve only heard from the users about `Timestamp Camera` and `Open Camera` so I guess it could be enough for the majority of them.
Alternatively in the future, we can try to build our own chooser without that limitation and then add other popular camera apps.

I think what I've described is simpler compared to specifying package names on a form level because it doesn't require all that discussion about the spec and error handling so maybe we should release it first if we don't have enough time for the other one or we can't decide how to implement it.

Assuming that users usually ask about those two camera apps allowing them to use those apps without doing anything on a form level might be a nice improvement.

Here is the code I added to test what's described above: https://github.com/getodk/collect/commit/b010d729fdb29f0c429fc5a6d06b3d5ae4c997c1

@lognaturel @seadowg what do you think?

**Comment by lognaturel** [comment]
It’s good to know that’s possible! I do think it’s important to give the form designer control, though. The camera apps are not interchangeable because they don’t produce the same artifacts. Pushing the decision to the data collector means they’ll inevitably make mistakes and even if they don’t it adds friction to their workflow.

**Comment by grzesiek2010** [comment]
> It’s good to know that’s possible! I do think it’s important to give the form designer control, though. The camera apps are not interchangeable because they don’t produce the same artifacts. Pushing the decision to the data collector means they’ll inevitably make mistakes and even if they don’t it adds friction to their workflow.

I mean yeah basically I agree. Form designers still would be able to force using a particular camera app. I just thought that if it's not specified by a form designer then allowing enumerators to use one of those cameras (if it's installed) would be nice.

**Comment by lognaturel** [comment]
> if it's not specified by a form designer then allowing enumerators to use one of those cameras (if it's installed) would be nice

Ah, I see, so it's an additional small feature: if one of a few camera apps we know about is installed, show the options, if not, go straight to default? And can a user set one as default that way or would they have to pick each time?

**Comment by grzesiek2010** [comment]
> if one of a few camera apps we know about is installed, show the options, if not, go straight to default? 

Yes

> And can a user set one as default that way or would they have to pick each time?

They would have to pick every time

my thinking is that it would kind of bring back the old behavior that some users miss with those limitations we already mentioned:
- up to 2 camera apps chosen by us
- it won't be possible to set the default one if the apps supported by us are installed

and using a specific camera app will be possible thanks to the second feature (the original idea described in this issue)
