### ISSUE TITLE
Replace calling browser intent with custom chrome tabs.

### ISSUE THREAD

**Issue by getsanjeev** [getodk/collect#563]
Launching the browser is a heavy context switch and should not be practised much. Custom chrome tab is a better way to launch URLs. I think this would enhance user experience.
While launching ODK website in About section, we can replace browser intent call with chrome tabs.
Whats say @lognaturel ?

**Comment by yanokwa** [comment]
@getsanjeev And what happens if Chrome isn't installed?

**Comment by getsanjeev** [comment]
@yanokwa What I know is - In that case simply it will launch the URL in system browser(default). It would be good if you have some suggestions.

**Comment by lakshyagupta21** [comment]
@getsanjeev You can use Webview in Activity to open About Section and store the webpage in cache so that if user opens the about section first it will retrieve the page from cache first, if page is not found in cache then it will load page from Internet , I think this would definitely enhance User Experience. @yanokwa Any suggestions ?

**Comment by getsanjeev** [comment]
@lakshyagupta21  Sure it can be done.
The good thing about chrome custom tabs is that - without managing things we can provide customisation. Here we dont need to write bulky codes just to show a single webpage.

**Comment by yanokwa** [comment]
[When should I use Chrome Custom Tabs vs WebView](https://developer.chrome.com/multidevice/android/customtabs#whentouse) suggests that this is a good optimization. 

Let's start slow, @getsanjeev. Replace the About browser launch in a branch. Then post in this issue what the experience is like on old devices with and without Chrome and on new devices with and without Chrome. 

Please use [LiceCap](http://www.cockos.com/licecap) or some other screen recorder so we can easily verify the behavior.

**Comment by getsanjeev** [comment]
@yanokwa Sure. Thanks for your feedback.

**Comment by shobhitagarwal1612** [comment]
@getsanjeev @yanokwa @lognaturel  I am a fan of `custom chrome tabs` as they make the web browsing experience in our own app much faster and stable. 

`Collect` calls for a browser intent only in the following cases:
- When visiting odk website from About Preferences
- When the user has to submit reviews and device doesn't have google play store app installed (but those devices might not have google chrome installed as well), also in the About Preferences

Since the scope of opening a browser is so little with such less use case, is it worth including another library in our app among already increasing number of external libraries? Also what will be the difference in the size of the apk after including the required gradle dependency for `custom chrome tabs`?

**Comment by getsanjeev** [comment]
@shobhitagarwal1612 I agree this issue has a smaller scope. I always favour using better means for any feature implementation. I do not think using chrome tabs would severely affect the size of app; though how exactly it would affect, still needs to be tested.
Thanks for the concern.

**Comment by yanokwa** [comment]
This is a tough call. 

@getsanjeev Can you see how much this adds to the APK?

**Comment by getsanjeev** [comment]
@yanokwa sure I will do it.

**Comment by getsanjeev** [comment]
@yanokwa What I could see is around 20kb. From APK Analyzer I have compared apks of both versions.
One without chrometabs and other including chromeTab dependency and some java code.
![selection_020](https://cloud.githubusercontent.com/assets/20872683/24068380/54a60224-0bb3-11e7-81d2-7d12508ff942.png)

**Comment by yanokwa** [comment]
@getsanjeev Thanks for being so thorough with this! I think this makes the app just a little bit nicer without changing the size too much. Please send in a PR.

**Comment by shobhitagarwal1612** [comment]
Fixed in #751
