### ISSUE TITLE
Maps unable to set location/ loading takes too much time after switching from Mapbox

### ISSUE THREAD

**Issue by dbemke** [getodk/collect#5633]
#### ODK Collect version
2023.1.1, the store version 2023.1.2
#### Android version
10, 13
#### Device used
Redmi 9T, Galaxy A23
#### Problem description
After switching from Mapbox to any other source of maps the time of searching for location on a map (e.g. in geopoint with map appearance) is too long. I’m not sure what are the factor causing that but the time varies from 30 sec to 5 minutes.
#### Steps to reproduce the problem
1. Google maps are set in project settings
2. Go to All widgets any Geo widget with maps – check if the map zooms to the location (in reasonable time).
3. Go to project settings and change the Basemap source to Mapbox.
4. Go to All widgets any Geo widget with maps – check if the map zooms to the location.
5. Go to project settings and change the Basemap to any other source (Google, OSM, Carto etc.)
6. Go to All widgets any Geo widget with maps – check if the map zooms to the location.
#### Expected behavior
The maps should set location in reasonable time

**Comment by grzesiek2010** [comment]
According to my thorough investigation, the issue has been around since we moved to Mapbox v10 in v2022.3.0 which means we have released three versions with that bug v2022.3.x, v2022.4.x, v2023.1.x. Taking it into account and the fact that switching between map engines is probably not a very common scenario I think it's not necessary to fix the problem ASAP in this milestone. However, I've spent a lot of time trying to figure out what's going on and playing with different versions/solutions so I'm going to continue working on this issue as a part of v2023.3 as I have some ideas in my head.

**Comment by dbemke** [comment]
Another issue that might be connected with this is missing location in audit logs in forms with background location tracking. After switching from Mapbox to a different source of maps in audit logs there are "location tracking enabled" and "location providers enabled" events but the location values are missing. If I force stop the app and fill the form again the location values are present in audit logs.
