### ISSUE TITLE
Select date and select time in a fieldlist adds or removes answers after swiping

### ISSUE THREAD

**Issue by dbemke** [getodk/collect#5652]
#### ODK Collect version
the store version 2023.1.2, the version 2023.2 Beta 4
#### Android version
10, 11, 13
#### Device used
Redmi 9T, Galaxy M12, Pixel 6a
#### Problem description
Select date and select time in a fieldlist adds or removes answers after swiping. In the dateTimeTest form 2 scenarios appear. 
In the first fieldlist (without required answers) if the user fills in just one of selects and swipes forward and backward, after coming back to the questions both are filled.
In the second fieldlist with the required questions if the user fills in just one answer and swipes backward and forwards both answers will be empty (one disappeared).
#### Steps to reproduce the problem
Scenario 1:
1. Go to dateTimeTest form.
[dateTimeTest.xml.txt](https://github.com/getodk/collect/files/11892748/dateTimeTest.xml.txt)
2. In the first question tap "Select date”, choose date and click ok (don’t fill second select).
3. Swipe to the next question.
4. Swipe back.

In this case both selects are filled.

Scenario 2:
1. Go to dateTimeTest form.
2. Go to the second fieldlist with required questions.
3. Tap "Select date”, choose date and click ok (don’t fill second select).
4. Swipe to the previous question.
5. Swipe forward.

In this case both selects are empty.
#### Expected behavior
Answers shouldn’t be added or removed after swiping.
#### Other information
If both of the answers are added and the users taps on one of selects and removes response, both responses are removed.

**Comment by grzesiek2010** [comment]
The first scenario is ok. It's one question that consists of two elements (date and time) displayed in two separate elements with two separate buttons. If someone sets the date but not time we set the time to the current one by default because we can't save the datetime answer with date but no time (and the other way around if you set only time the current date will be used).
When it comes to the second scenario I'm not sure... the behavior is slightly different because it's a require question and the answer is cleared I would say that it's ok. If a question is clearer both elements should be filled deliberately and not like in the first case so if you set only one element (date or time) it's ok to assume there is no answer at all.

@lognaturel do you think we should make this behavior consistent and maybe not to set date/time to the current one if it's not set (the first scenario)? If not please feel free to close the issue.

**Comment by lognaturel** [comment]
As @grzesiek2010 points out, there are no field lists here, this is a datetime input. 

I just tried the form with v2023.2.2 and I'm not experiencing the behavior that's described for the second form question. When I select just a date and leave time blank, I get a constraint toast when swiping forward. Android 5.1.1 though hopefully that makes no difference.

Either way, I think it's ok. If the value is not required, it does feel best to take what we can get and at least save the date. That means we have two options for the time: set it to current time or to 00:00. I think current time is reasonable. In the required case, we want users to fill out both date and time. I think a constraint toast is more expected. But clearing the value is ok -- they'll have to fill it out soon.

I don't think datetime is used very frequently so I think it's ok if it's a bit weird.

I would tend to close this issue.
