### ISSUE TITLE
Improve divider spacing

### ISSUE THREAD

**Issue by alyblenkin** [getodk/collect#5731]
Adding space before and after the divider. Currently, the button and divider are very close. 

![Image](https://github.com/getodk/collect/assets/7871340/060e79a8-8c61-407d-8893-ed53b6fc6114)

**Comment by grzesiek2010** [comment]
The main container (where we put every question) should have padding start/end/top/left. Currently every question take the whole available space (at least horizontally) and then every single element like question label, hint, buttons need to define margins themselves what is annoying (I've experience it recently while working on https://github.com/getodk/collect/pull/5725). Maybe historically there was a reason why we wanted questions to take the whole available space (horizontally) there was something but I can't recall now (@lognaturel do you remember maybe?). If that reason does not exist anymore we should fix that what should also address this issue.

**Comment by lognaturel** [comment]
I don't know specifically, sorry. I do know that small devices were a really important consideration initially. In particular, vertical space is still important to think about because it's helpful in some contexts to be able to fit multiple questions on a screen. We've prioritized readability/no distractions for each question over packing as many in as possible but it should still possible to show a few related questions in a field list.

**Comment by grzesiek2010** [comment]
ah maybe we wanted to increase the clickable area for some select questions (and we wanted to use even margins horizontally)? That rings a bell but for which appearance? I need to find it before changing anything.

**Comment by alyblenkin** [comment]
I added another screenshot in the description of this same spacing issue happening with the geopoint widget.

**Comment by grzesiek2010** [comment]
> ah maybe we wanted to increase the clickable area for some select questions (and we wanted to use even margins horizontally)? That rings a bell but for which appearance? I need to find it before changing anything.

It looks like it was the reason but we have to get rid of it now especially since we are going to implement a new way of displaying errors. See:
- https://github.com/getodk/collect/pull/5725#issuecomment-1816046868
- https://github.com/getodk/collect/pull/5725#issuecomment-1816050055
- https://github.com/getodk/collect/pull/5725#issuecomment-1816137571
