### ISSUE TITLE
Styling the project settings dialog

### ISSUE THREAD

**Issue by alyblenkin** [getodk/collect#5732]
We talked about this when we were implementing M3, and it wasn't easy to change to make it consistent at the time.

I think we can do some simple styling tweaks:

- Spacing 
- Move the cancel button to the right 
- Make the dialog radius consistent with the others
- Adding labels for the sections?

![Image](https://user-images.githubusercontent.com/7871340/266726095-51a29373-caf4-4018-9ff3-10c62b5e7026.jpg)

**Comment by alyblenkin** [comment]
I'll create a mockup before Tuesday for us to discuss

**Comment by lognaturel** [comment]
> Do we need to show "sandbox.getodk.cloud"?

It's there because for people who work across multiple servers, the project name may not be differentiating. For people who work on servers that require username and password, the username will be there too.

> This is also the only place where we use raster images instead of icons. We could use and icon with the colour to keep it consistent?

Do you mean the 📝 emoji? That's a user-provided character that can also be emoji. In the case of drafts, Central sets it to 📝. It should be a vector emoji. If you publish those forms, you'll see the first character of the project name there. You can change it in settings.

**Comment by alyblenkin** [comment]
@lognaturel, that's good feedback I was thinking maybe the server name doesn't need to be top-level information, but if the name isn't differentiating enough, that could be an issue.

**Comment by alyblenkin** [comment]
I've been playing around with a few ideas here https://www.figma.com/file/KFi9hIQdrRgo0rLqIC7Sg8/ODK-user-flows?type=design&node-id=2613%3A38622&mode=design&t=A9HfV9ov5ytOduTY-1

**Comment by alyblenkin** [comment]
Here is what I'm thinking. It's not drastically different, but it's a bit more consistent with the rest of the new designs.


![Image](https://github.com/getodk/collect/assets/7871340/1e38e8f9-e167-4134-9cfd-a9d2e80f6cda)
