### ISSUE TITLE
Fix spacing for read-only text widget 

### ISSUE THREAD

**Issue by alyblenkin** [getodk/collect#5751]
This is a follow-on issue from [#5725](https://github.com/getodk/collect/pull/5725#issuecomment-1731989207)

In the read-only text widget the answer is indented because the M3 text field has more padding. We want to fix this so everything is aligned to the left.

<img width="861" alt="Screenshot 2023-09-22 at 11 35 46 AM" src="https://github.com/getodk/collect/assets/7871340/153ba71e-f4dd-46ad-b746-d00da9af0d0a">

**Comment by grzesiek2010** [comment]
Ready-only widgets are under the hood represented by the same text widgets. The difference is that if it's read-only we want to display a text view instead of a text field. So far we have faked it by always displaying text fields but making the text field look like a text view if it's disabled (in ready-only mode). We achieved that by removing the background etc. what is not that easy with material components (because as you can see in the issue we have different margins).
I think we should stop doing that and introduce something less cumbersome. A good solution would be a custom view for those widgets that would contain both a text view and a text field but display only one element at a time depending on the state.

BTW. this applies not only to read-only text widgets but also to 
- external widgets 
- Bearing widget

generally it might used in widgets that start external apps/sensors. 
When such an app/sensor is not available we should switch to the manual mode and instead of displaying a Text view display a text field.

I will take a look a deeper look at this issue.
