### ISSUE TITLE
Audio button has no background

### ISSUE THREAD

**Issue by grzesiek2010** [getodk/collect#577]
#### Software and hardware versions 
Current master branch

#### Problem description
Audio button has no background.

#### Steps to reproduce the problem
1. Open "sample" form.
2. Go to the first question

#### Expected behavior
Audio button should look like before.

#### Other information 
It's coused by changes from #525:
[compileSdkVersion](https://github.com/opendatakit/collect/pull/525/files#diff-fa0f36229667501896e9f29c3a2a4b35R60)
[AudioButton](https://github.com/opendatakit/collect/pull/525/files#diff-ce9802d4c0f435bd3f26034d56b61e95R39)
**BEFORE:**
![before](https://cloud.githubusercontent.com/assets/3276264/23849398/c4a8fdf0-07db-11e7-93cd-49797d34f650.png)
**NOW:**
![now](https://cloud.githubusercontent.com/assets/3276264/23849408/c9387684-07db-11e7-9c55-fc32a85705a0.png)

@lognaturel you can mark this issue as "quick win".

**Comment by pratikmjoshi** [comment]
@grzesiek2010 Can I get to work on this?

**Comment by grzesiek2010** [comment]
I don't mind but @lognaturel assigns tasks so let's wait for her decision.

**Comment by pratikmjoshi** [comment]
Ok sure. I've fixed it though, so I'm ready to send the PR.

**Comment by lognaturel** [comment]
Yes please, @pratikmjoshi.

In general, for tasks that are well-scoped, it's ok to say "I am working on this" rather than asking for it. And @grzesiek2010, for issues you file, you absolutely can let people work on them!

The only time a core committer really has to be involved is when the issue isn't well defined or if it's not certain if or when it needs to be done.
