### ISSUE TITLE
Associating form types and automatically importing blank forms in the collect app.

### ISSUE THREAD

**Issue by supreme96** [getodk/collect#581]
It can be a useful feature to be able to to import blank forms to the collect app by simply opening them from a file manager. This is useful in the situations when the form has been downloaded to the device from sources outside the app such as a internet download or bluetooth transfer. 

Although this feature is not a necessity it will provide some convenience to technically inexperienced users or users new to the app.

**Comment by supreme96** [comment]
If this feature is required, I would love to work on it. I have a idea to do this. We will need to update the manifest to associate the form file types and make a background activity that moves the form file from it's current location on the devices to the `odk/forms/` folder. Then the form will automatically show up in the app.

**Comment by lognaturel** [comment]
I think this is a very interesting idea. That said, I imagine you'd have to associate with the XML file type which could be confusing because most XML files would fail.
 
Additionally, I don't know how practical it is to have a form that is not associated with a server. It could be filled out, certainly, but it could never be sent.

So I'm not sure that it would be useful for the true users of ODK who are leading field deployments. It might be helpful for developers but I think in general we can use `adb` as a quicker way to get forms on devices.
