### ISSUE TITLE
Do a round of memory profiling

### ISSUE THREAD

**Issue by lognaturel** [getodk/collect#5818]
#5777 revealed a memory leak.

Following that fix, we said we would do some additional memory profiling to identify other memory usage hot spots: https://github.com/getodk/collect/pull/5780#issuecomment-1767058396

While doing this memory profiling, we should take the opportunity to compare with v2023.1 so we can have a better sense of the memory impact of recent changes.

@grzesiek2010 did you already have some forms in mind? It would be good to try some with large internal and external secondary instances (choice lists in the form and attached CSVs) and with different predicate filter types (e.g. `someColumn = ${some_form_field}`, `startsWith(someColumn, ${some_form_field})`...)

**Comment by seadowg** [comment]
@grzesiek2010 there still an open question here I realised:

> @grzesiek2010 did you already have some forms in mind? It would be good to try some with large internal and external secondary instances (choice lists in the form and attached CSVs) and with different predicate filter types (e.g. someColumn = ${some_form_field}, startsWith(someColumn, ${some_form_field})...)

**Comment by grzesiek2010** [comment]
@lognaturel 
I don't have any particular form we could use but I agree that we should use something like you said. Probably something similar to what we had here: https://forum.getodk.org/t/looping-through-three-levels-of-data-from-attached-csvs-is-slow-in-web-form/44369/6?

**Comment by lognaturel** [comment]
Yes, that one is a perfect example. Maybe we just start with that one and see what we get comparing v2023.1 and the current `master`? If they're pretty similar, that may feel like enough.

**Comment by grzesiek2010** [comment]
According to our discussion above I've built 3 forms based on the one from the forum: https://forum.getodk.org/t/looping-through-three-levels-of-data-from-attached-csvs-is-slow-in-web-form/44369/6:
- a form with internal choices
- a form with external choices (with the `select_one_from_file` question)
- a form with external choices (with the `search` function)

They all use the same set of choices (10k households and 50k persons).

Here is the result showing the time needed to open such forms:

### First load time (no cache, no databases with choices)
| Form type | v2023.1.2 | master |
| ------------- | ------------- | ------------- |
| select from csv file | 4.2s | 1.8s |
| select with internal choices | 1.8s | 2.4s |
| select with the search function | 3s | 4s |

### Normal load time (with cache)
| Form type | v2023.1.2 | master |
| ------------- | ------------- | ------------- |
| select from csv file | 1.4s | 1.2s  |
| select with internal choices | 1.4s  | 1.1s  |
| select with the search function | 0.2s  | 0.3s  |

### Memory usage v2023.1.2
| Form type | opening a form | navigating in a form |
| ------------- | ------------- | ------------- |
| select from csv file | 70mb | 10mb |
| select with internal choices | 70mb | 10mb  |
| select with the search function | 10mb  | 5mb  |

### Memory usage master
| Form type | opening a form | navigating in a form |
| ------------- | ------------- | ------------- |
| select from csv file | 80mb | 10mb |
| select with internal choices | 80mb | 10mb  |
| select with the search function | 10mb  | 5mb  |

_*In all the cases the time and memory usage is the average value calculated based on ~10 attempts._

I didn't compare the time needed to navigate between questions because in all the cases everything works very smoothly.

The forms I've used: 
[forms.zip](https://github.com/getodk/collect/files/14117626/forms.zip)

@lognaturel it seems like it's enough or maybe I should check something else?
The only thing I've noticed is that when loading choices with the `search` function I can't do the same calculations to determine the number of repeats or like with the other two forms. I believe this might be just not supported but please let me know if you are familiar with it.

**Comment by lognaturel** [comment]
I'm a bit surprised that the form def cache makes such a big difference for the first two cases but I'm not particularly worried about it.

For this, we're interested in **memory**, not in time. We have tests in JavaRosa that show that the caching is effective at reducing time it takes to calculate choice lists and more broadly expressions with predicates but we have introduced some new data structures to do that. We believe that they mostly use shared references and won't be very big but we should know that with confidence.

We want to compare with [2023.1.2](https://github.com/getodk/collect/releases/tag/v2023.1.2) (not 2023.3.1) so that we're comparing the most recent caching with no caching at all.

It would be helpful to change values in the first select in the cascade. We expect that memory usage would now grow but it shouldn't be significant.

>  when loading choices with the search function I can't do the same calculations to determine the number of repeats 

That's right. The `search()` appearance/function exists totally outside of the rest of the form spec.

**Comment by grzesiek2010** [comment]
@lognaturel 
sorry don't know why I got focused on time but you are right we need to test memory usage too. I've updated the report. Everything seems fine to me and I don't see any differences.

**Comment by lognaturel** [comment]
Thank you! I think that gives us enough confidence to release without further profiling for now.
