### ISSUE TITLE
Adding menu icons

### ISSUE THREAD

**Issue by alyblenkin** [getodk/collect#5859]
**Problem**
It can be hard to scan and quickly find the menu item you're look for purely using text.

**Solution**
We want to make it easier for users to recognise the menu options by introducing icons

**Icons**
- Finalize all forms from drafts: [done all icon](https://fonts.google.com/icons?selected=Material%20Symbols%20Outlined%3Adone_all%3AFILL%400%3Bwght%40400%3BGRAD%400%3Bopsz%4024)
- Check for errors: [rule icon](https://fonts.google.com/icons?selected=Material%20Symbols%20Outlined%3Arule%3AFILL%400%3Bwght%40400%3BGRAD%400%3Bopsz%4024)
- Change language: [globe](https://fonts.google.com/icons?selected=Material%20Symbols%20Outlined%3Alanguage%3AFILL%400%3Bwght%40400%3BGRAD%400%3Bopsz%4024) 
- Project settings: [Settings gear](https://fonts.google.com/icons?selected=Material%20Symbols%20Outlined%3Asettings%3AFILL%401%3Bwght%40400%3BGRAD%400%3Bopsz%4024). Also updated in the [project settings dialog](https://www.figma.com/file/KFi9hIQdrRgo0rLqIC7Sg8/ODK-user-flows?type=design&node-id=3738%3A28069&mode=design&t=WFWRXwpGlibw67al-1).
- Change view: [eye](https://fonts.google.com/icons?selected=Material%20Symbols%20Outlined%3Avisibility%3AFILL%401%3Bwght%40400%3BGRAD%400%3Bopsz%4024)
- Record audio: [mic](https://fonts.google.com/icons?selected=Material%20Symbols%20Outlined%3Amic%3AFILL%401%3Bwght%40400%3BGRAD%400%3Bopsz%4024)
- Record location: [location](https://fonts.google.com/icons?selected=Material%20Symbols%20Outlined%3Alocation_on%3AFILL%400%3Bwght%40400%3BGRAD%400%3Bopsz%4024)
- Import QR code: [QR+](https://fonts.google.com/icons?selected=Material+Symbols+Outlined:qr_code_2_add:FILL@0;wght@400;GRAD@0;opsz@24&icon.query=Qr+code) 

![Image](https://github.com/getodk/collect/assets/7871340/cd807cf7-7119-4a65-8d2b-b58a2898edb8)

**Comment by alyblenkin** [comment]
@seadowg @grzesiek2010 - let me know if you want me to create a different issue for changing the checkbox to a [toggle](https://www.figma.com/file/KFi9hIQdrRgo0rLqIC7Sg8/ODK-user-flows?type=design&node-id=3738%3A27610&mode=design&t=pdTWx6QtPWOI8n2M-1) for recording audio or location.

**Comment by grzesiek2010** [comment]
@alyblenkin it's great you have mentioned replacing the checkbox with a toggle here in this issue because it allowed me to immediately identify problems that we would need to solve to do that and prepare one solution for both changes.
Working with the overflow menu turned out to be full of problems and small bugs I can't recall working with any other Android component like that recently that would be similarly difficult so I'm surprised...
The main problem is displaying a toggle instead of a checkbox which I've mentioned above. It's not possible to replace that checkbox if the menu item is displayed on the list (overflow menu) because its `showAsAction` attribute is set to `never`. It's also not possible to implement a whole custom layout for items displayed on such a list. To achieve something like that we would need to build our own popup menu with a custom layout, adapter etc. It would be something like: https://github.com/getodk/collect/pull/5865/commits/3bce05ee26ceb060e4c7dbfd204f3f03cd2aa9f4
It works but I'm not sure if it makes sense to implement such changes in our menus (mixing already existing menu providers with such custom popup menus) just for that one small change (checkbox -> toggle).
What do you think @seadowg? I've implemented it but looking at the complexity now I'm leaning towards not doing that.

**Comment by seadowg** [comment]
> What do you think @seadowg? I've implemented it but looking at the complexity now I'm leaning towards not doing that.

Yeah agreed. I don't think anything ever be worth creating a custom popup menu system for. 

Do we get subtext on menu items? I like the design using icons and subtext [here](https://www.figma.com/file/KFi9hIQdrRgo0rLqIC7Sg8/ODK-user-flows?type=design&node-id=3738-27810&mode=design&t=q0gU37thraJ08jI3-0). Even if we don't I think using icons and changing the action text works well.

**Comment by grzesiek2010** [comment]
> Do we get subtext on menu items? I like the design using icons and subtext [here](https://www.figma.com/file/KFi9hIQdrRgo0rLqIC7Sg8/ODK-user-flows?type=design&node-id=3738-27810&mode=design&t=q0gU37thraJ08jI3-0). Even if we don't I think using icons and changing the action text works well.

No, it's also not possible without a custom adapter so I think the option is either to keep the checkbox or remove it and display different icons and titles for enabled/disabled modes.

**Comment by seadowg** [comment]
> I think the option is either to keep the checkbox or remove it and display different icons and titles for enabled/disabled modes.

I think we should go with that. What do you think @alyblenkin?

**Comment by alyblenkin** [comment]
> No, it's also not possible without a custom adapter so I think the option is either to keep the checkbox or remove it and display different icons and titles for enabled/disabled modes.

Thanks for the feedback! This is super helpful to understand the complexity behind it. I think displaying different icons and titles for the states works well. So maybe something [like this](https://www.figma.com/file/KFi9hIQdrRgo0rLqIC7Sg8/ODK-user-flows?type=design&node-id=3817%3A22304&mode=design&t=1Sl2EE7iK04T6R6q-1).

**Comment by alyblenkin** [comment]
@grzesiek2010 @seadowg - I've removed any changes to the checkbox from this issue. Hélène thinks we should leave it as for now.

**Comment by lognaturel** [comment]
If we could have done the toggle easily, great. But given that we can't, seems like we should leave it alone because it's not very common to use that feature and it's unlikely that the checkbox is currently causing confusion.

**Comment by grzesiek2010** [comment]
Yeah as I said above I'm not a fan of that complexity that is required to display something else than a checkbox so I did not implement that.. @alyblenkin if you want you can take a look at the new icons https://github.com/getodk/collect/pull/5865

**Comment by alyblenkin** [comment]
@grzesiek2010 - completely get it! I'll have a look at the new icons now.
