### ISSUE TITLE
Auto send should retry if it fails

### ISSUE THREAD

**Issue by seadowg** [getodk/collect#5946]
Currently, auto send only retries if there is a problem acquiring the instance lock (other instance jobs are running). It should also retry if there is a network error for instance.

## Acceptance

- [ ] Given I'm using a project connected to a Central server
And I have auto send enabled
And I've revoked access for the app user for the project in Central
When I finalize a form
And auto send fails
And I add a new app user to Central and configure my project to use it (by changing the server URL)
Then my form is eventually submitted successfully

## Notes

We have a way to implement retries for background jobs that we already use for Match Exactly (in `SyncFormsTaskSpec`. We probably want to use the same back off settings (60s delay and exponential), but we won't want a max number of retries - we should continue to attempt to send until forms are all submitted.

This set up will result in the job running and failing forever if the user's credentials are no longer valid, and there won't be a prompt to change them. If we feel this isn't good enough, we can add a prompt later as an enhancement.

**Comment by lognaturel** [comment]
Followup at #6120 / #6121

This turned out more complicated than we expected and I want to capture a few notes from various places for documentation and our future selves.

* The prior implementation had a job triggered based on connection toggle. That meant if you were on a cell connection, had autosend configured to "WiFi only", and then connected to a WiFi network, autosend would not be triggered
* We stopped collecting analytics around the "cellular only" option after we saw it was in significant use. We hypothesize that users want to avoid inadvertently connecting to unsecure or not internet-enabled wifi hotspots that might be around. For this reason, we want to ensure continuity for this setting.
* The main cases we want retry with exponential backoff for are client-side timeouts and temporary server errors like 429s and some 500s.
* Write timeouts are configured to be after 60s so we hypothesize that they're not very common but we don't know.
