### ISSUE TITLE
Update copy on end screen

### ISSUE THREAD

**Issue by alyblenkin** [getodk/collect#5948]
We are updating the end screen message to make it more scanable and adding the link to the forum so users can learn more.

### Updated copy

**Finalized forms are not editable.**

If you need to make edits to your form, “Save as draft” until you’re ready to send. [Learn more](https://forum.getodk.org/t/finalized-forms-will-not-be-editable-starting-in-collect-v2024-1/42007)

![Image](https://github.com/getodk/collect/assets/7871340/02808f4b-4748-4acd-804e-cf38519c49d0)

**Comment by grzesiek2010** [comment]
Currently, we display different messages depending on the state:
- if auto-send is enabled: `You will not be able to make edits once you send. If you need to make changes, "Save as draft" until you're ready to send.`
- if auto-send is disabled: `You will not be able to make edits once you finalize. If you need to make changes, "Save as draft" until you're ready to send.`
- if saving drafts is disabled: `You will not be able to make edits once you finalize.`

We need to update all of them so:
- if auto-send is enabled: `Sent forms are not editable. If you need to make edits to your form, “Save as draft” until you’re ready to send. Learn more`
- if auto-send is disabled: `Finalized forms are not editable. If you need to make edits to your form, “Save as draft” until you’re ready to send. Learn more`
- if saving drafts is disabled: `Finalized forms are not editable. Learn more`

Does that sound right?

**Comment by alyblenkin** [comment]
> We need to update all of them so:
> 
> * if auto-send is enabled: `Sent forms are not editable. If you need to make edits to your form, “Save as draft” until you’re ready to send. Learn more`
> * if auto-send is disabled: `Finalized forms are not editable. If you need to make edits to your form, “Save as draft” until you’re ready to send. Learn more`
> * if saving drafts is disabled: `Finalized forms are not editable. Learn more`
> 
> Does that sound right?

Yes, looks good to me!

**Comment by grzesiek2010** [comment]
> Yes, looks good to me!

Cool, could the Lear more link be a separate element like we had in the case of the Google Drive deprecation banner?
![image](https://github.com/getodk/collect/assets/3276264/3dbb9f6d-5032-44c4-a18d-388dfa9b6dd2)

In your example, it's a part of the second string which makes it difficult to implement because:
- if we wanted to make it clickable (only the `Learn more`) part then it might be difficult to handle translations especially taking into account that we support both left-to-right and right-to-left languages.
- in the case where saving drafts is disabled we would display only that short title: `Finalized forms are not editable.` so having the Learn more link as a part of that title wouldn't look good.

**Comment by alyblenkin** [comment]
> Cool, could the Lear more link be a separate element like we had in the case of the Google Drive deprecation banner? !

That's good to know. In that case, I think we should do something like mockup [2 & 3 in Figma](https://www.figma.com/file/KFi9hIQdrRgo0rLqIC7Sg8/ODK-user-flows?type=design&node-id=4222%3A16915&mode=design&t=whhabWDM9VOeHDDz-1) with the button aligned to the left. I know it's aligned to the right in the Google Drive banner, but it makes the eye zig-zag around with all the other elements on the end screen. 

We also broke up the text to make it easier to scan, and I think we should keep it broken up even though it makes it longer with the 3 sections. 

> In the case where saving drafts is disabled, we would display only that short title: Finalized forms are not editable. so having the Learn more link as a part of that title wouldn't look good.

I was thinking "Learn more" would go on the second line like in the mockup above.

**Comment by grzesiek2010** [comment]
@alyblenkin sorry, it turned out that what you designed initially was doable and not that difficult as I thought so I've implements that.
Please review the pull request.

I have only one question... we display that warning in three states (you can see a screenshot for every state in the pull request):
- when auto send is disabled
- when auto send is enabled
- when saving as draft is disabled (and auto send is disabled)

but if auto send is enabled and saving drafts is disabled there is no warning:
![Screenshot_1707487403](https://github.com/getodk/collect/assets/3276264/9892e82d-6209-4581-a869-71615639c32d)

isn't it a case that we have missed? I think it should be consistent with the last case mentioned above `when saving as draft is disabled (and auto send is disabled)` and we should display `Sent forms are not editable` (just the title and the link to the forum with no message). What do you think?

**Comment by alyblenkin** [comment]
> @alyblenkin sorry, it turned out that what you designed initially was doable and not that difficult as I thought so I've implements that.

Wonderful news!! I was a bit sad about that :) 

> isn't it a case that we have missed? I think it should be consistent with the last case mentioned above when saving as draft is disabled (and auto send is disabled) and we should display Sent forms are not editable (just the title and the link to the forum with no message). What do you think?

That's a good point. I think we could take advantage of the opportunity to inform people. I don't think it would be harmful in any way to be consistent with the message "Sent forms are not editable" with the link. This might change in the future if we allow "Sent" forms to be editable, but that's a later thing for us to consider. 

I will file another issue.
