### ISSUE TITLE
Background in ranking items dialog in rank widget is white

### ISSUE THREAD

**Issue by dbemke** [getodk/collect#6047]
#### ODK Collect version
the master version 38a4b0ec4eea71fda685493b3931137b11ec5621
#### Android version
10, 14
#### Device used
Redmi t,Pixel 7a
#### Problem description
In rank widget in the dialog with choices all colors in the background changed to white.
The issue doesn’t occur in the store version 2024.1.3
![rank](https://github.com/getodk/collect/assets/56479916/03936aaf-b178-4a72-a545-62bc0484ef5d)

#### Steps to reproduce the problem
1. Set light mode in Collect.
2. Go to All widgets form to rank widget.
3. Tap "Rank items".
#### Expected behavior
![store](https://github.com/getodk/collect/assets/56479916/e8f86fbd-8ed8-4672-9a43-004b1e6b5d76)

**Comment by grzesiek2010** [comment]
The color of items didn't change but the color of the dialog did (https://github.com/getodk/collect/pull/6025). Now it's more gray and that's why the difference is not visible enough.
@alyblenkin what do you think? What color would you use other (for the items that you can rank)?

**Comment by alyblenkin** [comment]
> The color of items didn't change but the color of the dialog did (#6025). Now it's more gray and that's why the difference is not visible enough. @alyblenkin what do you think? What color would you use other (for the items that you can rank)?

Good spot! Could we make it the same gray as the text fields, which I believe is our surface container highest.

**Comment by grzesiek2010** [comment]
> Could we make it the same gray as the text fields, which I believe is our surface container highest.

This won't be enough. The difference between `colorSurfaceContainerHighest` and `colorSurfaceContainerHigh` (the color we used to display dialogs) is not visible enough.
![Screenshot_1711638743](https://github.com/getodk/collect/assets/3276264/960681ae-f967-4714-9b32-7dd3a9160e0a)

**Comment by alyblenkin** [comment]
Got it. Do we need to adjust the highest surface container to make the difference between them darker?

I believe we made the highest is #F2F2F2, so if we try #E0E0E0 or #EBEBEB the difference should be darker.

**Comment by grzesiek2010** [comment]
| #EBEBEB  | #E0E0E0 |
| ------------- | ------------- |
| ![Screenshot_1711643606](https://github.com/getodk/collect/assets/3276264/ce292bee-57d9-48f6-a9b8-f0bfcf98c882) | ![Screenshot_1711643680](https://github.com/getodk/collect/assets/3276264/a10f8b02-e788-45af-b0bf-f1481b99584a) |

I think the darker one looks better. The first one might not be visible in daylight. Any thoughts @alyblenkin?
`colorSurfaceContainerHighest` is the one we use to display the banner in the form end view and the no-errors pill (see related issue https://github.com/getodk/collect/issues/6046). @alyblenkin what colors should we use in those cases instead?

**Comment by grzesiek2010** [comment]
@alyblenkin I have the same problem with https://github.com/getodk/collect/issues/5845. The bottom sheet has that `Learn more about MBTiles` info section:
![image](https://github.com/getodk/collect/assets/3276264/8e99d320-f410-4924-b4e9-db47432d8f30)
and if I try to use the gray color we use in the form end view:
![image](https://github.com/getodk/collect/assets/3276264/20002d83-c718-458d-9026-7a298d489ac7)
It's not visible because the bottom sheet dialog has a darker background by default like normal dialogs. 

It would be good to decide what color should be used in such cases.

**Comment by alyblenkin** [comment]
> It's not visible because the bottom sheet dialog has a darker background by default like normal dialogs.

That's too bad - the new colour mapping isn't ideal in all cases! I'm not sure we want to introduce another colour. Another alternative I can think of is [creating a divider ](https://www.figma.com/file/KFi9hIQdrRgo0rLqIC7Sg8/ODK-user-flows?type=design&node-id=4914%3A17895&mode=design&t=WMCzD9gZo7gX8zJA-1)between the info section and the actions.

**Comment by grzesiek2010** [comment]
> Another alternative I can think of is [creating a divider ](https://www.figma.com/file/KFi9hIQdrRgo0rLqIC7Sg8/ODK-user-flows?type=design&node-id=4914%3A17895&mode=design&t=WMCzD9gZo7gX8zJA-1)between the info section and the actions.

I can do that for that new bottom sheet but this does not solve the problem with the ranking question type.

**Comment by alyblenkin** [comment]
@grzesiek2010 @seadowg, I'm wondering if we should adjust the surface colours again because they're making things pretty tricky. 

We need to figure out a way to create more colour options because we need a higher contrast for the ranking question type, and #E0E0E0 works well. However, we want the message on the end screen to be much lighter because the text is harder to read with a darker background. #EBEBEB is probably the darkest we would want for the messages because we had to switch it from blue to grey. Another idea is to remove the background colour for the messages so they are consistent throughout (end screen and bottom sheet). What do you think? Happy to chat about it too if that's easier!

**Comment by seadowg** [comment]
@alyblenkin We're currently in a situation where our "surface container low", "surface container" and "surface container high" are all the same so that's probably leading to some of these problems with contrast. It might be worth taking a step back and redefining the whole color set. 

When we converted to Material 3, the Android components library wasn't using the tonal surface colors yet so we weren't able to use the [Theme Builder](https://material-foundation.github.io/material-theme-builder/) properly where as we can now. Maybe it would be good to try defining a color palette there and export for the "Android Views (XML)" for us and we can define all the colors in one go?

**Comment by alyblenkin** [comment]
Capturing the summary from our group chat on slack here:

@seadowg we will find time to pair on plugging in the colours we already use into the tonal palette and hopefully it generates something that works well. 

@grzesiek2010 I don't think it's a huge deal for use to use the lighter grey for now for the ranking question until we sort out the colours. And as Callum said, the worse case is the beta goes out with the ranking problem.

**Comment by alyblenkin** [comment]
@grzesiek2010 - I wanted to give a quick update on this one. 

@seadowg and I briefly tried the [theme builder](https://material-foundation.github.io/material-theme-builder/) and added our colours, and it seems better than what they had before! It's not perfect and will need some tweaking, but they also now have a [figma plugin](https://www.figma.com/community/plugin/1034969338659738588/material-theme-builder) that I can play around with to propose different options.  I'll aim to do that as part of this release so that we can unblock this issue and avoid running into these same issues.

**Comment by seadowg** [comment]
Let's go with using `colorSurfaceContainerHighest` for now (like in https://github.com/getodk/collect/issues/6047#issuecomment-2025476840). We're looking to increase the contrast between the tonal colors, so this should get better when we do that next release.

**Comment by alyblenkin** [comment]
> Let's go with using `colorSurfaceContainerHighest` for now (like in [#6047 (comment)](https://github.com/getodk/collect/issues/6047#issuecomment-2025476840)). We're looking to increase the contrast between the tonal colors, so this should get better when we do that next release.

Did you happen to see this https://github.com/getodk/collect/issues/6171, @seadowg? I think the drag icon will significantly improve this interaction.

**Comment by seadowg** [comment]
> Did you happen to see this https://github.com/getodk/collect/issues/6171, @seadowg? I think the drag icon will significantly improve this interaction.

Yeah it's definitely nicer! I think we want a quick fix option we can apply before this next release though, so I'm still in favour of making the color change first.

**Comment by alyblenkin** [comment]
> Yeah it's definitely nicer! I think we want a quick fix option we can apply before this next release though, so I'm still in favour of making the color change first.

Makes sense!
