### ISSUE TITLE
Adding a container for select one questions

### ISSUE THREAD

**Issue by alyblenkin** [getodk/collect#6119]
Currently Collect has an older Material partial divider between the options for radio buttons and checkboxes , but we would like to improve the experience by adding a light border around the option to help with visual processing and make it easier to select. 

The border isn't part of the M3 components, so this would be a deviation. The border needs to be grey, so that it doesn't become visually distracting from the content.

- [Minimal select ](https://www.figma.com/design/KFi9hIQdrRgo0rLqIC7Sg8/ODK-user-flows?node-id=5366-26767&t=c3kxqniaPs8uDe6R-1)
- [Select autocomplete ](https://www.figma.com/design/KFi9hIQdrRgo0rLqIC7Sg8/ODK-user-flows?node-id=5366-20383&t=c3kxqniaPs8uDe6R-1)
- [Select likert scale](https://www.figma.com/design/KFi9hIQdrRgo0rLqIC7Sg8/ODK-user-flows?node-id=5562-117054&t=c3kxqniaPs8uDe6R-1)
- [Radio buttons and checkboxes](https://www.figma.com/design/KFi9hIQdrRgo0rLqIC7Sg8/ODK-user-flows?node-id=5258-107266&t=c3kxqniaPs8uDe6R-1)
- [2 column fixed grid](https://www.figma.com/design/KFi9hIQdrRgo0rLqIC7Sg8/ODK-user-flows?node-id=5258-107113&t=c3kxqniaPs8uDe6R-1)
- [3 column fixed](https://www.figma.com/design/KFi9hIQdrRgo0rLqIC7Sg8/ODK-user-flows?node-id=5258-107115&t=c3kxqniaPs8uDe6R-1)
- [3+ columns / packed ](https://www.figma.com/design/KFi9hIQdrRgo0rLqIC7Sg8/ODK-user-flows?node-id=5258-107117&t=c3kxqniaPs8uDe6R-1)
- [Images, no buttons](https://www.figma.com/design/KFi9hIQdrRgo0rLqIC7Sg8/ODK-user-flows?node-id=5375-36142&t=c3kxqniaPs8uDe6R-1)
- [Audio/video attached to options](https://www.figma.com/design/KFi9hIQdrRgo0rLqIC7Sg8/ODK-user-flows?node-id=487-20892&t=73BhGqbGM4r8rQOf-1)

![Image](https://github.com/getodk/collect/assets/7871340/6f9c66f5-e15d-41fb-8e68-6cfcd5b47c15)

[Figma](https://www.figma.com/file/KFi9hIQdrRgo0rLqIC7Sg8/ODK-user-flows?type=design&node-id=5023%3A37148&mode=design&t=uLD5lGgJxIhJP4Ng-1)

**Comment by lognaturel** [comment]
Here's a related forum thread: https://forum.getodk.org/t/better-radio-buttons-and-checkboxes/27775

I think we need to consider the impact on vertical spacing. Does it have to be as much as in the mockups? If so, maybe we should consider introducing this as a new appearance rather than the default. This additional spacing works really well when there are few options and it generally helps with tappability but the tradeoff is that there can be less context and more to scroll through with a lot of options. Not sure how to reason about that tradeoff!

Did you consider shading in addition to an outline to really make the selected item stand out? I'm not sure it's a good idea but feels worth trying.

**Comment by alyblenkin** [comment]
I love that the user linked to the [Laws of UX](https://lawsofux.com/fittss-law/) website. 

I think there are a few factors at play here that are impacting the vertical spacing in the mockups, which we can play around with and adjust! 

- I increased the height of the containers from 40px to 48px. I think ours are around 40px, but I wanted to check when we discuss this on Tuesday. 
- The current list of options is stacked, but I added 20px between each element. 

I think we should prioritize making the buttons easier to interact with and process, rather than trying to reduce vertical spacing so the user doesn't have to scroll. If they are too close together you may have the context, but it's harder to read. I've played around with a few more variations in figma with longer lists so we can see the trade-offs.

> Did you consider shading in addition to an outline to really make the selected item stand out? I'm not sure it's a good idea but feels worth trying.

I considered the selected state having a filled button, but not when unselected. I added a few mockups to show you what it would look like.

**Comment by grzesiek2010** [comment]
@alyblenkin, you asked for my thoughts, so here they are.

I like your proposal. It would be beneficial to file separate issues not only for select one/multiple but also for appearances like non-buttons.

My only concern is that it might disrupt some specific forms. I vaguely remember that a long time ago, we changed something small, like spacing or the divider between choices, and someone complained because they used selects to build some type of grid view. That small change made it no longer work well. Unfortunately, I can't find the issue now. However, I still believe it would be a nice change. If there are cases like that, it might be a good opportunity for us to learn about them and perhaps add new appearances to handle them specifically.

**Comment by alyblenkin** [comment]
> It would be beneficial to file separate issues not only for select one/multiple but also for appearances like non-buttons.

I can do file separate issues - I figured we might want to split them up!

> My only concern is that it might disrupt some specific forms. I vaguely remember that a long time ago, we changed something small, like spacing or the divider between choices, and someone complained because they used selects to build some type of grid view. That small change made it no longer work well. Unfortunately, I can't find the issue now. However, I still believe it would be a nice change. If there are cases like that, it might be a good opportunity for us to learn about them and perhaps add new appearances to handle them specifically.

I share your concern! I'm sure we will have to make adjustments based on what we learn, but like you said, those cases will help us think about the best solutions for those problems. My hope is that it makes selecting options a lot easier, especially for the non-button appearances. It will also be consistent with what we've implemented with web forms.

**Comment by seadowg** [comment]
@alyblenkin @grzesiek2010 should we close this now we have the other issues?

**Comment by alyblenkin** [comment]
I'm happy to close this issue now, if you are @grzesiek2010.
