### ISSUE TITLE
Answer entered in masked number questions can be seen on android keyboard in landscape view

### ISSUE THREAD

**Issue by WKobus** [getodk/collect#6122]
#### ODK Collect version
the master version b3cd4a057832c48ab04c0c380274e74e4ee28fe2

#### Android version
10, 11, 14

#### Device used
Redmi 9T, Galaxy M12, Pixel 7a

#### Problem description
Answer entered in masked number questions can be seen on android keyboard in landscape view.

#### Steps to reproduce the problem
1. Open masked text form
[masked_text.xlsx.txt](https://github.com/getodk/collect/files/15187325/masked_text.xlsx.txt)
2. Go to any number question
3. Input numbers
4. Rotate device to landscape view

#### Expected behavior
Answer entered in masked number question should be hidden on android keyboard in landscape view

**Comment by grzesiek2010** [comment]
The issue we're facing is that we can create an EditText that only allows entering numbers and is password-protected if it's a standard numeric text field without any variations. However, in our case, when we use integer questions, it is `TYPE_NUMBER_FLAG_SIGNED`, and for decimal questions, it is `TYPE_NUMBER_FLAG_DECIMAL`. The `isPasswordInputType` method from the `TextView` class demonstrates this limitation:

```
    static boolean isPasswordInputType(int inputType) {
        final int variation =
                inputType & (EditorInfo.TYPE_MASK_CLASS | EditorInfo.TYPE_MASK_VARIATION);
        return variation
                == (EditorInfo.TYPE_CLASS_TEXT | EditorInfo.TYPE_TEXT_VARIATION_PASSWORD)
                || variation
                == (EditorInfo.TYPE_CLASS_TEXT | EditorInfo.TYPE_TEXT_VARIATION_WEB_PASSWORD)
                || variation
                == (EditorInfo.TYPE_CLASS_NUMBER | EditorInfo.TYPE_NUMBER_VARIATION_PASSWORD);
    }
``` 

I kind of hacked it by using the transformation method (PasswordTransformationMethod) directly: https://github.com/getodk/collect/blob/master/collect_app/src/main/java/org/odk/collect/android/views/WidgetAnswerText.kt#L63
However, this doesn't work in landscape mode when the EditText is in full-screen mode - the transformation method doesn't function, (any) including the password transformation.

What can we do about this? Here are some options:
- Disable full-screen mode for EditTexts (either entirely or only when the masked appearance is used). This is not an issue with larger devices, as they use a floating keyboard instead of full-screen mode, so there would be no difference.
- Stop supporting the masked appearance in integer and decimal question types (or only use positive numbers in integer questions when the masked appearance is used).
- Leave it as it is since it's not a critical issue and, as mentioned above, only affects smaller devices without a floating keyboard in landscape mode.

@seadowg @lognaturel 
what do you think? I would vote for the first option.

**Comment by seadowg** [comment]
I'd vote for option 2 (don't support masked for integer and decimal questions). It seems like a reasonable trade off. Not opposed to option 1 though if that's everyone else's preference: it just seems like even more maintenance to a feature that already feels like it's got a undeservedly high code cost.

**Comment by lognaturel** [comment]
I find full-screen mode pretty disorienting so I'd be happy to do away with it if it's a change that's easy to make and understand.

But I do see @seadowg's point and am fine with either of the other two options, really. Sorry I don't have a more helpful opinion here!

**Comment by grzesiek2010** [comment]
> I find full-screen mode pretty disorienting so I'd be happy to do away with it if it's a change that's easy to make and understand.

It is easy but is it ok from the UI perspective? @alyblenkin what do you think? It wouldn't be possible to answer questions on smaller devices in landscape mode I guess.
@alyblenkin if you want I can create an apk with that change for you so that you can play with it.

**Comment by alyblenkin** [comment]
> @alyblenkin if you want I can create an apk with that change for you so that you can play with it.

That would be great, if it's not too much work!

**Comment by alyblenkin** [comment]
I think I'm leaning towards option 2 without playing around with it because we could make it clear in the documentation that we don't support masked for integer and decimal questions and that wouldn't be as confusing from a user experience perspective.

**Comment by lognaturel** [comment]
I didn’t realize it would be impossible to fill in. That doesn’t sound like a good option, then. Happy to go with what @alyblenkin prefers!
