### ISSUE TITLE
Unable to change an offline layer to "none”

### ISSUE THREAD

**Issue by dbemke** [getodk/collect#6228]
#### ODK Collect version
the master version f63cda2e8af1be7b0dfdf8a2c59908ae7fa5a00b
#### Android version
10, 14
#### Device used
Redmi 9T, Pixel 7a
#### Problem description
Unable to change an offline layer to "none” after other layer was chosen before. The issue occurs both in the map view and in Collect map settings. In select layers both the previous offline layer and "none" are selected before saving the layer
#### Steps to reproduce the problem
1. Go to any map and tap the offline layers icon.
2. Add, select and save an offline layer.
3. Tap the offline layer icon and try to select and save "none”.
4. Tap the offline layer icon and check which layer was saved.
#### Expected behavior
It should be possible to select "none”.

**Comment by seadowg** [comment]
@grzesiek2010 I won't get a chance to look at this, but it looks to me like it's a bug in `SingleSelectViewModel` - setting the selection back to `null` will always return to the "fallback" selection in the data. Basically you should be able to do this:

```kotlin
val data = MutableLiveData(listOf(SelectItem("blah", null, false), SelectItem("foo", null, true)))
val singleSelectViewModel = SingleSelectViewModel(data)
singleSelectViewModel.select("blah")
singleSelectViewModel.clear()
singleSelectView.getSelected() // null
```

Instead of `null` we'd end up with `"foo"` selected. We probably just need a test and a fix there.
