### ISSUE TITLE
Change in the way ranges look

### ISSUE THREAD

**Issue by dbemke** [getodk/collect#6288]
#### ODK Collect version
the master version a9c57b94bd7d935e4a62cfd9052066eb15ec7328
#### Android version
10, 14
#### Device used
Redmi 9T, Pixel 7a
#### Problem description
The progress in geopoint widget and range widget changes (a dot at the end and the space at the end of filled part). 
![range](https://github.com/user-attachments/assets/c1337c28-ddab-456a-bc62-5092f0c2fa8e)
![lodation](https://github.com/user-attachments/assets/06552bea-5fe9-4200-a7a8-584aba10ce8d)

#### Steps to reproduce the problem
1. Go to All question types form.
2. Check geopoint widget.
3. Check range widget

**Comment by seadowg** [comment]
@alyblenkin probably worth having a look at this!

**Comment by grzesiek2010** [comment]
In the location dialog, it might be ok but it doesn't look good in the range widget I think.

**Comment by alyblenkin** [comment]
I think both cases are pretty confusing. 

For the range widget, we should use the [slider](https://m3.material.io/components/sliders/guidelines#70a70b78-c033-4a0b-85f7-43ed8696d138). 

In the geopoint dialog, I think we can use the [progress bar](https://m3.material.io/components/progress-indicators/guidelines#28b13c8b-6aa5-4ad6-b7cf-1c13a13b3063), but avoid breaking it up into two sections because it's not clear what's happening.
