### ISSUE TITLE
Only create/update local entities for forms using entity spec `v2024.1`

### ISSUE THREAD

**Issue by lognaturel** [getodk/collect#6384]
Currently, if a CSV attachment is marked with entityList=true in the form manifest, it is processed as an Entity List and submissions to that form may update and create Entities offline.

This means that as soon as a user connects to a server that produces entityList=true in the manifest, they will start getting offline Entities in Collect, even if they are using older form versions that don't include `branchId` and `trunkVersion`. Central would like to guarantee that only submissions with those attributes had offline effects in clients.

To prevent problems like these, Collect should only create/update local entities for forms that use entity spec `v2024.1`. If a form has a spec version greater than `v2024.1` it should fail to parse as normal.

**Comment by seadowg** [comment]
@lognaturel marking this as ready as I don't think I have any disagreements or anything to add!

**Comment by seadowg** [comment]
Actually as soon as I got into it, I realized I don't understand it!

> Ideally we could process CSV attachments as offline Entity Lists only if entityList=true AND the form definition includes those two attributes.

I'm not sure that this is quite right. Some forms that refer to entities might be purely follow up and so won't include an `entity` node. Because of that, I think we always want to load local entities (as opposed to their CSV) in forms that reference an instance with a name matching a local entity list.

Do you mean we **only update the local entity list from forms that include the two attributes**? In that world, registration forms will always create local entities (as they don't include the attributes anyway), but update forms will only update local entities if they include `trunkVersion`/`branchId`. Alternatively, we could only modify local entity lists from forms that use entity spec `v2024.1`.

**Comment by seadowg** [comment]
@lognaturel and I discussed this on a call. I'll update the issue description, but basically:

* We want to use local entities (from the DB) for follow up/update forms regardless of entity spec versions as there are performance benefits
* Collect should still reject the next entity spec version (not just not create local entities)
* Collect should only create/update local entities if the form entity spec version is `v2024.1` to avoid local updates and server updates getting into a bad state
