### ISSUE TITLE
Difference in data between Central and Collect when sending finalized entity pulldata form after updating entity

### ISSUE THREAD

**Issue by WKobus** [getodk/collect#6464]
#### ODK Collect version
the master version 4603e6782245bf94bbf7b299b82ccbacae16a097
#### Android version
10, 14 
#### Device used
Redmi 7, Galaxy M23
#### Problem description
There is difference in data between Central and Collect in entity pulldata form after updating entity. In Collect after finalizing form and updating entity selected in entity pulldata form, there is entity data from update form, however after sending this entity pulldata form to central data on central is same as when the form was finalized.
This issue may be connected to issue #6382 
#### Steps to reproduce the problem
1. Scan user "Entity pulldata" from project https://staging.getodk.cloud/#/projects/103
2. Open Cactus registration form, fill it and finalize
3. Open entity pulldata form
4. In first question type Tag from previously finalized cactus registration form and finalize form
5. Open Cactus monitoring form select entity from previously finalized cactus registration form, fill form and send or finalize it
6. Go to ready to send and open entity pulldata form
7. Check data and send entity pulldata form
8. Go to central submission tab for entity pulldata form and check data from sent form
#### Expected behavior
Data in entity pulldata form should be same in Collect and on central after sending it

**Comment by seadowg** [comment]
@WKobus could you record a video of the problem here? I'm pretty sure I understand what's happening, but I want to double-check you're definitely seeing the same thing.

As far as I can tell, this is expected but a good example of a confusing scenario with entities. In step 3 and 4, you fill a form with a selected entity and then in 5 you update that same entity. When you open the submission created in step 3 and 4, you see the data from the update made in 5 because Collect reruns calculations and gets the up-to-date entity values even though this is not what's in the submission. As you point out, this is another instance of #6382. A good thing to check when seeing problems like this is the actual submission file on disk rather than viewing it through Collect.

**Comment by WKobus** [comment]
@seadowg Yea, here is the video with reproduction of issue, at the end of video you can see data that is visible in Collect and below the video I uploaded screenshot with data that was sent to Central.


https://github.com/user-attachments/assets/ea21ce7a-871e-4a28-83e4-ca98ad388ec7


![centralData](https://github.com/user-attachments/assets/84e61123-4846-4308-b89e-1b0144dda8a8)

**Comment by seadowg** [comment]
@WKobus the video freezes when you open the pull data form to view the data, but it looks like you're editing the finalized form? That shouldn't be possible.

That aside, it looks like this is expected to me, and it's just #6832. Do you agree?

**Comment by WKobus** [comment]
@seadowg Oh, sorry I didn't see that video freezes, in the video I think I just opened entity pulldata form from start new form, something wrong happened with the video I guess, but yea I agree that the issue looks like #6832
