### ISSUE TITLE
Entities after upgrading to the current master

### ISSUE THREAD

**Issue by dbemke** [getodk/collect#6502]
#### ODK Collect version
the master version f38ba7ed24b2c810b8ddfe4aaf7bcbdefaf6bc19
#### Android version
10, 14
#### Device used
Redmi 9T, Pixel 7a
#### Problem description
After upgrading from beta 7 to the current master entities db files are wiped (no entities from the server or locally created) but entities are visible in the list of update and follow-up forms. Afterwards if a user finalizes/sends a draft of the registration form, entities are removed from the list in update forms and there’s only the new entity. 
Should entities be visible in update and follow-up forms after upgrading (and wiping entities) or just locally created entities should be removed in db files and update forms?
#### Steps to reproduce the problem
1. Install v2024.3.0 beta 7.
2. Download a project with registration and update for with the new entity spec and some entities in the dataset.
(e.g. user trees https://staging.getodk.cloud/#/projects/113/app-users )
3. Go to the registration form and save it as draft.
4. Upgrade to the current master.
5. Open the update form (there are some entities).
6. Go to the draft and send it.
7. Open the update form (there’s only the sent entity).

**Comment by lognaturel** [comment]
~This is expected and I think it’s ok because it only affects upgrades from a beta version.~

This is not quite what I expected it to be at first read. We should find out why entities available in step 5 aren't still available in step 7.

**Comment by lognaturel** [comment]
When you open the update form in step 5, Collect doesn't yet know that it's dealing with an Entity List because it hasn't made a form update request to the server. That means it loads the CSV in memory and shows all existing Entities.

Then step 6 (or finalizing any filled form that results in Entity creation) creates the `trees` Entity List table and populates it with the Entity that's created by finalization.

In step 7, Collect now sees the Entity List table and loads Entities from there. Only the ones that were locally created are included.

If you refresh from the server after that, the Entities on the server are merged into the local list and everything should look as expected.

It's not ideal, but I think it's easy enough to explain to users. Basically, if you're upgrading from a beta, we recommend first submitting all finalized forms. After you upgrade, you need to make sure to refresh from the server before you take any other action.

**Comment by seadowg** [comment]
As far as I can tell, this makes sense. In step 5 you're loading entities from the CSV and then in step 7 you're using local entities (as one gets created by finalizing the draft). I'm assuming running a refreshing forms sorts everything out? 

I'm a little surprised that this didn't get sorted out by form update running when you updated from Beta 7 to `master` though. What form update mode was in use? I'm wondering if doing this in quick succession means form update doesn't run again because it already ran recently.

**Comment by lognaturel** [comment]
> I'm a little surprised that this didn't get sorted out by form update running when you updated from Beta 7 to master though

I wondered about this. I had match exactly turned on. What triggers form update on upgrade? I definitely observed it systematically when looking at https://github.com/getodk/collect/issues/6493 and never when looking at this one.

**Comment by dbemke** [comment]
> What form update mode was in use? 

Match exactly

**Comment by seadowg** [comment]
> What triggers form update on upgrade?

All background work gets rescheduled. @dbemke could you check this again and see if the form update definitely doesn't run for you when upgrading? My guess is that it's not going to run again if it ran recently.

**Comment by lognaturel** [comment]
> All background work gets rescheduled

How is an upgrade detected? Could there be a difference between going between betas and going from the prior released version to a beta?

**Comment by dbemke** [comment]
> could you check this again and see if the form update definitely doesn't run for you when upgrading?

Since there's beta 8 in the store I can't reproduce the steps described in the issue. Now I can only check upgrading from the store version to beta 8.

**Comment by seadowg** [comment]
> How is an upgrade detected? Could there be a difference between going between betas and going from the prior released version to a beta?

It should use version code which will increment for each release (regardless of type). Let me have a look and confirm what happens.

**Comment by seadowg** [comment]
@dbemke while I'm looking into this, I just wanted to point out that you could also investigate by using the Github APKs. Both Beta 7 and 8 are available.

**Comment by seadowg** [comment]
Playing around with it, it looks like we do run updates right after upgrading. I verified this by doing an upgrade seconds after a match exactly had run and saw it run again. It might be that this is delayed on some devices of course. @dbemke could you check again upgrading from Beta 7 to Beta 8? I'm going to close this, but we can reopen if those checks don't work as expected.

@lognaturel I'll add a quick note to the beta thread that the new release will clear entities out.

**Comment by lognaturel** [comment]
Thank you!
