### ISSUE TITLE
Ambiguous wording related to GPS accuracy

### ISSUE THREAD

**Issue by brontolosone** [getodk/collect#6507]
Collect version: v2024.2.4

Somewhat related: #4696

Let's start with a screenshot:

![saved_at_5m](https://github.com/user-attachments/assets/bec3362f-f919-44ed-9835-a18c43193e5d)

The sticking point is the text

> saved at 5m

If one is not already in the know, one could wonder what `5m` means. 5 minutes? 5 meters? 5 meters of what? Saving? What is it going to save and how does that affect me?
What I, as a somewhat-insider, think it _might_ mean is "the question value will be auto-recorded (once? or also updated as long as I have the question open?) as soon as the accuracy looks decent, for a value of "decent" of `<5 meter` of LocationProvider-reported accuracy". If it does mean that, then the UI message `saved at 5m` doesn't quite cover that meaning. I think the UI message could be better.

Location provider accuracy in itself is a bit of a fuzzy concept in Android. Anyone can write a LocationProvider... Initially I thought it might be nice to use straight-from-the-horses-mouth NMEA messages (via `NmeaListener` or `OnNmeaMessageListener`) but that approach is [not a happy path](https://gitlab.com/mvglasow/satstat/-/issues/119#note_146782250) which might be why Collect resorts to just using `LocationProvider.getAccuracy()`. :thinking: 

In the screenshot below, the reported accuracy might indeed be the GPS HDOP value, as at least [one person](https://stackoverflow.com/a/6993494) seems to think, but... it doesn't reflect the _current_ state of the precision (keeping in mind that "current" is a troublesome concept to start with). With actual true honest GPS, you can't have any precision with 0 satellites, because you can't have any fix with 0 satellites. But with a fused location provider you can maybe, for instance if you're surrounded by many WiFi access points that have been mapped; but the UI doesn't tell you whether such is the case; it doesn't tell you whether your fix is coming from GPS, or has been estimated using telecom tower / wifi AP triangulation. In that light, the below screenshot is surprising:

![saved_at_5m_2](https://github.com/user-attachments/assets/db39549f-d7d7-4f06-9db0-cfb5308ca646)

So I think there may be room for improvement in the UI:
- cheap fixes if we can find the right words to convey what we mean, so a more informative text than `saved at 5m`, and demystifying how we can have any accuracy while seeing 0 satellites.
- speculative: more expensive improvements might be possible by presenting actionable information on the [sources of information we use](https://github.com/getodk/collect/blob/193dd38266a847e7075bc9326e9e43b0a51ffd00/location/src/main/java/org/odk/collect/location/BaseLocationClient.kt#L30-L45).

**Comment by seadowg** [comment]
Yeah, a lot of the wording here was hard to get right, and I agree that we might not have ended up in the best place. 

This kind of open-ended discussion is much better suited to the [forum](https://forum.getodk.org/). You should have seen a prompt to post there when creating this in fact - did you not?

Could you please repost there and I'll close this?

**Comment by lognaturel** [comment]
I'm not really sure where to keep track of these kinds of thoughts! It's not quite user feedback since @brontolosone comes at things from a much more technical perspective than most of our users and of course is now internal. It's mostly a question about why things were done a certain way and about whether a different direction should be considered. Maybe we could keep them in the constellation of docs we have linked from the research library. The forum is probably ok but I think posts with this level of detail can be overwhelming and discouraging to non-developers (most of our community).

@alyblenkin any thoughts on where this should go? It is related to your current Web Forms design work so it could go with that.

The high level goal for this question type is to give data collectors who have minimal training hints to help them get as high accuracy of a point as possible. In general, the best action for them to take is to wait until the location is automatically captured. However, that's not always possible for environmental or time reasons so we also want to give them the option to capture the location early.

> If one is not already in the know, one could wonder what 5m means. 5 minutes? 5 meters? 5 meters of what? Saving? What is it going to save and how does that affect me?

The goal there was to allow end users to pattern match. Most end users who would encounter this dialog are unlikely to know much about accuracy. We want them to see a value that ends in `m` at the top of the screen and another one that ends in `m` in this sentence. It's really important that the message be short and not use technical words. 

> the UI doesn't tell you whether such is the case; it doesn't tell you whether your fix is coming from GPS, or has been estimated using telecom tower / wifi AP triangulation. In that light, the below screenshot is surprising

I don't really understand this piece! The screenshot says "satellites: 0". The thinking there is that this is an easy thing to train for if it's relevant for your use case: you can write a hint that says something like "you should see at least 4 satellites, move around until you do" or whatever special guidance you want to give. The documentation includes information about the fused provider (https://docs.getodk.org/collect-location/) but the interface an end user sees doesn't feel like the right place for it.

**Comment by brontolosone** [comment]
> The goal there was to allow end users to pattern match.

one can't pattern match on `m` in the first screenshot, because there's no other `m` in the first screenshot.

**Comment by brontolosone** [comment]
> The thinking there is that this is an easy thing to train for if it's relevant for your use case: you can write a hint that says something like [...]

Ah yes, true, no amount of great UI/wording is going to explain the intricacies of Android location providers, for everyone, for every occasion, for the exact extent that it's relevant for their specific use case, all the time. There's no substitute for specific training in the local context.
But we do need to convey enough actionable information to inform such training. And if something can be less ambiguous, then that's a win.

Note that depending on locale one might not be immediately think of `m` as meters, in some places they use imperial units — the `m` might sooner pattern match with `minutes`.
Another challenge is that when the number goes up, accuracy is down, which can make wording confusing — saying "once accuracy is lower than 5 meters" is confusing, as would be the converse "once accuracy has risen to 5 meters or lower". :sob: 

Some compact variant of _"The point will be recorded as soon as accuracy is 5 meter or better"_ could be more complete?

**Comment by lognaturel** [comment]
> might not be immediately think of m as meters, in some places they use imperial units — the m might sooner pattern match with minutes.

I don't know if this matters if the goal is to establish a pattern with what's above with the expectation that most people don't have a sense of what accuracy really means. It's true that there's nothing to match with when the accuracy shows "--". I've never seen it show for very long but maybe it's possible in some contexts.

> Another challenge is that when the number goes up, accuracy is down, which can make wording confusing — saying "once accuracy is lower than 5 meters" is confusing

Agreed, that's why we went with "at" even though it may not be strictly accurate.

> Some compact variant of "The point will be recorded as soon as accuracy is 5 meter or better" could be more complete?

Maybe we could omit that line altogether? We included it because this value can be configured on a per-question basis. A form could have multiple point questions with different accuracy thresholds and so it's nice to have some reminder/indicator of what to expect. My hunch is that once a person has used the question type a couple of times the information becomes more useful. We do see from analytics that a majority of points are captured automatically once the threshold is reached. I imagine that folks who don't have much training are confused at first, see the instruction to wait, and then see that the point is automatically captured eventually.

**Comment by alyblenkin** [comment]
This is a great conversation! While we haven't explicitly received feedback about the dialog in user research that doesn't mean we couldn't make it a better user experience. Given the other geo improvements we want to do for Web Forms and Collect, we'll need to assess where this fits in our priorities and find ways to get feedback on it.

Next Steps
**Add Feedback to Research Library:**
The library is a mix of internal and external feedback, so I'll add the feedback and label it accordingly.

**Track Feedback:**
I’ll keep an eye on the forum and user research sessions to see if this comes up.

**Consider for Insiders Call:**
Our next Insiders call focuses on collecting and editing a point, which might touch on usability indirectly. I'll think about it and see if we can work it in.

---
**Additional Context:**
When I first encountered this dialog, I was confused, likely because I hadn't seen anything like it before. So I think anyway to give them more hints or improve things would be great so they can get as high accuracy point as possible. 

We also did a [workshop on improving all geo questions](https://app.mural.co/t/getodk7867/m/getodk7867/1714679387531/fe757fa8b0bbf995fa94ce8fbeb6c1b0062eeb8c?sender=uf326a03b6c46695558a51554) and the QA team shared feedback like using more action-oriented messages ("try moving around") and clarifying the information displayed under the progress bar. So that gave me a few ideas for some design iterations for Web Forms.

I explored ways to simplify and improve the information hierarchy. One idea I had was something like what I have below as a starting point for discussion. It’s not validated, nor have we reviewed from a technical perspective, but I think your feedback is super helpful and something we can use to help drive the conversation forward. 

One possible path forward would be to copy what we have with Collect because that's lower risk and wouldn't involve any new training. And then iterate on it and improve both and share this plan with the community so everyone is aligned and onboard. But again, something to consider with prioritization. 

![3  Save location - poor accuracy](https://github.com/user-attachments/assets/badbe77c-d896-4ee5-a9da-ab594f2b8789)
