### ISSUE TITLE
Local entities with only a space in the label

### ISSUE THREAD

**Issue by dbemke** [getodk/collect#6518]
#### ODK Collect version
the store version 2024.3.0 beta 8, the master version bae51166e42a099c50b88087c8b5f5558a3f9adc
#### Android version
10, 14
#### Device used
Redmi 9T, Pixel 7a
#### Problem description
I noticed one difference between Collect and Central. In Collect it’s possible to create a local entity with just a space in the label field, but Central won’t create that entity.

#### Steps to reproduce the problem
1. Download project – user "colors” https://staging.getodk.cloud/#/projects/101/app-users
2. Set auto send to "off”.
3. Go to Color registration form and enter a space in questions.
4. Finalize the form.
5. Go to Color update form and check if the entity was created.
6. Send the registration form to Central and check if the entity was created

#### Expected behavior
A local entity shouldn't be created if there's only a space in the label field

**Comment by seadowg** [comment]
@lognaturel I'm guessing this will stay disallowed in Central?

**Comment by lognaturel** [comment]
My feeling is that a whitespace-only label should not be allowed because it points to a form design issue. Even if it happens because you have something like `concat(${first_name}, " ", ${last_name})` and the name values are blank, that suggests those fields should have been required.

We haven't discussed with Central yet, though. If you agree with that reasoning, we can go ahead and address this one in Collect. Otherwise let's have a discussion with Central in early 2025.

**Comment by seadowg** [comment]
> My feeling is that a whitespace-only label should not be allowed because it points to a form design issue. Even if it happens because you have something like concat(${first_name}, " ", ${last_name}) and the name values are blank, that suggests those fields should have been required.

Yup this makes sense to me!

**Comment by lognaturel** [comment]
Adding this constraint to the spec: https://github.com/getodk/xforms-spec/pull/322
