### ISSUE TITLE
Only add analytics credentials to release builds

### ISSUE THREAD

**Issue by yanokwa** [getodk/collect#655]
Currently, we track analytics from every fork of Collect. This is not a great idea because we don't need to see activity from random forks of Collect. We should only include analytics credentials on release builds.

**Comment by lognaturel** [comment]
One easy thing that I think we should do is add `analytics.setDryRun(BuildConfig.DEBUG);` to `getDefaultTracker` so that we don't log analytics from debug builds. Release builds of production forks will still log to our analytics but I actually think that's ok. It's an advantage to have more information and if forks choose not to take control of the analytics, I think that's good for the core. The only disadvantage is that we might get some information about things that are not in core. But I expect that most forks that do significant customization would change the key.
