### ISSUE TITLE
display a dialog and suggesting user go to the settings when location provider are disabled.

### ISSUE THREAD

**Issue by getsanjeev** [getodk/collect#686]
When location providers are disabled, display user to go to settings and turn it on, would be a good thing.

**Comment by jnordling** [comment]
This excites already for the GeoPoint GeoShape and GeoTrace widgets. Same with the #687
<img src="https://cloud.githubusercontent.com/assets/11786919/24073058/753df262-0bc7-11e7-87a5-d309be0100a0.png" width="200px" />

**Comment by lognaturel** [comment]
@jnordling Can you say more? Are you against @getsanjeev's change? Currently, when location services are off, it is not possible to enter a GeoPoint activity. His change brings the user to settings to enable them if desired. Are you saying you'd rather a dialog? I think the proposed change is a good one since GeoPoint can't be used at all without location services enabled.

**Comment by jnordling** [comment]
No not against it at all, I know that for geopoint with the "map" or "placement-map" with appearance tags should have this functionality like the other geo-widgets inside the activity once you open the widget (I guess the regular geopoint got left out :(. I was just suggesting to use the same dialog. Sorry I should have been more specific to begin with @lognaturel. @getsanjeev good catch, I think the toasts is rather dated for this type of stuff.
