### ISSUE TITLE
Hide Downloaded Forms

### ISSUE THREAD

**Issue by rajatthakur** [getodk/collect#711]
The Get Blank Form Activity (FormDownloadList.java) shows all forms even the ones that are already present on the device.I feel only the new forms or the ones which have been updated should be made available for download.

#### Feature description
Hide downloaded forms from Get Blank Form Activity.

#### Expected behavior
Only the forms which are not already present on the device should be available for download.

**Comment by lognaturel** [comment]
Please wait for discussion before making changes to existing behavior to make sure the changes are desirable given the software's use.

**Comment by grzesiek2010** [comment]
@lognaturel maybe now it makes sense. Maybe we should add an option to hide such forms by default (user can change it). We can display only new forms or newer versions (since we implemented that option).

What do you think?

**Comment by shobhitagarwal1612** [comment]
I agree with @grzesiek2010. According to me giving the option of downloading the already downloaded versions of forms ends up people trying to download it again which is of no use. So we can either hide them from the list of available forms or disable the checkbox so that those can't be downloaded by a user
