### ISSUE TITLE
Back button when navigating "My Drive" goes all the way back to root

### ISSUE THREAD

**Issue by lognaturel** [getodk/collect#741]
#### Software and hardware versions 
Collect v1.4.16-127-g4673b97e

#### Problem description
When protocol is set to "Google Drive, Google Sheets", it's possible to navigate through multiple layers of directories in the drive. The "Back" button always goes back to the root.

#### Steps to reproduce the problem
1. Set protocol to "Google Drive, Google Sheets"
1. Set the Google account to a user who has directories within directories in Drive
1. Tap "Get Blank Form"
1. Tap on a few layers of directories
1. Tap "Back"

#### Expected behavior
The "Back" button should go back one level.

**Comment by pratikmjoshi** [comment]
@lognaturel I'll handle this if its ok.

**Comment by lognaturel** [comment]
Sounds good, @pratikmjoshi

**Comment by shobhitagarwal1612** [comment]
@pratikmjoshi Are you still looking into this bug?

**Comment by pratikmjoshi** [comment]
@shobhitagarwal1612 @lognaturel  Yes I am, I'm stuck on it though. It seems that the parent id is not assigned, and therefore when back button is pressed, it is going all the way back to the root because that is the default value. However, I'm not sure how to get the parent id of a file/directory since Google API v3 docs are relatively new. I am not able to find an answer on stackoverflow either. I was thinking of having a separate stack containing parent ids, but when I tried implementing that, I encountered some errors. Do you have any suggestions?

**Comment by shobhitagarwal1612** [comment]
@pratikmjoshi Thanks for your efforts. I agree that the documentation for the APIs is not very clear. I am familiar with the codebase that you are working on. New code for fetching files in GoogleDriveActivity was not written very thoughtfully by me as this activity was broken after updating to the newer APIs. So, it needs some refactoring too. I noticed that you are also working on #873. Are you still interested in handling this issue? If not then I'd be more than happy to work on this issue :smiley:

**Comment by lognaturel** [comment]
@pratikmjoshi Any updates on this issue? It'd be great to have it addressed for this month's release!

**Comment by shobhitagarwal1612** [comment]
Fixed in #967

**Comment by pratikmjoshi** [comment]
@lognaturel I'm really sorry that I didn't get back to you on this. Exams are around the corner so I wasn't able to get back on this issue.

**Comment by lognaturel** [comment]
That's ok, @pratikmjoshi, I hope your exams go really well! 😊 Thanks again to @shobhitagarwal1612 for taking it on.

**Comment by pratikmjoshi** [comment]
Thanks! I'll get right back to contributing when they're over
