### ISSUE TITLE
Add form level support for auto-send and auto-delete

### ISSUE THREAD

**Issue by yanokwa** [getodk/collect#791]
**Problem**
We have a user whose campaign has forms that need to be deleted on send because they are sensitive. The same user has other forms that need to be kept on the device because the data is useful to the day to day work of the enumerator.

**Proposal**
In the settings sheet of the XLSForm, we will add an `auto_send` and `auto_delete` heading. If the values underneath this heading is `true`, then the form will behave accordingly and override the settings of the device. In Collect, the XML we'll look for is: `<submission orx:auto-delete="true" orx:auto-submit="true" >`

**Comment by yanokwa** [comment]
@lognaturel What are chances we could get this into the April release?

**Comment by lognaturel** [comment]
Since it's May, I give getting it in the April release a solid 0% chance. 😏 😁

This isn't hard to do on the Collect side of things but we should first get consensus on the XForms approach and then get it into pyxform. We should start now but I think aiming for the June release will be most realistic I think.

**Comment by lognaturel** [comment]
Oh wait. There isn't a link to the XForms issue but now that I think about it, are both already approved?
