### ISSUE TITLE
Refactor AppListActivity and AppListFragment

### ISSUE THREAD

**Issue by grzesiek2010** [getodk/collect#797]
We use [AppListActivity](https://github.com/opendatakit/collect/blob/master/collect_app/src/main/java/org/odk/collect/android/activities/AppListActivity.java) for lists which extends ListActivity and [AppListFragment](https://github.com/opendatakit/collect/blob/master/collect_app/src/main/java/org/odk/collect/android/fragments/AppListFragment.java) for lists which extends ListFragment. AppListFragment was added a few weeks ago and now we have a few duplicated methods in both places. We should refactor the code. probably we should use ListFragments in all our lists so then we can keep only AppListFragment class. We should start work on this as soon as possible as there are more and more duplicated methods.

**Comment by shobhitagarwal1612** [comment]
I'd like to handle this issue.

**Comment by shobhitagarwal1612** [comment]
This can be achieved by converting other ListActivities into ListFragments as well. I have already done this before for some activities in this [PR](https://github.com/opendatakit/collect/pull/552)
But it is proposed in some GSoC proposals and also in [mine](https://docs.google.com/document/d/19FEwVFovP4GDqTMiJF-FeCF46FnsEHZAmbd_o1hBYfo/edit#) that the use of list views should be replaced with recycler views. So we should discuss this first whether we are ready to make the above conversion. If no, then we can proceed with this refactoring otherwise it would be of no use to do this task as all of this work would be discarded with the implementation of RecyclerView

@grzesiek2010 @lognaturel @yanokwa Any thoughts?

**Comment by lognaturel** [comment]
That's a good point, @shobhitagarwal1612. It does seem likely that the change to `RecyclerView` will happen so waiting for that seems like a fine idea. @grzesiek2010 does that sound good to you?

**Comment by Ishmeetsingh97** [comment]
@lognaturel @shobhitagarwal1612 @yanokwa  Indeed, It is a good idea to convert all the listviews to recyclerview due to performance issues.
I would like to contribute here if possible.

**Comment by grzesiek2010** [comment]
@lognaturel yes I think it's ok.

**Comment by lognaturel** [comment]
@grzesiek2010 @shobhitagarwal1612 @Ishmeetsingh97 I will close this issue for now and we will do the refactor as part of a switch to `RecyclerView`.
