### ISSUE TITLE
label / list-nolabel appearance issue

### ISSUE THREAD

**Issue by yanokwa** [getodk/collect#808]
> Im trying to use appearance label/list-nolabel in a group but the list-nolabel item doesn't appear in screen. Im attaching xls, xml and media files in case someone want to replicate the issue. If the issue remains in other cases different than me, i think we find a bug.

From neridavid.martinez@gmail.com
File: [bug.zip](https://github.com/opendatakit/collect/files/886864/bug.zip)

**Comment by getsanjeev** [comment]
@yanokwa I am new to it. But I would like to work.

**Comment by grzesiek2010** [comment]
It works as expected to me. When we use **label appearance** we use [LabelWidget](https://github.com/opendatakit/collect/blob/master/collect_app/src/main/java/org/odk/collect/android/widgets/LabelWidget.java#L49) :

> The Label Widget does not return an answer. The purpose of this widget is to be the top entry in a field-list with a bunch of list widgets below.

If we use **list-nolabel appearance** then we use [ListWidget](https://github.com/opendatakit/collect/blob/master/collect_app/src/main/java/org/odk/collect/android/widgets/ListWidget.java#L58) and we can see only radio buttons.
In both cases expected behaviour is described in the attached links.

Here is a form with all variants of select one widget:
[selectOne.txt](https://github.com/opendatakit/collect/files/889543/selectOne.txt)

**Comment by lognaturel** [comment]
I'm not clear on what the problem was but is it possible #679 fixed it too? @grzesiek2010 when you check out v1.5.1 to try out #802, I'd recommend trying this one out too to see if you can identify a problem with the attached form and confirm we fixed it.

**Comment by getsanjeev** [comment]
@log sorry guys I was busy with my GSoC proposal. It seems as if people are already working on it. Should I look into it?

**Comment by lognaturel** [comment]
@getsanjeev, let's see what @grzesiek2010 finds and then if there actually is a problem you can take it on! I suspect it's been fixed already.

**Comment by grzesiek2010** [comment]
@lognaturel #679 isn't related. I tink Neri didn't understand those widgets. I've sent an email to him so let's wait for confirmation

**Comment by lognaturel** [comment]
Ok, thanks. Please respond to [this thread](https://groups.google.com/forum/#!topic/opendatakit/ETl_1mxEoL0) so everyone can see the answer.

**Comment by lognaturel** [comment]
No answer from the original poster so I think we can close for now!
