### ISSUE TITLE
ODK Collect and google play service

### ISSUE THREAD

**Issue by CorentinLemaitre** [getodk/collect#824]
Hello,
I use your app on a galaxy note 2 with cyanogen i have download ODK collect last version from your website and install it. 
It works for everything except the location. An error message say that There is no google play service on my device. Then i can not collect my location. 

After that i have download the app via f droid (1.2.2 is the last version) and it work well but it is a very old version. 
Is there any possibility to give location without google play service?
What is the last version that can work without the google play service?

**Comment by nribeka** [comment]
@CorentinLemaitre which widget are you trying to use to collect data? Are you using geopoint? 

I think at least the geopoint shouldn't require google play installed since it's using the device gps and network provider to get the location. This could be a bug on the Collect code too.

@grzesiek2010 I had a chat with @lognaturel and this could be a bug introduced recently.

**Comment by lognaturel** [comment]
We added the check for Play Services when addressing #132. @grzesiek2010 and I discussed again when working on #726 and concluded it was necessary.

@CorentinLemaitre could you please try 1.4.16 from [here](https://opendatakit.org/downloads/download-info/odk-collect-apk/#) and let us know if that works for you?

**Comment by CorentinLemaitre** [comment]
@nribeka I don't know wich widget is used. Is there any way to know wich widget is used ? 
@lognaturel it works well with the 1.4.16.

**Comment by nribeka** [comment]
If it's working on 1.4.16, then you're using geopoint widget to collect the location data.

So @lognaturel, this is a bug I think and something I need to consider when using the gms location api to get the location. Since the long term gms is not gonna happen soon, maybe we should patch this bug and update Collect?

**Comment by lognaturel** [comment]
@nribeka Agreed. For now using GeoPoint should not force a check on Google Play Services since it doesn't appear to be needed.

**Comment by CorentinLemaitre** [comment]
OK super! If I understand, I have no change to do for the moment. I can continue to use the 1.4.16 and try the next version when it comes out.

Thanks a lot!

**Comment by lognaturel** [comment]
That's right, @CorentinLemaitre -- the next release will go back to allowing access to the GeoPoint widget without play services. You just need to avoid 1.5.0 and 1.5.1 which don't. Thanks for reporting this so we could get it addressed quickly!
