### ISSUE TITLE
Rename collect_app to app

### ISSUE THREAD

**Issue by yanokwa** [getodk/collect#835]
I don't know why `collect_app` was chosen (paging @mitchellsundt @jbeorse) as the name of the app module, but unless we have a good reason, I think we should use [Android conventions](https://developer.android.com/studio/build/index.html#build-files) and the conventions are that the app module is called `app`.

This will likely break open PRs or affect downstream forks, but there's never going to be a good time to do this change. And if we decide to make this change, we'll need to give developers a heads up on the list and on the Slack.

Some might argue that this doesn't matter, but my neurosis (and the [broken window theory](https://en.wikipedia.org/wiki/Broken_windows_theory) as it applies to software), demands that we have a discussion about the pros and cons.

**Comment by lognaturel** [comment]
I personally only think that it's worth doing if there's one pro! Is there anything that's not possible now because of this? Do we gain anything at all?

**Comment by wbrunette** [comment]
Well since @yanokwa  brought up his neurosis let me try and shed some light on this to avoid the side effects of neurosis. NOTE:  The people who would know for sure are @jbeorse or @marshallb93.

My recollection is, when @jbeorse and @marshallb93 were first porting all ODK projects over to gradle they experimented with mutli-module projects in Android Studio (this was back when Android Studio was more experimental and less stable). Multi-module projects are barely mentioned on the style link @yanokwa included however there this is a revealing sentence "However, multi-module projects need to specify each module that should go into the final build. " At the time all ODK tools couldn't all be named app. I (@wbrunette) thought it would not be contributor friendly to have one big workspace for all ODK so asked @jbeorse and @marshallb93 to break them into smaller projects so there is only one app per Android Studio project/workspace.

In ODK 2.0 we still have multi-module project builds that include linked libraries so androidcommon_lib and androidlibrary_lib have different names to be linked into with a single app project. However we kept the single app per Android Studio project/workspace paradigm. Using that paradigm the app folder does not need to be named so collect_app can be changed to app.

Howevever, @yanokwa you should check out google own same code as they have still have repos that does not use the word app every where and instead use the name of the module. My guess is at some point they changed the naming conventions. For example https://github.com/googlesamples/android-UniversalMusicPlayer

@jbeorse and @marshallb93 feel free to correct my recollection of historical decisions.

**Comment by jbeorse** [comment]
@wbrunette is correct, this is an artifact of sharing a build system with the ODK 2.0 tools and multi-module projects. There is no compelling reason to keep collect_app vs app that I can think of, though there's no compelling reason to switch in my opinion either. As @wbrunette mentioned, there are other projects that don't follow this convention; I don't think its super strict. There is no functional difference.

**Comment by lognaturel** [comment]
Thank you, @jbeorse @wbrunette for that background. @yanokwa I propose we close this issue for now and it can be reopened if we find a good reason to do it.

**Comment by yanokwa** [comment]
Not being able to rename the folder remains annoying to me, but I agree that this causes downstream pain for no benefit. I'm closing this issue until I can find a good reason! 😂
