### ISSUE TITLE
Change printed label margins

### ISSUE THREAD

**Issue by ghost** [getodk/collect#863]
#### Software and hardware versions 
Collect v1.5.1, Android v5.0.2, Zebra RW220 Printer

#### Problem description
I was able to print barcodes using Zebra RW220. The problem is that the information is not fully displayed on the label, that is, on the left margin, part of the barcode and text has been cutout. 
(See attached image of a printout)
How do I change the barcode label margins to see all the information?
#### Steps to reproduce the problem
I tried setting the printer label settings through a computer but it didn't work for me.

Thanks
![barcode printout](https://cloud.githubusercontent.com/assets/12542345/24866454/d511a758-1e12-11e7-9479-888da96a2865.png)

**Comment by ghost** [comment]
Any progress on this issue? Anyone?
Thanks

**Comment by lognaturel** [comment]
There's unfortunately nothing we can do on the Collect side to fix this. Does the device itself let you set a stock size? Can you get a correctly-printed label with the Zebra app?

Perhaps @clarlars has some more insights on whether there might be something in the sensors framework or the driver that can be configured?

**Comment by mkaranja** [comment]
Hi all,
Sorry I took long to respond  but since I figured out how to go about it, it's time this issue is closed.
Changing the margins is indeed possible. Just go to the odk zebra printer driver source code (https://github.com/opendatakit/sensordrivers/blob/master/ZebraMzSeriesPrinter/src/org/opendatakit/sensors/drivers/zebra/bt/PrinterDriver.java) and change the print margins

The line to edit indicated beow, change (! 0) to (! 100) or any desired number. This increases the left margins making 
printCmd.append("! 0 200 200 " + labelHeight + " 1\r\n ON-FEED IGNORE\r\n ENCODING UTF-8\r\n");
printCmd.append("! 100 200 200 " + labelHeight + " 1\r\n ON-FEED IGNORE\r\n ENCODING UTF-8\r\n");

**Comment by grzesiek2010** [comment]
Since it's not a bug in Collect I'm closing the issue.
