### ISSUE TITLE
Error with calculate value when used in constraint_message

### ISSUE THREAD

**Issue by lbramley** [getodk/collect#874]
Collect v1.5.1, on a Nexus 7 running Android 5.0.2

I created a form where calculate fields are used to create both a value used for a constraint and text to use in the constraint message. However, while the constraint itself seems to work correctly when I view the form on my tablet, the constraint message doesn't - instead of displaying my text from the calculate field, it displays e.g. "${0}". This same text works when I use it in a note instead. I've attached a sample form where this is reproduced.

Thanks,
Laura

[constraintMessageError.xlsx](https://github.com/opendatakit/collect/files/916089/constraintMessageError.xlsx)

**Comment by grzesiek2010** [comment]
It's on the Javarosa side I've created the issue there https://github.com/opendatakit/javarosa/issues/36

**Comment by lognaturel** [comment]
@lbramley Do you need to have constraint messages in multiple languages? The issue seems to be that localized constraint messages can't properly include dynamic text like the result of a calculate. I'm not totally sure whether that's intentional behavior or not and will need to keep exploring that. If you don't need translated constraint messages, this form should work: [constraintMessageError.xlsx](https://github.com/opendatakit/collect/files/1012408/constraintMessageError.xlsx).

**Comment by lognaturel** [comment]
I'm going to close this issue since as @grzesiek2010 stated, it pertains to the JavaRosa library that Collect is built on top of. If you'd like to keep being notified on our progress, @lbramley, I invite you to use the subscribe button to the right of the issues at opendatakit/javarosa#36 and opendatakit/xforms-spec#125. Additionally, if we do end up adding support for what you were doing in the original form, we will notify you here. Thanks for reporting this!

**Comment by lbramley** [comment]
Thanks Helene, sorry for the delayed reply. Unfortunately I did need constraint messages in multiple languages. I’ll subscribe to keep following - thanks!

**Comment by lognaturel** [comment]
@lbramley A little late to the party here but as of Collect 1.13.x you can use references to other values in constraint message text. Hope you will find it helpful for future surveying!

**Comment by Kalyan-Lama** [comment]
Hi @lognaturel,

The issue seems to be closed but when i try it out in the ODKCollect v1.27.1 i don't see it working as it should. Did i get something wrong?

**Have also attached the xlsform for testing:**

[Constraint Dynamic Error Message.xlsx](https://github.com/getodk/collect/files/4739859/Constraint.Dynamic.Error.Message.xlsx)
