### ISSUE TITLE
Replaces Existing Data on Google Spreadsheet 

### ISSUE THREAD

**Issue by lokpriya** [getodk/collect#931]
#### Software and hardware versions 
Collect v1.5.1, Android 5.1 device used...

#### Problem description
While submitting the data on Google Spreadsheet the existing data is replaced from the new one.
#### Expected behavior
The data should be continue on rows 
#### Other information 
Things you tried, stack traces, related issues, suggestions on how to fix it...

**Comment by lognaturel** [comment]
@lokpriya I am not able to reproduce this using a fresh install of Collect v1.5.1 from the Play Store. Is this a form that you created recently or that you were using with previous versions of Collect? If the form .xml file can be shared publicly, it would be helpful if you could attach it here. You will need to download it from Google Drive and then rename it to .txt because GitHub doesn't accept XML files. Then you can drag and drop the file in a comment box to upload it.

**Comment by lokpriya** [comment]
@lognaturel I have attached the file. Even updating from the google play store same problem exists.
[UMLADMUN.txt](https://github.com/opendatakit/collect/files/945804/UMLADMUN.txt)

**Comment by lognaturel** [comment]
Thank you very much for attaching the form @lokpriya , that's hugely helpful. I can reproduce the problem with it but not with other forms that I have tried and I'm digging into the root cause. My initial hypothesis is that it has to do with the first value/column being blank. In the mean time, you can go to File > See revision history to see any data that might have come in.

**Comment by lognaturel** [comment]
It does seem like I can fix the problem by replacing `<notice/>` with something like
```
<notice>
  →
</notice>
```
Any text can go in the notice default but interestingly, `&#x20;` doesn't seem to work (space).

I created a minimal form that I thought would fail ([notice-and-name.txt](https://github.com/opendatakit/collect/files/946008/notice-and-name.txt)) but it doesn't so I'm still not clear on what the root cause of the problem is.

Rows are added to the spreadsheet by the Sheets API [append method](https://developers.google.com/sheets/api/guides/values#appending_values) which seems it shouldn't overwrite things.

**Comment by grzesiek2010** [comment]
@lognaturel looks like api bug...

There are two possible solutions:
1.
https://github.com/opendatakit/collect/blob/master/collect_app/src/main/java/org/odk/collect/android/tasks/GoogleSheetsAbstractUploader.java#L597
we can add: 

> .setInsertDataOption("INSERT_ROWS")

but then new row is added at the top of collection - in the second row and only when I use that (strange) form, if I use other forms everything works like before.

2.
https://github.com/opendatakit/collect/blob/master/collect_app/src/main/java/org/odk/collect/android/tasks/GoogleSheetsAbstractUploader.java#L584
We can check if an answer is empty and then just add a space " ".

Which solution is better?

**Comment by lognaturel** [comment]
@grzesiek2010 Are you able to reproduce it consistently? Did the notice and name form fail? I feel like there might be something else going on. Also note that when I added a space as a default in the original form, that did NOT work.

**Comment by grzesiek2010** [comment]
@lognaturel 
I was able to reproduce the issue.
Both proposal solutions fix the problem.

**Comment by lognaturel** [comment]
@lokpriya @grzesiek2010 just put in a fix that will go out in the next release at the end of the month!
