### ISSUE TITLE
Front Camera by default

### ISSUE THREAD

**Issue by imran3may** [getodk/collect#969]
I would like to request to add a feature to ODK for opening the front camera by default. In some cases the users may need to take their own snap as a record and the level of users are: they can hardly can mange to use couple of functions on a form and flipping camera could be big issue for them.

**Comment by lognaturel** [comment]
There was a conversation about this [here](https://groups.google.com/forum/#!searchin/opendatakit/front%7Csort:relevance/opendatakit/6ao-O_B2Wlk/57fGH3STAQAJ). Seems it could be valuable to low-literacy users so we should try to do it.

I think this is something organizations would specify for particular image fields in their forms. It's very much client-specific so I think adding an `appearance` attribute value on the `upload` makes sense. It's a little bit strange because it wouldn't change the full appearance of the widget but rather just the appearance of the camera when the user chooses to take a picture.

@imran3may In this case, do you want to allow users to select existing pictures (as the standard image widget does) or do you also want to force them to take a new picture? That's something we could do as well. Then maybe `selfie` would be an appropriate name for the `appearance` value.

`<upload ref="my_image" appearance="selfie" mediatype="image/*">`

**Comment by imran3may** [comment]
Hi Hélène,

*Actually to force them taking a picture if they want to submit one. As the
objective is to see a patients' appearance for the day.*

*Thanks,*
*Imran  *


A N M AL IMRAN (Imran)
Brossard, QC
Canada
Cell: +1 (438) 501 3576

**Comment by grzesiek2010** [comment]
@lognaturel 
I've tried to force choosing front camera with small hack like here:

> if (Build.VERSION.SDK_INT >= Build.VERSION_CODES.LOLLIPOP_MR1) {
  intent.putExtra("android.intent.extras.LENS_FACING_FRONT", 1);
} else {
  intent.putExtra("android.intent.extras.CAMERA_FACING", 1);
}

but it doesn't work on all devices. I've tested:
**Samsung Galaxy 4 Android 5.0.1** - it works
**Samsung Duos Android 4.2.2** - it doesn't work

and generally that trick is not recommended.

so it looks like it will require more changes and we need to add our capture image activity. Then in that activity we should be able to choose front camera.
